<ul id="languages_tabs" class="nav nav-tabs">
    <?php
    $locale = Zend_Registry::get("Zend_Translate")->getLocale();
    $defaultLang = (array_key_exists($locale, $this->langs)) ? $locale : 'fr';
    ?>
    <?php foreach ($this->langs as $code => $lang) : ?>
        <li class="<?php if (count($this->langs) == 1 || $code == $defaultLang) echo 'active' ?>"
            data-toggle="tooltip"
            data-placement="bottom"
            title="<?php echo ucfirst(Zend_Locale::getTranslation($code, 'language', $locale)); ?>">
            <a href="<?php echo '#' . $code . '_form'; ?>" data-toggle="tab">
                <img class="<?php echo 'flag_' . $code;
                if (count($this->langs) == 1 || $code == $defaultLang) echo '_selected'; ?>" src='/img/spacer.gif'/>
            </a>
        </li>
    <?php endforeach; ?>
</ul>

<?php echo $this->form; ?>

<?php // $this->jQuery()->addJavascriptFile("/js/administratemail/edittemplate.js"); ?>
<script>
    var options = {
        convert_urls: false,
        menubar: false,
        height: 400,
        plugins: "link image code fullscreen table textcolor",
        toolbar1: "bold italic underline | styleselect | undo redo | alignleft aligncenter alignright alignjustify | bullist numlist | link image | code"
    };
    __initMCE("textarea", undefined, options);</script>
<script>
    $(document).ready(function () {
        $('a[data-toggle="tab"]').on('shown', function (e) {
            $('a[data-toggle="tab"] img').each(function () {
                var currentClass = $(this).attr('class');
                $(this).attr('class', currentClass.replace('_selected', ''));
            });
            var currentClass = $(this).find('img').attr('class');
            $(this).find('img').attr('class', currentClass + '_selected');
        });
    });
</script>
