<style>

    #col-tabs {
        padding: 0 30px 20px 20px;
    }

    ul#languages_tabs {
        width: 100%;
        padding-right: 10px;
    }

    ul#languages_tabs > li {
        float: right;
    }
</style>
<?php $this->jQuery()->addJavascriptFile("/js/administratemail/reminders.js"); ?>

<span class="col-md-9 col-md-offset-3 ccsd_form_required"><?php echo $this->translate('Champ requis') ?></span>

<form data-library="ccsd" role="form"<?php
if ($this->element->getAttrib('name')) {
    echo ' name="' . $this->element->getAttrib('name') . '"';
}
if ($this->element->getAttrib('id')) {
    echo ' id="' . $this->element->getAttrib('id') . '"';
}
if ($this->element->getAttrib('class')) {
    echo 'class="' . $this->element->getAttrib('class') . '"';
}
if ($this->element->getAction()) {
    echo 'action="' . $this->element->getAction() . '"';
}
if ($this->element->getMethod()) {
    echo 'method="' . $this->element->getMethod() . '"';
}
?>>

    <?php $elements = $this->element->getElements(); ?>

    <div id="type-element" class="form-group row">
        <?php echo $elements['type']; ?>
    </div>

    <div id="recipient-element" class="form-group row">
        <?php echo $elements['recipient']; ?>
    </div>

    <div id="delay-element" class="form-group row">
        <?php echo $elements['delay']; ?>
    </div>

    <div id="repetition-element" class="form-group row">
        <?php echo $elements['repetition']; ?>
    </div>

    <?php if (count($this->langs) > 1) : ?>
        <div class="row">
            <div id="col-tabs" class="col-md-9 col-md-offset-3">
                <ul id="languages_tabs" class="nav nav-tabs">
                    <?php foreach ($this->langs as $code => $lang) : ?>
                        <li class="<?php if ($code == $this->locale) echo 'active' ?>"
                            data-toggle="tooltip"
                            data-placement="bottom"
                            title="<?php echo ucfirst(Zend_Locale::getTranslation($code, 'language', $this->locale)); ?>">
                            <a href="<?php echo '#' . $code . '_form'; ?>" data-toggle="tab">
                                <img class="<?php echo 'flag_' . $code;
                                if ($code == $this->locale) echo '_selected'; ?>" src='/img/spacer.gif'/>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    <?php endif; ?>

    <div<?php if (count($this->langs) > 1) : ?> class="tab-content"<?php endif; ?>>
        <?php foreach ($this->langs as $code => $lang) : ?>
            <div
                id="<?php echo $code; ?>_form"<?php if (count($this->langs) > 1) : ?> class="tab-pane fade in<?php if ($code == $this->locale) echo ' active' ?>"<?php endif; ?>>
                <div id="<?php echo $code ?>_custom_template-element" class="form-group row">
                    <?php echo $elements[$code . '_custom_template']; ?>
                </div>

                <div id="<?php echo $code ?>_default_subject-element" class="form-group row">
                    <?php echo $elements[$code . '_default_subject']; ?>
                </div>

                <div id="<?php echo $code ?>_custom_subject-element" class="form-group row">
                    <?php echo $elements[$code . '_custom_subject']; ?>
                </div>

                <div id="<?php echo $code ?>_default_body-element" class="form-group row">
                    <?php echo $elements[$code . '_default_body']; ?>
                </div>

                <div id="<?php echo $code ?>_custom_body-element" class="form-group row">
                    <?php echo $elements[$code . '_custom_body']; ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>

</form>
