<?php
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
?>
<div>
    <?php
    if ($controller === 'paper' &&
        !empty($this->current_demand) &&
        !in_array($this->paper->getStatus(), Episciences_Paper::$_noEditableStatus, true))  :
        ?>
        <div class="btn-group">
            <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
                <?php echo $this->translate('Répondre à cette demande'); ?>
                <span class="caret" style="margin-left: 5px;"></span>
            </a>
            <ul class="dropdown-menu">
                <?php if (Episciences_Auth::getUid() === $this->paper->getUid()): ?>
                    <li>
                        <a href="/paper/contactrequest?id=<?= $this->current_demand['PCID'] ?>"
                           title="<?= $this->translate('Contacter sans dépôt de version') ?>"
                           class="modal-opener"
                           data-target="#"><?= $this->translate('Contacter sans dépôt de version') ?>
                        </a>
                    </li>
                <?php endif; ?>
                <li>
                    <a href="/paper/answerrequest?id=<?php echo $this->current_demand['PCID']; ?>"
                       title="<?php echo $this->translate('Répondre sans faire de modifications'); ?>"
                       class="modal-opener"
                       data-target="#"><?php echo $this->translate('Répondre sans faire de modifications'); ?>
                    </a>
                </li>
                <?php if ($this->review->getSetting(Episciences_Review::SETTING_CAN_ANSWER_WITH_TMP_VERSION)) : ?>
                    <li>
                        <a href="/paper/tmpversion?id=<?php echo $this->current_demand['PCID']; ?>"
                           title="<?php echo $this->translate('Envoyer une version temporaire'); ?>"
                           class="modal-opener"
                           data-target="#"><?php echo $this->translate('Envoyer une version temporaire'); ?>
                        </a>
                    </li>
                <?php endif; ?>
                <li>
                    <a href="/paper/newversion?id=<?php echo $this->current_demand['PCID']; ?>"
                       title="<?php echo $this->translate('Proposer une nouvelle version'); ?>"
                       class="modal-opener"
                       data-target="#"><?php echo $this->translate('Proposer une nouvelle version'); ?>
                    </a>
                </li>
            </ul>
        </div>
    <?php endif; ?>
</div>