<?php
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
/** @var Episciences_Paper $paper */
$paper = $this->paper;
?>
<div>
    <?php
    if ($controller === 'paper' &&
            !empty($this->current_demand) &&
            !in_array($paper->getStatus(), Episciences_Paper::$_noEditableStatus, true))  :
        ?>
        <div class="btn-group">
            <a id="answer-request" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
                <?php echo $this->translate('Répondre à cette demande'); ?>
                <span class="caret" style="margin-left: 5px;"></span>
            </a>
            <ul class="dropdown-menu">

                <li>
                    <?php

                    $newVersionHref = $this->url(['controller' => $controller, 'action' => 'newversion', 'id' => $this->current_demand['PCID']]);

                    if ($this->zIdentifier) {  // from z-submission: new version submission
                        $newVersionHref .= '&z-identifier=' . $this->zIdentifier;
                    }

                    ?>
                    <a id="new-version" href="<?= $newVersionHref ?>"
                       title="<?= $this->translate('Proposer une nouvelle version') ?>"
                       class="modal-opener"
                       data-target="#"><?= $this->translate('Proposer une nouvelle version') ?>
                    </a>
                </li>

                <?php if (!$this->doNotDisplayContactChoice) : ?>
                    <?php if ($paper->isOwner()): ?>
                        <li>
                            <a href="<?= $this->url(['controller' => $controller, 'action' => 'contactrequest', 'id' => $this->current_demand['PCID']])?>"
                               title="<?= $this->translate('Contacter sans dépôt de version') ?>"
                               class="modal-opener"
                               data-target="#"><?= $this->translate('Contacter les éditeurs (avec une pièce jointe)') ?>
                            </a>
                        </li>
                    <?php endif; ?>

                <?php endif; ?>

                <?php if ($paper->getStatus() !== Episciences_Paper::STATUS_TMP_VERSION_ACCEPTED) : ?>
                    <li>
                        <a href="<?= $this->url(['controller' => $controller, 'action' => 'answerrequest', 'id' => $this->current_demand['PCID']]) ?>"
                           title="<?php echo $this->translate('Répondre sans faire de modifications'); ?>"
                           class="modal-opener"
                           data-target="#"><?php echo $this->translate('Répondre sans faire de modifications'); ?>
                        </a>
                    </li>


                    <?php if ($this->review->getSetting(Episciences_Review::SETTING_CAN_ANSWER_WITH_TMP_VERSION)) : ?>
                        <li>
                            <a href="<?= $this->url(['controller' => $controller, 'action' => 'tmpversion', 'id' => $this->current_demand['PCID']]) ?>"
                               title="<?php echo $this->translate('Envoyer une version temporaire'); ?>"
                               class="modal-opener"
                               data-target="#"><?php echo $this->translate('Envoyer une version temporaire'); ?>
                            </a>
                        </li>
                    <?php endif; ?>

                <?php endif; ?>
            </ul>
        </div>
    <?php endif; ?>
</div>