<?php
/** @var Zend_Controller_Request_Http $request */
$request = Zend_Controller_Front::getInstance()->getRequest();
$controller = $request->getControllerName();
$action = $request->getActionName();
/** @var Zend_Form $form */
$form = $this->paperFilter();

// A gérer en AJAX (dataTable)
$form->getElement('submit')->setAttrib('type', '');
$form->setAction('');

echo $form;
?>
<hr/>
<?php //if ($this->papers) : ?>

<?php
$this->getHelper('webpackAssets')->queueScript('datatables-bootstrap');
$this->getHelper('webpackAssets')->queueStylesheet('datatables-bootstrap');
$this->getHelper('webpackAssets')->queueStylesheet('tom-select');
$this->getHelper('webpackAssets')->queueScript('tom-select');
$this->jQuery()->addJavascriptFile('/js/common/tomselect-filters.js');
?>


<table class="table table-bordered dataTable table-responsive-lg" id="papers" style="width: 100%;">
    <thead>
    <tr>
        <th class="text-center"><?php echo $this->translate('Id permanent'); ?></th>
        <th class="text-center"><?php echo $this->translate('Id document'); ?></th>
        <th class="text-center"
            data-name="<?php echo $this->translate('Statut'); ?>"><?php echo $this->translate('Statut'); ?></th>
        <th><?php echo $this->translate('Titre'); ?></th>
        <th class="text-center"><?php echo $this->translate('Volume'); ?></th>
        <th class="text-center"><?php echo $this->translate('Rubrique'); ?></th>
        <th class="text-center"><?php echo $this->translate('Proposé le'); ?></th>
    </tr>
    </thead>
    <tbody></tbody>
</table>

<script type="text/javascript">
    let selfAction = <?php echo "'$action'"; ?>;
    let selfController = <?php echo "'$controller'"; ?>;

    bootTomSelectFilters(
        ['status', 'ratingStatus', 'vid', 'sid', 'editors', 'reviewers', 'doi', 'repositories'],
        {plugins: ['checkbox_options', 'dropdown_input', 'remove_button']}
    );
</script>

<?php $this->jQuery()->addJavascriptFile('/js/paper/submitted.js'); ?>

<?php //else : ?>
<?php //echo $this->translate('Aucun article pour le moment') ?>
<?php //endif; ?>
