<div class="col-md-11">
    <div class="panel-heading">
        <h2 class="panel-title"><?php echo $this->translate('Accès à un article'); ?></h2>
    </div>
    <div>
        <div class="row">
            <div class="input-group">
                <input id="paper_identifier" class="form-control"
                       style="border-right:0; border-color:#ccc;"
                       placeholder="<?php echo $this->translate("Identifiant de l'article"); ?>">
                <span class="input-group-addon">
                        <button id="go_to_article" type="submit" style="border:0; background:transparent;">
                            <span class="glyphicon glyphicon-arrow-right"></span>
                        </button>
                    </span>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var $identifier = $('#paper_identifier');

    $("#go_to_article").on('click', function () {
        goToArticle();
    });

    $identifier.on('keyup', function (e) {
        if (e.keyCode === 13) {
            goToArticle();
        }
    });

    function goToArticle() {
        var idValue = $identifier.val().trim();
        var url = '/';
        if (!idValue) {
            alert(translate("Veuillez indiquer l'identifiant du document."));
            return;
        }

        if (isNaN(idValue) || idValue <= 0) {
            alert(translate("La valeur saisie n'est pas correcte, l'identifiant doit être un nombre positif."));
            return;
        }

        // get last docid

        var request = $.ajax({
            type: "POST",
            url: "/paper/ajaxgetlastpaperid",
            data: {id: idValue}
        });
        request.done(function (response) {
            var jsonParsed = JSON.parse(response);
            var lastDocid = parseInt(jsonParsed.docid);
            if (jsonParsed.exception) {
                console.log(jsonParsed.exception);
            }
            if (lastDocid !== 0) {
                url = '/' + jsonParsed.controller + '/view?id=' + lastDocid;
                document.location.href = url;
                return true;
            } else if (jsonParsed.error) {
                alert(jsonParsed.error);
                return false;
            }
        });
    }
</script>






