<?php if ($this->grid->getCriteria()) : ?>
    <table class="table table-striped table-bordered dataTable" id="grid_<?php echo $this->grid->getId() ?>">

        <thead>
        <tr role="row">
            <th><?php echo $this->translate('Critère'); ?></th>
            <th width="30"><?php echo $this->translate('Coeff.'); ?></th>
            <th><?php echo $this->translate('Commentaires'); ?></th>
            <th><?php echo $this->translate('Upload'); ?></th>
            <th><?php echo $this->translate('Notation'); ?></th>
            <th><?php echo $this->translate('Visibilité'); ?></th>
            <?php if (Episciences_Auth::isSecretary()) : ?>
                <th><?php echo $this->translate('Actions'); ?></th>
            <?php endif; ?>
        </tr>
        </thead>

        <tbody>
        <?php foreach ($this->grid->getCriteria() as $criterion) : ?>
        <?php /* @var Episciences_Rating_Criterion $criterion  */?>

            <tr id="grid_<?php echo $this->grid->getId() ?>_criterion_<?php echo $criterion->getId(); ?>">
                <td>
                    <span class="handle glyphicon glyphicon-move" style="margin-right: 10px"></span><?php
                    if ($criterion->getType() == 'separator') echo '<b>';
                    echo $criterion->getLabel();
                    if ($criterion->getType() == 'separator') echo '</b>';

                    ?></td>
                <td class="c-coeff"><?php echo (is_numeric($criterion->getCoefficient())) ? $criterion->getCoefficient() : '-'; ?></td>
                <td><?php echo ($criterion->getComment_setting()) ? $this->translate('Oui') : $this->translate('Non'); ?></td>
                <td><?php echo ($criterion->getAttachment_setting()) ? $this->translate('Oui') : $this->translate('Non'); ?></td>
                <td><?php
                    if ($criterion->getCoefficient()) {
                        echo $this->translate('Evaluation quantitative');
                        echo ' (';
                        if ($criterion->isCustom()) {
                            echo $this->translate('personnalisée');
                        } elseif (count($criterion->getOptions()) == 11) {
                            echo $this->translate('sur 10');
                        } elseif (count($criterion->getOptions()) == 6) {
                            echo $this->translate('sur 5');
                        }
                        echo ')';
                    } elseif ($criterion->getOptions()) {

                        if (($criterion->getOptions()[0]['value'] == 0) && ($criterion->getOptions()[0]['label'] == null)) {
                            echo $this->translate('Évaluation libre');
                        } else {
                            echo $this->translate('Evaluation qualitative');
                            echo ' (';
                            if ($criterion->isCustom()) {
                                echo $this->translate('personnalisée');
                            } else {
                                echo $this->translate('classique');
                            }
                            echo ')';
                        }
                    } elseif ($criterion->getType() == 'separator') {
                        echo $this->translate('Séparateur');
                    } else {
                        // kept for compatibility ?
                        echo $this->translate('Évaluation libre');
                    }

                    ?></td>
                <td><?php echo ($criterion->getVisibility()) ? ucfirst($this->translate($criterion->getVisibility())) : ucfirst($this->translate('editors')); ?></td>
                <?php if (Episciences_Auth::isSecretary()) : ?>
                    <td style="text-align:right;">
                        <a class="btn btn-xs btn-default pull-left"
                           title="<?php echo $this->translate('Modifier'); ?>"
                            <?php if ($criterion->getType() == 'separator') : ?>
                           href="<?= $this->url(['controller' => 'grid', 'action' => 'editseparator', 'rgid' => $this->grid->getId(), 'id' => $criterion->getId()]) ?>">
                            <?php else : ?>
                                href="/grid/editcriterion?rgid=<?php echo $this->grid->getId(); ?>&amp;id=<?php echo $criterion->getId(); ?>">
                            <?php endif; ?>

                            <span class="glyphicon glyphicon-edit"></span>&nbsp;<?php echo $this->translate('Modifier'); ?>
                        </a>
                        <a class="btn btn-xs btn-danger delete"
                           title="<?php echo $this->translate('Supprimer'); ?>"
                           href="<?= $this->url(['controller' => 'grid', 'action' => 'deletecriterion', 'rgid' => $this->grid->getId(), 'id' => $criterion->getId()]) ?>">
                            <span class="glyphicon glyphicon-trash"></span>&nbsp;<?php echo $this->translate('Supprimer'); ?>
                        </a>
                    </td>
                <?php endif; ?>

            </tr>
        <?php endforeach; ?>
        </tbody>

    </table>


    <script>

        $(document).ready(function () {
            $('#grid_<?php echo $this->grid->getId(); ?> tbody').sortable({
                handle: $('.handle'),
                helper: function (e, ui) {
                    ui.children().each(function () {
                        $(this).width($(this).width());
                    });
                    return ui;
                },
                start: function (e, ui) {
                    ui.placeholder.height(ui.item.height());
                },
                update: function (event, ui) {
                    $(this).find('span.handle').addClass('disabled');
                    $.ajax({
                        url: JS_PREFIX_URL + "grid/sortcriterion",
                        type: 'POST',
                        data: {sorted: $(this).sortable("toArray"), rgid: <?php echo $this->grid->getId(); ?>},
                        dataType: "json",
                        success: function (result) {
                            location.reload();
                        },
                        error: function () {
                            $(this).find('span.handle').removeClass('disabled');
                        }
                    });
                },
                placeholder: "placeholder"
            });
        });
    </script>


<?php else : ?>
    <p><?php echo $this->translate("Aucun critère de notation"); ?>.</p>
<?php endif; ?>

<?php if (Episciences_Auth::isSecretary()) : ?>
    <div id="grid-actions">
        <?php if ($this->defaultGrid) : ?>
        <?php if ($this->defaultGrid->getId() != $this->grid->getId()) : ?>
            <a href="<?= $this->url(['controller' => 'grid', 'action' => 'copy', 'from' => $this->defaultGrid->getId(), 'to' => $this->grid->getId()]) ?>">
                <button type="button" class="btn btn-default">
                    <?php echo $this->translate('Copier grille par défaut'); ?>
                </button>
            </a>
            <?php endif; ?>
        <?php endif; ?>

        <a href="<?= $this->url(['controller' => 'grid', 'action' => 'addseparator', 'rgid' => $this->grid->getId(), 'type' => 'separator']) ?>">
            <button type="button" class="btn btn-default">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                <?php echo $this->translate('Ajouter un séparateur'); ?>
            </button>
        </a>

        <a href="<?= $this->url(['controller' => 'grid', 'action' => 'addcriterion', 'rgid' => $this->grid->getId()]) ?>">
            <button type="button" class="btn btn-default">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                <?php echo $this->translate('Ajouter un critère'); ?>
            </button>
        </a>


        <?php if ($this->grid->getCriteria()) : ?>
            <a class="modal-opener"
               href="<?= $this->url(['controller' => 'grid', 'action' => 'view', 'rgid' => $this->grid->getId()])?>"
               data-width="50%">
                <button type="button" class="btn btn-default view-grid">
                    <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>&nbsp;
                    <?php echo $this->translate('Visualiser la grille'); ?>
                </button>
            </a>
        <?php endif; ?>

    <?php if ((int)$this->grid->getId() !== 0) : ?>
        <a class="delete" href="<?= $this->url(['controller' => 'grid', 'action' => 'delete', 'rgid' => $this->grid->getId()]) ?>">
            <button type="button" class="btn btn-danger">
                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>&nbsp;
                <?php echo $this->translate('Supprimer cette grille'); ?>
            </button>
        </a>
    <?php endif; ?>
    </div>


<?php endif; ?>