<?php
$users = $this->users;
$trace = $this->trace;
$message = '';
?>

<?php if (empty($users)) : ?>

    <?php if (array_key_exists('error', $trace)) : ?>

        <?php $message = $trace['error']; ?>

    <?php elseif (array_key_exists('ignore_reviewer', $trace) && $trace['ignore_reviewer']): ?>

        <?php $message = $trace['message']; ?>

    <?php endif; ?>
    <div>
        <br>
        <p class="alert-warning"><?= $message ?></p>
    </div>
<?php else : ?>
    <?php
    $ccsdUsers = [];
    $must = (!$this->is_search_with_mail) ? $this->translate('pouvez') : $this->translate('devez');
    $alert_text = $this->translate('Vous') . ' ' . $must . ' ' . $this->translate('choisir un relecteur dans la liste ci-dessous : ');
    $list_title = '';
    ?>
    <div class="alert alert-info" style="<?php if (!$this->is_search_with_mail) : echo 'margin-top: 20px;'; endif; ?>">
        <h4>
            <strong>
                <?php if (!$this->is_search_with_mail) : ?>
                    <?php
                    $alert_text .= $this->translate("Si votre relecteur n'est pas dans la liste ci-dessous, continuez avec le nouvel utilisateur que vous venez de saisir.");
                    $list_title .= $this->translate('Nous avons trouvé des utilisateurs homonymes :');

                    ?>
                <?php else: ?>
                    <?php
                    $list_title .= $this->translate('Nous avons trouvé des utilisateurs avec une adresse de courriel identique');
                    ?>
                <?php endif; ?>
                <?= $list_title ?>
            </strong>
        </h4>
        <p>
            <i>
                <?= $this->translate($alert_text) ?>
            </i>
        </p>
    </div>

    <div>
        <br>
        <table class="table dataTable hover" id="ccsd_user_invitation">
            <thead>
            <th><?=  $this->translate('Prénom') ?></th>
            <th><?=  $this->translate('Nom') ?></th>
            <th><?=  $this->translate('Identifiant') ?></th>
            <th><?=  $this->translate('Courriel') ?></th>
            <th><?=  $this->translate('Langue') ?></th>
            <th><?=  $this->translate('Invitation(s)') ?></th>
            <th><?=  $this->translate('Relecture(s)') ?></th>
            <th>
                <span class="glyphicon glyphicon-info-sign"
                      data-toggle="tooltip"
                      data-placement="top"
                      title="<?=  $this->translate('Utilisateur de Episciences ?') ?>"
                      style="padding-right: 10px;"
                >
                </span>
            </th>
            </thead>
            <tbody>
            <?php /** @var Episciences_User $user */
            foreach ($users as $user) : ?>
                <?php
                $ccsdUsers[$user->getUid()] = [
                    'firstname' => $this->escape($user->getFirstname()),
                    'lastname' => $this->escape($user->getLastname()),
                    'email' => $this->escape($user->getEmail()),
                    'full_name' => (!$user->getFirstname()) ? $this->escape($user->getLastname()) : $this->escape($user->getLastname() . ' ' . $user->getFirstname()),
                    'user_name' => $user->getUsername(),
                    'locale' => $user->getLangueid()
                ];
                ?>
                <tr
                        id="ccsduser_<?=  $user->getUid() ?>"
                        data-toggle="tooltip"
                        data-placement="top"
                        title="<?=  $this->translate('Inviter ce relecteur') . '...' ?>"
                >
                    <td><?=  $user->getFirstname() ?></td>
                    <td><?=  $user->getLastname() ?></td>
                    <td><?=  $user->getUsername() ?></td>
                    <td><?=  $user->getEmail() ?></td>
                    <td><?=  ucfirst(Zend_Locale::getTranslation($user->getLangueid(), 'language', Episciences_Tools::getLocale())) ?></td>
                    <td class="text-center"><?=  $this->users_stat[$user->getUid()]['invitations_nbr'] ?></td>
                    <td class="text-center"><?=  $this->users_stat[$user->getUid()]['reviewing_complete_nbr'] ?></td>
                    <td>
                        <?php if ($this->users_stat[$user->getUid()]['is_epi_user']): ?>
                            <span class="glyphicon glyphicon-ok-sign text-success"></span>
                        <?php else: ?>
                            <span class="glyphicon glyphicon-minus"></span>

                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <script>

        let ccsd_users = <?=  json_encode($ccsdUsers, JSON_THROW_ON_ERROR) ?>;

        <?php if($this->is_search_with_mail) : ?>
        let  is_search_with_mail = <?=  $this->is_search_with_mail ?>
        <?php endif; ?>

            $(document).ready(function () {
                $('[data-toggle="tooltip"]').tooltip();
                dt_init('ccsd_user_invitation', ccsd_users);
            });

    </script>

<?php endif; ?>



