<p><?php echo $this->translate("Merci d'éviter de la création de plusieurs comptes pour un même utilisateur."); ?></p>

<p><?php echo $this->translate("Possibilités pour inviter un relecteur : "); ?></p>
<ol>
    <li><?php echo $this->translate('Relecteur connu par la revue.'); ?>
    </li>

    <li><?php echo $this->translate("Nouveau relecteur : "); ?>
    </li>
    <ol>
        <li><?php echo $this->translate("Utilisateur connu d'Episciences"); ?></li>
        <li><?php echo $this->translate("Nouvel utilisateur : création d'un compte invité") ?></li>
    </ol>
</ol>

<p><?php echo $this->translate('Merci de vérifier :'); ?></p>

<ul>
    <li> <?php echo $this->translate("Si le relecteur n'est pas connu de la revue, vérifier s'il a un compte dans Episciences."); ?></li>
    <li> <?php echo $this->translate("Si le relecteur est inconnu de la revue, une liste d'utilisateur avec un nom similaire pourra vous être proposée. Merci de vérifier dans cette liste si votre relecteur n'a pas déjà un compte."); ?></li>
</ul>


