<style>
    form#send_form {
        width: 95%;
    }
    .modal-content {
        padding-left: 2%;
    }
</style>
<div class="modal fade" id="modal-box" tabindex="-1" role="dialog" aria-labelledby="journalModal" aria-hidden="true">
    <div class="modal-dialog modal-lg" <?php
    if ($this->style) {
        echo 'style="';
        foreach ($this->style as $property => $value) {
            echo $property . ':' . $value . ';';
        }
        echo '"';
    }
    ?>>
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="modal-title"></h4>
            </div>

            <div class="modal-body">
                <div class="row">
                <?php if ($this->content) : ?>
                    <?php echo $this->content; ?>
                <?php else : ?>
                    <script>$(this).parent('.modal-body').html(getLoader());</script>
                <?php endif; ?>
                </div>
            </div>


            <div class="modal-footer">
                <?php if ($this->buttons !== false) : ?>
                    <button type="button" class="btn btn-default"
                            data-dismiss="modal"><?php echo $this->translate('Annuler'); ?></button>
                    <?php if (!$this->hideSubmit) : ?>
                        <button type="button" class="btn btn-primary"
                                id="submit-modal"><?php echo $this->translate('Valider'); ?></button>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div><!-- /.modal -->
