<?php
$docid = $this->docid;
?>

<div class="panel panel-default collapsable">
    <div class="panel-heading">
        <h2 class="panel-title"><?= $this->translate('Exporter') ?></h2>
    </div>
    <div class="panel-body in" style="overflow: visible">

        <?php

        $exportFormat['bibtex'] = 'BibTeX';
        $exportFormat['tei'] = '<abbr title="Text Encoding Initiative">TEI</abbr>';
        $exportFormat['dc'] = ' <abbr title="Dublin Core">DC</abbr>';
        $exportFormat['datacite'] = 'OpenAIRE';
        $exportFormat['crossref'] = 'Crossref';
        $exportFormat['doaj'] = 'DOAJ';
        $exportFormat['zbjats'] = 'zbJATS';
        $exportFormat['json'] = 'JSON';

        foreach ($exportFormat as $format => $title) {
            $exportUrl = $this->url(['id' => $docid], $format);
            printf('<a class="btn btn-default btn-sm" target="_blank" href="%s">%s</a>&nbsp;', $exportUrl, $title);
        }
        ?>

    </div>
</div>