<?php
/** @var Episciences_Paper $paper */
$paper = $this->paper;

/** @var Episciences_Review $review */
$review = $this->review;
?>


<?php if ($this->displayPaperPasswordBloc) : ?>
    <div class=" panel panel-default collapsable">

        <div class="panel-heading">
            <h2 class="panel-title"><?= $this->translate('Mot de passe papier') ?></h2>
        </div>

        <div class="row">
            <div class="col-sm-6 col-sm-offset-3" style="margin-top: 5px;">

                <?php if ($paper->isOwner()) : ?>
                    <p class="text-justify text-info small">
                        <?= $this->translate("Si vous le souhaitez, vous pouvez partager le mot de passe papier permettant ainsi à la revue de mettre à jour ou de remplacer ce papier dans l'archive ouverte.") ?>
                    </p>
                <?php endif; ?>

                <form method="post" id="paper-password-form">

                    <div class="input-group">
                        <input type="password" class="form-control" name="paperPassword"
                               id="paper-password" <?= $this->paperPassword ? 'value="' . $this->paperPassword . '"' : 'placeholder=' . $this->translate('Secret') ?>
                               autocomplete="off" <?= !$paper->isOwner() ? 'readonly' : '' ?>>
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span id="copy-text" data-toggle="tooltip" title="<?= $this->translate('Copier') ?>"
                                      class="darkgrey fa-solid fa-copy"></span>
                            </button>
                        </span>

                    </div>

                    <div>
                        <input type="checkbox" id="pwd-visibility">
                        <label class="small text-danger"
                               for="pwd-visibility"><?= $this->translate('Afficher le mot de passe') ?></label>
                    </div>
                    <?php if ($paper->isOwner()): ?>
                        <input type="submit" name="savePaperPassword" class="col-xs-12 btn btn-primary btn-sm"
                               value="<?= $this->translate('Enregistrer') ?>" style="margin-bottom: 5px;">
                    <?php endif; ?>

                </form>
            </div>
        </div>
    </div>

    <script>


        let $pwdInput = $('#paper-password');
        let $copyTextElem = $('#copy-text')

        $('#pwd-visibility').on('change', function () {
            $(this).prop('checked') ? $pwdInput.prop('type', 'text') : $pwdInput.prop('type', 'password');
        });

        $copyTextElem.on('click', function () {
            let $this = $(this);

            navigator.clipboard.writeText($pwdInput.val()).then(function () {

                updateTooltipTitle($this, 'Copié !');

            }, function () {
                alert('Failure to write to the clipboard');
            });

        });


        $copyTextElem.on('mouseleave', function () {
            let $this = $(this);
            updateTooltipTitle($this, 'Copier');
        })

    </script>

<?php endif; ?>
