<?php

$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$vid = $this->article->getVid();
$docId = $this->article->getDocid();

?>

<div id="volumes_<?= (int) $docId ?>">

    <?php // master volume ********************************************** ?>
    <div id="master_volume_<?= (int) $docId ?>">
        <?php // master volume assignment button (check if paper is editable) ?>
        <?php if (
            !$this->article->isRefused() &&
            !$this->article->isRemoved() &&
            !$this->article->isObsolete() &&
            !$this->article->isDeleted()): ?>
            <?php if ($this->isPartial): ?>
                <button class="btn btn-default btn-xs" role="button" <?= $this->disabled ?>
                        style="margin-right: 5px"
                        data-modal="master-volume"
                        data-docid="<?= (int) $docId ?>"
                        data-vid="<?= (int) $vid ?>"
                        data-partial="true"
                        data-toggle="tooltip"
                        title="<?= $this->translate('Assigner au volume principal') ?>">
                    <i class="fa-solid fa-pen-to-square"></i>
                </button>
            <?php else: ?>
                <button class="btn btn-default btn-sm" role="button" <?= $this->disabled ?>
                        style="margin-right: 5px"
                        data-modal="master-volume"
                        data-docid="<?= (int) $docId ?>"
                        data-vid="<?= (int) $vid ?>"
                        data-partial="false">
                    <i class="fa-solid fa-pen-to-square" style="margin-right: 5px"></i>
                    <?= $this->translate('Modifier') ?>
                </button>
            <?php endif; ?>
        <?php else: ?>
            <button class="btn btn-default btn-xs disabled" style="margin-right: 5px">
                <i class="fa-solid fa-pen-to-square"></i>
            </button>
        <?php endif; ?>
        <?php if (!$this->isPartial): ?>
            <?= $this->translate('Volume principal :') ?>
        <?php endif; ?>
        <span id="master_volume_name_<?= (int) $docId ?>">
            <?php if ($vid && array_key_exists($vid, $this->volumes)): ?>
                <?= $this->volumes[$vid]->getNameKey() ?>
                <?= $this->partial('partials/paper_volume_position.phtml', [
                    'docId' => $docId,
                    'vid' => $vid,
                    'position' => $this->article->getPosition(),
                    'from' => $action
                ]); ?>
            <?php else: ?>
                <?= $this->translate('aucun') ?>
            <?php endif; ?>
        </span>
    </div>

    <?php if (!$this->isPartial): ?>
        <?php // secondary volumes ********************************************** ?>
        <div id="other_volumes_<?= (int) $docId ?>">
            <?php // secondary volumes assignment button (check if paper is editable) ?>
            <?php if (!$this->article->isRefused() &&
                !$this->article->isRemoved() &&
                !$this->article->isObsolete() &&
                !$this->article->isDeleted()): ?>
                <button class="btn btn-default btn-sm" role="button" <?= $this->disabled ?> <?= $this->ariaDisabled ?>
                        style="margin-right: 5px"
                        data-modal="other-volumes"
                        data-docid="<?= (int) $docId ?>"
                        data-partial="false">
                    <i class="fa-solid fa-pen-to-square" style="margin-right: 5px"></i>
                    <?= $this->translate('Modifier') ?>
                </button>
            <?php else: ?>
                <button class="btn btn-default btn-sm disabled" style="margin-right: 5px">
                    <i class="fa-solid fa-pen-to-square" style="margin-right: 5px"></i>
                    <?= $this->translate('Modifier') ?>
                </button>
            <?php endif; ?>
            <?= $this->translate('Volumes secondaires :') ?>
            <span id="other_volumes_list_<?= (int) $docId ?>"><?= $this->partial('partials/paper_other_volumes.phtml', ['article' => $this->article, 'volumes' => $this->volumes]) ?></span>
        </div>
    <?php endif; ?>

</div>
