<script src="/js/administratepaper/request-doi.js"></script>


<div id="doi-panel" class="panel panel-default collapsable"
     data-doi-assign-mode="<?= $this->doiAssignMode ?>"
     data-paperid="<?= $this->paperid ?>"
     data-docid="<?= $this->docid ?>">
    <div class="panel-heading">
        <h2 class="panel-title"><?php echo $this->translate('DOI'); ?></h2>
    </div>
    <div class="panel-body in">

        <?php
        if ($this->doiQueueStatus) {
            $doiStatusText = $this->translate($this->doiQueueStatus);
            echo '<span id="doi-status" class="doi-status">' . sprintf($this->doiQueueStatusHtml, $doiStatusText) . '</span>';
        } else {
            echo '<span id="doi-status" class="doi-status"></span>';
        }
        ?>
        <div id="doi-status-loader" style="display: none;"></div>
        <?php
        if ($this->paperDoi) {
            echo '<span id="doi-link" class="doi-link">' . $this->DoiAsLink($this->paperDoi) . '</span>';
            $doiActionText = $this->translate('Mettre à jour le DOI');
        } else {
            echo '<span id="doi-link" class="doi-link"></span>';
            $doiActionText = $this->translate('Ajouter un DOI');
        }

        ?>

        <?php if (($this->canBeAssignedDOI) && (Episciences_Auth::isAllowedToManageDoi())) : ?>
            <?php if ($this->doiQueueStatus === Episciences_Paper_DoiQueue::STATUS_MANUAL)  : ?>
                <button id="doi-action" class="btn btn-default btn-sm popover-link edit-doi" style="margin-left: 5px"
                        onclick="getDoiForm(this, <?php echo $this->paperid ?>)">
                    <span class="fas fa-edit" style="margin-right: 5px"></span><?php echo $doiActionText; ?>
                </button>
            <?php endif; ?>


       <?php //not assigned ?>
            <?php if ($this->doiQueueStatus === Episciences_Paper_DoiQueue::STATUS_NOT_ASSIGNED): ?>

            <?php // auto ?>
                <?php if ($this->doiAssignMode !== Episciences_Review_DoiSettings::DOI_ASSIGN_MODE_DISABLED): ?>
                    <button id="requestNewDoi" data-docid="<?php echo $this->docid ?>"
                            class="btn btn-default btn-sm popover-link" style="margin-left: 5px">
                <span class="fas fa-robot"
                      style="margin-right: 5px"></span><?php echo $this->translate('Demander un DOI'); ?>
                    </button>

                <?php // Disabled:  manual input by journal ?>
                <?php else : ?>


                    <button class="btn btn-default btn-sm popover-link edit-doi" style="margin-left: 5px"
                            onclick="getDoiForm(this, <?= $this->paperid ?>)">
                        <span class="glyphicon glyphicon glyphicon-cog" style="margin-right: 5px"></span>
                        <?= $this->translate($doiActionText) ?>
                    </button>

                <?php endif; ?>
            <?php endif; ?>


        <?php endif; ?>
        <?php if ($this->doiQueueStatus === Episciences_Paper_DoiQueue::STATUS_ASSIGNED
            && Episciences_Auth::isAllowedToManageDoi()) : ?>
            <button id="removeDoi" data-paperid="<?php echo $this->paperid ?>"
                    data-docid="<?php echo $this->docid ?>"
                    class="btn btn-default btn-sm popover-link"
                    style="margin-left: 5px"
                    onclick="removeDoi(this,<?= $this->paperid ?>,<?= $this->docid ?>,'<?= $this->paperDoi ?>')">
                <span class="fa-solid fa-rotate-left"
                      style="margin-right: 5px"></span><?php echo $this->translate('Annuler le DOI'); ?>
            </button>
        <?php endif; ?>
    </div>

</div>