<?php

$isAskAuthorsFinalVersionEnabled = $this->review->getSetting(Episciences_Review::SETTING_SYSTEM_PAPER_FINAL_DECISION_ALLOW_REVISION);
$suggestionInfoMsg = "Votre suggestion à déjà été enregistrée.";
/** @var Episciences_Paper $paper */
$paper = $this->paper;
$status = $paper->getStatus();
$changeStatusMsg = "Changer le statut de l'article";
$publishMsg = "Publier l'article";
$refusalMsg = "Refuser l'article";

if ($paper->isTmp()) {
    $acceptMsg = 'Demander la version définitive';
} else if (!$isAskAuthorsFinalVersionEnabled) {
    $acceptMsg = 'Accepter et passer à la préparation de copie';
} else {
    $acceptMsg = "Accepter l'article";
}

$acceptedAskAuthorFinalVersion = "Accepté - en attente de la version finale";
$waitingAuthorSources = "Demander à l'auteur ses sources (À mettre en forme par la revue)";
$waitingFinalVersion = "Demander la version finale (À mettre en forme par l’auteur)";
$reviewFormattingMsg = 'Mise en forme revue terminée, demander la version finale';
$validFinalVersionMsg = 'Accepter comme version finale';
$assignedCopyEditors = $paper->getCopyEditors();
$isAssignedCopyEditors = !empty($assignedCopyEditors);
$copyEditingNotStarted = !$paper->isCopyEditingProcessStarted();
$isInRevision = $paper->isRevisionRequested();
$isNotTheFirstVersion = empty($paper->getPreviousVersions());
$askSourcesAgainMsg = "Redemander à l'auteur ses sources (À mettre en forme par la revue)";
$askFinalVersionAgainMsg = "Demander à nouveau la version finale à l'auteur";
$acceptedWaitingForAuthorValidation = "Accepté - en attente de validation par l'auteur";
// For the copy editors
$onBeHalfOfMsg  = $this->translate("Répondre au nom de l'auteur");

$description = '';
$ancre = '';
if (array_key_exists(Episciences_Auth::getUid(), $assignedCopyEditors)) {
    if ($paper->isAlreadyAcceptedWaitingForAuthorFinalVersion()) {
        $ancre = '#answer';
    } elseif ($paper->isCopyEditingProcessStarted()) {
        $ancre = '#copy-editing';
    }

    $description .= '<small>';
    $description .= '<em>';
    $description .= $this->translate("L'auteur n'a pas encore répondu :");
    $description .= '<br>';
    $description .= $this->translate("Aucune action n'est requise de votre part");
    $description .= ', ';
    $description .= $this->translate("Il n'est donc pas possible de modifier le statut de l'article.");
    $description .= '<br>';
    $description .= '</em>';
    $description .= '</small>';
}


// **** CHIEF EDITORS, administrator and secretary (git #235) : can do whatever they want *****************************
if (Episciences_Auth::isSecretary()) : ?>
    <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <?= $this->translate($changeStatusMsg) ?> <span class="caret" style="margin-left: 5px"></span>
        </button>
        <ul class="status-menu dropdown-menu" role="menu">
            <?php if ($paper->isReadyToPublish()) : ?>
                <!-- publication request -->
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".publication-modal"><?= $this->translate($publishMsg) ?>
                    </a>
                </li>

                <!-- revision request -->
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".minor-revision-modal"><?= $this->translate('Demander des modifications mineures') ?></a>
                </li>

                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".major-revision-modal"><?= $this->translate('Demander des modifications majeures') ?></a>
                </li>

            <?php elseif ($paper->isAccepted()) : ?>
                <?php // Ask author's final version  ?>
                <?php if ($isAskAuthorsFinalVersionEnabled) : ?>
                    <li>
                        <a href="#" data-toggle="modal"
                           data-target=".accepted-ask-author-final-version-modal"><?= $this->translate($acceptedAskAuthorFinalVersion) ?></a>
                    </li>
                <?php endif; ?>

                <?php // Préparation de copie: en attente des sources auteurs?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".waiting-for-author-sources-modal"><?= $this->translate($waitingAuthorSources) ?>
                    </a>
                </li>
                <?php // Préparation de copie: en attente de de la mise en forme auteur ?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".waiting-for-author-formatting-modal"><?= $this->translate($waitingFinalVersion) ?>
                    </a>
                </li>

                <!-- publish paper -->
                <?php if ($copyEditingNotStarted && !$paper->isTmp()) : ?>
                    <li>
                        <a href="#" data-toggle="modal"
                           data-target=".publication-modal"><?= $this->translate($publishMsg) ?>
                        </a>
                    </li>
                <?php endif; ?>

            <?php elseif ($status === Episciences_Paper::STATUS_ACCEPTED_FINAL_VERSION_SUBMITTED_WAITING_FOR_COPY_EDITORS_FORMATTING) : ?>

                <?php if ($isAskAuthorsFinalVersionEnabled) : ?>

                    <li>
                        <a href="#" data-toggle="modal"
                           data-target=".review-formatting-accepted-ask-author-validation-modal"
                           onclick="editAttachmentDescription($(this));"><?= $this->translate($acceptedWaitingForAuthorValidation) ?></a>
                    </li>


                    <li>
                        <a href="#" data-toggle="modal"
                           data-target=".accepted-ask-author-final-version-modal"><?= $this->translate($acceptedAskAuthorFinalVersion) ?></a>
                    </li>

                <?php else: ?>

                    <?php // Copy ed. : mise en forme par la revue terminée?>
                    <li>
                        <a href="#" data-toggle="modal"
                           data-target=".review-formatting-submitted-modal"
                           onclick="editAttachmentDescription($(this));"><?= $this->translate($reviewFormattingMsg) ?>
                        </a>
                    </li>
                <?php endif; ?>

            <?php elseif ($status === Episciences_Paper::STATUS_CE_AUTHOR_SOURCES_DEPOSED) : ?>
                <?php // Copy ed. : mise en forme revue terminée?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".review-formatting-submitted-modal"
                       onclick="editAttachmentDescription($(this));"><?= $this->translate($reviewFormattingMsg) ?>
                    </a>
                </li>

                <?php // Préparation de copie: redemander les sources?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".waiting-for-author-sources-modal"><?= $this->translate($askSourcesAgainMsg) ?>
                    </a>
                </li>

            <?php elseif ($status === Episciences_Paper::STATUS_CE_AUTHOR_FINAL_VERSION_DEPOSED) : ?>

                <?php // Préparation de copie: prêt à publier ?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".ready-to-publish-modal"><?= $this->translate($validFinalVersionMsg) ?>
                    </a>
                </li>

                <?php // Préparation de copie: redemander la mise en forme à l'auteur ?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".waiting-for-author-formatting-modal"><?= $this->translate($askFinalVersionAgainMsg) ?>
                    </a>
                </li>

            <?php elseif (!$isInRevision && $copyEditingNotStarted) : ?>
                <!-- accept paper -->
                <li><a href="#" data-toggle="modal"
                       data-target=".acceptance-modal"><?= $this->translate($acceptMsg) ?></a>
                </li>

                <!-- revision request -->
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".minor-revision-modal"><?= $this->translate('Demander des modifications mineures') ?></a>
                </li>

                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".major-revision-modal"><?= $this->translate('Demander des modifications majeures') ?></a>
                </li>

            <?php elseif ($status === Episciences_Paper::STATUS_ACCEPTED_WAITING_FOR_AUTHOR_VALIDATION) : ?>

                <?php if ($isAskAuthorsFinalVersionEnabled) : ?>

                    <li>
                        <a href="#" data-toggle="modal"
                           data-target=".accepted-ask-author-final-version-modal"><?= $this->translate($acceptedAskAuthorFinalVersion) ?></a>
                    </li>

                <?php else: ?>

                    <?php // Copy ed. : mise en forme par la revue terminée?>
                    <li>
                        <a href="#" data-toggle="modal"
                           data-target=".review-formatting-submitted-modal"
                           onclick="editAttachmentDescription($(this));"><?= $this->translate($reviewFormattingMsg) ?>
                        </a>
                    </li>
                <?php endif; ?>

            <?php endif; ?>

            <!-- ask other editors -->
            <?php if (!empty($this->other_editors)) : ?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".ask-other-editors-modal"><?= $this->translate("Demander l'avis d'autres rédacteurs") ?></a>
                </li>
            <?php else : ?>
                <li data-toggle="tooltip" data-placement="top"
                    title="<?= $this->translate("Il n'y a pas d'autres rédacteurs à qui demander un avis.") ?>">
                    <a class="disabled"><?= $this->translate("Demander l'avis d'autres rédacteurs") ?></a>
                </li>
            <?php endif; ?>

            <!-- reject paper -->
            <li>
                <a href="#" data-toggle="modal"
                   data-target=".refusal-modal"><?= $this->translate($refusalMsg) ?></a>
            </li>
        </ul>
    </div>

<?php
// **** EDITORS: can do some stuff, depending of journal settings *****************************
elseif (Episciences_Auth::isEditor() || Episciences_Auth::isGuestEditor()) : ?>
    <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <?= $this->translate($changeStatusMsg) ?> <span class="caret" style="margin-left: 5px"></span>
        </button>
        <ul class="status-menu dropdown-menu" role="menu">

            <?php if ($paper->isAccepted()) : ?>

                <?php // Préparation de copie: en attente des sources auteurs?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".waiting-for-author-sources-modal"><?= $this->translate($waitingAuthorSources) ?>
                    </a>
                </li>

                <?php // Préparation de copie: en attente de de la mise en forme auteur ?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".waiting-for-author-formatting-modal"><?= $this->translate($waitingFinalVersion) ?>
                    </a>
                </li>

                <?php if ($copyEditingNotStarted && $this->review->getSetting('editorsCanPublishPapers')) :    // editors have permission to publish papers ?>
                    <?php if (
                        $this->isRequiredReviewersOk ||
                        $isNotTheFirstVersion ||                         // if this is not the first version of this paper
                        !$this->review->getSetting('requiredReviewers')  // if there is no minimum number of rating reports, or it has been matched
                    ) : ?>

                        <?php // PUBLISH PAPER?>
                        <li>
                            <a href="#" data-toggle="modal"
                               data-target=".publication-modal"><?= $this->translate($publishMsg) ?></a>
                        </li>

                    <?php else : // if there is not enough rating reports, display a notice ?>
                        <li data-toggle="tooltip"
                            data-placement="right"
                            title="<?= $this->translate("Vous ne pouvez pas publier cet article, car le nombre minimum de relectures (%s) n'a pas été atteint.", $this->review->getSetting('requiredReviewers')) ?>">
                            <a class="disabled"><?= $this->translate($publishMsg) ?></a>
                        </li>
                    <?php endif; ?>
                <?php else: ?>
                    <?php // recommandation de publier l'article?>
                <?php endif; ?>

            <?php elseif ($status === Episciences_Paper::STATUS_CE_AUTHOR_SOURCES_DEPOSED) : ?>
                <?php // Copy ed. : mise en forme revue terminée?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".review-formatting-submitted-modal"
                       onclick="editAttachmentDescription($(this));"><?= $this->translate($reviewFormattingMsg) ?>
                    </a>
                </li>

                <?php // Préparation de copie: redemander les sources?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".waiting-for-author-sources-modal"><?= $this->translate($askSourcesAgainMsg) ?>
                    </a>
                </li>

            <?php elseif ($status === Episciences_Paper::STATUS_CE_AUTHOR_FINAL_VERSION_DEPOSED) : ?>

                <?php // Préparation de copie: prêt à publier ?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".ready-to-publish-modal"><?= $this->translate($validFinalVersionMsg) ?>
                    </a>
                </li>

                <?php // Préparation de copie: redemander la mise en forme à l'auteur ?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".waiting-for-author-formatting-modal"><?= $this->translate($askFinalVersionAgainMsg) ?>
                    </a>
                </li>

            <?php elseif ($paper->isReadyToPublish()) : ?>
                <?php if ($this->review->getSetting('editorsCanPublishPapers')) : ?>
                    <li>
                        <a href="#" data-toggle="modal"
                           data-target=".publication-modal"><?= $this->translate($publishMsg) ?></a>
                    </li>
                <?php else: ?>
                    <?php // recommandation de publier?>
                <?php endif; ?>

                <?php // ACCEPT PAPER ************    ?>
            <?php else: ?>
                <?php if (!$isInRevision && $copyEditingNotStarted && $this->review->getSetting('editorsCanAcceptPapers')) :    // editors have permission to accept papers ?>
                    <?php if (
                        $this->isRequiredReviewersOk ||
                        $isNotTheFirstVersion ||                         // if this is not the first version of this paper
                        !$this->review->getSetting('requiredReviewers')  // if there is no minimum number of rating reports, or it has been matched

                    ) : ?>
                        <li>
                            <a href="#" data-toggle="modal"
                               data-target=".acceptance-modal"><?= $this->translate($acceptMsg) ?></a>
                        </li>
                    <?php else : // if there is not enough rating reports, display a notice ?>
                        <li data-toggle="tooltip"
                            data-placement="right"
                            title="<?= $this->translate("Vous ne pouvez pas accepter cet article, car le nombre minimum de relectures (%s) n'a pas été atteint.", $this->review->getSetting('requiredReviewers')) ?>">
                            <a class="disabled"><?= $this->translate($acceptMsg) ?></a>
                        </li>
                    <?php endif; ?>

                <?php elseif (!$paper->isReadyToPublish() && !$paper->isAcceptedSubmission()): // editors do not have permission to accept papers, but can suggest to do it ?>
                    <li onclick="showForm('accept'); return false;"
                        data-toggle="tooltip"
                        data-placement="right"
                        title="<?= $this->suggestedAccept ? $this->translate($suggestionInfoMsg) : '' ?>"
                    >
                        <a <?= !$this->suggestedAccept ? 'href="#" data-toggle="modal" data-target=".suggestions-status-modal"' : 'class="disabled"' ?>><?= $this->translate("Recommander d'accepter l'article") ?></a>
                    </li>
                <?php endif; ?>
            <?php endif; ?>

            <?php // REJECT PAPER ************    ?>
            <?php if ($this->review->getSetting('editorsCanRejectPapers')) :    // editors have permission to reject papers ?>
                <?php if ($isNotTheFirstVersion) : // if this is not the first version of this paper ?>
                    <li>
                        <a href="#" data-toggle="modal"
                           data-target=".refusal-modal"><?= $this->translate($refusalMsg) ?>
                        </a>
                    </li>
                <?php else : // display a notice ?>
                    <li data-toggle="tooltip" data-placement="right"
                        title="<?= $this->translate("Cet article n'est pas la première version de ce document, vous ne pouvez pas donc le refuser.") ?>">
                        <a class="disabled"><?= $this->translate($refusalMsg) ?></a>
                    </li>
                <?php endif; ?>
            <?php else : // editors do not have permission to reject papers, but can suggest to do it?>
                <li onclick="showForm('refuse'); return false;"
                    data-toggle="tooltip"
                    data-placement="right"
                    title="<?= $this->suggestedRefuse ? $this->translate($suggestionInfoMsg) : '' ?>"
                >
                    <a <?= !$this->suggestedRefuse ? 'href="#" data-toggle="modal" data-target=".suggestions-status-modal"' : 'class="disabled"' ?>><?= $this->translate("Recommander de refuser l'article") ?></a>
                </li>
            <?php endif; ?>

            <?php // ASK FOR A REVISION ************    ?>
            <?php if ($copyEditingNotStarted && $this->review->getSetting('editorsCanAskPaperRevisions')) :    // editors have permission to ask for a revision ?>
                <?php if (
                    $this->isRequiredReviewersOk ||
                    $isNotTheFirstVersion ||                         // if this is not the first version of this paper
                    !$this->review->getSetting('requiredReviewers')  // if there is no minimum number of rating reports, or it has been matched

                ) : ?>
                    <?php if (!$isInRevision) : ?>
                        <li>
                            <a href="#" data-toggle="modal"
                               data-target=".minor-revision-modal"><?= $this->translate('Demander des modifications mineures') ?></a>
                        </li>
                        <li><a href="#" data-toggle="modal"
                               data-target=".major-revision-modal"><?= $this->translate('Demander des modifications majeures') ?></a>
                        </li>
                    <?php endif; ?>
                <?php else : // if there is not enough rating reports, display a notice ?>
                    <li data-toggle="tooltip"
                        data-placement="right"
                        title="<?= $this->translate("Vous ne pouvez faire de demande de modifications, car le nombre minimum de relectures (%s) n'a pas été atteint.", $this->review->getSetting('requiredReviewers')) ?>">
                        <a class="disabled"><?= $this->translate("Demander des modifications") ?></a>
                    </li>
                <?php endif; ?>
            <?php else : // editors do not have permission to reject papers, but can suggest to do it?>
                <li onclick="showForm('newversion'); return false;"
                    data-toggle="tooltip"
                    data-placement="right"
                    title="<?= $this->suggestedRevision ? $this->translate($suggestionInfoMsg) : '' ?>"
                >
                    <a <?= !$this->suggestedRevision ? 'href="#" data-toggle="modal" data-target=".suggestions-status-modal"' : 'class="disabled"' ?>><?= $this->translate("Suggérer de demander une nouvelle version") ?></a>
                </li>
            <?php endif; ?>

            <!-- ask other editors -->
            <?php if (!$paper->isEditable()) : ?>
                <?php if (!empty($this->other_editors)) : ?>
                    <!-- ASK OTHER EDITORS -->
                    <li>
                        <a href="#" data-toggle="modal"
                           data-target=".ask-other-editors-modal"><?= $this->translate("Demander l'avis d'autres rédacteurs") ?></a>
                    </li>
                <?php else : ?>
                    <li data-toggle="tooltip" data-placement="top"
                        title="<?= $this->translate("Il n'y a pas d'autres rédacteurs à qui demander un avis.") ?>">
                        <a class="disabled"><?= $this->translate("Demander l'avis d'autres rédacteurs") ?></a>
                    </li>
                <?php endif; ?>
            <?php endif; ?>
        </ul>
    </div>
    <?php // Copy editor?>
<?php elseif (Episciences_Auth::isCopyEditor()) : ?>
    <div class="btn-group">
        <?php if ($paper->isAccepted()) : ?>
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <?= $this->translate($changeStatusMsg) ?> <span class="caret" style="margin-left: 5px"></span>
            </button>
            <ul class="status-menu dropdown-menu" role="menu">
                <?php // ask author's final version  ?>
                <?php if ($isAskAuthorsFinalVersionEnabled) : ?>
                    <li>
                        <a href="#" data-toggle="modal"
                           data-target=".accepted-ask-author-final-version-modal"><?= $this->translate($acceptedAskAuthorFinalVersion) ?></a>
                    </li>
                <?php endif; ?>

                <?php // Préparation de copie: en attente des sources auteurs?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".waiting-for-author-sources-modal"><?= $this->translate($waitingAuthorSources) ?></a>
                </li>

                <?php // Préparation de copie: en attente de de la mise en forme auteur ?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".waiting-for-author-formatting-modal"><?= $this->translate($waitingFinalVersion) ?></a>
                </li>
            </ul>

        <?php elseif ($status === Episciences_Paper::STATUS_CE_AUTHOR_SOURCES_DEPOSED) : ?>
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <?= $this->translate($changeStatusMsg) ?> <span class="caret" style="margin-left: 5px"></span>
            </button>
            <ul class="status-menu dropdown-menu" role="menu">
                <?php // Copy ed. : mise en forme par la revue terminée ?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".review-formatting-submitted-modal"
                       onclick="editAttachmentDescription($(this));"><?= $this->translate($reviewFormattingMsg) ?>
                    </a>
                </li>

                <?php // Préparation de copie: redemander les sources?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".waiting-for-author-sources-modal"><?= $this->translate($askSourcesAgainMsg) ?>
                    </a>
                </li>
            </ul>

        <?php elseif ($status === Episciences_Paper::STATUS_CE_AUTHOR_FINAL_VERSION_DEPOSED) : ?>

            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <?= $this->translate($changeStatusMsg) ?> <span class="caret" style="margin-left: 5px"></span>
            </button>
            <ul class="status-menu dropdown-menu" role="menu">

                <?php // Préparation de copie : prêt à publier ?>

                <a href="#" data-toggle="modal" class="btn btn-primary btn-sm"
                   data-target=".ready-to-publish-modal"><?= $this->translate($validFinalVersionMsg) ?></a>

                <?php // Préparation de copie: redemander la mise en forme à l'auteur ?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".waiting-for-author-formatting-modal"><?= $this->translate($askFinalVersionAgainMsg) ?>
                    </a>
                </li>
            </ul>

        <?php elseif ($status === Episciences_Paper::STATUS_ACCEPTED_FINAL_VERSION_SUBMITTED_WAITING_FOR_COPY_EDITORS_FORMATTING) : ?>

            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <?= $this->translate($changeStatusMsg) ?> <span class="caret" style="margin-left: 5px"></span>
            </button>

            <ul class="status-menu dropdown-menu" role="menu">

                <?php if ($isAskAuthorsFinalVersionEnabled) : ?>
                    <li>
                        <a href="#" data-toggle="modal"
                           data-target=".review-formatting-accepted-ask-author-validation-modal"
                           onclick="editAttachmentDescription($(this));"><?= $this->translate($acceptedWaitingForAuthorValidation) ?></a>
                    </li>


                    <li>
                        <a href="#" data-toggle="modal"
                           data-target=".accepted-ask-author-final-version-modal"><?= $this->translate($acceptedAskAuthorFinalVersion) ?></a>
                    </li>

                <?php else: ?>

                    <?php // Copy ed. : mise en forme par la revue terminée?>
                    <li>
                        <a href="#" data-toggle="modal"
                           data-target=".review-formatting-submitted-modal"
                           onclick="editAttachmentDescription($(this));"><?= $this->translate($reviewFormattingMsg) ?>
                        </a>
                    </li>
                <?php endif; ?>

            </ul>

        <?php elseif ($status === Episciences_Paper::STATUS_APPROVED_BY_AUTHOR_WAITING_FOR_FINAL_PUBLICATION) : ?>
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <?= $this->translate($changeStatusMsg) ?> <span class="caret" style="margin-left: 5px"></span>
            </button>

            <ul class="status-menu dropdown-menu" role="menu">
                <!-- publication request -->
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".publication-modal"><?= $this->translate($publishMsg) ?>
                    </a>
                </li>
            </ul>

        <?php else: ?>
        <div>
            <?= $description ?>
            <a href="<?= $this->paperUrl . $ancre ?>" class="btn btn-default btn-sm" role="button" style="margin-top: 5px;"><?= $onBeHalfOfMsg ?></a>
            <?php endif; ?>

        </div>

    </div>

<?php endif ?>

<?php // ******* MODALS (FORMS) ***************** ?>
<?php if (Episciences_Auth::isAllowedToManagePaper()) : ?>
    <?php // *** publication form ************ ?>
    <?php if ($paper->isAccepted() || $paper->isReadyToPublish()) : ?>
        <?=
        $this->partial('partials/paper-status-modal.phtml', [
            'target' => 'publication-modal',
            'title' => $publishMsg,
            'body' => $this->publicationForm
        ]) ?>

    <?php
// *** acceptation form ************
    else: ?>

        <?=
        $this->partial('partials/paper-status-modal.phtml', [
            'target' => 'acceptance-modal',
            'title' => $acceptMsg,
            'body' => $this->acceptanceForm
        ]) ?>

    <?php endif; ?>

    <?php // *** minor revision request form ********** ?>
    <?=
    $this->partial('partials/paper-status-modal.phtml', [
        'target' => 'minor-revision-modal',
        'title' => 'Demander des modifications mineures',
        'body' => $this->minorRevisionForm
    ]) ?>

    <?php // *** major revision request form ********** ?>
    <?=
    $this->partial('partials/paper-status-modal.phtml', [
        'target' => 'major-revision-modal',
        'title' => 'Demander des modifications majeures',
        'body' => $this->majorRevisionForm
    ]) ?>

    <?php // *** reject form ********** ?>
    <?=
    $this->partial('partials/paper-status-modal.phtml', [
        'target' => 'refusal-modal',
        'title' => $refusalMsg,
        'body' => $this->refusalForm
    ]) ?>

    <?php // *** ask other editors form ********** ?>
    <?php if (!empty($this->other_editors)) : ?>
        <?=
        $this->partial('partials/paper-status-modal.phtml', [
            'target' => 'ask-other-editors-modal',
            'title' => "Demander l'avis d'autres rédacteurs",
            'body' => $this->askOtherEditorsForm
        ]) ?>
    <?php endif; ?>

    <?php // *** suggestions status  ********** ?>
    <?php if ($this->suggestionsStatusForm) : ?>
        <?=
        $this->partial('partials/paper-status-modal.phtml', [
            'target' => 'suggestions-status-modal',
            'title' => 'Suggestions',
            'body' => $this->suggestionsStatusForm,
            'withoutFooter' => true
        ]) ?>

    <?php endif; ?>
<?php endif; ?>

<?php if (Episciences_Auth::isCopyEditor() || Episciences_Auth::isSecretary()) : ?>
    <?php // accepted article: ask author's final version  ?>
    <?=
    $this->partial('partials/paper-status-modal.phtml', [
        'target' => 'accepted-ask-author-final-version-modal',
        'title' => $acceptedAskAuthorFinalVersion,
        'body' => $this->acceptedAskAuthorFinalVersionForm
    ]) ?>

    <?php // : Accepted - waiting for authors to validate ?>
    <?=
    $this->partial('partials/paper-status-modal.phtml', [
        'target' => 'review-formatting-accepted-ask-author-validation-modal',
        'title' => $acceptedWaitingForAuthorValidation,
        'body' => $this->acceptedAskAuthorValidationForm
    ]) ?>

    <?php if ($paper->isApprovedByAuthor()) : ?>

        <?=
        $this->partial('partials/paper-status-modal.phtml', [
            'target' => 'publication-modal',
            'title' => $publishMsg,
            'body' => $this->publicationForm
        ]) ?>

    <?php endif; ?>


<?php endif; ?>

<?php // Waiting for author sources request ?>
<?=
$this->partial('partials/paper-status-modal.phtml', [
    'target' => 'waiting-for-author-sources-modal',
    'title' => 'Demander des sources auteur',
    'body' => $this->authorSourcesRequestForm
]) ?>

<?php // Waiting for author  formatting (last version)?>
<?=
$this->partial('partials/paper-status-modal.phtml', [
    'target' => 'waiting-for-author-formatting-modal',
    'title' => "Demander la mise en forme par l'auteur (version finale)",
    'body' => $this->authorFormattingRequestForm
]) ?>

<?php // la mise en forme par la revue est terminée ?>
<?=
$this->partial('partials/paper-status-modal.phtml', [
    'target' => 'review-formatting-submitted-modal',
    'title' => $reviewFormattingMsg,
    'body' => $this->reviewFormattingDeposedForm
]) ?>

<?php // ready to publish :  once the final version is submitted ?>
<?=
$this->partial('partials/paper-status-modal.phtml', [
    'target' => 'ready-to-publish-modal',
    'title' => $validFinalVersionMsg,
    'body' => $this->ceAcceptFinalVersionForm
]) ?>


