<?php
/** @var Episciences_Paper $paper */
$paper = $this->paper;
$first = key($this->author_comments);
$isAllowedToEditComment = (
        !in_array($paper->getStatus(), $paper::$_noEditableStatus, true) &&
        (
                (
                        Episciences_Auth::isSecretary() &&
                        Zend_Controller_Front::getInstance()->getRequest()->getControllerName() === PaperDefaultController::ADMINISTRATE_PAPER_CONTROLLER
                ) ||
                $paper->isOwner()
        )
);
?>
<div id="author_comments" style="max-height: 200px; overflow: auto">

    <?php if (!$this->author_comments) : ?>
        <?php if ($isAllowedToEditComment): ?>
            <?php $addCommentUrl = '/comments/addcomment/docid/' . $paper->getDocid() ?>
            <button class="btn btn-default btn-xs pull-right" style="margin-right:9px;"
                    onclick="javascript:location.href='<?= $addCommentUrl ?>'">
                    <span class="glyphicon glyphicon-plus-sign"
                          style="margin-right: 5px;"></span><?= $this->translate('Ajouter') ?>
            </button>
        <?php endif; ?>
    <?php else : ?>
        <?php foreach ($this->author_comments as $key => $value) : ?>

            <?php $margin = ($key === $first) ? '0' : '20px'; ?>
            <div style="margin-top: <?= $margin; ?>" class="small">
                <strong><?= $this->translate('Soumis le : ') . $this->Date($value['WHEN'], null, Zend_Date::DATE_LONG . ' - ' . Zend_Date::TIME_SHORT); ?>
                    : </strong>
                [<?= ($value['UID'] == Episciences_Auth::getUid()) ? $this->translate('vous') : $value['SCREEN_NAME'] ?>
                ]
                <?php if ($isAllowedToEditComment): ?>
                    <?php $edit_comment_url = '/comments/editcomment/pcid/' . $value['PCID']; ?>
                    <button class="btn btn-default btn-xs pull-right" style="margin-right:9px;"
                            onclick="javascript:location.href='<?= $edit_comment_url ?>'">
                    <span class="glyphicon glyphicon-pencil"
                          style="margin-right: 5px;"></span><?= $this->translate('Modifier') ?>
                    </button>
                <?php endif; ?>
                <div><?= Episciences_Tools::formatText($this->escape($value['MESSAGE'])) ?></div>

                <?php if ($value['FILE']) : ?>
                    <table class="table" id="tableCoverLetter">
                        <thead>
                        <tr>
                            <th style="border: none;"><?php echo $this->translate("Lettre d'accompagnement"); ?></th>
                            <!--th style="text-align: right"><?php echo $this->translate('Action'); ?></th-->
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                <a href="/docfiles/comments/<?php echo $value['DOCID'] . '/' . $value['FILE'] ?>"
                                   target="_blank">
                                    <?php echo $value['FILE']; ?>
                                </a>
                            </td>
                            <td style="text-align: right">
                                <?php echo $this->partial('partials/remove_file_comment.phtml', ['comment' => $value]); ?>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>

    <?php endif ?>
</div>












