<?php
$logs_with_details = [
    Episciences_Paper_Logger::CODE_MAIL_SENT,
    Episciences_Paper_Logger::CODE_REMINDER_SENT,
    Episciences_Paper_Logger::CODE_EDITOR_ASSIGNMENT,
    Episciences_Paper_Logger::CODE_EDITOR_UNASSIGNMENT,
    Episciences_Paper_Logger::CODE_REVIEWER_INVITATION,
    Episciences_Paper_Logger::CODE_REVIEWER_INVITATION_ACCEPTED,
    Episciences_Paper_Logger::CODE_REVIEWER_INVITATION_DECLINED,
    Episciences_Paper_Logger::CODE_ABANDON_PUBLICATION_PROCESS,
    Episciences_Paper_Logger::CODE_CONTINUE_PUBLICATION_PROCESS,
    Episciences_Paper_Logger::CODE_COPY_EDITOR_ASSIGNMENT,
    Episciences_Paper_Logger::CODE_COPY_EDITOR_UNASSIGNMENT,
    Episciences_Paper_Logger::CODE_CE_AUTHOR_SOURCES_REQUEST,
    Episciences_Paper_Logger::CODE_CE_AUTHOR_SOURCES_DEPOSED,
    Episciences_Paper_Logger::CODE_NEW_PAPER_COMMENT,
    Episciences_Paper_Logger::CODE_CE_AUTHOR_FINALE_VERSION_REQUEST,
    Episciences_Paper_Logger::CODE_CE_AUTHOR_FINALE_VERSION_DEPOSED,
    Episciences_Paper_Logger::CODE_CE_REVIEW_FORMATTING_DEPOSED,
    Episciences_Paper_Logger::CODE_CE_AUTHOR_FINAL_VERSION_SUBMITTED,
    Episciences_Paper_Logger::CODE_CE_READY_TO_PUBLISH,
    Episciences_Paper_Logger::CODE_AUTHOR_COMMENT_COVER_LETTER,
    Episciences_Paper_Logger::CODE_EDITOR_COMMENT,
    Episciences_Paper_Logger::CODE_REVISION_REQUEST_TMP_VERSION,
    Episciences_Paper_Logger::CODE_PAPER_COMMENT_FROM_REVIEWER_TO_CONTRIBUTOR,
    Episciences_Paper_Logger::CODE_PAPER_COMMENT_FROM_CONTRIBUTOR_TO_REVIEWER,
    Episciences_Paper_Logger::CODE_COI_REPORTED
]; ?>

<?php foreach ($this->logs as $log) : ?>

    <?php if (in_array($log['ACTION'], $logs_with_details, false)) : ?>
        <a    class="modal-opener"
        href="/administratepaper/log?id=<?php echo $log['LOGID'] ?>"
        data-width="50%"
        title="<?php echo $this->translate($log['ACTION']) ?>">
    <?php endif; ?>

    <div
            style="padding:5px; margin-bottom:5px; margin-right: 5px" role="alert"
            data-date="<?php echo $this->Date($log['DATE'], null, 'MM/dd/y'); ?>"
            data-time="<?php echo $this->Date($log['DATE'], null, Zend_Date::TIME_MEDIUM); ?>"
            class="log-entry <?php echo $log['ACTION']; ?> alert alert-<?php echo Episciences_Paper_Logger::$_css[$log['ACTION']]; ?> alert-fixed">

        <span style="font-size:11px; margin-right: 5px"
              class="label label-<?php echo Episciences_Paper_Logger::$_css[$log['ACTION']]; ?>">
            <?php echo $this->Date($log['DATE'], null, Zend_Date::DATE_MEDIUM . ' ' . Zend_Date::TIME_MEDIUM); ?>
        </span>

        <span>
            <strong><?php echo $this->translate($log['ACTION']); ?></strong>
            <?php
            try {
                $detail = ($log['DETAIL']) ? Zend_Json::decode($log['DETAIL']) : [];
            } catch (Zend_Json_Exception $e) {
                $detail = [];
                error_log($e->getMessage() . ' of docid ' . $log['DOCID']);
            }

            $status = isset($detail['status']) && in_array($detail['status'], array_merge(Episciences_Paper::STATUS_CODES, Episciences_Paper::OTHER_STATUS_CODE), false) ?
                $this->translate(Episciences_Paper::$_statusLabel[$detail['status']]) :
                $this->translate('undefined status');
            $tag = (isset($detail['user']['tag']) && !empty($detail['user']['tag'])) ? (' [ ' . $this->translate($detail['user']['tag']) . ' ]') : '';
            $fullName = $detail['user']['fullname'] ?? 'undefined';

            ?>
            <?php switch ($log['ACTION']): ?>
<?php case Episciences_Paper_Logger::CODE_STATUS: ?><?php // Tout affichage entre une structure switch et le premier case va produire une erreur de syntaxe. ?>
                    <?php echo $this->translate(' :'); ?>
                    <?php // Il  arrive en DEV. de récupérer des valeurs inattendues ?>
                    <?= $status ?>
                    <?php break; ?>

                <?php case Episciences_Paper_Logger::CODE_RESTORATION_OF_STATUS: ?>
                    <?php echo $this->translate(' :'); ?>
                    <?= $status ?>
                    <?php break; ?>
                <?php case Episciences_Paper_Logger::CODE_ALTER_REPORT_STATUS: ?>
                    <?php echo $fullName; ?>
                    <?php break; ?>

                <?php case Episciences_Paper_Logger::CODE_EDITOR_UNASSIGNMENT:
                case Episciences_Paper_Logger::CODE_EDITOR_ASSIGNMENT: ?>
                    <?php echo $this->translate(' :'); ?>
                    <?php echo $fullName; ?>
                    <?= $tag ?>
                    <?php break; ?>

                <?php case Episciences_Paper_Logger::CODE_PAPER_UPDATED: ?>
                    <?= '(V' . $detail['version']['old'] . ' > ' . 'V' . $detail['version']['new'] . ')' ?>
                    <?= $this->translate(' :')  ?>
                    <?= $fullName ?>
                    <?php break; ?>
                <?php

                case Episciences_Paper_Logger::CODE_COPY_EDITOR_UNASSIGNMENT:
                case Episciences_Paper_Logger::CODE_REVIEWER_INVITATION:
                case Episciences_Paper_Logger::CODE_REVIEWER_INVITATION_ACCEPTED:
                case Episciences_Paper_Logger::CODE_REVIEWER_ASSIGNMENT:
                case Episciences_Paper_Logger::CODE_REVIEWER_INVITATION_DECLINED:
                case Episciences_Paper_Logger::CODE_REVIEWING_IN_PROGRESS:
                case Episciences_Paper_Logger::CODE_REVIEWING_COMPLETED:
                case Episciences_Paper_Logger::CODE_CE_AUTHOR_SOURCES_DEPOSED:
                case Episciences_Paper_Logger::CODE_CE_AUTHOR_FINAL_VERSION_SUBMITTED:
                case Episciences_Paper_Logger::CODE_NEW_PAPER_COMMENT:
                case Episciences_Paper_Logger::CODE_COPY_EDITOR_ASSIGNMENT:
                case Episciences_Paper_Logger::CODE_AUTHOR_COMMENT_COVER_LETTER:
                case Episciences_Paper_Logger::CODE_EDITOR_COMMENT:
                case Episciences_Paper_Logger::CODE_CE_AUTHOR_FINALE_VERSION_DEPOSED:
                case Episciences_Paper_Logger::CODE_MONITORING_REFUSED:
                case Episciences_Paper_Logger::CODE_PAPER_COMMENT_FROM_REVIEWER_TO_CONTRIBUTOR:
                case Episciences_Paper_Logger::CODE_PAPER_COMMENT_FROM_CONTRIBUTOR_TO_REVIEWER:
                case Episciences_Paper_Logger::CODE_REVISION_REQUEST_NEW_VERSION:
                case Episciences_Paper_Logger::CODE_REVISION_REQUEST_TMP_VERSION:
                case Episciences_Paper_Logger::CODE_REVISION_REQUEST_ANSWER:
                ?>
                    <?php echo $this->translate(' :'); ?>
                    <?php echo $fullName; ?>
                    <?php break; ?>

                <?php case Episciences_Paper_Logger::CODE_REVIEWER_UNASSIGNMENT: ?>
                    <?php if (array_key_exists(Episciences_Reviewer::STATUS_UNINVITED, $detail) && $detail[Episciences_Reviewer::STATUS_UNINVITED] === Episciences_Reviewer::STATUS_UNINVITED ): ?>
                        <?= '[ ' . $this->translate(Episciences_Reviewer::STATUS_UNINVITED) . ' ]' ?>
                    <?php endif; ?>
                    <?= $this->translate(' :') ?>
                    <?= $fullName ?>
                    <?php break; ?>

                <?php case Episciences_Paper_Logger::CODE_MAIL_SENT: ?>
                <?php case Episciences_Paper_Logger::CODE_REMINDER_SENT: ?>
                    <?php if (array_key_exists('To', $detail['mail'])) : ?>
                        <?php echo $this->translate("à") . ' ' . implode(', ', $detail['mail']['To']); ?>
                    <?php endif; ?>
                    <?php echo $this->translate(' :'); ?>
                    <?php echo $detail['mail']['Subject']; ?>
                    <?php break; ?>

                <?php case Episciences_Paper_Logger::CODE_SECTION_SELECTION: ?>
                    <?php echo $this->translate(' :'); ?>
                    <?= $detail['sid'] !== 0 ? $this->translate('section_' . $detail['sid'] . '_title') : $this->translate('Hors rubrique'); ?>
                    <?php break; ?>

                <?php case Episciences_Paper_Logger::CODE_VOLUME_SELECTION: ?>
                    <?php echo $this->translate(' :'); ?>
                    <?php echo ($detail['vid'] !== 0) ? $this->translate('volume_' . $detail['vid'] . '_title') : $this->translate('Hors volume'); ?>
                    <?php break; ?>

                <?php case Episciences_Paper_Logger::CODE_OTHER_VOLUMES_SELECTION: ?>
                    <?= $this->translate(' :') ?>
                    <?php

                    $volumesLabel = [];

                    foreach ($detail['vids'] as $sVid) {
                        $volumesLabel [] = $this->translate('volume_' . $sVid['vid'] . '_title');
                    }
                    ?>

                    <?= (!empty($volumesLabel)) ? implode(', ', $volumesLabel) : $this->translate('Hors volume (s)') ?>
                    <?php break; ?>

                <?php
                case Episciences_Paper_Logger::CODE_CE_AUTHOR_FINALE_VERSION_REQUEST:
                case Episciences_Paper_Logger::CODE_CE_READY_TO_PUBLISH:
                case Episciences_Paper_Logger::CODE_CE_REVIEW_FORMATTING_DEPOSED:
                case Episciences_Paper_Logger::CODE_CE_AUTHOR_SOURCES_REQUEST:
                    ?>
                    <?php echo $this->translate(' :'); ?>
                    <?php echo $fullName . ' > ' . $detail['submitter']['fullname']; ?>
                    <?php break; ?>

                <?php
                case Episciences_Paper_Logger::CODE_ALTER_PUBLICATION_DATE: ?>
                    <?= $this->translate(' :') ?>
                    <?= $detail['newDate'] . ' > ' ?>
                    <?= $fullName ?>
                    <?php break; ?>

                <?php case Episciences_Paper_Logger::CODE_COI_REPORTED: ?>
                    <?= $this->translate(' :') ?>
                    <?= strtoupper($this->translate($detail['conflict']['answer'])) . ' > ' ?>
                    <?= $fullName ?>
                <?php break; ?>
                <?php endswitch ?>

            <span class="log-detail-icon glyphicon glyphicon-plus"></span>
        </span>
    </div>

    <?php if (in_array($log['ACTION'], $logs_with_details, false)) : ?>
        </a>
    <?php endif; ?>

<?php endforeach; ?>
