<?php
$docid = $this->docid;
?>

<?php
$exportUrl = $this->url(['id' => $docid]);
$exportFormat['bibtex'] = 'BibTeX';
$exportFormat['tei'] = 'TEI';
$exportFormat['dc'] = 'Dublin Core';
$exportFormat['datacite'] = 'OpenAIRE';
$exportFormat['crossref'] = 'Crossref';
$exportFormat['doaj'] = 'DOAJ';
$exportFormat['zbjats'] = 'ZbMATH Open';
$exportFormat['json'] = 'JSON';
?>
<div class="dropdown">
    <button id="dLabel" class="btn btn-default btn" style="margin-top: 0.5em" type="button" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">
        <?= $this->translate('Exporter') ?> <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dLabel">
        <?php
        foreach ($exportFormat as $format => $title) {
            printf('<li><a class="" target="_blank" href="%s/%s">%s</a></li>', $exportUrl, $format, $title);
        }
        ?>
    </ul>
</div>
