<?php

/** @var Zend_Controller_Request_Http $request */
$request = Zend_Controller_Front::getInstance()->getRequest();
$controller = $request->getControllerName();
$action = $request->getActionName();

/** @var Episciences_Paper $paper */
$paper = $this->paper;

$message = '';
$url = '';
$docId = $paper->getDocId();

$isOwner = $paper->isOwner();

if ($controller === PaperDefaultController::ADMINISTRATE_PAPER_CONTROLLER) {

    $message = "Aller à la page publique de cet article";
    $url = $this->url(['controller' => PaperDefaultController::PUBLIC_PAPER_CONTROLLER, 'action' => 'view', 'id' => $docId]);

} elseif (!$isOwner && Episciences_Auth::isAllowedToManageDoi()) {

    $message = "Aller à la page de gestion de cet article";
    $url = $this->url(['controller' => PaperDefaultController::ADMINISTRATE_PAPER_CONTROLLER, 'action' => 'view', 'id' => $docId]);
}
?>

<?php if ($url !== '' && !$isOwner) : ?>
    <a class="btn btn-default btn-xs pull-right" href="<?= $url ?>" style="margin-left: 10px;"><i class="fas fa-link" style="margin-right: 5px;"></i><?= $this->translate($message) ?></a>
<?php endif; ?>
