<?php

/** @var Zend_Controller_Request_Http $request */
$request = Zend_Controller_Front::getInstance()->getRequest();
$controller = $request->getControllerName();
$action = $request->getActionName();
$message = '';

if ($controller === 'administratepaper') {
    $message = "Aller à la page de l'article";
    $url = '/paper/view?id=' . $this->docId;
} else {
    $message = "Aller à la page de gestion de l'article";
    $url = '/administratepaper/view?id=' . $this->docId;

}
?>
<a class="btn btn-default btn-xs pull-right" href="<?= $url ?>" style="margin-left: 10px;"><i class="fas fa-link" style="margin-right: 5px;"></i><?= $this->translate($message) ?></a>
