<?php
$comments = $this->copyEditingDemands;
$replyForms = $this->copyEditingReplyForms;
$status = $this->paperStatus;
$latestDocId = $this->latestDocId;
$linkToLatestDocId = $this->linkToLatestDocId;
$towPoints = $this->translate(' :');
$isFinalVersionRequest = false;
foreach ($comments as $id => $comment) : ?>
    <?php // Copy editing : plusieurs fichiers peuvent être uploader => encodage json
    // TODO A CONVERTIR TOUT EN JSON DANS LA BD
    ?>
    <div class="small">
        <div id="copy-editing-request-<?= $id ?>">
            <strong><em class="fas fa-paper-plane" style="margin-right: 5px;"></em><?= $this->Date($comment['WHEN'], null, Zend_Date::DATE_LONG . ' - ' . Zend_Date::TIME_SHORT) . $towPoints . ' ' ?></strong>
            <?php
            echo '(';
            if (!in_array($comment['TYPE'], Episciences_CommentsManager::$_copyEditingRequestTypes, false)
            ) {
                echo $this->translate('contributeur');
            } else {
                echo $this->translate('comité éditorial');
            }
            if ((int)$comment['UID'] === Episciences_Auth::getUid()) {
                echo $towPoints . ' ' . $this->translate('vous');
            } elseif (Episciences_Auth::isSecretary() || Episciences_Auth::isEditor() || Episciences_Auth::isCopyEditor()) {
                echo ' : ' . $comment['SCREEN_NAME'];
            }
            echo ') <strong>' . $towPoints . ' </strong><span class="label label-status-' . $comment['TYPE'] . '">' . $this->translate(Episciences_CommentsManager::$_typeLabel[$comment['TYPE']]) . '</span>'; ?>
        </div>

        <?php if ($replyForms) : ?>
            <?php

            $isFinalVersionRequest = in_array($comment['TYPE'], Episciences_CommentsManager::$_copyEditingFinalVersionRequest, false);
            $commentType = (int)$comment['TYPE'];
            $replyBtnClass = 'btn-default';
            $btnTitle = '';

            $isDisabled = in_array($status, Episciences_Paper::$_noEditableStatus, true);

            if ($isFinalVersionRequest) {
                $replyBtnMsg = 'Soumettre la version finale';
                $replyBtnClass = 'btn-primary';
                $btnTitle = "Soumettre la version finale de l'archive ouverte";
            } elseif ($commentType === Episciences_CommentsManager::TYPE_WAITING_FOR_AUTHOR_SOURCES_REQUEST) {
                $replyBtnMsg = 'Ajouter les fichiers sources';
                $isDisabled = $isDisabled || $status === Episciences_Paper::STATUS_CE_REVIEW_FORMATTING_DEPOSED;
            } elseif ($commentType === Episciences_CommentsManager::TYPE_WAITING_FOR_AUTHOR_FORMATTING_REQUEST) {
                $replyBtnMsg = 'Ajouter la version formatée';
                //La version formatée par l'auteur a été validée
                $isDisabled = $isDisabled || $status === Episciences_Paper::STATUS_CE_AUTHOR_FORMATTING_DEPOSED;
            } else {
                $replyBtnMsg = 'Répondre';
            }

            $toolTip = !(empty($btnTitle)) ? 'data-toggle="tooltip"' . ' ' . 'title="' . $this->translate($btnTitle) . '"' : '';

            $disabled = $isDisabled ? 'disabled' : '';

            ?>

            <button id="replyFormBtn_<?= $id ?>" style="margin: 10px 0 20px 20px"
                    class='btn btn <?= $replyBtnClass; ?> btn-sm replyButton' <?= $disabled . ' ' . $toolTip ?>>
                <span class="glyphicon glyphicon-edit "></span> <?= $this->translate($replyBtnMsg) ?>
            </button>

        <?php endif; ?>
    </div>
    <?php if (!empty($replyForms[$id])) : ?>
        <div id="replyForm_<?= $id ?>" class="replyForm small" style="margin: 20px 20px 10px 20px; display: none">
            <?php if ($isFinalVersionRequest) : ?>
                <?= $this->partial('paper/new_version_show_result.phtml', ['form' => $replyForms[$id]]) ?>
            <?php else: ?>
                <?= $replyForms[$id] ?>
            <?php endif; ?>
        </div>
    <?php endif; ?>

    <?php if (isset($comment['replies'])) : ?>

        <?php foreach ($comment['replies'] as $reply) : ?>
            <?php
            $isFinalVersion = (int)$reply['TYPE'] === Episciences_CommentsManager::TYPE_CE_AUTHOR_FINAL_VERSION_SUBMITTED;
            $infoMsg = '<strong>' . $towPoints . ' </strong>';
            $infoMsg .= $isFinalVersion ? ('<a class="btn btn-primary btn-sm" href="' . $linkToLatestDocId . '" data-toggle="tooltip" title="' . $this->translate('Accéder à la version finale') . '"><i class="fas fa-link" style="margin-right: 5px;"></i>') : '';
            $infoMsg .= !$isFinalVersion ? '<span class="label label-status-' . $reply['TYPE'] . '">' : '';
            $infoMsg .= $this->translate(Episciences_CommentsManager::$_typeLabel[$reply['TYPE']]);
            $infoMsg .= !$isFinalVersion ? '</span>' :  '';
            $infoMsg .= $isFinalVersion ? '</a>' : '';
            ?>
            <br>
            <div style="margin: 10px 0 10px 20px" class="small">

                <span>
                    <strong>
                        <em class="fas fa-reply" style="margin-right: 5px;"></em>
                        <?= $this->Date($reply['WHEN'], null, Zend_Date::DATE_LONG . ' - ' . Zend_Date::TIME_SHORT) . $towPoints . ' ' ?>
                    </strong>
                </span>

                <?php if ((int)$reply['UID'] === Episciences_Auth::getUid()) : ?>
                    (<?= $this->translate('vous') ?>)
                <?php else: ?>
                    (<?= $this->translate('l\'auteur') . ' : ' . $reply['SCREEN_NAME'] ?>)
                <?php endif; ?>
                <?= $infoMsg; ?>

                <div><?= Episciences_Tools::formatText($this->escape($reply['MESSAGE'])) ?></div>

                <?php if ($reply['FILE']) : ?>
                    <?php $files = Episciences_Tools::isJson($reply['FILE']) ? json_decode($reply['FILE'], true) : (array)$reply['FILE'] ?>
                    <hr>
                    <p class="small">
                        <strong><?= $this->translate('Fichier(s) joint(s)'); ?> :</strong>
                    </p>

                    <?php foreach ($files as $file) : ?>
                        <div class="col-sm-10">
                            <a href="/docfiles/ce/<?= $reply['DOCID'] . '/' . $file . '/' . $reply['PCID'] ?>"
                               target="_blank">
                                <?= $file; ?>
                            </a>
                        </div>
                        <div class="col-sm-2">
                            <?= $this->partial('partials/remove_file_comment.phtml', ['comment' => $reply, 'fileName' => $file]) ?>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>

<?php endforeach; ?>
