<?php
/** @var Episciences_Paper $paper */
$paper = $this->paper;
$dataDescriptors = $paper->getDataDescriptors() ?? [];
$tmp = $dataDescriptors;
$isMultiple = count($dataDescriptors) > 1;
?>

<div class="panel panel-default collapsable">
    <div class="panel-heading">
        <?php

        $isPublished = $paper->isPublished();
        $latest = array_shift($tmp);
        /** @var \Episciences\Files\File $file */
        $file = $latest?->getFile();
        $preview = null;
        $fileName = '';

        if ($file) {
            $preview = sprintf('/docfiles/dd/%s/%s', $file->getDocid(), $file->getName());
            $fileName = $file->getName();
        }

        if ($paper->isSoftware()) {
            $panelTile = $isMultiple && !$isPublished ? 'Descripteurs de logiciel' : 'Descripteur de logiciel';
        } else {
            $panelTile = $isMultiple && !$isPublished ? 'Descripteurs de données' : 'Descripteur de données';
        }

        ?>


        <?php if ($isPublished) :
            $linkedData = $paper->getLinkedDataByRelation();
            if ($linkedData && strtoupper($linkedData->getName()) === Episciences_Repositories::HAL_LABEl) {
                $fileName = $linkedData->getValue();
                $preview = Episciences_Repositories::getPaperUrl(Episciences_Repositories::HAL_REPO_ID, $linkedData->getValue());
            }
            ?>
        <?php endif; ?>

        <h2 class="panel-title"><?= sprintf('%s <span class="small fa-solid fa-chevron-right" style="margin-right:5px;"></span><span class="small badge"">%s</span>', $this->translate($panelTile), $fileName) ?></h2>
    </div>

    <div class="panel-body in">

        <?php if ($preview) : ?>
            <?= $this->partial('partials/data_descriptor_preview.phtml', ['typeMime' => $latest?->getFile()->getTypeMime(), 'preview' => $preview]) ?>
        <?php endif; ?>

        <?php if (Episciences_Auth::isSecretary() || $paper->isOwner()) : ?>

            <?php if (!empty($dataDescriptors)) : ?>

                <div class="small" style="margin-top: 10px;">
                    <table class="table" id="data-descriptor">
                        <thead>
                        <tr>
                            <th style="border: none;"><?= $isMultiple ? $this->translate("Fichiers") : $this->translate("Fichier") ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($dataDescriptors as $dd): ?>
                            <?php

                            $vLabel = '';

                            if ($isMultiple) {

                                if ($dd->getId() === $dataDescriptors[array_key_first($dataDescriptors)]->getId()) {
                                    $vLabel = !Episciences_Auth::isLogged() ? '' : sprintf('<span class="label label-status-0">%s</span>', $this->translate('dernière version'));
                                } else {

                                    $vLabel = sprintf('(v%s)', $dd->getVersion());

                                }

                            }

                            ?>
                            <?php if ($fileName = $dd->getFile()->getName()) : ?>
                                <tr id="data-descriptor-<?= $dd->getId() ?>" <?= count($dataDescriptors) === $dd->getVersion() ? 'class="active"' : '' ?>>
                                    <td>
                                        <a href="<?= sprintf('/docfiles/dd/%s/%s', $dd->getDocid(), $fileName) ?>"
                                           target="_blank"><?= sprintf('%s', $fileName) ?>
                                        </a>&nbsp;<?= $vLabel ?>
                                    </td>
                                    <td>
                                        <strong class="pull-right">
                                            <?= $this->translate('Soumis le : ') . $this->Date($dd->getSubmissionDate(), null, Zend_Date::DATE_LONG . ' - ' . Zend_Date::TIME_SHORT) ?>
                                        </strong>

                                    </td>
                                </tr>
                            <?php endif; ?>
                        <?php endforeach; ?>
                        </tbody>
                    </table>

                </div>

            <?php endif; ?>

            <?php if ($this->ddNewVersionForm) : ?>

                <?php if ($this->isAllowedToAddNewVersion): ?>

                    <div>
                        <button id="btn-add" class="btn btn-sm btn-default" type="button"
                                onclick="processForm($(this));"><i
                                    class="fa-solid fa-plus"></i>&nbsp;<?= $this->translate("Ajouter une nouvelle version") ?>
                        </button>
                    </div>

                    <?php $this->jQuery()->addJavascriptFile('/js/paper/data_descriptor.js'); ?>


                <?php endif; ?>

                <div id="dd-new-version-form" style="display: none;"><?= $this->ddNewVersionForm ?></div>

            <?php endif; ?>

        <?php endif; ?>

    </div>


</div>




