<?php // first position in view => position 0 in VOLUME_PAPER_POSITION table?>
<span id="position_ <?= $this->docId ?>"> <span class="label label-default"
          tabindex="0"
          data-toggle="tooltip"
          data-placement="top"
          title="<?= $this->escape($this->translate("Numéro de l'article dans un volume (ordre)")) ?>"
    ># <?= $this->position + 1 ?></span> &nbsp;
        <?php if (Episciences_Auth::isSecretary()) : ?>
            <?php
            $params = ['controller' => 'volume', 'action' => 'edit', 'id' => $this->vid, 'from' => $this->from];
            if ($this->from === 'view') {
                $params ['docid'] = $this->docId;
            }
            ?>
            <a href="<?= $this->url($params) ?>"
               class="btn btn-default btn-xs"
               data-toggle="tooltip"
               data-placement="top"
               title="<?= $this->escape($this->translate("Propriétés du volume et ordre des articles")) ?>">
                <i class="fa-solid fa-arrow-down-1-9"></i>
            </a>
        <?php endif; ?>
    </span>