<?php
/** @var Episciences_Paper $paper */
$paper = $this->paper;
$loggedUid = Episciences_Auth::getUid();
?>
<div class="panel-group" id="ratings">
    <?php foreach ($this->reports as $uid => $report) : ?>
        <?php /** @var Episciences_Rating_Report $report */
        $reviewer = new Episciences_Reviewer();
        $reviewer->find($uid);
        $reviewerScreenName = ($uid === $loggedUid) ?
            ucfirst($this->translate('vous')) : $reviewer->getScreenName();

        $byUid = $report->getOnbehalf_uid();
        $viaViceMessage = '';

        if ($byUid) {
            $byUidUser = new Episciences_User();
            $byUidUser->find($byUid);
            $userScreenName = ($byUid === $loggedUid) ?
                ucfirst($this->translate('vous')) : $byUidUser->getScreenName();

            $viaViceMessage .= '<span class="badge alert-info" style="margin-right: 5px;">' . ucfirst($this->translate('via')) . '</span>';
            $viaViceMessage .= ' [ ' . $userScreenName . ' ] ' . ' ';
            $viaViceMessage .= '<span class="badge alert-info" style="margin-right: 5px;">' . ucfirst($this->translate('pour le compte de')) . '</span>' . ' [ ' . $reviewerScreenName . ' ] ';
            $viaViceMessage .= ' ( ' . ucfirst($this->translate('reviewer') . ' ' . $reviewer->getAlias($paper->getDocid())) . ' )';
        }

        $message = '';

        if ($this->isAllowedToSeeReportDetails) { // pour les relectures ajoutées
            if ($byUid) { // Affichage du nom de celui qui a fait la relecture à la place d'un autre relecteur
                $message .= $viaViceMessage;
            } else { // $byUid == 0
                $message = '<span class="badge alert-success" style="margin-right: 5px;">' . ucfirst($this->translate('par')) . '</span>';
                $message .= ' [ ' . $reviewerScreenName . ' ] ';
                $message .= ' ( ' . ucfirst($this->translate('reviewer') . ' ' . $reviewer->getAlias($paper->getDocid())) . ' )';
            }

        } else if ($uid === $loggedUid) { // reviewer
            $message .= $reviewerScreenName;
        } else {
            $message .= ucfirst($this->translate('reviewer') . ' ' . $reviewer->getAlias($paper->getDocid()));
        }

        ?>
        <?php if ($report->getStatus()) : ?>
            <div class="panel panel-warning">
                <div class="panel-heading" data-parent="#ratings" data-toggle="collapse"
                     data-target="#rating-<?= $report->getUid() ?>">
                    <h4 class="panel-title">
                        <strong><?= $message ?>
                        </strong>
                        <?php if ($this-> isAllowedToSeeReportDetails && is_numeric($report->getScore())) : ?>
                            : <?= round(($report->getScore() / $report->getMax_score()), 1) ?>
                        <?php endif; ?>
                        <span class="grey pull-right"><?= $this->Date($report->getUpdate_date()) ?>
                            <span class="glyphicon glyphicon-chevron-down" style="margin-left: 5px;"></span>
                        </span>
                    </h4>
                </div>
                <div id="rating-<?= $report->getUid() ?>" class="panel-collapse collapse rating">
                    <div class="panel-body">
                        <?= $this->partial('partials/paper_report.phtml', ['report' => $report, 'paper' => $paper]) ?>
                    </div>
                </div>
            </div>
        <?php endif; ?>

        <?php if ($this->isAllowedToSeeReportDetails && count($paper->getRatings()) > 1 && $paper->getAverageRating()) : ?>
            <div style="margin-top: 20px; font-size: 16px" class="text-center darkgrey"><strong>
                    <?= $this->translate('Note moyenne') ?> :
                    <?= $paper->getAverageRating(1) . '/' . $report->getMax_score() ?>
                </strong></div>
        <?php endif; ?>

    <?php endforeach; ?>

    <?php if ($this->isAllowedToSeeReportDetails && count($paper->getRatings()) > 1 && $paper->getAverageRating()) : ?>
        <div style="margin-top: 20px; font-size: 16px" class="text-center darkgrey"><strong>
                <?= $this->translate('Note moyenne') ?> :
                <?= $paper->getAverageRating(1) . '/' . $report->getMax_score() ?>
            </strong></div>
    <?php endif; ?>

</div>



