<?php
$citations  = $this->citations;
?>
<div id="citations-body" class="panel panel-default collapsable">
    <div class="panel-heading">
        <h2 class="panel-title"><?= $this->translate('Citations') ?></h2>
    </div>
    <div class="panel-body in" style="overflow: visible">
        <div>
            <label id="citations-label" for="citations"></label>
            <button type="button" id="btn-show-citations" class="btn btn-default btn-sm"><i class="fa-solid fa-quote-left"></i> <?= $this->translate('Display citations') ?></button>
            <button type="button" id="btn-hide-citations" class="btn btn-default btn-sm" style="display:none;"><i class="fa-solid fa-quote-left"></i> <?= $this->translate('Hide citations') ?></button>
            <div id="list-citations" style="display:none;"><?= $citations ?></div>
        </div>
    </div>
</div>