<?php
/**
 * Created by PhpStorm.
 * User: chibane
 * Date: 17/09/18
 * Time: 15:40
 */
$request = Zend_Controller_Front::getInstance()->getRequest();
$controller = $request->getControllerName();
$action = $request->getActionName();
/** @var Episciences_Paper $currentPaper */
$currentPaper = $this->paper;
$loggedUid = Episciences_Auth::getUid();
$isAllowedToEditVersion = $currentPaper->getEditor($loggedUid) || $currentPaper->getCopyEditor($loggedUid);
?>
<div id="versions" class="panel panel-default collapsable">
    <div class="panel-heading">
        <h2 class="panel-title"><?= $this->translate('Versions') ?></h2>
    </div>
    <div class="panel-body in" style="overflow: visible">
        <ol class="list-unstyled">
            <?php /** @var Episciences_Paper $paper */ ?>
            <?php foreach ($this->versions as $v => $paper) : ?>
                <?php $docId = $paper->getDocid(); ?>
                <li>
                    <?php if ($currentPaper->getDocid() !== $docId) : ?><a href="/<?= $controller ?>/<?= $action ?>/id/<?= $docId ?>"><?php endif; ?>
                        <?php $sourceMsg = (!$paper->isImported()) ? $this->translate('Soumise le : ') : $this->translate('Importée le : ') ?>
                        <?= $this->translate("Version") ?>&nbsp;<span id="version-of-paper-<?= $docId ?>"><?= $v ?></span>
                        <span class="label label-status-0 pull-right"><?= $sourceMsg . Episciences_View_Helper_Date::Date($paper->getWhen()) ?></span>
                        <?php if ($currentPaper->getDocid() !== $docId) : ?></a><?php endif; ?>

                    <?php if (
                        $controller === PaperDefaultController::ADMINISTRATE_PAPER_CONTROLLER &&
                        !$paper->isTmp() && ($docId === $this->versions[array_key_first($this->versions)]->getDocId()) &&
                        $this->isEditableVersion
                    ) : ?>
                        <a class="btn btn-default btn-xs" role="button"
                           onclick="getVersionEditingForm(this, <?= $docId ?>)"><i class="fas fa-edit" style="margin-right: 5px"></i><?= $this->translate('Modifier') ?></a>
                    <?php endif; ?>
                    <?php if($paper->isTmp()) : ?><span class="label label-status-0"><?= $this->translate('temporaire')?></span><?php endif; ?>
                </li>

            <?php endforeach; ?>
        </ol>
    </div>
</div>

