<?php

/** @var Episciences_Paper $paper */
$paper = $this->paper;

if ($paper->isOwner()) {
    $description = $this->translate('Si vous le souhaitez et si la revue vous le demande, vous pouvez partager');
    $description .= ' ';
    $description .= $this->translate("ici le mot de passe papier lui permettant de mettre à jour ce papier dans arXiv, en particulier pour mettre en ligne la version finale mise en page de votre article. Ce mot de passe est chiffré et sera automatiquement supprimé à la publication de l'article. Seuls les gestionnaires de votre article ont accès à ce mot de passe.");
    $description .= ' (';
    $description .= sprintf(ucfirst($this->translate("le nombre maximum de caractères autorisé est de <strong>%u</strong>")), MAX_PWD_INPUT_SIZE);
    $description .= ')';
} else {
    $description = $this->translate("Ce champ contient le mot de passe arXiv de l'article si les auteurs/autrices ont accepté de le partager avec la revue. Il peut servir à mettre en ligne une nouvelle version de l'article à la place de l'auteur.");
}

/** @var Episciences_Review $review */
$review = $this->review;
?>


<?php if ($this->displayPaperPasswordBloc) : ?>
    <div class=" panel panel-default collapsable">

        <div class="panel-heading">
            <h2 class="panel-title"><?= $this->translate('Mot de passe papier arXiv') ?></h2>
        </div>

        <div class="row">
            <div class="col-sm-12" style="margin-top: 5px;">

                <div class="col-sm-7">


                    <p class="text-justify help-block">
                        <?= $description ?>
                    </p>


                </div>

                <div class="col-sm-5" style="margin-top: 5px">

                    <form method="post" id="paper-password-form">

                        <div class="input-group">
                            <input type="password" class="form-control" name="paperPassword"
                                   id="paper-password" <?= $this->paperPassword ? 'value="' . $this->paperPassword . '"' : 'placeholder="' . $this->translate('Mot de passe papier arXiv') . '"' ?>
                                   autocomplete="off" <?= !$paper->isOwner() ? 'readonly' : '' ?> maxlength="40">
                            <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span id="copy-text" data-toggle="tooltip" title="<?= $this->translate('Copier') ?>"
                                      class="darkgrey fa-solid fa-copy"></span>
                            </button>
                                <?php if ($paper->isOwner()): ?>
                                    <button form="paper-password-form" class="btn btn-primary" type="submit" name="savePaperPassword" value="savePaperPassword">
                                   <?= $this->translate('Enregistrer') ?>
                                </button>
                                <?php endif; ?>
                        </span>

                        </div>

                        <div>
                            <input type="checkbox" id="pwd-visibility" style="margin-top: 5px; margin-bottom: 5px;">
                            <label class="small"
                                   for="pwd-visibility"><?= $this->translate('Afficher le mot de passe') ?></label>
                        </div>


                    </form>


                </div>


            </div>
        </div>
    </div>

    <script>


        let $pwdInput = $('#paper-password');
        let $copyTextElem = $('#copy-text')

        $('#pwd-visibility').on('change', function () {
            $(this).prop('checked') ? $pwdInput.prop('type', 'text') : $pwdInput.prop('type', 'password');
        });

        $copyTextElem.on('click', function () {
            let $this = $(this);

            navigator.clipboard.writeText($pwdInput.val()).then(function () {

                updateTooltipTitle($this, 'Copié !');

            }, function () {
                alert('Failure to write to the clipboard');
            });

        });


        $copyTextElem.on('mouseleave', function () {
            let $this = $(this);
            updateTooltipTitle($this, 'Copier');
        })

    </script>

<?php endif; ?>
