<?php echo $this->editor_comment_form;
$this->jQuery()->addJavascriptFile('/js/common/visualDeleteFile.js');
?>

<?php if (!empty($this->editor_comments)) : ?>
    <?php $first = key($this->editor_comments); ?>
    <div id="editor_comments" style="max-height: 800px; overflow: auto">
    <?php foreach ($this->editor_comments as $id=>$comment) : ?>
        <?php $margin = ($id == $first) ? '0' : '20px'; ?>
        <div style="margin-top: <?php echo $margin;?>" class="small">
            <img src="<?= PREFIX_URL ?>user/photo/name/<?= urlencode($this->escape($comment['SCREEN_NAME'])) ?>/uid/<?= $comment['UID'] ?>/size/<?= Ccsd_User_Models_User::IMG_NAME_INITIALS ?>?v=<?php echo Episciences_Auth::getPhotoVersion() ?>"
                 class="user-photo-thumb" alt="avatar">
            <strong><?php echo $this->Date($comment['WHEN'], null, Zend_Date::DATE_LONG.' - '.Zend_Date::TIME_SHORT); ?> : </strong>
            (<?php echo ($comment['UID'] == Episciences_Auth::getUid()) ? $this->translate('vous') : $comment['SCREEN_NAME']; ?>)
            <div><?= Episciences_Tools::formatText(Episciences_Tools::epi_html_decode($comment['MESSAGE'])) ?></div>
            <?php if ($comment['FILE']) :?>
                <div class="col-sm-10">
                    <a href="<?= sprintf('%sdocfiles/comments/%s/%s', PREFIX_URL, $comment['DOCID'], $comment['FILE']) ?>" target="_blank"> <?= $comment['FILE'] ?></a>
                </div>
            <div class="col-sm-2">
                <?php echo $this->partial('partials/remove_file_comment.phtml', ['comment' => $comment]); ?>
            </div>
            <?php endif;?>
        </div>
    <?php endforeach; ?>
    </div>
<?php endif; ?>


