<?php if ($this->paper->_revisionDeadline) : ?>
    <p>
        <small><?= $this->translate("Version révisée attendue avant le :") ?>
            <strong id="revision-deadline"><?= $this->Date($this->paper->_revisionDeadline) ?></strong></small>
        <?php
        if (
            Zend_Controller_Front::getInstance()->getRequest()->getControllerName() === PaperDefaultController::ADMINISTRATE_PAPER_CONTROLLER &&

            (
                Episciences_Auth::isAdministrator() ||
                $this->paper->isEditor(Episciences_Auth::getUid())
            )
        ) : ?>
            <button class="btn btn-xs btn-default"
                    onclick="getRevisionDeadlineForm(this, <?= $this->paper->getDocid() ?>, <?= $this->currentDemand['PCID'] ?>)">
                <span class="fa-solid fa-calendar-days fa-xs" style="margin-right: 5px"></span>
                <?= $this->translate('Modifier') ?>
            </button>
        <?php endif ?>
    </p>
<?php endif; ?>