<?php
$citations  = $this->citations;
?>
<div id="citations-body" class="panel panel-default collapsable">
    <div class="panel-heading">
        <h2 class="panel-title"><?= $this->translate('Citations') ?></h2>
    </div>
    <div class="panel-body in" style="overflow: visible">
        <div>
            <label id="citations-label" for="citations"></label>
            <div id="citations-body"><?= $citations ?></div>
        </div>
    </div>
</div>