<?php // Liste des volumes secondaires **********************************************
/** @var Episciences_Paper $article */
$article = $this->article;
/** @var Episciences_Volume[] $volumes */
$volumes = $this->volumes;
/** @var Episciences_Volume_Paper[] $othersVolumes */
$othersVolumes = $article->getOtherVolumes();
?>

<?php if (!empty($othersVolumes)) : ?>
    <?php
    $i = 0;
    foreach ($othersVolumes as $paper_volume) {
        $i++;
        if ($paper_volume->getVid() == $article->getVid()) {
            continue;
        }
        /** @var Episciences_Volume $volume */
        $volume = $volumes[$paper_volume->getVid()];
        echo $this->translate($volume->getNameKey());
        if ($i < count($othersVolumes)) {
            echo ', ';
        }
    }
    ?>
<?php else : ?>
    <?php echo $this->translate('aucun'); ?>
<?php endif; ?>