<?php
/**
 * Created by PhpStorm.
 * User: chibane
 * Date: 17/09/18
 * Time: 15:40
 */
$request = Zend_Controller_Front::getInstance()->getRequest();
$controller = $request->getControllerName();
$action = $request->getActionName();
/** @var Episciences_Paper $currentPaper */
$currentPaper = $this->paper;
$loggedUid = Episciences_Auth::getUid();
$isAllowedToEditVersion = $currentPaper->getEditor($loggedUid) || $currentPaper->getCopyEditor($loggedUid);
?>
<style>
    #versions .versions-table > tbody > tr:first-child > td {
        border-top: none;
    }
</style>
<div id="versions" class="panel panel-default collapsable">
    <div class="panel-heading">
        <h2 class="panel-title"><?= $this->translate('Versions') ?></h2>
    </div>
    <div class="panel-body in" style="overflow: visible; padding: 5px 0;">
        <table class="table table-condensed versions-table" style="margin-bottom: 0;">
            <tbody>
            <?php /** @var Episciences_Paper $paper */ ?>
            <?php foreach ($this->versions as $v => $paper) : ?>
                <?php $docId = $paper->getDocid(); ?>
                <tr>
                    <td style="vertical-align: middle; border-top-color: #eee; padding-left: 15px;">
                        <?php if ($currentPaper->getDocid() !== $docId) : ?><a href="<?= $this->url(['controller' => $controller, 'action' => $action, 'id' => $docId])?>"><?php endif; ?>
                            <?= $this->translate("Version") ?>&nbsp;<span id="version-of-paper-<?= $docId ?>"><?= $v ?></span>
                            <?php if ($currentPaper->getDocid() !== $docId) : ?></a><?php endif; ?>

                        <?php if (
                            $controller === PaperDefaultController::ADMINISTRATE_PAPER_CONTROLLER &&
                            !$paper->isTmp() && ($docId === $this->versions[array_key_first($this->versions)]->getDocId()) &&
                            $this->isEditableVersion
                        ) : ?>
                            <a class="btn btn-default btn-xs" role="button" title="<?= $this->translate('Modifier') ?>" aria-label="<?= $this->translate('Modifier') ?>"
                               onclick="getVersionEditingForm(this, <?= $docId ?>)"><i class="fas fa-edit" aria-hidden="true"></i></a>
                        <?php endif; ?>
                        <?php if($paper->isTmp()) : ?><span class="label label-status-0"><?= $this->translate('temporaire')?></span><?php endif; ?>
                    </td>
                    <td class="text-left" style="vertical-align: middle; white-space: nowrap; border-top-color: #eee; padding-right: 15px;">
                        <?php $sourceMsg = (!$paper->isImported()) ? $this->translate('Soumise le : ') : $this->translate('Importée le : ') ?>
                        <span class="label label-status-0"><?= $sourceMsg . Episciences_View_Helper_Date::Date($paper->getWhen()) ?></span>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

