<div class="panel-body in">
    <div class="row">
        <div class="col-md-12">
            <?php if ($this->enabledManageFromPublicPage === true) : ?>
                <a id="epi-citation-app-enabled-public" style="margin-bottom: 8px;" class="btn btn-default btn-sm" target="_blank" href="<?=$this->apiEpiBibCitation?>/login?url=<?=$this->urlcallapibib?>"><i class="fas fa-edit"></i> <?= $this->translate('Gérer les références bibliographiques') ?></a>
            <?php endif;?>
            <div id="biblio-refs-container"></div>
            <div id="visualize-biblio-refs" data-value="<?= $this->urlcallapibib ?>" data-api="<?=$this->apiEpiBibCitation?>" <?php if ($this->enabledManageFromPublicPage === true) : ?>data-all="1" <?php endif;?> hidden></div>
        </div>
    </div>
</div>