<?php
$suggestionInfoMsg = "Votre suggestion à déjà été enregistrée.";
/** @var Episciences_Paper $paper */
$paper = $this->paper;
$status = $paper->getStatus();
$changeStatusMsg = "Changer le statut de l'article";
$publishMsg = "Publier l'article";
$refusedMsg = "Refuser l'article";

if ($paper->isTmp()) {
    $acceptMsg = 'Demander la version définitive';
} else if (!$this->review->getSetting(Episciences_Review::SETTING_SYSTEM_PAPER_FINAL_DECISION_ALLOW_REVISION)) {
    $acceptMsg = 'Accepter et passer à la préparation de copie';
} else {
    $acceptMsg = "Accepter l'article";
}

$acceptedAskAuthorFinalVersion = "Demander la version finale à l'auteur";
$waitingAuthorSources = "Demander à l'auteur ses sources (À mettre en forme par la revue)";
$waitingFinalVersion = "Demander la version finale (À mettre en forme par l’auteur)";
$reviewFormattingMsg = 'Mise en forme revue terminée, demander la version finale';
$validFinalVersionMsg = 'Accepter comme version finale';
$assignedCopyEditors = $paper->getCopyEditors();
$isAssignedCopyEditors = !empty($assignedCopyEditors);
$copyEditingNotStarted = !$paper->copyEditingProcessStarted();
$isInRevision = $paper->isRevisionRequested();
$isNotTheFirstVersion = empty($paper->getPreviousVersions());
$askSourcesAgainMsg = "Redemander à l'auteur ses sources (À mettre en forme par la revue)";
$askFinalVersionAgainMsg = "Demander à nouveau la version finale à l'auteur";
// **** CHIEF EDITORS, administrator and secretary (git #235) : can do whatever they want *****************************
if (Episciences_Auth::isSecretary()) : ?>
    <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <?= $this->translate($changeStatusMsg) ?> <span class="caret" style="margin-left: 5px"></span>
        </button>
        <ul class="status-menu dropdown-menu" role="menu">
            <?php if ($paper->isReadyToPublish()) : ?>
                <!-- publication request -->
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".publication-modal"><?= $this->translate($publishMsg) ?>
                    </a>
                </li>

                <!-- revision request -->
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".minor-revision-modal"><?= $this->translate('Demander des modifications mineures') ?></a>
                </li>

                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".major-revision-modal"><?= $this->translate('Demander des modifications majeures') ?></a>
                </li>

            <?php elseif ($paper->isAccepted()) : ?>
                <?php // Ask author's final version  ?>
                <?php if ($this->review->getSetting(Episciences_Review::SETTING_SYSTEM_PAPER_FINAL_DECISION_ALLOW_REVISION)) : ?>
                    <li>
                        <a href="#" data-toggle="modal"
                           data-target=".accepted-ask-author-final-version-modal"><?= $this->translate($acceptedAskAuthorFinalVersion) ?></a>
                    </li>
                <?php endif; ?>

                <?php // Préparation de copie: en attente des sources auteurs?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".waiting-for-author-sources-modal"><?= $this->translate($waitingAuthorSources) ?>
                    </a>
                </li>
                <?php // Préparation de copie: en attente de de la mise en forme auteur ?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".waiting-for-author-formatting-modal"><?= $this->translate($waitingFinalVersion) ?>
                    </a>
                </li>

                <!-- publish paper -->
                <?php if ($copyEditingNotStarted && !$paper->isTmp()) : ?>
                    <li>
                        <a href="#" data-toggle="modal"
                           data-target=".publication-modal"><?= $this->translate($publishMsg) ?>
                        </a>
                    </li>
                <?php endif; ?>

            <?php elseif ($status === Episciences_Paper::STATUS_CE_AUTHOR_SOURCES_DEPOSED) : ?>
                <?php // Copy ed. : mise en forme revue terminée?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".review-formatting-deposed-modal"
                       onclick="editAttachmentDescription($(this));"><?= $this->translate($reviewFormattingMsg) ?>
                    </a>
                </li>

                <?php // Préparation de copie: redemander les sources?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".waiting-for-author-sources-modal"><?= $this->translate($askSourcesAgainMsg) ?>
                    </a>
                </li>

            <?php elseif ($status === Episciences_Paper::STATUS_CE_AUTHOR_FINAL_VERSION_DEPOSED) : ?>

                <?php // Préparation de copie: prêt à publier ?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".ready-to-publish-modal"><?= $this->translate($validFinalVersionMsg) ?>
                    </a>
                </li>

                <?php // Préparation de copie: redemander la mise en forme à l'auteur ?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".waiting-for-author-formatting-modal"><?= $this->translate($askFinalVersionAgainMsg) ?>
                    </a>
                </li>

            <?php elseif (!$isInRevision && $copyEditingNotStarted) : ?>
                <!-- accept paper -->
                <li><a href="#" data-toggle="modal"
                       data-target=".acceptance-modal"><?= $this->translate($acceptMsg) ?></a>
                </li>

                <!-- revision request -->
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".minor-revision-modal"><?= $this->translate('Demander des modifications mineures') ?></a>
                </li>

                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".major-revision-modal"><?= $this->translate('Demander des modifications majeures') ?></a>
                </li>
            <?php endif; ?>

            <!-- ask other editors -->
            <?php if (!empty($this->other_editors)) : ?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".ask-other-editors-modal"><?= $this->translate("Demander l'avis d'autres rédacteurs") ?></a>
                </li>
            <?php else : ?>
                <li data-toggle="tooltip" data-placement="top"
                    title="<?= $this->translate("Il n'y a pas d'autres rédacteurs à qui demander un avis.") ?>">
                    <a class="disabled"><?= $this->translate("Demander l'avis d'autres rédacteurs") ?></a>
                </li>
            <?php endif; ?>

            <!-- reject paper -->
            <li>
                <a href="#" data-toggle="modal"
                   data-target=".refusal-modal"><?= $this->translate($refusedMsg) ?></a>
            </li>
        </ul>
    </div>

<?php
// **** EDITORS: can do some stuff, depending of journal settings *****************************
elseif (Episciences_Auth::isEditor() || Episciences_Auth::isGuestEditor()) : ?>
    <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <?= $this->translate($changeStatusMsg) ?> <span class="caret" style="margin-left: 5px"></span>
        </button>
        <ul class="status-menu dropdown-menu" role="menu">

            <?php if ($paper->isAccepted()) : ?>

                <?php // ask author's final version  ?>
                <?php if ($this->review->getSetting(Episciences_Review::SETTING_SYSTEM_PAPER_FINAL_DECISION_ALLOW_REVISION)) : ?>
                    <li>
                        <a href="#" data-toggle="modal"
                           data-target=".accepted-ask-author-final-version-modal"><?= $this->translate($acceptedAskAuthorFinalVersion) ?></a>
                    </li>
                <?php endif; ?>

                <?php // Préparation de copie: en attente des sources auteurs?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".waiting-for-author-sources-modal"><?= $this->translate($waitingAuthorSources) ?>
                    </a>
                </li>

                <?php // Préparation de copie: en attente de de la mise en forme auteur ?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".waiting-for-author-formatting-modal"><?= $this->translate($waitingFinalVersion) ?>
                    </a>
                </li>

                <?php if ($copyEditingNotStarted && $this->review->getSetting('editorsCanPublishPapers')) :    // editors have permission to publish papers ?>
                    <?php if (
                        $this->isRequiredReviewersOk ||
                        $isNotTheFirstVersion ||                         // if this is not the first version of this paper
                        !$this->review->getSetting('requiredReviewers')  // if there is no minimum number of rating reports, or it has been matched
                    ) : ?>

                        <?php // PUBLISH PAPER?>
                        <li>
                            <a href="#" data-toggle="modal"
                               data-target=".publication-modal"><?= $this->translate($publishMsg) ?></a>
                        </li>

                    <?php else : // if there is not enough rating reports, display a notice ?>
                        <li data-toggle="tooltip"
                            data-placement="right"
                            title="<?= $this->translate("Vous ne pouvez pas publier cet article, car le nombre minimum de relectures (%s) n'a pas été atteint.", $this->review->getSetting('requiredReviewers')) ?>">
                            <a class="disabled"><?= $this->translate($publishMsg) ?></a>
                        </li>
                    <?php endif; ?>
                <?php else: ?>
                    <?php // recommandation de publier l'article?>
                <?php endif; ?>

            <?php elseif ($status === Episciences_Paper::STATUS_CE_AUTHOR_SOURCES_DEPOSED) : ?>
                <?php // Copy ed. : mise en forme revue terminée?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".review-formatting-deposed-modal"
                       onclick="editAttachmentDescription($(this));"><?= $this->translate($reviewFormattingMsg) ?>
                    </a>
                </li>

                <?php // Préparation de copie: redemander les sources?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".waiting-for-author-sources-modal"><?= $this->translate($askSourcesAgainMsg) ?>
                    </a>
                </li>

            <?php elseif ($status === Episciences_Paper::STATUS_CE_AUTHOR_FINAL_VERSION_DEPOSED) : ?>

                <?php // Préparation de copie: prêt à publier ?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".ready-to-publish-modal"><?= $this->translate($validFinalVersionMsg) ?>
                    </a>
                </li>

                <?php // Préparation de copie: redemander la mise en forme à l'auteur ?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".waiting-for-author-formatting-modal"><?= $this->translate($askFinalVersionAgainMsg) ?>
                    </a>
                </li>

            <?php elseif ($paper->isReadyToPublish()) : ?>
                <?php if ($this->review->getSetting('editorsCanPublishPapers')) : ?>
                    <li>
                        <a href="#" data-toggle="modal"
                           data-target=".publication-modal"><?= $this->translate($publishMsg) ?></a>
                    </li>
                <?php else: ?>
                    <?php // recommandation de publier?>
                <?php endif; ?>

                <?php // ACCEPT PAPER ************    ?>
            <?php else: ?>
                <?php if (!$isInRevision && $copyEditingNotStarted && $this->review->getSetting('editorsCanAcceptPapers')) :    // editors have permission to accept papers ?>
                    <?php if (
                        $this->isRequiredReviewersOk ||
                        $isNotTheFirstVersion ||                         // if this is not the first version of this paper
                        !$this->review->getSetting('requiredReviewers')  // if there is no minimum number of rating reports, or it has been matched

                    ) : ?>
                        <li>
                            <a href="#" data-toggle="modal"
                               data-target=".acceptance-modal"><?= $this->translate($acceptMsg) ?></a>
                        </li>
                    <?php else : // if there is not enough rating reports, display a notice ?>
                        <li data-toggle="tooltip"
                            data-placement="right"
                            title="<?= $this->translate("Vous ne pouvez pas accepter cet article, car le nombre minimum de relectures (%s) n'a pas été atteint.", $this->review->getSetting('requiredReviewers')) ?>">
                            <a class="disabled"><?= $this->translate($acceptMsg) ?></a>
                        </li>
                    <?php endif; ?>

                <?php elseif (!$paper->isReadyToPublish() && !$paper->isAcceptedSubmission()): // editors do not have permission to accept papers, but can suggest to do it ?>
                    <li onclick="showForm('accept'); return false;"
                        data-toggle="tooltip"
                        data-placement="right"
                        title="<?= $this->suggestedAccept ? $this->translate($suggestionInfoMsg) : '' ?>"
                    >
                        <a <?= !$this->suggestedAccept ? 'href="#" data-toggle="modal" data-target=".suggestions-status-modal"' : 'class="disabled"' ?>><?= $this->translate("Recommander d'accepter l'article") ?></a>
                    </li>
                <?php endif; ?>
            <?php endif; ?>

            <?php // REJECT PAPER ************    ?>
            <?php if ($this->review->getSetting('editorsCanRejectPapers')) :    // editors have permission to reject papers ?>
                <?php if ($isNotTheFirstVersion) : // if this is not the first version of this paper ?>
                    <li>
                        <a href="#" data-toggle="modal"
                           data-target=".refusal-modal"><?= $this->translate($refusedMsg) ?>
                        </a>
                    </li>
                <?php else : // display a notice ?>
                    <li data-toggle="tooltip" data-placement="right"
                        title="<?= $this->translate("Cet article n'est pas la première version de ce document, vous ne pouvez pas donc le refuser.") ?>">
                        <a class="disabled"><?= $this->translate($refusedMsg) ?></a>
                    </li>
                <?php endif; ?>
            <?php else : // editors do not have permission to reject papers, but can suggest to do it?>
                <li onclick="showForm('refuse'); return false;"
                    data-toggle="tooltip"
                    data-placement="right"
                    title="<?= $this->suggestedRefuse ? $this->translate($suggestionInfoMsg) : '' ?>"
                >
                    <a <?= !$this->suggestedRefuse ? 'href="#" data-toggle="modal" data-target=".suggestions-status-modal"' : 'class="disabled"' ?>><?= $this->translate("Recommander de refuser l'article") ?></a>
                </li>
            <?php endif; ?>

            <?php // ASK FOR A REVISION ************    ?>
            <?php if ($copyEditingNotStarted && $this->review->getSetting('editorsCanAskPaperRevisions')) :    // editors have permission to ask for a revision ?>
                <?php if (
                    $this->isRequiredReviewersOk ||
                    $isNotTheFirstVersion ||                         // if this is not the first version of this paper
                    !$this->review->getSetting('requiredReviewers')  // if there is no minimum number of rating reports, or it has been matched

                ) : ?>
                    <?php if (!$isInRevision) : ?>
                        <li>
                            <a href="#" data-toggle="modal"
                               data-target=".minor-revision-modal"><?= $this->translate('Demander des modifications mineures') ?></a>
                        </li>
                        <li><a href="#" data-toggle="modal"
                               data-target=".major-revision-modal"><?= $this->translate('Demander des modifications majeures') ?></a>
                        </li>
                    <?php endif; ?>
                <?php else : // if there is not enough rating reports, display a notice ?>
                    <li data-toggle="tooltip"
                        data-placement="right"
                        title="<?= $this->translate("Vous ne pouvez faire de demande de modifications, car le nombre minimum de relectures (%s) n'a pas été atteint.", $this->review->getSetting('requiredReviewers')) ?>">
                        <a class="disabled"><?= $this->translate("Demander des modifications") ?></a>
                    </li>
                <?php endif; ?>
            <?php else : // editors do not have permission to reject papers, but can suggest to do it?>
                <li onclick="showForm('newversion'); return false;"
                    data-toggle="tooltip"
                    data-placement="right"
                    title="<?= $this->suggestedRevision ? $this->translate($suggestionInfoMsg) : '' ?>"
                >
                    <a <?= !$this->suggestedRevision ? 'href="#" data-toggle="modal" data-target=".suggestions-status-modal"' : 'class="disabled"' ?>><?= $this->translate("Suggérer de demander une nouvelle version") ?></a>
                </li>
            <?php endif; ?>

            <!-- ask other editors -->
            <?php if (!$paper->isEditable()) : ?>
                <?php if (!empty($this->other_editors)) : ?>
                    <!-- ASK OTHER EDITORS -->
                    <li>
                        <a href="#" data-toggle="modal"
                           data-target=".ask-other-editors-modal"><?= $this->translate("Demander l'avis d'autres rédacteurs") ?></a>
                    </li>
                <?php else : ?>
                    <li data-toggle="tooltip" data-placement="top"
                        title="<?= $this->translate("Il n'y a pas d'autres rédacteurs à qui demander un avis.") ?>">
                        <a class="disabled"><?= $this->translate("Demander l'avis d'autres rédacteurs") ?></a>
                    </li>
                <?php endif; ?>
            <?php endif; ?>
        </ul>
    </div>
    <?php // Copy editor?>
<?php elseif (Episciences_Auth::isCopyEditor()) : ?>
    <div class="btn-group">
        <?php if ($paper->isAccepted()) : ?>
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <?= $this->translate($changeStatusMsg) ?> <span class="caret" style="margin-left: 5px"></span>
            </button>
            <ul class="status-menu dropdown-menu" role="menu">
                <?php // ask author's final version  ?>
                <?php if ($this->review->getSetting(Episciences_Review::SETTING_SYSTEM_PAPER_FINAL_DECISION_ALLOW_REVISION)) : ?>
                    <li>
                        <a href="#" data-toggle="modal"
                           data-target=".accepted-ask-author-final-version-modal"><?= $this->translate($acceptedAskAuthorFinalVersion) ?></a>
                    </li>
                <?php endif; ?>

                <?php // Préparation de copie: en attente des sources auteurs?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".waiting-for-author-sources-modal"><?= $this->translate($waitingAuthorSources) ?></a>
                </li>

                <?php // Préparation de copie: en attente de de la mise en forme auteur ?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".waiting-for-author-formatting-modal"><?= $this->translate($waitingFinalVersion) ?></a>
                </li>
            </ul>

        <?php elseif ($status === Episciences_Paper::STATUS_CE_AUTHOR_SOURCES_DEPOSED) : ?>
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <?= $this->translate($changeStatusMsg) ?> <span class="caret" style="margin-left: 5px"></span>
            </button>
            <ul class="status-menu dropdown-menu" role="menu">
                <?php // Copy ed. : mise en forme revue terminée?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".review-formatting-deposed-modal"
                       onclick="editAttachmentDescription($(this));"><?= $this->translate($reviewFormattingMsg) ?>
                    </a>
                </li>

                <?php // Préparation de copie: redemander les sources?>
                <li>
                    <a href="#" data-toggle="modal"
                       data-target=".waiting-for-author-sources-modal"><?= $this->translate($askSourcesAgainMsg) ?>
                    </a>
                </li>
            </ul>

        <?php elseif ($status === Episciences_Paper::STATUS_CE_AUTHOR_FINAL_VERSION_DEPOSED) : ?>

            <?php // Préparation de copie: prêt à publier ?>

            <a href="#" data-toggle="modal" class="btn btn-primary btn-sm"
               data-target=".ready-to-publish-modal"><?= $this->translate($validFinalVersionMsg) ?></a>

            <?php // Préparation de copie: redemander la mise en forme à l'auteur ?>
            <li>
                <a href="#" data-toggle="modal"
                   data-target=".waiting-for-author-formatting-modal"><?= $this->translate($askFinalVersionAgainMsg) ?>
                </a>
            </li>

        <?php else: ?>
            <a href="#" class="btn btn-default btn-sm disabled" role="button"
               aria-disabled="true"><?= $this->translate("Vous ne pouvez pas changer le statut de l'article : temporairement indisponible.") ?></a>
        <?php endif; ?>
    </div>

<?php endif ?>

<?php // ******* MODALS (FORMS) ***************** ?>
<?php if (Episciences_Auth::isAllowedToManagePaper()) : ?>
    <?php // *** publication form ************ ?>
    <?php if ($paper->isAccepted() || $paper->isReadyToPublish()) : ?>
        <div class="modal fade publication-modal" tabindex="-1" role="dialog" aria-labelledby="publication-modal"
             aria-hidden="true">
            <div class="modal-dialog" style="width: 50%">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title"><?= $this->translate($publishMsg) ?></h4>
                    </div>
                    <div class="modal-body"><?= $this->publicationForm ?></div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default"
                                data-dismiss="modal"><?= $this->translate('Annuler') ?></button>
                        <button type="button" id="submit-modal-publication"
                                class="btn btn-primary submit-modal"><?= $this->translate('Valider') ?></button>
                    </div>
                </div>
            </div>
        </div>

    <?php
// *** acceptation form ************
    else: ?>
        <div class="modal fade acceptance-modal" tabindex="-1" role="dialog" aria-labelledby="acceptance-modal"
             aria-hidden="true">
            <div class="modal-dialog" style="width: 50%">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title"><?= $this->translate($acceptMsg) ?></h4>
                    </div>
                    <div class="modal-body">
                        <?= $this->acceptanceForm ?>
                        <div class="contacts_container"></div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default"
                                data-dismiss="modal"><?= $this->translate('Annuler') ?></button>
                        <button type="button" id="submit-modal-acceptance"
                                class="btn btn-primary submit-modal"><?= $this->translate('Valider') ?></button>
                    </div>
                </div>
            </div>
        </div>
    <?php endif; ?>

    <?php // accepted article: ask author's final version  ?>
    <div class="modal fade accepted-ask-author-final-version-modal" tabindex="-1" role="dialog"
         aria-labelledby="accepted-ask-author-final-version-modal"
         aria-hidden="true">
        <div class="modal-dialog" style="width: 50%">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"><?= $this->translate("Demander la version final à l'auteur") ?></h4>
                </div>
                <div class="modal-body"><?= $this->acceptedAskAuthorFinalVersionForm ?></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default"
                            data-dismiss="modal"><?= $this->translate('Annuler') ?></button>
                    <button type="button" id="submit-modal-minor-revision"
                            class="btn btn-primary submit-modal"><?= $this->translate('Valider') ?></button>
                </div>
            </div>
        </div>
    </div>

    <?php // *** minor revision request form ********** ?>
    <div class="modal fade minor-revision-modal" tabindex="-1" role="dialog" aria-labelledby="minor-revision-modal"
         aria-hidden="true">
        <div class="modal-dialog" style="width: 50%">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"><?= $this->translate("Demander des modifications mineures") ?></h4>
                </div>
                <div class="modal-body"><?= $this->minorRevisionForm ?></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default"
                            data-dismiss="modal"><?= $this->translate('Annuler') ?></button>
                    <button type="button" id="submit-modal-minor-revision"
                            class="btn btn-primary submit-modal"><?= $this->translate('Valider') ?></button>
                </div>
            </div>
        </div>
    </div>

    <?php // *** major revision request form ********** ?>
    <div class="modal fade major-revision-modal" tabindex="-1" role="dialog" aria-labelledby="major-revision-modal"
         aria-hidden="true">
        <div class="modal-dialog" style="width: 50%">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"><?= $this->translate("Demander des modifications majeures") ?></h4>
                </div>
                <div class="modal-body"><?= $this->majorRevisionForm ?></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default"
                            data-dismiss="modal"><?= $this->translate('Annuler') ?></button>
                    <button type="button" id="submit-modal-major-revision"
                            class="btn btn-primary submit-modal"><?= $this->translate('Valider') ?></button>
                </div>
            </div>
        </div>
    </div>

    <?php // *** reject form ********** ?>
    <div class="modal fade refusal-modal" tabindex="-1" role="dialog" aria-labelledby="refusal-modal"
         aria-hidden="true">
        <div class="modal-dialog" style="width: 50%">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"><?= $this->translate($refusedMsg) ?></h4>
                </div>
                <div class="modal-body"><?= $this->refusalForm ?></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default"
                            data-dismiss="modal"><?= $this->translate('Annuler') ?></button>
                    <button type="button" id="submit-modal-refusal"
                            class="btn btn-primary submit-modal"><?= $this->translate('Valider') ?></button>
                </div>
            </div>
        </div>
    </div>

    <?php // *** ask other editors form ********** ?>
    <?php if (!empty($this->other_editors)) : ?>
        <div class="modal fade ask-other-editors-modal" tabindex="-1" role="dialog"
             aria-labelledby="ask-other-editors-modal" aria-hidden="true">
            <div class="modal-dialog" style="width: 50%">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title"><?= $this->translate("Demander l'avis d'autres rédacteurs") ?></h4>
                    </div>
                    <div class="modal-body">
                        <?= $this->askOtherEditorsForm ?>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default"
                                data-dismiss="modal"><?= $this->translate('Annuler') ?></button>
                        <button type="button" id="submit-modal-ask-other-editors"
                                class="btn btn-primary submit-modal"><?= $this->translate('Valider') ?></button>
                    </div>
                </div>
            </div>
        </div>
    <?php endif; ?>

    <?php if ($this->suggestionsStatusForm) : ?>
        <?php // *** suggestions status  ********** ?>
        <div class="modal fade suggestions-status-modal" tabindex="-1" role="dialog"
             aria-labelledby="suggestion-status-modal" aria-hidden="true">
            <div class="modal-dialog" style="width: 50%">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title"><?= $this->translate('Suggestions') ?></h4>
                    </div>
                    <div class="modal-body"><?= $this->suggestionsStatusForm ?></div>
                </div>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>

<?php // Waiting for author sources request?>
<div class="modal fade waiting-for-author-sources-modal" tabindex="-1" role="dialog"
     aria-labelledby="waiting-for-author-resources-modal" aria-hidden="true">
    <div class="modal-dialog" style="width: 50%">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?= $this->translate("Demander des sources auteur") ?></h4>
            </div>
            <div class="modal-body"><?= $this->authorSourcesRequestForm ?></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default"
                        data-dismiss="modal"><?= $this->translate('Annuler') ?></button>
                <button type="button" id="submit-modal-author-sources"
                        class="btn btn-primary submit-modal"><?= $this->translate('Valider') ?></button>
            </div>
        </div>
    </div>
</div>

<?php // Waiting for author  formatting (last version)?>
<div class="modal fade waiting-for-author-formatting-modal" tabindex="-1" role="dialog"
     aria-labelledby="waiting-for-author-formatting-modal" aria-hidden="true">
    <div class="modal-dialog" style="width: 50%">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?= $this->translate("Demander la mise en forme par l'auteur (version finale)") ?></h4>
            </div>
            <div class="modal-body"><?= $this->authorFormattingRequestForm ?></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default"
                        data-dismiss="modal"><?= $this->translate('Annuler') ?></button>
                <button type="button" id="submit-modal-author-formatting"
                        class="btn btn-primary submit-modal"><?= $this->translate('Valider') ?></button>
            </div>
        </div>
    </div>
</div>


<?php // Mise en forme revue terminée)?>
<div class="modal fade review-formatting-deposed-modal" tabindex="-1" role="dialog"
     aria-labelledby="review-formatting-deposed-modal" aria-hidden="true">
    <div class="modal-dialog" style="width: 50%">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?= $this->translate($reviewFormattingMsg) ?></h4>
            </div>
            <div class="modal-body"><?= $this->reviewFormattingDeposedForm ?></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default"
                        data-dismiss="modal"><?= $this->translate('Annuler') ?></button>
                <button type="button" id="submit-modal-review-formatting-submitted"
                        class="btn btn-primary submit-modal"><?= $this->translate('Valider') ?></button>
            </div>
        </div>
    </div>
</div>

<?php // ready to publish : une fois la version finale est déposée)?>
<div class="modal fade ready-to-publish-modal" tabindex="-1" role="dialog"
     aria-labelledby="ready-to-publish-modal" aria-hidden="true">
    <div class="modal-dialog" style="width: 50%">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?= $this->translate($validFinalVersionMsg) ?></h4>
            </div>
            <div class="modal-body"><?= $this->ceAcceptFinalVersionForm ?></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default"
                        data-dismiss="modal"><?= $this->translate('Annuler') ?></button>
                <button type="button" id="submit-modal-ce-accept-final-version"
                        class="btn btn-primary submit-modal"><?= $this->translate('Valider') ?></button>
            </div>
        </div>
    </div>
</div>
