<?php


// TODO: VERIFIER CE TEMPLATE (COMPARER AVEC PAPER_VOLUME)
$this->jQuery()->addJavascriptFile('/js/administratepaper/editorsAndCopyEditors-assignment.js');

$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
/** @var Episciences_Paper $paper */
$paper = $this->article;
/** @var array $editors */
$editors = $this->editors;
$loggedUid = Episciences_Auth::getUid();
$isAssignedToPaper = array_key_exists($loggedUid, $editors);
$disabled = '';
$title = '';
$ariaDisabled = 'aria-disabled="false"';
if ($this->isMonitoringRefused) {
    $disabled = 'disabled';
    $ariaDisabled = 'aria-disabled="true"';
    $title = "Le suivi de l'article sera bientôt confié à un autre rédacteur";
}

?>

<?php
// alert
$alertMsg = "Vous ne souhaitez plus gérer cet article, sa gestion vous sera bientôt retirée.";
?>

<?php if ($isAssignedToPaper && $this->isMonitoringRefused): ?>
    <div class="alert alert-warning" style="margin-top: 20px">
        <strong><?= $this->translate($alertMsg); ?></strong><br/>
    </div>
<?php endif; ?>

<div id="<?= $this->id ?: 'editors' ?>" class="editors">
    <?php if (count($editors)) : ?>

        <?php /** @var Episciences_Editor $editor */
        foreach ($editors as $editor) : ?>
            <div class="editor" style="margin-bottom: 5px;">

                <a class="btn btn-default" href="/user/view/userid/<?= $editor->getUid(); ?>" target="_blank">
                    <span data-toggle="tooltip"
                          class="fa-regular fa-address-card"
                          style="margin: 0.2rem"
                          title="<?php echo $this->translate("Voir le profil") ?>">
                    </span>
                </a>

                <?php if ($editor->getUid() !== Episciences_Auth::getUid()) : ?>
                    <a class="modal-opener btn btn-default" href="/administratemail/send/recipient/<?= $editor->getUid() ?>/paper/<?= $paper->getDocid() ?>">
                    <span data-toggle="tooltip"
                          class="glyphicon glyphicon-envelope"
                          style="margin: 0.2rem"
                          title="<?= $this->translate("Contacter ce rédacteur") ?>">
                    </span>
                    </a>
                <?php endif; ?>

                <?php if (Episciences_Auth::isSecretary()) : ?>
                    <a class="btn btn-default" href="/user/su/uid/<?php echo $editor->getUid(); ?>">
                        <span data-toggle="tooltip"
                              style="margin: 0.2rem"
                              title="<?php echo $this->translate("Se connecter avec ce compte."); ?>"
                              class="fas fa-user-secret">

                        </span>
                    </a>&nbsp;
                <?php endif; ?>

                <img src="/user/photo/name/<?= urlencode($this->escape($editor->getScreenName())); ?>/uid/<?= $editor->getUid(); ?>/size/<?= Ccsd_User_Models_User::IMG_NAME_INITIALS ?>?v=<?php echo Episciences_Auth::getPhotoVersion() ?>"
                     class="user-photo-small" alt="avatar">
                <span style="margin-left: 0.5em;"><strong><?php echo $editor->getScreenName(); ?></strong></span>


                <?php
                $sections = $editor->getAssignedSections();
                if ($sections) {
                    $msg = $this->translate(array("Rédacteur de la rubrique : ", "Rédacteur des rubriques : ", count($sections)));
                    $sectionNames = [];
                    /** @var Episciences_Section $section */
                    foreach ($sections as $section) {
                        $sectionNames[] = '"' . $section->getNameKey() . '"';
                    }
                    $msg .= implode(', ', $sectionNames);
                } else {
                    $msg = '';
                }
                ?>
                <?php if ($msg) : ?><span class="lightgrey text-info" style="margin-left: 5px;">
                    (<?= $msg; ?>)</span><?php endif; ?>
            </div>
        <?php endforeach; ?>
    <?php else: ?>
        <p>
            <?= $this->translate('Aucun rédacteur pour le moment') . '.'; ?>
        </p>
    <?php endif; // endif(count($editors)) ?>

    <?php if ($paper->getEditor(Episciences_Auth::getUid()) && $paper->isEditable()) : ?>
        <button id="refused_monitoring_button-<?= $loggedUid; ?>" data-toggle="tooltip" data-placement="right"
                title="<?= $this->translate($title); ?>"
                class="btn btn-default btn-sm popover-link <?= $disabled; ?>" role="button" <?= $ariaDisabled; ?>
                onclick="getRefusedMonitoringForm(<?= $paper->getDocid(); ?>, <?= $loggedUid; ?>)"
        >
            <span class="glyphicon glyphicon-log-out"></span>
            <?= $this->translate('Je ne souhaite plus gérer cet article'); ?>
        </button>
    <?php endif; ?>

    <?php // editors assignment button ********************************************** ?>
    <?php if (Episciences_Auth::isSecretary() && $paper->isEditable()) : ?>
        <?php
        $btnName = 'Assigner des rédacteurs';
        $btnId = 'editors';
        ?>
        <?= $this->partial('partials/paper_editors_copyeditors_assign_button.phtml', [
            'paper' => $paper, 'btnName' => $btnName, 'btnId' => $btnId, 'isPartial' => $this->isPartial
        ]);
        ?>
    <?php endif; ?>
</div>
