<?php
$docid = $this->paper->getDocid();
$doi = $this->escape('https://doi.org/'.$this->paper->getDoi());
$title = $this->escape($this->paper->getTitle());
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
// twitter

$url = "https://x.com/intent/tweet/?text=".$title."&url=".$doi;
$contributorSocialMedia = $this->contributorSocialMedia;

$coAuthors = $this->coAuthorsList;
// for mastodon

if (Episciences_Auth::isLogged()) {
    $identity = Episciences_Auth::getInstance()->getIdentity()->toArray();
    $loggedUser = new Episciences_User($identity);
    $loggedUserSocialMedia = $loggedUser->getSocialMedias();
} else {
    $loggedUserSocialMedia = null;
}

$socialCoAuthorList = [];
if ($contributorSocialMedia && substr_count($contributorSocialMedia, "@") === 1) {
    $url = "https://x.com/intent/tweet/?text=".$title;
    if (!is_null($contributorSocialMedia)) {
        foreach ($coAuthors as $coAuthorInfo) {
            /** @var Episciences_User $coAuthorInfo */
            $socialCoAuthor = $coAuthorInfo->getSocialMedias();
            if (!is_null($socialCoAuthor) && substr_count($socialCoAuthor, "@") === 1) {
                $socialCoAuthorList[] = $socialCoAuthor;
            }
        }
        $url .= (strpos($contributorSocialMedia, "@") === 0) ? " ".$contributorSocialMedia
            : " @".$contributorSocialMedia;
        if (!empty($socialCoAuthorList)) {
            foreach ($socialCoAuthorList as $socialCo) {
                $url .= (strpos($contributorSocialMedia, "@") === 0) ? " ".$socialCo
                    : " @".$socialCo;
            }
        }
    }
    $url.="&url=".$doi;
}
?>
<div class="panel-body in">

    <div class="row">
        <div class="col-md-9">


            <!-- Sharingbutton E-Mail -->
            <a class="resp-sharing-button__link"
               href="mailto:?subject=<?= $title ?>&amp;body=<?= $doi ?>"
               target="_self" rel="noopener" aria-label="">
                <div class="resp-sharing-button resp-sharing-button--email resp-sharing-button--small">
                    <div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solidcircle">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                            <path d="M12 0C5.38 0 0 5.38 0 12s5.38 12 12 12 12-5.38 12-12S18.62 0 12 0zm8 16c0 1.1-.9 2-2 2H6c-1.1 0-2-.9-2-2V8c0-1.1.9-2 2-2h12c1.1 0 2 .9 2 2v8z"/>
                            <path d="M17.9 8.18c-.2-.2-.5-.24-.72-.07L12 12.38 6.82 8.1c-.22-.16-.53-.13-.7.08s-.15.53.06.7l3.62 2.97-3.57 2.23c-.23.14-.3.45-.15.7.1.14.25.22.42.22.1 0 .18-.02.27-.08l3.85-2.4 1.06.87c.1.04.2.1.32.1s.23-.06.32-.1l1.06-.9 3.86 2.4c.08.06.17.1.26.1.17 0 .33-.1.42-.25.15-.24.08-.55-.15-.7l-3.57-2.22 3.62-2.96c.2-.2.24-.5.07-.72z"/>
                        </svg>
                    </div>
                </div>
            </a>

            <!-- Sharingbutton Twitter/X -->
            <a class="resp-sharing-button__link"
               href="<?= $url ?>"
               target="_blank" rel="noopener" aria-label="">
                <div class="resp-sharing-button resp-sharing-button--twitter resp-sharing-button--small">
                    <div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solidcircle">
                        <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="100" height="100" viewBox="0,0,256,256">
                            <g fill-opacity="0" fill="#6c4e4a" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal"><path d="M0,256v-256h256v256z" id="bgRectangle"></path></g><g fill="#000000" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal"><g transform="scale(5.12,5.12)"><path d="M5.91992,6l14.66211,21.375l-14.35156,16.625h3.17969l12.57617,-14.57812l10,14.57813h12.01367l-15.31836,-22.33008l13.51758,-15.66992h-3.16992l-11.75391,13.61719l-9.3418,-13.61719zM9.7168,8h7.16406l23.32227,34h-7.16406z"></path></g></g>
                        </svg>
                    </div>
                </div>
            </a>
            <?php if ($loggedUserSocialMedia && substr_count($loggedUserSocialMedia, "@") > 1) :
                $loggedUserInfo = Episciences_Tools::getMastodonSeparatedInfo($loggedUserSocialMedia);
                ?>
                <!-- Sharingbutton Mastodon -->
                <a class="resp-sharing-button__link"
                   href="<?= "https://" . $loggedUserInfo[2] . "/share?text=" . $title . '&url=' . $doi ?>"
                   target="_blank" rel="noopener" aria-label="">
                    <div class="resp-sharing-button resp-sharing-button--mastodon resp-sharing-button--small">
                        <div aria-hidden="true"
                             class="resp-sharing-button__icon resp-sharing-button__icon--solidcircle">
                            <svg xmlns="http://www.w3.org/2000/svg" class="bi bi-mastodon" viewBox="0 0 16 16">
                                <path d="M11.19 12.195c2.016-.24 3.77-1.475 3.99-2.603.348-1.778.32-4.339.32-4.339 0-3.47-2.286-4.488-2.286-4.488C12.062.238 10.083.017 8.027 0h-.05C5.92.017 3.942.238 2.79.765c0 0-2.285 1.017-2.285 4.488l-.002.662c-.004.64-.007 1.35.011 2.091.083 3.394.626 6.74 3.78 7.57 1.454.383 2.703.463 3.709.408 1.823-.1 2.847-.647 2.847-.647l-.06-1.317s-1.303.41-2.767.36c-1.45-.05-2.98-.156-3.215-1.928a3.614 3.614 0 0 1-.033-.496s1.424.346 3.228.428c1.103.05 2.137-.064 3.188-.189zm1.613-2.47H11.13v-4.08c0-.859-.364-1.295-1.091-1.295-.804 0-1.207.517-1.207 1.541v2.233H7.168V5.89c0-1.024-.403-1.541-1.207-1.541-.727 0-1.091.436-1.091 1.296v4.079H3.197V5.522c0-.859.22-1.541.66-2.046.456-.505 1.052-.764 1.793-.764.856 0 1.504.328 1.933.983L8 4.39l.417-.695c.429-.655 1.077-.983 1.934-.983.74 0 1.336.259 1.791.764.442.505.661 1.187.661 2.046v4.203z"/>
                            </svg>
                        </div>
                    </div>
                </a>
            <?php endif; ?>


            <!-- Sharingbutton LinkedIn -->
            <a class="resp-sharing-button__link"
               href="https://www.linkedin.com/shareArticle?mini=true&amp;url=<?= $doi ?>&amp;title=<?= $title ?>&amp;summary=<?= $title ?>&amp;source=<?= $doi ?>"
               target="_blank" rel="noopener" aria-label="">
                <div class="resp-sharing-button resp-sharing-button--linkedin resp-sharing-button--small">
                    <div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solidcircle">
                        <svg version="1.1" x="0px" y="0px" width="24px" height="24px" viewBox="0 0 24 24"
                             enable-background="new 0 0 24 24" xml:space="preserve">
            <path d="M12,0C5.383,0,0,5.383,0,12s5.383,12,12,12s12-5.383,12-12S18.617,0,12,0z M9.5,16.5h-2v-7h2V16.5z M8.5,7.5 c-0.553,0-1-0.448-1-1c0-0.552,0.447-1,1-1s1,0.448,1,1C9.5,7.052,9.053,7.5,8.5,7.5z M18.5,16.5h-3V13c0-0.277-0.225-0.5-0.5-0.5 c-0.276,0-0.5,0.223-0.5,0.5v3.5h-3c0,0,0.031-6.478,0-7h3v0.835c0,0,0.457-0.753,1.707-0.753c1.55,0,2.293,1.12,2.293,3.296V16.5z"/>
        </svg>
                    </div>
                </div>
            </a>

            <!-- Sharingbutton Reddit -->
            <a class="resp-sharing-button__link"
               href="https://reddit.com/submit/?url=<?= $doi ?>&amp;resubmit=true&amp;title=<?= $title ?>"
               target="_blank" rel="noopener" aria-label="">
                <div class="resp-sharing-button resp-sharing-button--reddit resp-sharing-button--small">
                    <div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solidcircle">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                            <circle cx="9.391" cy="13.392" r=".978"/>
                            <path d="M14.057 15.814c-1.14.66-2.987.655-4.122-.004-.238-.138-.545-.058-.684.182-.13.24-.05.545.19.685.72.417 1.63.646 2.568.646.93 0 1.84-.228 2.558-.642.24-.13.32-.44.185-.68-.14-.24-.445-.32-.683-.18zM5 12.086c0 .41.23.78.568.978.27-.662.735-1.264 1.353-1.774-.2-.207-.48-.334-.79-.334-.62 0-1.13.507-1.13 1.13z"/>
                            <path d="M12 0C5.383 0 0 5.383 0 12s5.383 12 12 12 12-5.383 12-12S18.617 0 12 0zm6.673 14.055c.01.104.022.208.022.314 0 2.61-3.004 4.73-6.695 4.73s-6.695-2.126-6.695-4.74c0-.105.013-.21.022-.313C4.537 13.73 4 12.97 4 12.08c0-1.173.956-2.13 2.13-2.13.63 0 1.218.29 1.618.757 1.04-.607 2.345-.99 3.77-1.063.057-.803.308-2.33 1.388-2.95.633-.366 1.417-.323 2.322.085.302-.81 1.076-1.397 1.99-1.397 1.174 0 2.13.96 2.13 2.13 0 1.177-.956 2.133-2.13 2.133-1.065 0-1.942-.79-2.098-1.81-.734-.4-1.315-.506-1.716-.276-.6.346-.818 1.395-.88 2.087 1.407.08 2.697.46 3.728 1.065.4-.468.987-.756 1.617-.756 1.17 0 2.13.953 2.13 2.13 0 .89-.54 1.65-1.33 1.97z"/>
                            <circle cx="14.609" cy="13.391" r=".978"/>
                            <path d="M17.87 10.956c-.302 0-.583.128-.79.334.616.51 1.082 1.112 1.352 1.774.34-.197.568-.566.568-.978 0-.623-.507-1.13-1.13-1.13z"/>
                        </svg>
                    </div>
                </div>
            </a>

            <!-- Sharingbutton Facebook -->
            <a class="resp-sharing-button__link"
               href="https://facebook.com/sharer/sharer.php?u=<?= $doi ?>" target="_blank" rel="noopener"
               aria-label="">
                <div class="resp-sharing-button resp-sharing-button--facebook resp-sharing-button--small">
                    <div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solidcircle">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                            <path d="M12 0C5.38 0 0 5.38 0 12s5.38 12 12 12 12-5.38 12-12S18.62 0 12 0zm3.6 11.5h-2.1v7h-3v-7h-2v-2h2V8.34c0-1.1.35-2.82 2.65-2.82h2.35v2.3h-1.4c-.25 0-.6.13-.6.66V9.5h2.34l-.24 2z"/>
                        </svg>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-3">
            <?php echo $this->partial('partials/paper_export.phtml', ['docid' => $docid]); ?>
        </div>
    </div>

</div>