<?php

$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$sid = $this->article->getSid();

?>

<div class="section">

    <?php // Section assignment button ?>
    <?php if ($this->isAllowed && !$this->article->isRefused() && !$this->article->isObsolete() && !$this->article->isDeleted()): ?>
        <?php if ($this->isPartial): ?>
            <button class="btn btn-default btn-xs pull-right"
                    data-modal="section"
                    data-docid="<?= (int) $this->article->getDocid() ?>"
                    data-partial="true"
                    data-toggle="tooltip"
                    title="<?= $this->translate('Déplacer dans une rubrique') ?>">
                <i class="fa-solid fa-pen-to-square"></i>
            </button>
        <?php else: ?>
            <button class="btn btn-default btn-sm"
                    style="margin-right: 5px"
                    data-modal="section"
                    data-docid="<?= (int) $this->article->getDocid() ?>"
                    data-partial="false">
                <i class="fa-solid fa-pen-to-square" style="margin-right: 5px"></i>
                <?= $this->translate('Modifier') ?>
            </button>
        <?php endif; ?>
    <?php elseif (!$this->isAllowed && Episciences_Auth::getUid() == $this->article->getUid()): ?>
        <button class="btn btn-default btn-xs pull-right" disabled="disabled"
                data-toggle="tooltip"
                title="<?= $this->translate('Vous ne pouvez pas modifier un article que vous avez vous-même déposé.') ?>">
            <i class="fa-solid fa-pen-to-square"></i>
        </button>
    <?php endif; ?>

    <?php // Section name ?>
    <?php if (!$this->isPartial): ?>
        <?= $this->translate('Section :') ?>
    <?php endif; ?>
    <?php if ($sid && array_key_exists($sid, $this->sections)): ?>
        <?= $this->translate($this->sections[$sid]->getNameKey()) ?>
    <?php elseif (!$this->isPartial): ?>
        <?= $this->translate('Hors rubrique') ?>
    <?php endif; ?>

</div>
