<?php
$op = '';
$this->declareVars(array(
        'parsedSearchParams' => array()
));

// if ($this->formErrorsMessages) {
// var_dump($this->formErrorsMessages);
// }

$formAction = $this->url(array(
        'controller' => 'search',
        'action' => 'author'
), null, true);

?>


<!-- Simple Search -->

<div class="span12 offset2 clearfix">
	<form id="search-simple" action="<?php echo $formAction; ?>"
		name="search-simple" method="get" class="form-horizontal span11">

		<div class="input-append">
			<div class="btn-group">
				<input
                    data-src="aut"
                    id="q" name="q" class="span6" type="text" pattern=".{0,300}"
					title="300 caractères max."
					placeholder="<?php echo $this->translate("Nom d'auteur"); ?>"
					x-webkit-speech style="min-width: 200px;" tabindex="1"
					value="<?php if (array_key_exists('q', $this->parsedSearchParams) ) { echo $this->escape($this->parsedSearchParams['q']); } ?>" />





						<?php
    //if (array_key_exists('q', $this->parsedSearchParams)) {
        ?>

						 <span data-toggle="dropdown" data-target="#searchoptionsdropdown"
					class="add-on btn dropdown-toggle"> <span id="search-options-dropdown"
					class="glyphicon glyphicon-cog"></span></span>
<?php
    //}
    ?>
					<button name="submit" type="submit" class="btn btn-primary">
					<span class="glyphicon glyphicon-search white"></span>&nbsp;<?php echo $this->translate('Rechercher');?>
					</button>
			</div>
		</div>
	</form>
</div>

<!-- //Simple Search -->

<div class="span6 offset6 clearfix">
	<div id="searchoptionsdropdown" class="pull-left btn-group dropdown"
		style="min-width: 400px; padding-bottom: 0px;">

		<ul class="keepopen dropdown-menu clearfix">
			<li class="nav-header"><?php echo $this->translate('Options'); ?>
				<button type="button" style="z-index: 9999; position: relative;"
					class="close"
					onclick="$('.dropdown').removeClass('open open-permanent')">×</button>

			</li>

			<li class="divider"></li>

			<li class="clearfix nav-list">
				<!-- Nombre de résultats par page ============================== -->
				<p><?php echo $this->translate('Nombre de résultats par page :'); ?></p>
				<div class="btn-group" data-toggle="buttons-radio">
<?php
$urlParams = $this->parsedSearchParams;

foreach ($this->paginatorNumberOfResultsArray as $paginatorNumberOfResults) {
    $isActive = '';

    if (isset($this->parsedSearchParams['rpp']) and ($this->parsedSearchParams['rpp'] == $paginatorNumberOfResults)) {
        // valeur en cours
        $isActive = ' btn-success active disabled';
    }

    if (! isset($this->parsedSearchParams['rpp']) and $paginatorNumberOfResults == $this->paginatordefaultNumberOfResults) {
        // valeur par défaut
        $isActive = ' btn-success active disabled';
    }

    $urlParams['rpp'] = $paginatorNumberOfResults;

    echo '<a href="' . $this->escape($this->url($urlParams, null, TRUE)) . '" class="btn btn-small' . $isActive . '">';
    echo $this->escape($paginatorNumberOfResults);
    echo '</a>';
}
?>
</div> <!-- Nombre de résultats par page ============================== -->

				<hr /> <!-- Tri des résultats -->
				<p><?php echo $this->translate('Tri des résultats :'); ?></p>




   <?php

$sortDataForView['score desc'] = '<span class="glyphicon glyphicon-filter pull-left"></span>&nbsp;' . $this->translate('Pertinence');

$sortDataForView['name asc'] = '<span class="glyphicon glyphicon-user pull-left"></span>&nbsp;' . $this->translate('Auteur A&rarr;Z');
$sortDataForView['name desc'] = '<span class="glyphicon glyphicon-user pull-left"></span>&nbsp;' . $this->translate('Auteur Z&rarr;A');

$sortDataForView['team asc'] = '<span class="glyphicon glyphicon-book pull-left"></span>&nbsp;' . $this->translate('Équipe de recherche A&rarr;Z');
$sortDataForView['team desc'] = '<span class="glyphicon glyphicon-book pull-left"></span>&nbsp;' . $this->translate('Équipe de recherche Z&rarr;A');

$sortDataForView['org asc'] = '<span class="glyphicon glyphicon-calendar pull-left"></span>&nbsp;' . $this->translate('Organisme  A&rarr;Z');
$sortDataForView['org desc'] = '<span class="glyphicon glyphicon-calendar pull-left"></span>&nbsp;' . $this->translate('Organisme  A&rarr;Z');
?>

<div class="btn-group btn-group-vertical">
    <?php
    $urlParams = $this->parsedSearchParams;

    foreach ($sortDataForView as $sortType => $sortLabel) {
        $isActive = '';
        if (isset($this->parsedSearchParams['sort']) and ($this->parsedSearchParams['sort'] == $sortType)) {
            $isActive = ' btn-success active disabled';
        } elseif (! isset($this->parsedSearchParams['sort']) and ($sortType == 'score desc')) {
            $isActive = ' btn-success active disabled';
        } else {
            $urlParams['sort'] = $sortType;
        }

        echo '<a  href="';
        echo $this->escape($this->url($urlParams, null, TRUE));
        echo '" class="btn btn-small' . $isActive . '">';
        echo $this->translate($sortLabel);
        echo '</a>';
    }

    ?>
            </div> <!-- Tri des résultats -->
			</li>




			<li class="clearfix nav-list">
				<!-- Nombre de résultats par page ============================== -->
				<p><?php //echo $this->translate('Nombre de résultats par page :'); ?></p>
				<div class="btn-group" data-toggle="buttons-radio">
<?php
$urlParams = $this->parsedSearchParams;

// foreach ($this->paginatorNumberOfResultsArray as $paginatorNumberOfResults) {
//     $isActive = '';

//     if (isset($this->parsedSearchParams['rpp']) and ($this->parsedSearchParams['rpp'] == $paginatorNumberOfResults)) {
//         // valeur en cours
//         $isActive = ' btn-success active disabled';
//     }

//     if (! isset($this->parsedSearchParams['rpp']) and $paginatorNumberOfResults == $this->paginatordefaultNumberOfResults) {
//         // valeur par défaut
//         $isActive = ' btn-success active disabled';
//     }

//     $urlParams['rpp'] = $paginatorNumberOfResults;

//     echo '<a href="' . $this->escape($this->url($urlParams, null, TRUE)) . '" class="btn btn-small' . $isActive . '">';
//     echo $this->escape($paginatorNumberOfResults);
//     echo '</a>';
// }
?>
</div> <!-- Nombre de résultats par page ============================== -->



			</li>


			<li class="form-actions modal-footer"><button type="button"
					class="btn"
					onclick="$('.dropdown').removeClass('open open-permanent')"><?php echo $this->translate('Annuler');?></button></li>
		</ul>

	</div>
</div>









