<?php
/**
 * @var Episciences_Volume $volume
 */
$volume = $this->volume;
$volumeUrl = sprintf('/volume/view/id/%s', $this->escape($volume->getVid()));
?>

<div class="media">
    <div id="metadatas" class="media-left">
        <a href="<?= $volumeUrl ?>">
            <?php if ($volume->getMetadatas()) : ?>
                <?php foreach ($volume->getMetadatas() as $metadata) : ?>

                    <?php if ($metadata->hasFile() && $metadata->isPicture()) : ?>

                        <?php
                        $mTitles = $metadata->getTitles();
                        $locale = Episciences_Tools::getLocale();
                        $alt = array_key_exists($locale, $mTitles) ? $mTitles[$locale] : $mTitles[array_key_first($mTitles)];
                        ?>

                        <img src="<?= $metadata->getFileUrl() ?>"
                             class="media-object img-thumbnail"
                             style="max-width: 10em"
                             alt="<?= $alt ?>" data-toggle="tooltip" title="<?= $alt ?>"/>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endif; ?>
        </a>
    </div>
    <div class="media-body">
        <h4 class="media-heading">
            <a href="<?= $volumeUrl ?>">
                <?= $this->translate($volume->getNameKey()) ?>
            </a>
            <?php
            $countOfPublishedArticles = count($volume->getIndexedPapers());
            if ($countOfPublishedArticles > 1) {
                echo '<span class="text-muted">(' . $countOfPublishedArticles . ' ' . $this->translate('articles') . ')</span>';
            } elseif ($countOfPublishedArticles === 1) {
                echo '<span class="text-muted">(' . $countOfPublishedArticles . ' ' . $this->translate('article') . ')</span>';
            }
            ?>
        </h4>
        <?php if ($volume->getSetting(Episciences_Volume::VOLUME_IS_PROCEEDING) === "1"): ?>
            <p> <?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_NAME) !== ''){ echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_NAME).";"; } ?>
                <?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_THEME) !== ''){ echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_THEME).";"; } ?>
                <?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_ACRONYM) !== ''){ echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_ACRONYM).";"; } ?>
                <?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_NUMBER) !== ''){ echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_NUMBER).";"; } ?>
                <?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_START_DATE) !== ''){ echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_START_DATE).";"; } ?>
                <?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_END_DATE) !== ''){ echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_END_DATE); } ?>
            </p>
        <?php endif; ?>
        <?php if (Zend_Registry::get('Zend_Translate')->isTranslated($volume->getDescriptionKey())) : ?>

            <p><?= $this->translate($volume->getDescriptionKey()) ?></p>

        <?php endif; ?>
        <?php if ($volume->getSetting(Episciences_Volume::VOLUME_IS_PROCEEDING) === "1" && substr(strrchr($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_DOI), "."), 1) !== ''): ?>
            <p><?= "DOI: <a href='https://doi.org/".$volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_DOI)."'target='_blank' rel='noopener'>".$volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_DOI)."</a>" ?></p>
        <?php endif; ?>
    </div>
</div>

<hr/>
