<?php
/**
 * @var Episciences_Volume $volume
 */
$volume = $this->volume;
$volumeUrl = $this->url(['controller' => 'volume', 'action' => 'view', 'id' => $this->escape($volume->getVid())]);
?>

<div class="media">
    <div id="metadatas" class="media-left">
        <a href="<?= $volumeUrl ?>">
            <?php if ($volume->getMetadatas()) : ?>
                <?php foreach ($volume->getMetadatas() as $metadata) : ?>

                    <?php if ($metadata->hasFile() && $metadata->isPicture()) : ?>

                        <?php
                        $mTitles = $metadata->getTitles();
                        $locale = Episciences_Tools::getLocale();
                        $alt = array_key_exists($locale, $mTitles) ? $mTitles[$locale] : $mTitles[array_key_first($mTitles)];
                        ?>

                        <img src="<?= $metadata->getFileUrl() ?>"
                             class="media-object img-thumbnail"
                             style="max-width: 10em"
                             alt="<?= $alt ?>" data-toggle="tooltip" title="<?= $alt ?>"/>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endif; ?>
        </a>
    </div>
    <div class="media-body">
        <h4 class="media-heading">
            <a href="<?= $volumeUrl ?>">
                <?= Episciences_Tools::convertMarkdownToHtml($volume->getNameKey()) ?>
            </a>
            <?php
            $countOfPublishedArticles = $volume->getNbOfPapersInVolume();
            if ($countOfPublishedArticles > 1) {
                echo '<span class="text-muted">(' . $countOfPublishedArticles . ' ' . $this->translate('articles') . ')</span>';
            } elseif ($countOfPublishedArticles === 1) {
                echo '<span class="text-muted">(' . $countOfPublishedArticles . ' ' . $this->translate('article') . ')</span>';
            }
            ?>
        </h4>
        <?php if ($volume->getSetting(Episciences_Volume::VOLUME_IS_PROCEEDING) === "1"): ?>
            <p><b style="font-size: 14px"><?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_NAME) !== ''){ echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_NAME);} ?></b></p>
            <p>
                <?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_ACRONYM) !== ''){ echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_ACRONYM).";"; } ?>
                <?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_NUMBER) !== ''){ echo "N°".$volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_NUMBER).";"; } ?>
            </p>
            <p>
                <?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_LOCATION) !== ''){echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_LOCATION).";";} ?>
                <?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_START_DATE) !== '' && $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_END_DATE) !== '') {
                    if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_START_DATE) === $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_END_DATE) ){
                        echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_START_DATE);
                    } else {
                        echo Zend_Registry::get('Zend_Translate')->translate('Du').' '.$volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_START_DATE).' '.Zend_Registry::get('Zend_Translate')->translate('Au').' '.$volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_END_DATE);
                    }
                }
                ?>
            </p>
            <p><?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_THEME) !== ''){ echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_THEME).";"; } ?></p>
        <?php endif; ?>
        <?php if ($volume->getDescriptionKey()) : ?>

            <p><?= Episciences_Tools::convertMarkdownToHtml($volume->getDescriptionKey()) ?></p>

        <?php endif; ?>
        <?php if ($volume->getSetting(Episciences_Volume::VOLUME_IS_PROCEEDING) === "1" && substr(strrchr($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_DOI), "."), 1) !== ''): ?>
            <p><?= "DOI: <a href='https://doi.org/".$volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_DOI)."'target='_blank' rel='noopener'>".$volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_DOI)."</a>" ?></p>
            <?php endif; ?>
    </div>
</div>

<hr/>
