<?php
/** @var Episciences_Paper $paper */
$paper = $this->paper;
$authors = $paper->getMetadata('authors');
$subjects = $paper->getMetadata('subjects');

$titles = $paper->getAllTitles();

$abstracts = $paper->getAllAbstracts();

$dateSubmitted = new DateTime($paper->getSubmission_date());
$dateUpdated = new DateTime($paper->getModification_date());
$dateIssued = new DateTime($paper->getPublication_date());
$publicationYear = new DateTime($paper->getPublication_date());

/** @var $journal Episciences_Review */
$journal = $this->journal;
$journalUrl = $journal->getUrl();
$journalDoi = $journal->getSetting(Episciences_Review::SETTING_JOURNAL_DOI);

$enrichmentAuthors = $paper->getAuthors();
$enrichmentLicence = $paper->getLicence();
$enrichmentFundings = $paper->getFundings();
$enrichmentLinkedData = $paper->getLinkedData();


$interWorkRelationship = [
    "isDerivedFrom","hasDerivation","isReviewOf",'hasReview',
    "isCommentOn","hasComment","isReplyTo","hasReply","basedOnData",
    "isDataBasisFor","hasRelatedMaterial","isRelatedMaterial",
    "isCompiledBy","compiles","isDocumentedBy","documents",
    "isSupplementTo","isSupplementedBy","isContinuedBy",
    "continues","isPartOf","hasPart","references",
    "isReferencedBy","isBasedOn","isBasisFor","requires","isRequiredBy","finances","isFinancedBy"
];


if (defined('RVISSN')) {
    $issn = $this->FormatIssn(RVISSN);
} else {
    $issn = '';
}

$timestamp = time();
?>
<doi_batch xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.crossref.org/schema/4.8.1 https://www.crossref.org/schemas/crossref4.8.1.xsd"
           xmlns="http://www.crossref.org/schema/4.8.1" xmlns:jats="http://www.ncbi.nlm.nih.gov/JATS1" xmlns:fr="http://www.crossref.org/fundref.xsd"
           version="4.8.1">
    <head>
        <doi_batch_id><?php echo DOMAIN . '_' . $paper->getPaperid() . '_' . $timestamp; ?></doi_batch_id>
        <timestamp><?php echo $timestamp; ?></timestamp>
        <depositor>
            <depositor_name><?php echo DOMAIN; ?></depositor_name>
            <email_address><?php echo DOI_EMAIL_CONTACT; ?></email_address>
        </depositor>
        <registrant><?php echo DOMAIN; ?></registrant>
    </head>
    <body>
    <journal>
        <journal_metadata language="en">
            <full_title><?php echo $this->escape($journal->getName()); ?></full_title>
            <?php if ($issn !== '') : ?>
                <issn media_type="electronic"><?php echo $this->escape($issn); ?></issn>
            <?php endif; ?>
            <?php if ($journalDoi) : ?>
                <doi_data>
                    <doi><?php echo $this->escape($journalDoi); ?></doi>
                    <resource><?php echo $this->escape($journalUrl); ?></resource>
                </doi_data>
            <?php endif; ?>
        </journal_metadata>
        <journal_issue>
            <publication_date media_type="online">
                <month><?php echo $publicationYear->format('m'); ?></month>
                <day><?php echo $publicationYear->format('d'); ?></day>
                <year><?php echo $publicationYear->format('Y'); ?></year>
            </publication_date>

            <?php if ($this->volume !== '') : ?>
                <journal_volume>
                    <volume><?php echo Ccsd_Tools_String::truncate($this->escape($this->volume), 29, '...'); ?></volume>
                </journal_volume>
            <?php endif; ?>
            <?php if ($this->section !== '') : ?>
                <issue><?php echo Ccsd_Tools_String::truncate($this->escape($this->section), 29, '...'); ?></issue>
            <?php endif; ?>
        </journal_issue>
        <journal_article publication_type="full_text">
            <titles>
                <?php $titleCount = 0; ?>
                <?php foreach ($titles as $lang => $title) : ?>
                    <?php
                    if ($titleCount == 0): ?>
                        <title><?php echo $this->escape($title) ?></title>
                        <?php $titleCount++; ?>
                    <?php elseif ($titleCount == 1) : ?>
                        <original_language_title
                                language="<?php echo $this->escape($lang) ?>"><?php echo $this->escape($title) ?></original_language_title>
                        <?php $titleCount++; ?>
                    <?php endif; ?>


                <?php endforeach; ?>
            </titles>


            <?php
            if (is_array($authors)) { ?>
                <contributors>
                    <?php
                    foreach ($authors as $order => $creatorName) {
                        $givenName= '';
                        $familyName= '';
                        if (str_contains($creatorName, ',')) {
                            [$familyName, $givenName] = explode(', ', $creatorName);
                        } else {
                            $familyName = $creatorName;
                        }

                    ?>
                    <?php if ($order === 0) : ?>
                    <person_name sequence="first" contributor_role="author">
                        <?php else: ?>
                        <person_name sequence="additional" contributor_role="author">
                            <?php endif; ?>
                            <?php if($givenName !=='') :?>
                            <given_name><?php echo $this->escape($givenName) ?></given_name>
                            <?php endif; ?>
                            <surname><?php echo $this->escape($familyName) ?></surname>
                            <?php if (!empty($enrichmentAuthors)): ?>
                                <?php if (!empty($enrichmentAuthors[$order]['affiliation'])): ?>
                                    <?php foreach ($enrichmentAuthors[$order]['affiliation'] as $affiliationAuthor) { ?>
                                        <affiliation><?= $this->escape($affiliationAuthor['name']) ?></affiliation>
                                    <?php } ?>
                                <?php endif; ?>
                                <?php if (isset($enrichmentAuthors[$order]['orcid'])): ?>
                                    <ORCID><?= "https://orcid.org/" . $this->escape($enrichmentAuthors[$order]['orcid']) ?></ORCID>
                                <?php endif; ?>
                            <?php endif; ?>
                        </person_name>
                        <?php
                        }
                        ?>
                </contributors>
                <?php
            }
            ?>
            <?php if ($abstracts): ?>

                <jats:abstract>
                    <?php
                    foreach ($abstracts as $lang => $abstract) {

                        $abstract = trim($abstract);

                        if (('International audience' === $abstract) || (preg_match("/^Comment:/", $abstract))) {
                            continue;
                        }

                        if ($lang && Zend_Locale::isLocale($lang)) {
                            $langId = ' xml:lang="' . $lang . '"';
                        } else {
                            $langId = '';
                        }

                        echo '<jats:p' . $langId . '>';
                        echo $this->escape($abstract);
                        echo '</jats:p>';
                    }
                    ?>
                </jats:abstract>
            <?php endif; ?>

            <publication_date media_type="online">
                <month><?php echo $publicationYear->format('m'); ?></month>
                <day><?php echo $publicationYear->format('d'); ?></day>
                <year><?php echo $publicationYear->format('Y'); ?></year>
            </publication_date>

            <publisher_item>
                <item_number
                        item_number_type="article_number"><?php echo $paper->getPaperid(); ?></item_number>
            </publisher_item>
            <?php if (!empty($enrichmentFundings)): ?>
                <program name="fundref" xmlns="http://www.crossref.org/fundref.xsd">
                    <?php foreach ($enrichmentFundings as $fundingInfo) { ?>
                        <?php if ($fundingInfo['funderName'] !== "unidentified" || $fundingInfo['code'] !== "unidentified" || $fundingInfo['projectTitle'] !== "unidentified") : ?>
                                <assertion name="fundgroup">
                                    <?php if ($fundingInfo['funderName'] !== "unidentified") : ?>
                                        <assertion name="funder_name"><?= $this->escape($fundingInfo['funderName']) ?></assertion>
                                    <?php endif; ?>
                                    <?php if ($fundingInfo['code'] !== "unidentified") : ?>
                                        <assertion name="award_number"><?= $this->escape($fundingInfo['code']) ?></assertion>
                                    <?php endif; ?>
                                </assertion>
                        <?php endif; ?>
                    <?php } ?>
                </program>
            <?php endif; ?>
            <?php if ($enrichmentLicence !== ""): ?>
                <program xmlns="http://www.crossref.org/AccessIndicators.xsd">
                    <license_ref start_date="<?= date("Y-m-d", strtotime($paper->getPublication_date()))?>"><?= $this->escape($enrichmentLicence) ?></license_ref>
                </program>
            <?php endif; ?>
            <program xmlns="http://www.crossref.org/relations.xsd">

                <?php if ($paper->getRepoid() === Episciences_Repositories::getRepoIdByLabel('arXiv')) : ?>
                    <related_item>
                        <intra_work_relation identifier-type="arxiv" relationship-type="isSameAs">arXiv:<?php echo $this->escape($paper->getIdentifier()); ?></intra_work_relation>
                    </related_item>
                    <related_item>
                        <intra_work_relation identifier-type="doi" relationship-type="isSameAs"><?= Episciences_Repositories::getRepoDoiPrefix($paper->getRepoid()) ?>/arXiv.<?php echo $this->escape($paper->getIdentifier()); ?></intra_work_relation>
                    </related_item>
                <?php elseif ($paper->getRepoid() === Episciences_Repositories::getRepoIdByLabel('Zenodo')) : ?>
                    <related_item>
                        <intra_work_relation identifier-type="doi" relationship-type="isSameAs"><?= Episciences_Repositories::getRepoDoiPrefix($paper->getRepoid()) ?>/zenodo.<?php echo $this->escape($paper->getIdentifier()); ?></intra_work_relation>
                    </related_item>
                <?php elseif ($paper->getRepoid() === Episciences_Repositories::getRepoIdByLabel('Hal')) : ?>
                    <related_item>
                        <intra_work_relation identifier-type="uri" relationship-type="isSameAs"><?php echo $this->escape($paper->getDocUrl()); ?></intra_work_relation>
                    </related_item>
                <?php endif; ?>

                <?php if (!empty($this->previousVersionsUrl)) :?>
                    <?php foreach ($this->previousVersionsUrl as $preprintUrl) { ?>
                        <related_item>
                            <intra_work_relation identifier-type="uri" relationship-type="hasPreprint"><?php echo $this->escape($preprintUrl); ?></intra_work_relation>
                        </related_item>
                    <?php } ?>
                <?php endif; ?>

                <?php if (!empty($enrichmentLinkedData)) : ?>
                    <?php foreach ($enrichmentLinkedData as $linkedData) { ?>
                        <?php if (in_array(lcfirst($linkedData['relationship']), $interWorkRelationship, true)) :?>
                            <related_item>
                                <inter_work_relation identifier-type="<?= $this->escape(strtolower($linkedData['link'])) ?>" relationship-type="<?= $this->escape(lcfirst($linkedData['relationship'])) ?>"><?php echo $this->escape($linkedData['value']); ?></inter_work_relation>
                            </related_item>
                        <?php endif; ?>
                    <?php } ?>
                <?php endif; ?>

            </program>

            <doi_data>
                <doi><?php echo htmlentities($this->doi, ENT_XML1); ?></doi>
                <resource><?php echo $journalUrl . '/' . $paper->getPaperid(); ?></resource>
                <collection property="crawler-based">
                    <item crawler="iParadigms">
                        <resource><?php echo $journalUrl . '/' . $paper->getDocid() . '/pdf'; ?></resource>
                    </item>
                </collection>
            </doi_data>

        </journal_article>
    </journal>
    </body>
</doi_batch>
