<records>
    <?php foreach ($this->listOfPaper as $value): ?>
        <?php
        $paperLanguage = $value->getMetadata('language');
        if ($paperLanguage == '') {
            $paperLanguage = 'eng';
            // TODO temporary fix see https://gitlab.ccsd.cnrs.fr/ccsd/episciences/issues/215
        }

        $section = "";
        $doi = $value->getDoi();

        if ($value->getSid()) {
            /* @var $oSection Episciences_Section */
            $oSection = Episciences_SectionsManager::find($value->getSid());
            if ($oSection) {
                $section = $oSection->getName('en', true);
            }
        }
        ?>
        <?php echo $this->partial('partials/doajpaper.phtml',[
            'paper'=> $value,
            'journal'=> $this->journal,
            'doi'=>$doi,
            'volume'=> $this->volume,
            'section'=>$section,
            'paperLanguage'=>$paperLanguage
            ]
        ); ?>
    <?php endforeach; ?>
</records>