<?php
Zend_Controller_Front::getInstance()->getRequest()->setActionName($this->page);
if (isset($this->controller) && $this->controller != '') {
    Zend_Controller_Front::getInstance()->getRequest()->setControllerName($this->controller);
}

$locale = Zend_Registry::get("Zend_Translate")->getLocale();

if ($this->mode === 'edit') {
    //Edition de la page?>
    <style>
        .mce-fullscreen {
            z-index: 2000;
        }
    </style>

    <?php
    $this->jQuery()->addJavascriptFile(VENDOR_TINYMCE_JQUERY);
    $this->jQuery()->addJavascriptFile(VENDOR_TINYMCE);
    $this->jQuery()->addJavascriptFile(TINYMCE_DIR . "tinymce_patch.js");

    echo $this->form; ?>
    <script>
        __initMCE('textarea:last', undefined, {
            theme: "modern",
            plugins: "textcolor link image code fullscreen table visualblocks paste",
            toolbar1: "bold italic underline strikethrough | forecolor backcolor | alignleft aligncenter alignright alignjustify | bullist numlist | link image | table | styleselect | removeformat visualblocks | code",
            menubar: false,
            <?php if ($locale === 'fr') : ?>
            language: 'fr_FR'
            <?php endif; ?>
        });
    </script>

    <?php
} else {
        echo $this->content;

        if ($this->canEdit) {
            Zend_Controller_Front::getInstance()->getRequest()->setActionName($this->page); ?>
        <div class="form-actions text-center">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <form action="#" method="post" style="margin:0;">
                <input type="hidden" name="method" value="edit"/>
                <button class="btn btn-default" type="submit"><i
                            class="glyphicon glyphicon-pencil"></i>&nbsp;<?php echo $this->translate('Modifier le contenu de la page') ?>
                </button>
            </form>
        </div>
        <?php
        }
    }
