version: 2
updates:
  # JavaScript/Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "staging"
    open-pull-requests-limit: 10
    reviewers:
      - "maintainer"
    assignees:
      - "maintainer"

  # PHP Composer dependencies
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "staging" 
    open-pull-requests-limit: 10
    reviewers:
      - "maintainer"
    assignees:
      - "maintainer"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "staging"
    open-pull-requests-limit: 3