<ul>
    <li>
        <span><i class="fas fa-rss"></i></span>
        <a target="_blank"
           href="<?= $this->url(['controller' => 'rss', 'action' => 'papers'])?>"><?php echo $this->translate('Retrouvez les derniers articles publiés.'); ?></a>
    </li>


    <li>
        <span><i class="fas fa-rss"></i></span>
        <a target="_blank" href="<?= $this->url(['controller' => 'rss', 'action' => 'news']) ?>"><?php echo $this->translate('Retrouvez les dernières actualités.'); ?></a>
    </li>

</ul>