<ul>
    <li>
        <span><i class="fas fa-rss"></i></span>
        <a target="_blank"
           href="/rss/papers"><?php echo $this->translate('Retrouvez les derniers articles publiés.'); ?></a>
    </li>


    <li>
        <span><i class="fas fa-rss"></i></span>
        <a target="_blank" href="/rss/news"><?php echo $this->translate('Retrouvez les dernières actualités.'); ?></a>
    </li>

</ul>