<?php
/**
 * Generates the two configuration files the PHPUnit bootstrap needs, so that the test
 * suite can actually run on CI.
 *
 * Both files are gitignored (see .gitignore) because they hold per-environment values:
 *   - tests/config/env-test.php : defines RVCODE, read by defineJournalConstants()
 *   - config/pwd.json           : defines every DB/service constant, read by public/bdd_const.php
 *
 * Without them the bootstrap aborts. That used to be silent: `exit($string)` and `die($string)`
 * both return exit code 0, so PHPUnit never ran a single test and CI still reported success.
 * tests/bootstrap.php now fails with exit code 1 instead; this script is what keeps CI green
 * for the right reason.
 *
 * Usage: php .github/scripts/setup-test-config.php
 *
 * Existing files are never overwritten, so running this by mistake on a developer machine
 * cannot destroy a working local configuration. Pass --force to regenerate them anyway.
 *
 * Environment variables (all optional, defaults match the docker-compose dev stack):
 *   TEST_RVCODE, DB_HOST, DB_PORT, DB_USER, DB_PASSWORD, DB_NAME, DB_AUTH_NAME
 */

$root = dirname(__DIR__, 2);
$force = in_array('--force', $argv, true);

$rvCode = getenv('TEST_RVCODE') ?: 'dev';
$dbHost = getenv('DB_HOST') ?: '127.0.0.1';
$dbPort = (int)(getenv('DB_PORT') ?: 3306);
$dbUser = getenv('DB_USER') ?: 'root';
$dbPassword = getenv('DB_PASSWORD') ?: 'root';
$dbName = getenv('DB_NAME') ?: 'test_episciences';
$dbAuthName = getenv('DB_AUTH_NAME') ?: 'test_episciences_auth';

// --- tests/config/env-test.php ------------------------------------------------------------
// RVCODE has to resolve to an existing data/<rvcode> directory: defineJournalConstants()
// builds REVIEW_PATH with realpath(), which returns false for a missing directory and would
// silently collapse REVIEW_PATH to '/'.
$dataDir = $root . '/data/' . $rvCode;

if (!is_dir($dataDir) && !mkdir($dataDir, 0777, true) && !is_dir($dataDir)) {
    fwrite(STDERR, sprintf('Unable to create the journal data directory: %s%s', $dataDir, PHP_EOL));
    exit(1);
}

$envTest = <<<PHP
<?php
// Generated by .github/scripts/setup-test-config.php -- do not edit by hand.
putenv("RVCODE=$rvCode");

PHP;

writeFileOrFail($root . '/tests/config/env-test.php', $envTest, $force);

// --- config/pwd.json ----------------------------------------------------------------------
// Derived from the committed template so that a new key added to config/dist-pwd.json is
// automatically picked up by CI instead of silently missing from the test environment.
$templatePath = $root . '/config/dist-pwd.json';
$template = file_get_contents($templatePath);

if ($template === false) {
    fwrite(STDERR, sprintf('Unable to read the configuration template: %s%s', $templatePath, PHP_EOL));
    exit(1);
}

try {
    $config = json_decode($template, true, 512, JSON_THROW_ON_ERROR);
} catch (JsonException $e) {
    fwrite(STDERR, sprintf('%s is not valid JSON: %s%s', $templatePath, $e->getMessage(), PHP_EOL));
    exit(1);
}

// EPI is the main database, CAS the authentication one, SOLR reuses the main one: the test
// suite never queries Solr, but the constants must exist for the Zend bootstrap to succeed.
$databases = [
    'EPI' => $dbName,
    'CAS' => $dbAuthName,
    'SOLR' => $dbName,
];

foreach ($databases as $section => $name) {
    $config[$section]['HOST'] = $dbHost;
    $config[$section]['PORT'] = $dbPort;
    $config[$section]['NAME'] = $name;
    $config[$section]['USER'] = $dbUser;
    $config[$section]['PWD'] = $dbPassword;
}

writeFileOrFail(
    $root . '/config/pwd.json',
    json_encode($config, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . PHP_EOL,
    $force
);

printf('Test configuration ready (RVCODE=%s, database=%s@%s:%d).%s', $rvCode, $dbName, $dbHost, $dbPort, PHP_EOL);

function writeFileOrFail(string $path, string $contents, bool $force): void
{
    if (!$force && file_exists($path)) {
        printf('Kept existing %s (use --force to overwrite).%s', $path, PHP_EOL);
        return;
    }

    if (file_put_contents($path, $contents) === false) {
        fwrite(STDERR, sprintf('Unable to write %s%s', $path, PHP_EOL));
        exit(1);
    }
}
