<?php
/**
 * Generates the configuration the PHPUnit bootstrap needs, so that the test suite can actually
 * run on CI.
 *
 * Two files are required and both are gitignored, because they hold per-environment values:
 *   - tests/config/env-test.php : defines RVCODE, read by defineJournalConstants()
 *   - a pwd.json                : defines every database and service constant, read by
 *                                 public/bdd_const.php
 *
 * The generated pwd.json is written to tests/config/, never to config/. public/bdd_const.php
 * resolves its location through the PWD_PATH constant, and best_define() honours a PWD_PATH
 * environment variable, so exporting PWD_PATH=<repo>/tests/config is enough to isolate the test
 * configuration from a developer's working one. The workflows set that variable; see
 * .github/workflows/php-tests.yml.
 *
 * Without these files the bootstrap aborts. That used to be silent: `exit($string)` and
 * `die($string)` both return exit code 0, so PHPUnit ran zero tests and CI still reported
 * success. tests/bootstrap.php now fails with exit code 1 instead; this script is what keeps CI
 * green for the right reason.
 *
 * Usage: php .github/scripts/setup-test-config.php
 *
 * Existing files are never overwritten, so running this by mistake cannot destroy a working local
 * configuration. Pass --force to regenerate them anyway.
 *
 * Environment variables (all optional, defaults match the docker-compose dev stack):
 *   TEST_RVCODE, DB_HOST, DB_PORT, DB_USER, DB_PASSWORD, DB_NAME, DB_AUTH_NAME
 */

$root = dirname(__DIR__, 2);
$force = in_array('--force', $argv, true);

$rvCode = getenv('TEST_RVCODE') ?: 'dev';
$dbHost = getenv('DB_HOST') ?: '127.0.0.1';
$dbPort = (int)(getenv('DB_PORT') ?: 3306);
$dbUser = getenv('DB_USER') ?: 'root';
$dbPassword = getenv('DB_PASSWORD') ?: 'root';
$dbName = getenv('DB_NAME') ?: 'test_episciences';
$dbAuthName = getenv('DB_AUTH_NAME') ?: 'test_episciences_auth';

// --- writable directories -------------------------------------------------------------------
// The dist template points its log and mail paths at placeholders such as /logs/file/path.
// Monolog builds its directory on first write and throws when it cannot, which turns any test
// exercising a logging code path into an error. Everything is redirected under tmp/ instead.
$logPath = $root . '/tmp/test-logs/';
$mailPath = $root . '/tmp/test-mail/';

makeDirectoryOrFail($logPath);
makeDirectoryOrFail($mailPath);

// --- data/ ------------------------------------------------------------------------------------
// data/ is gitignored and provisioned from the src/data/default template; this mirrors what the
// `init-data-dir` make target does for a development environment.
//
// Two things depend on it. RVCODE has to resolve to an existing data/<rvcode> directory, because
// defineJournalConstants() builds REVIEW_PATH with realpath(), which returns false for a missing
// directory and would silently collapse REVIEW_PATH to '/'. And Bootstrap::_initNavigation()
// falls back to data/default/config/navigation.json when the journal has no navigation of its
// own, then fails hard if that file is missing too.
copyDirectory($root . '/src/data/default', $root . '/data/default');

$dataDir = $root . '/data/' . $rvCode;

foreach (['config', 'files', 'languages', 'layout', 'public', 'tmp'] as $subDirectory) {
    makeDirectoryOrFail($dataDir . '/' . $subDirectory);
}

$navigation = $dataDir . '/config/navigation.json';

if (!file_exists($navigation) && !copy($root . '/data/default/config/navigation.json', $navigation)) {
    fwrite(STDERR, sprintf('Unable to create %s%s', $navigation, PHP_EOL));
    exit(1);
}

// --- tests/config/env-test.php ----------------------------------------------------------------
$envTest = <<<PHP
<?php
// Generated by .github/scripts/setup-test-config.php -- do not edit by hand.
putenv("RVCODE=$rvCode");

PHP;

writeFileOrFail($root . '/tests/config/env-test.php', $envTest, $force);

// --- tests/config/pwd.json --------------------------------------------------------------------
// Derived from the committed template so that a new key added to config/dist-pwd.json is
// automatically picked up by CI instead of silently missing from the test environment.
$templatePath = $root . '/config/dist-pwd.json';
$template = file_get_contents($templatePath);

if ($template === false) {
    fwrite(STDERR, sprintf('Unable to read the configuration template: %s%s', $templatePath, PHP_EOL));
    exit(1);
}

try {
    $config = json_decode($template, true, 512, JSON_THROW_ON_ERROR);
} catch (JsonException $e) {
    fwrite(STDERR, sprintf('%s is not valid JSON: %s%s', $templatePath, $e->getMessage(), PHP_EOL));
    exit(1);
}

// EPI is the main database and CAS the authentication one; they hold distinct schemas and must
// not be pointed at the same place. SOLR reuses the main one: the suite never queries Solr, but
// the constants have to exist for the Zend bootstrap to succeed.
$databases = [
    'EPI' => $dbName,
    'SOLR' => $dbName,
    'CAS' => $dbAuthName,
];

foreach ($databases as $section => $name) {
    $config[$section]['HOST'] = $dbHost;
    $config[$section]['PORT'] = $dbPort;
    $config[$section]['NAME'] = $name;
    $config[$section]['USER'] = $dbUser;
    $config[$section]['PWD'] = $dbPassword;
}

$config['EPISCIENCES']['LOG_PATH'] = $logPath;
$config['EPISCIENCES']['EXCEPTIONS_LOG_PATH'] = $logPath;
$config['EPISCIENCES']['SOLR_LOG_PATH'] = $logPath;
$config['EPISCIENCES']['MAIL_PATH'] = $mailPath;

// The template value contains spaces, which Episciences_Api_OpenAlexApiClient percent-encodes
// into the query string. OpenAlexApiClientTest asserts on the raw value, so a space-free key is
// needed for the assertion to mean anything.
$config['OPENALEX']['APIKEY'] = 'ci-openalex-api-key';

writeFileOrFail(
    $root . '/tests/config/pwd.json',
    json_encode($config, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . PHP_EOL,
    $force
);

printf(
    'Test configuration ready (RVCODE=%s, databases=%s + %s on %s:%d).%s',
    $rvCode,
    $dbName,
    $dbAuthName,
    $dbHost,
    $dbPort,
    PHP_EOL
);
printf('Remember to export PWD_PATH=%s/tests/config before running PHPUnit.%s', $root, PHP_EOL);

function makeDirectoryOrFail(string $path): void
{
    if (!is_dir($path) && !mkdir($path, 0777, true) && !is_dir($path)) {
        fwrite(STDERR, sprintf('Unable to create %s%s', $path, PHP_EOL));
        exit(1);
    }
}

/**
 * Recursively copies a template directory, never overwriting an existing file.
 */
function copyDirectory(string $source, string $destination): void
{
    makeDirectoryOrFail($destination);

    foreach (scandir($source) ?: [] as $entry) {
        if ($entry === '.' || $entry === '..') {
            continue;
        }

        $from = $source . '/' . $entry;
        $to = $destination . '/' . $entry;

        if (is_dir($from)) {
            copyDirectory($from, $to);
            continue;
        }

        if (!file_exists($to) && !copy($from, $to)) {
            fwrite(STDERR, sprintf('Unable to copy %s to %s%s', $from, $to, PHP_EOL));
            exit(1);
        }
    }
}

function writeFileOrFail(string $path, string $contents, bool $force): void
{
    if (!$force && file_exists($path)) {
        printf('Kept existing %s (use --force to overwrite).%s', $path, PHP_EOL);
        return;
    }

    if (file_put_contents($path, $contents) === false) {
        fwrite(STDERR, sprintf('Unable to write %s%s', $path, PHP_EOL));
        exit(1);
    }
}
