<?php
$request = Zend_Controller_Front::getInstance()->getRequest();
$params = $request->getParams();
?>

<?php if (
        isset($params['userid']) &&
        Episciences_Auth::isSecretary() &&
        Episciences_Auth::getUid() !== (int)$params['userid']) : ?>
    <div class="alert alert-info" role="alert"><i class="fas fa-info-circle"></i>&nbsp;
        <?= $this->translate("Modification de l'adresse e-mail d'un autre compte utilisateur") ?>
    </div>

<?php endif; ?>


<?php if ($this->isNotAllowedToChangeEmail): ?>

    <div class="alert alert-warning text-justify" role="alert"><i class="fas fa-info-circle"></i>&nbsp;
        <?= $this->translate($this->infoMsg) ?>
        <br>
        <?= $this->userloginsStr ?>
    </div>


<?php endif; ?>


<?php
if ($this->form) {
    $this->form->setAction($this->url());
    echo $this->form;
}
