<?php
/**
 * Formulaire de modification de mot de passe
 */

$this->layout()->pageTitle = $this->translate("Changer le mot de passe de votre compte");

$this->layout()->pageDescription = $this->translate('Changement de mot de passe');

if ($this->resultMessage) {
    echo $this->resultMessage;
}

?>
<div class="alert alert-info" role="alert"><i class="fas fa-info-circle"></i>&nbsp;
    <?= $this->translate('Pour des raisons de sécurité, le changement de mot de passe invalide vos sessions et vous devrez vous connecter à nouveau.'); ?>
</div>


<?php if (APPLICATION_ENV == 'demo') : ?>
    <p><?php echo $this->translate("Dans l'environnement de démo, vous ne pouvez pas modifier le mot de passe."); ?></p>
<?php else : ?>
    <?php
    if ($this->form) {
        echo $this->form;
    }
    ?>

<?php endif; ?> 