<?php
$this->jQuery()->addJavascriptFile('/js/user/affiliations.js');
$this->layout()->pageTitle = $this->translate("Créer un compte");
$this->layout()->pageDescription = $this->translate("Création d'un compte sur le Service Central d'Authentification du CCSD");
?>
<?php if (Ccsd_User_Models_User::ACCOUNT_CREATE_SUCCESS == $this->resultMessage) : ?>
    <div class="alert alert-info alert-fixed">
        <p><?php echo $this->translate("Le compte %s a bien été créé.", $this->fullUserName); ?></p><br/>
        <p><?php echo $this->translate('Vous devez valider votre compte avant de pouvoir vous authentifier.'); ?></p>
        <p><?php echo $this->translate("Nous venons de vous envoyer un e-mail à l'adresse : "); ?><a
                    href="mailto:<?php echo $this->escape($this->userEmail); ?>"
            ><?php echo $this->escape($this->userEmail); ?></a>
        </p>
        <p>
            <strong><?php echo $this->translate('Cet e-mail contient un lien de validation sur lequel vous devez cliquer pour valider votre compte.'); ?></strong>
        </p>
    </div>

    <p>
        <a href="<?php echo $this->url([], null, true); ?>">
            <button class="btn btn-default">
                <span class="glyphicon glyphicon-home" style="margin-right: 5px"></span>
                <?php echo $this->translate("Retourner à l'accueil"); ?>
            </button>
        </a>
    </p>
<?php endif; ?>

<?php
if ($this->form) {
    if (CAPTCHA_BRAND === 'ALTCHA') {
        echo '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/altcha@3.1.0/dist/external/altcha.min.css"'
            . ' integrity="sha256-/mz0TW+CcPNef6nkwV2G6367GtjTA34GR2bx5oBNMk0="'
            . ' crossorigin="anonymous">';
        echo '<script src="https://cdn.jsdelivr.net/npm/altcha@3.1.0/dist/main/altcha.min.js"'
            . ' integrity="sha256-2MYsWfWlelQoomIYmzpiE5cZ9PwpHjXlEPmdheE5C0c="'
            . ' crossorigin="anonymous"></script>';
        echo '<script>$altcha.algorithms.set("ARGON2ID",()=>new Worker("/js/vendor/altcha/argon2id.js"));</script>';
    }

    echo $this->form;
}
