<?php $this->jQuery()->addJavascriptFile('/js/user/user.js'); ?>
    <div id="message"></div>
<?php
foreach ($this->element->getElements() as $element) {
    if ($element->getDecorator('HtmlTag')) {
        $element->getDecorator('HtmlTag')->setOption("class", "col-md-9 form-group");
    }

    echo $element;
    if ($element->getName() == 'LANGUEID') {
        echo '<hr style="padding:0.5em;">';
    }
}
