<h1><?php echo $this->translate('Déconnexion du serveur d\'authentification du') ?> <abbr
            title="Centre pour la Communication Scientifique Directe">CCSD</abbr></h1>

<?php if ($this->message == Ccsd_User_Models_User::LOGOUT_SUCCESS) : ?>
    <div class="alert alert-success" role="alert"><i class="fas fa-check"></i>
        &nbsp;<?php echo $this->translate('Déconnexion réussie') ?></div>

    <?php
    if ($this->reason) {
        echo '<div class="alert alert-info" role="alert"><i class="fas fa-info-circle"></i>&nbsp;';
        echo $this->translate($this->reason);
        echo '</div>';
    }
    ?>
    <p>
        <a href="/user/login" class="btn btn-primary"><span class="glyphicon glyphicon-user glyphicon-white" aria-hidden="true"></span>
            &nbsp;
            <?php echo $this->translate('Nouvelle connexion') ?></a>
    </p>


<?php else : ?>
    <div class="alert alert-danger" role="alert"><?php echo $this->translate('Échec de la déconnexion') ?></div>
    <p><a href="/" class="btn btn-danger"><?php echo $this->translate('Retourner à l\'accueil') ?></a></p>
<?php endif; ?>





