<?php if (Ccsd_User_Models_User::ACCOUNT_INVALID_USERNAME == $this->resultMessage) : ?>
<div class="alert alert-error">
	<?php echo $this->translate('Aucun compte valide n\'a été trouvé pour ce nom d\'utilisateur')?>.
</div>
<?php endif; ?>

<?php if (Ccsd_User_Models_User::ACCOUNT_VALID_USERNAME == $this->resultMessage) : ?>
<div class="alert alert-success">
	<?php echo $this->translate("Vous allez recevoir la procédure de changement de mot de passe à l'adresse e-mail associée à ce compte")?>.
</div>
<?php endif; ?>

<?php 
if ($this->form) {
    echo $this->form;
}
