<?php if (Ccsd_User_Models_User::ACCOUNT_INVALID_USERNAME == $this->resultMessage) : ?>
<div class="alert alert-error">
	<?php echo $this->translate('Aucun compte valide n\'a été trouvé pour ce nom d\'utilisateur')?>.
</div>
<?php endif; ?>

<?php if (Ccsd_User_Models_User::ACCOUNT_VALID_USERNAME == $this->resultMessage) : ?>
<div class="alert alert-success">
	<?php echo $this->translate("Vous allez recevoir la procédure de changement de mot de passe à l'adresse e-mail associée à ce compte")?>.
</div>
<?php endif; ?>

<?php
if ($this->form) {
    if (CAPTCHA_BRAND === 'ALTCHA') {
        echo '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/altcha@3.1.0/dist/external/altcha.min.css"'
            . ' integrity="sha256-/mz0TW+CcPNef6nkwV2G6367GtjTA34GR2bx5oBNMk0="'
            . ' crossorigin="anonymous">';
        echo '<script src="https://cdn.jsdelivr.net/npm/altcha@3.1.0/dist/main/altcha.min.js"'
            . ' integrity="sha256-2MYsWfWlelQoomIYmzpiE5cZ9PwpHjXlEPmdheE5C0c="'
            . ' crossorigin="anonymous"></script>';
        echo '<script>$altcha.algorithms.set("ARGON2ID",()=>new Worker("/js/vendor/altcha/argon2id.js"));</script>';
    }
    echo $this->form;
}
