<h2><?php echo $this->translate('Changement de votre mot de passe')?></h2>

<?php if ($this->resultMessage == Ccsd_User_Models_User::ACCOUNT_RESET_PASSWORD_FAILURE) : ?>
<div class="alert alert-error">
	<p><?php echo $this->translate('Le jeton que vous avez fourni n\'existe pas ou n\'est plus valide')?>.</p>
	<p><?php echo $this->translate('Vous pouvez en demander un nouveau grâce au lien ci-dessous')?></p>
</div>
<?php $url = $this->url(array('controller' => 'user', 'action' => 'accountlostpassword'), null, true); ?>
<a class="btn" href="<?php echo $url; ?>"><?php echo $this->translate('Réinitialiser mon mot de passe')?></a>
<?php endif; ?>

<?php if ($this->resultMessage == Ccsd_User_Models_User::ACCOUNT_RESET_PASSWORD_SUCCESS) : ?>
<div class="alert alert-success"><?php echo $this->translate('Votre mot de passe a bien été changé')?></div>
<?php endif; ?>

<?php 
if ($this->form) {
    $this->form->setAction($this->url());
    echo $this->form;
}
