<?php
$this->layout()->pageTitle = $this->translate("Changer le mot de passe API associé à votre compte");
$this->layout()->pageDescription = $this->translate('Changement de mot de passe API');
?>

<?= $this->resultMessage ?: '' ?>

<div class="alert alert-info" role="alert"><i class="fas fa-info-circle"></i>
    <?= $this->translate("Ce mot de passe est réservé à l'usage exclusif de l'") ?>
    <a target='_blank' href='<?= EPISCIENCES_API_URL ?? '#' ?>'><?= $this->translate('API Episciences')?></a>
</div>

<?= $this->form ?: '' ?>
