<?php if (!empty($this->affiliations)) : ?>
    <?php foreach ($this->affiliations as $index => $affiliation): ?>
        <small>
            <?php if (isset($affiliation['label']) && !empty($affiliation['label'])) : ?>

                <?php if (isset($affiliation['rorId']) && !empty($affiliation['rorId'])) : ?>
                    <a href="<?= $this->escape($affiliation['rorId']) ?>" target="_blank">
                        <img src="/img/ROR-iD.png" alt="ROR-iD" height="<?= $this->height ?? 24 ?>px"/>
                    </a>
                <?php else: ?>
                    <img src="/img/NO-ROR-iD.png" alt="NO-ROR-iD" height="<?= $this->height ?? 24 ?>px"/>
                <?php endif; ?>
                <?= $this->escape($affiliation['label']) ?>
            <?php endif; ?>
        </small>
        <br>

    <?php endforeach; ?>
<?php endif; ?>

