<?php if (count($this->pages)) { ?>
    <ol class="breadcrumb">
        <?php foreach($this->pages as $i => $page) {
            $active = $page->isActive();
            ?>
            <li class="<?php echo $active ? 'active' : ''?>">
                <?php if ($active) { ?>
                    <?php echo $this->translate($page->getLabel())?>
                <?php } else { ?>
                    <a href="<?php echo '/' . $page->getController() . '/' . $page->getAction();?>"><?php echo $this->translate($page->getLabel())?></a>
                <?php } ?>
            </li>
        <?php
        }?>
    </ol>
<?php } ?>