<?php if (count($this->pages)) { ?>
    <ol class="breadcrumb">
        <?php foreach ($this->pages as $i => $page) {
            $active = $page->isActive();
            ?>
            <li class="<?= $active ? 'active' : '' ?>">
                <?php if ($active) { ?>
                    <?= $this->translate($page->getLabel()) ?>
                <?php } else { ?>
                    <a href="<?= $this->url(['controller' => $page->getController(), 'action' => $page->getAction()]) ?>"><?= $this->translate($page->getLabel()) ?></a>
                <?php } ?>
            </li>
            <?php
        } ?>
    </ol>
<?php } ?>