<?php
$log = $this->log;
$conflictDetail = $log['detail']['conflict'];
$isReverted = isset($this->isReverted) && $this->isReverted;
?>
<table class="log-details">
    <tr>
        <td class="td-label"><?= !$isReverted ? $this->translate("Rapporté le") : $this->translate("Annulé le") ?></td>
        <td class="small"><?= $this->Date($log['date'], null, Zend_Date::DATE_LONG . ' - ' . Zend_Date::TIME_SHORT) ?></td>
    </tr>
    <tr>
        <td class="td-label"><?= ucfirst($this->translate('par')) ?></td>
        <td class="small">
            <?= $this->user['fullname'] ?>
        </td>
    </tr>

    <tr>
        <td class="td-label"><?= $this->translate('Id permanent') ?></td>
        <td class="small">
            <?= $conflictDetail['paperId'] ?>
        </td>
    </tr>

    <?php if(isset($log['docid'])) : ?>
        <tr>
            <td class="td-label"><?= $this->translate('Id document') ?></td>
            <td class="small">
                <?= $log['docid'] ?>
            </td>
        </tr>
    <?php endif;?>

    <?php if (!empty($conflictDetail['message'])) : ?>
        <tr>
            <td class="td-label"><?= $this->translate('Détails') ?></td>
            <td class="small"><?= Episciences_Tools::formatText(htmlspecialchars_decode($conflictDetail['message'])) ?></td>
        </tr>
    <?php endif; ?>
</table>









