<style>
    .editors-list {
        max-height: 150px;
        overflow: auto;
        margin-bottom: 10px;
    }
</style>
<?php if ($this->suggestedEditors) : ?>
    <p><i>
            <?php echo $this->translate(array("L'auteur a suggéré un rédacteur", "L'auteur a suggéré des rédacteurs", count($this->suggestedEditors))); ?>
            :
            <?php

            $lastItem = end($this->suggestedEditors);
            foreach ($this->suggestedEditors as $editorId) {

                if (is_array($this->editors) && array_key_exists($editorId, $this->editors)) {
                    echo $this->editors[$editorId]->getFullname();
                }

                if (current($this->suggestedEditors) != $lastItem) {
                    echo ', ';
                }
            }
            ?>
            .</i></p>
<?php endif; ?>

<?php if ($this->editorsForm) : ?>
    <?php echo $this->editorsForm; ?>
<?php else : ?>
    <?php echo $this->translate('Aucun rédacteur enregistré') . '.' ?>
<?php endif; ?>