<?php
$this->layout()->pageTitle = $this->translate("Gérer les articles");
$this->layout()->description = ($this->pageDescription) ?: $this->translate("Gestion des articles de la revue.");

$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();


/** @var Zend_Form $form */
$form = $this->paperFilter();

// A gérer en AJAX (dataTable)
$form->getElement('submit')->setAttrib('type', '');
$form->setAction($this->url());

echo $form;
?>
<hr/>
<?php
$this->jQuery()->addJavascriptFile(VENDOR_JQUERY_DATATABLES);
$this->jQuery()->addJavascriptFile(VENDOR_DATATABLES_BOOTSTRAP);
$this->jQuery()->addJavascriptFile('/js/administratepaper/editor-availability.js');
$this->jQuery()->addJavascriptFile('/js/administratepaper/editorsAndCopyEditors-assignment.js');
$this->jQuery()->addStylesheet(VENDOR_DATATABLES_CSS);
$this->jQuery()->addJavascriptFile("/js/datepicker/datepicker-" . Zend_Registry::get('lang') . ".js");
$this->jQuery()->addJavascriptFile("/js/datepicker/datepicker.js");
$this->jQuery()->addJavascriptFile(VENDOR_TINYMCE_JQUERY);
$this->jQuery()->addJavascriptFile(VENDOR_TINYMCE);
$this->jQuery()->addJavascriptFile(TINYMCE_DIR . "tinymce_patch.js");
?>

<table class="table table-bordered dataTable table-responsive-lg" id="papers" style="width: 100%;">
    <thead>
    <tr>
        <th class="text-center"><?= $this->translate('Id permanent'); ?></th>
        <th class="text-center"><?= $this->translate('Id document'); ?></th>
        <th class="text-center" data-name="<?= $this->translate('Statut'); ?>"><?= $this->translate('Statut'); ?></th>
        <th><?= $this->translate('Titre'); ?></th>
        <th class="text-center"><?= $this->translate('Volume principal'); ?></th>
        <th class="text-center"><?=$this->translate('Rubrique'); ?></th>
        <th class="text-center"><?= $this->translate('Relecteurs'); ?></th>
        <th class="text-center"><?= $this->translate('Rédacteurs'); ?></th>
        <th class="text-center"><?= $this->translate('Préparateurs de copie'); ?></th>
        <th class="text-center"><?= $this->translate('Contributeur'); ?></th>
        <th class="text-center"><?= $this->translate('Proposé le'); ?></th>
        <th class="text-center"><?= $this->translate('Date de publication'); ?></th>
    </tr>
    </thead>
    <tbody></tbody>
</table>

<?php

$status = [];
$noEditors = [];

$editableWithoutEditorsData = [
    'status' => $status,
    'editors' => $noEditors
];

if (Episciences_Auth::isAdministrator()) {

    $status = array_values(array_diff(Episciences_PapersManager::getAllStatus(RVID, 'ASC'), Episciences_Paper::$_noEditableStatus));
    $noEditors = [Episciences_View_Helper_PaperFilter::NONE_KEY];
}

try {
    $editableWithoutEditorsData = json_encode([
        'editors' => $noEditors,
        'status' => $status
    ], JSON_THROW_ON_ERROR);


} catch (JsonException $e) {

    trigger_error($e->getMessage());
}

?>


<script type="text/javascript">


    let selfController = <?= "'$controller'" ?>;
    let selfAction = <?= "'$action'" ?>;

    const editableWithoutEditorsData = <?= $editableWithoutEditorsData ?>;

    $.getScript("/js/paper/submitted.js?_=v<?= APPLICATION_VERSION ?>;");
    $.getScript("/js/administratepaper/section-assignment.js?_=v<?= APPLICATION_VERSION ?>");
    $.getScript("/js/administratepaper/volume-assignment.js?_=v<?= APPLICATION_VERSION ?>");

</script>




