<form action="/administratepaper/savemastervolume" id="volume-form-<?= (int) $this->docid ?>" autocomplete="off">
    <label for="master_volume_select" class="sr-only"><?= $this->translate('Volume') ?></label>
    <select class="form-control" name="vid" id="master_volume_select">
        <option value=""><?= $this->translate('Hors volume') ?></option>
        <?php foreach ($this->volumes as $volume): ?>
            <option value="<?= (int) $volume->getVid() ?>"
                <?= ($volume->getVid() === $this->vid) ? 'selected' : '' ?>>
                <?= $this->escape($volume->getNameKey()) ?>
            </option>
        <?php endforeach; ?>
    </select>
</form>

<?php if (null !== $this->paperPosition): ?>
    <?php
        $alert = $this->translate("Si le papier est retiré du volume cela n'entraîne pas le réordonnancement automatique des autres articles.");
        $alert .= '<br>';
        $alert .= $this->translate("Il est toujours possible de modifier cet ordre manuellement via l'édition du volume.");
    ?>
    <div class="alert alert-warning alert-dismissible" style="margin-top: 16px; margin-bottom: 0">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">&times;</button>
        <strong><i class="fas fa-exclamation-circle"></i></strong> <?= $alert ?>
    </div>
<?php endif; ?>
