<form action="/administratepaper/saveothervolumes" id="volumes-form-<?= (int) $this->docid ?>" autocomplete="off">

    <label for="other_volumes_select" class="sr-only"><?= $this->translate('Volumes secondaires') ?></label>
    <select name="vids[]" id="other_volumes_select" multiple>
        <?php foreach ($this->volumes as $volume): ?>
            <option value="<?= (int) $volume['vid'] ?>"
                <?= $volume['checked'] ? 'selected' : '' ?>>
                <?= $this->escape($volume['name']) ?>
            </option>
        <?php endforeach; ?>
    </select>

</form>
