<?php if (isset($this->apiEpiBibCitation, $this->urlcallapibib)): ?>
    <div class="panel-body in">
        <div class="row">
            <div id="container-processing-biblio-refs" class="col-md-12">
                <?php if ($this->paper->isPublished()): ?>
                    <a id="epi-citation-app" class="btn btn-default btn-sm" target="_blank"
                       href="<?= $this->apiEpiBibCitation ?>/login?repoid=<?= $this->repoId ?>&url=<?= $this->urlcallapibib ?>"
                       style="margin-bottom: 8px;"><i
                                class="fas fa-edit"></i> <?= $this->translate('Gérer les références') ?>
                    </a>
                <?php endif; ?>
                <ol id="biblio-refs-container"></ol>
                <div class="biblio-ref-legend">
                    <small>
                        <i class="fa-solid fa-square-xmark" style="color:#c0392b;"></i> <?= $this->translate('Référence problématique') ?>
                        &nbsp;&nbsp;
                        <i class="fa-solid fa-square-check" style="color:#009527;"></i> <?= $this->translate('Référence validée') ?>
                        &nbsp;&nbsp;
                        <i class="fa-solid fa-square" style="color:#aaa;"></i> <?= $this->translate('Référence non validée') ?>
                    </small>
                </div>
                <div id="visualize-biblio-refs" data-value="<?= $this->urlcallapibib ?>"
                     data-api="<?= $this->apiEpiBibCitation ?>" data-all="1" hidden></div>
            </div>
        </div>
    </div>

<?php endif ?>