<form id="section-assignment-form-<?= (int) $this->docid ?>" role="form" autocomplete="off">

    <label for="section_select" class="sr-only"><?= $this->translate('Rubrique') ?></label>
    <select class="form-control" name="sid" id="section_select">
        <option value=""><?= $this->translate('Hors rubrique') ?></option>
        <?php foreach ($this->sections as $section): ?>
            <option value="<?= (int) $section->getSid() ?>"
                <?= ($section->getSid() == $this->sid) ? 'selected' : '' ?>
                data-has-editors="<?= $section->hasEditors() ? 'true' : 'false' ?>">
                <?= $this->escape($section->getNameKey()) ?>
            </option>
        <?php endforeach; ?>
    </select>

    <div class="checkbox" hidden>
        <label>
            <input type="checkbox" name="assignEditors" id="assignEditors">
            <?= $this->translate('Assigner les rédacteurs de cette rubrique à cet article') ?>
        </label>
    </div>

</form>
