%%RECIPIENT_SCREEN_NAME%%,

Vous avez été automatiquement assigné à cet article : "<i>#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</i>", qui est une version temporaire de <a href="%%PAPER_URL%%">celui-ci</a>.
Vous pouvez accéder à la page de relecture <a href="%%TMP_PAPER_URL%%">ici</a>.


Sincères salutations,
--
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
