%%RECIPIENT_SCREEN_NAME%%,

Un relecteur vient de poster un commentaire concernant votre article (#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%), proposé le %%SUBMISSION_DATE%% :

%%COMMENT%%

Vous pouvez lui répondre en vous connectant sur : <a href="%%PAPER_URL%%">%%PAPER_URL%%</a>

--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
