Bonjour %%RECIPIENT_SCREEN_NAME%%,

La version finale déposée pour l'article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>) nécessite un fichier LaTeX/source corrigé.

Message de l'équipe éditoriale :
%%COMMENT%%

Veuillez utiliser le lien ci-dessus pour déposer le ou les fichiers corrigés.

Sincères salutations,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
