%%RECIPIENT_SCREEN_NAME%%,

L'article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>) vient d'être accepté.

Vous pouvez donc choisir entre les deux statuts suivants:

1) Demandez à l'auteur les sources (article formaté par la revue). Dans ce cas, vous devez attribuer cet article à un <strong>préparateurs de copie</strong> via le module &laquo;<strong>Assigner des préparateurs de copie</strong>&raquo;.

2) Demander la version finale (À mettre en forme par l’auteur). Dans ce cas (si cela n'est pas déjà fait), vous devez rendre accessible les fichiers de style de la revue et les règles de préparation d'un document en suivant ces consignes :

- Combiner l'ensemble de ces fichiers en un seul dossier zippé et nommé : <strong>%%REVIEW_CE_RESOURCES_NAME%%</strong>
   - Ajouter ce dossier zippé aux ressource de la revue via ce lien : <a href="%%ALL_REVIEW_RESOURCES_LINK%%">Ressources</a>

--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
