Bonjour %%RECIPIENT_SCREEN_NAME%%,

Le processus de publication de votre article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>)
que vous aviez proposé le %%SUBMISSION_DATE%% vient d'être stoppé.

Notez bien qu'il ne vous sera plus possible de soumettre cet article dans cette revue. L'abandon est définitif.


--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
