%%RECIPIENT_SCREEN_NAME%%,

Le %%COMMENT_DATE%%, un relecteur a posté un commentaire concernant un article dont vous êtes responsable (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>) :

**************
%%COMMENT%%
**************

L'auteur de cet article vient de répondre à ce commentaire :

**************
%%ANSWER%%
**************


Sincères salutations,
--
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
