Bonjour %%RECIPIENT_SCREEN_NAME%%,

L'article <a href="%%PAPER_URL">(#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%)</a> proposé par <em>%%CONTRIBUTOR_FULL_NAME%%</em>, le <em>%%SUBMISSION_DATE%%</em> sous forme de version temporaire a été accepté par <em>%%REQUESTER_SCREEN_NAME%%</em>.

Sincères salutations,
--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>


