Bonjour %%RECIPIENT_SCREEN_NAME%%,

Votre article (#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%) que vous aviez proposé le %%SUBMISSION_DATE%% est en attente des sources auteur pour la préparation de copie.

Pour télécharger vos fichiers sources, veuillez vous connecter sur : <a href="%%PAPER_URL%%">%%PAPER_URL%%</a>.

Sincères salutations,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_USERNAME_LOST_LOGIN%%">Login oublié ?</a></span>
