%%RECIPIENT_SCREEN_NAME%%,

Le comité éditorial demande que vous apportiez des modifications majeures à votre article (#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%), proposé le %%SUBMISSION_DATE%%.

Merci de répondre à cette demande avant la date limite :  <span class="revision_deadline">%%REVISION_DEADLINE%%</span>.

Pour répondre à cette demande, veuillez vous connecter sur : <a href="%%PAPER_URL%%">%%PAPER_URL%%</a>.

%%PAPER_RATINGS%%

Sincères salutations,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
