Bonjour %%RECIPIENT_SCREEN_NAME%%,

Le comité éditorial demande que vous mettiez en forme votre article (#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%), proposé le %%SUBMISSION_DATE%%.

Ci-dessous les références bibliographiques de votre article :

    - Date de soumission : %%PAPER_SUBMISSION_DATE%%
    - Date de la dernière révision : %%LAST_REVISION_DATE%%
    - Dates de révisions (si multiples versions): %%REVISION_DATES%%
    - Date d’acceptation : %%ACCEPTANCE_DATE%%
    - Identifiant permanent de l’article : %%PERMANENT_ARTICLE_ID%%
    - Nom de la section : %%SECTION_NAME%%
    - Nom du volume : %%VOLUME_NAME%%
    - Ordre de l’article dans le volume : %%PAPER_POSITION_IN_VOLUME%%
    - Rédacteur(s) du volume : %%VOLUME_EDITORS%%
    - DOI : %%DOI%%
    - Année en cours : %%CURRENT_YEAR%%
    - Référence bibliographique du volume : %%TAG_VOL_BIBLIOG_REF%%

Les fichiers de style et les règles de préparation d'un document adapté à ce style se trouvent à l'adresse suivante : <a href="%%REVIEW_CE_RESOURCES_URL%%">%%REVIEW_CE_RESOURCES_URL%%</a>

Veuillez ne pas encore soumettre le fichier traité à vos archives, mais attendez que nous vous donnions le feu vert pour cette version finale.

Pour télécharger votre document mis en forme, veuillez vous connecter sur : <a href="%%PAPER_URL%%">%%PAPER_URL%%</a>.


Sincères salutations,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>