%%RECIPIENT_SCREEN_NAME%%,

Le %%COMMENT_DATE%%, vous aviez posté un commentaire concernant un article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>) :

%%COMMENT%%

L'auteur de cet article vient de vous répondre :

%%ANSWER%%


--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
