Cher/chère %%RECIPIENT_SCREEN_NAME%%,

Vous avez été invité à relire l'article "<i>#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</i>".
La date limite de rendu de relecture de cet article a été modifiée par %%SENDER_FULL_NAME%%.
La nouvelle date limite de rendu de relecture est : <span class="updated_deadline">%%UPDATED_DEADLINE%%</span>.


--
A bientôt sur Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
