Bonjour %%RECIPIENT_SCREEN_NAME%%,

%%CONTRIBUTOR_FULL_NAME%% a déposé la version finale et le mot de passe arXiv pour l'article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>).

Message :
%%COMMENT%%

Les éventuels fichiers d'accompagnement déposés par l'auteur sont joints à ce message.

Sincères salutations,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
