Bonjour %%RECIPIENT_SCREEN_NAME%%,

L'auteur de l'article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>) a décidé d'abandonner sa soumission dans la revue %%REVIEW_NAME%%.
Vous pouvez arrêter votre relecture.

--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>