Bonjour %%RECIPIENT_SCREEN_NAME%%,

%%REQUESTER_SCREEN_NAME%%, l'auteur vient de répondre, suite à votre demande de %%REQUEST_DATE%%.

Lorsque vous avez fini de mettre en forme l'article, merci de retourner sur la page de l'article
et d'y déposer la version formatée en cliquant sur "Mise en forme revue terminée, demander la version finale".

Sa réponse est disponible ici (rubrique travail éditorial) : <a href="%%PAPER_URL%%">%%PAPER_URL%%</a>

--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>