Cher/chère %%RECIPIENT_SCREEN_NAME%%,

Un relecteur (%%REVIEWER_FULLNAME%%) vient de terminer l'évaluation d'un article dont vous avez la charge (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>).

Voici son évaluation : 

%%PAPER_RATING%%


--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
