Bonjour %%RECIPIENT_SCREEN_NAME%%,

Le processus de publication de l'article a été réactivé :

Le statut actuel de l'article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>) est : <span style="text-decoration: underline;">%%LAST_STATUS%%</span>.

--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>