Bonjour %%RECIPIENT_SCREEN_NAME%%,

%%CONTRIBUTOR_FULL_NAME%% a approuvé le bon à tirer pour l'article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>).

Message :
%%COMMENT%%

L'article peut maintenant poursuivre le circuit de publication.

Sincères salutations,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
