Bonjour %%RECIPIENT_SCREEN_NAME%%,

L'article (#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%) que vous aviez proposé le %%SUBMISSION_DATE%% vient d'être mis en forme par le préparateur de copie.

Je vous serais geé de bien vouloir confirmer cette mise en forme.

Sincères salutations,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>

