Bonjour %%RECIPIENT_SCREEN_NAME%%,

Votre demande d'achever le processus de publication de votre article (#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%) que vous aviez proposé le %%SUBMISSION_DATE%%
a bien été prise en compte le <b>%%ACTION_DATE%%</b> à %%ACTION_TIME%%.

Notez bien qu'il ne vous sera plus possible de soumettre cet article dans cette revue. L'abandon est définitif.

--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
