Bonjour %%RECIPIENT_SCREEN_NAME%%,

Vous avez été invité à relire l'article suivant : <a href="%%PAPER_REPO_URL%%">"<i>#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</i>".</a>
Merci de nous indiquer si vous acceptez ou non cette relecture, en vous connectant à cette page :

<a href="%%INVITATION_URL%%">%%INVITATION_URL%%</a>

Pour vous connecter, il vous suffit d'utiliser vos identifiants CCSD (cet identifiant est commun aux différents services du CCSD: HAL, Episciences...).

Sans réponse de votre part sous un délai de %%INVITATION_DEADLINE%%, nous considérerons que vous n'étiez pas intéressé.
Si vous acceptez cette invitation, merci de bien vouloir nous remettre votre rapport d'évaluation avant le <span class="rating_deadline">%%RATING_DEADLINE%%</span>.


Sincères salutations,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
