Bonjour %%RECIPIENT_SCREEN_NAME%%,

L'équipe éditoriale vous demande la version finale et le mot de passe arXiv pour l'article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>).

Message de l'équipe éditoriale :
%%COMMENT%%

Veuillez utiliser le lien ci-dessus pour déposer la version finale et le mot de passe.

Sincères salutations,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
