Cher/chère %%RECIPIENT_SCREEN_NAME%%,

%%REVIEWER_FULLNAME%% vient de refuser de relire l'article suivant : "<a href="%%PAPER_URL%%"><i>#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</i></a>".

Suggestion de relecteur : %%REVIEWER_SUGGESTION%%

Motif du refus : %%REFUSAL_REASON%%


--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
