Bonjour %%RECIPIENT_SCREEN_NAME%%,

Le bon à tirer de votre article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>) est prêt pour validation.

Message de l'équipe éditoriale :
%%COMMENT%%

Veuillez utiliser le lien ci-dessus pour relire le bon à tirer et l'approuver ou demander des corrections.

Sincères salutations,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
