Bonjour %%RECIPIENT_SCREEN_NAME%%,

Le mot de passe arXiv fourni pour l'article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>) n'a pas pu être validé.

Message de l'équipe éditoriale :
%%COMMENT%%

Veuillez utiliser le lien ci-dessus pour déposer un mot de passe corrigé.

Sincères salutations,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
