Bonjour %%RECIPIENT_SCREEN_NAME%%,

L'auteur vient de vous proposer une nouvelle version de son article, consultable ici : <a href="%%PAPER_URL%%">%%PAPER_URL%%</a>

Le %%REQUEST_DATE%%, %%REQUESTER_EXPRESSION%% à l'auteur de l'article "<i>#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</i>" la demande suivante :

%%REQUEST_MESSAGE%%

--
A bientôt sur Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
