Bonjour %%RECIPIENT_SCREEN_NAME%%,

Vous avez été automatiquement ré-invité à relire cet article : "<i>#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</i>", qui est une nouvelle version de <a href="%%PAPER_URL%%">celui-ci</a>.
Merci de nous indiquer si vous acceptez ou non cette relecture, en vous connectant à cette page : <a href="%%INVITATION_URL%%">%%INVITATION_URL%%</a>.

Sans réponse de votre part sous un délai de %%INVITATION_DEADLINE%%, nous considérerons que vous n'étiez pas intéressé.
Si vous acceptez cette invitation, merci de bien vouloir nous remettre votre rapport d'évaluation avant le %%RATING_DEADLINE%%.

--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
