Cher/chère %%RECIPIENT_SCREEN_NAME%%,

Vous venez d'accepter de relire l'article suivant : "<i>#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</i>".
Merci beaucoup pour votre participation ! 

Vous pouvez désormais commencer votre relecture en vous rendant sur cette page : <a href="%%PAPER_URL%%">%%PAPER_URL%%</a> 

Merci de bien vouloir nous remettre votre rapport d'évaluation avant le %%RATING_DEADLINE%%.


--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
