%%RECIPIENT_SCREEN_NAME%%,

L'article (#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%) que vous aviez proposé le %%SUBMISSION_DATE%% sous forme de version temporaire a été accepté par le comité éditorial.
Veuillez maintenant le déposer sur une archive ouverte, et le proposer comme version définitive.

%%PAPER_RATINGS%%


Sincères salutations,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
