Bonjour %%RECIPIENT_SCREEN_NAME%%,

Vous avez été choisi par l'auteur pour suivre son article (#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%).
Merci de vous connecter à <a href="%%PAPER_URL%%">cette page</a> pour suivre le cycle de relecture.

Si vous refusez de gérer cet article, merci de bien vouloir le signaler au comité éditorial.


--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
