Bonjour %%RECIPIENT_SCREEN_NAME%%,

L'article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>) est prêt pour la mise en page.

Message de l'équipe éditoriale :
%%COMMENT%%

Veuillez utiliser le lien ci-dessus pour accéder à la page de gestion de l'article.

Sincères salutations,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
