Bonjour %%RECIPIENT_SCREEN_NAME%%,

Un auteur vient de proposer un nouvel article (#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%).

Pour le gérer, merci de vous connecter sur : <a href="%%PAPER_URL%%">%%PAPER_URL%%</a>

%%REFUSED_ARTICLE_MESSAGE%% <a href="%%REFUSED_PAPER_URL%%">%%REFUSED_PAPER_URL%%</a>

Si vous refusez de gérer cet article, merci de bien vouloir le signaler au comité éditorial.

--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
