%%RECIPIENT_SCREEN_NAME%%,

La préparation de copie de l'article (#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%) vous a été attribuée.
Merci de vous connecter à <a href="%%PAPER_URL%%">cette page</a> pour suivre le cycle de préparation de copie.


--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_USERNAME_LOST_LOGIN%%">Login oublié ?</a></span>
