Cher/chère %%RECIPIENT_SCREEN_NAME%%,

Veuillez maintenant déposer l'article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>) sur une archive ouverte, et le proposer comme version définitive.

Merci de répondre à cette demande avant la date limite : <span class="revision_deadline">%%REVISION_DEADLINE%%</span>.

Sincères salutations,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
