%%RECIPIENT_SCREEN_NAME%%,

%%REVIEWER_FULLNAME%% vient d'accepter de relire un article dont vous avez la charge (<a href="%%PAPER_URL%%">"<i>#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</i>"</a>).

Son rapport d'évaluation devrait être terminé avant le %%RATING_DEADLINE%%. 


--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
