Bonjour %%RECIPIENT_SCREEN_NAME%%,

Un auteur vient de proposer un nouvel article <a href="%%PAPER_URL%%">(#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%).</a>

%%REFUSED_ARTICLE_MESSAGE%% <a href="%%REFUSED_PAPER_URL%%">%%REFUSED_PAPER_URL%%</a>

--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
