Bonjour %%RECIPIENT_SCREEN_NAME%%,

Merci d'avoir proposé votre article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>) à %%REVIEW_CODE%%.
Vous serez informé tout au long de la progression de la relecture de votre article.


--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
