Bonjour %%RECIPIENT_SCREEN_NAME%%,

Vous avez accepté de relire un article <a href="%%PAPER_URL%%">(#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%)</a>, et nous vous en remercions.
Néanmoins, cet article vient d'être accepté, il n'est plus nécessaire de le relire.

Merci pour votre compréhension.

--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>