Bonjour %%RECIPIENT_SCREEN_NAME%%,

L'article (#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%) que vous aviez proposé le %%SUBMISSION_DATE%% vient d'être mis en forme par le préparateur de copie.

<strong>Veuillez maintenant déposer la version finale ci-jointe sur l'archive ouverte <a href="%%PAPER_REPO_URL%%" target="_blank">%%PAPER_REPO_URL%%</a> <em>(le délai de mise en ligne est variable selon l'archive)</em>,
    et la proposer comme version définitive en vous connectant sur : <a href="%%PAPER_URL%%">%%PAPER_URL%%</a>
</strong>


Sincères salutations,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
