Bonjour %%RECIPIENT_SCREEN_NAME%%,

L'auteur de l'article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>) a décidé d'abandonner sa soumission dans la revue %%REVIEW_NAME%%.
Vous n'avez donc plus besoin d'assigner un rédacteur.

--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>
