Bonjour %%RECIPIENT_SCREEN_NAME%%,

Un article pour lequel vous avez reçu une invitation de relecture (#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%) a été supprimé de %%REVIEW_CODE%% par son auteur (%%CONTRIBUTOR_FULL_NAME%%).

Merci de ne pas tenir compte de cette invitation.

--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
