Bonjour %%RECIPIENT_SCREEN_NAME%%,

La préparation de copie de l'article (#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%) a été confiée à un autre préparateur de copie.
Vous n'avez plus besoin de suivre cette étape de préparation de copie.


--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
