Bonjour %%RECIPIENT_SCREEN_NAME%%,

Le bon à tirer de l'article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>) a été renvoyé en mise en page.

Message :
%%COMMENT%%

Veuillez utiliser le lien ci-dessus pour mettre à jour le bon à tirer.

Sincères salutations,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
