%%RECIPIENT_SCREEN_NAME%%,

Le %%REQUEST_DATE%%, vous aviez envoyé à l'auteur de l'article "<i>#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</i>" la demande suivante : 

%%REQUEST_MESSAGE%%


L'auteur n'a pas souhaité apporter de modifications à son article pour le moment, mais vous a répondu :

%%REQUEST_ANSWER%%


--
A bientôt sur Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
