Bonjour %%RECIPIENT_SCREEN_NAME%%,

L'éditeur %%COI_EDITOR_FULL_NAME%% a déclaré un conflit d'intérêts pour l'article <a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>.

Cet éditeur a été automatiquement retiré de la gestion de l'article.

Vous pouvez gérer cet article depuis cette page : <a href="%%PAPER_URL%%">%%PAPER_URL%%</a>

--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Nom d'utilisateur oublié ?</a></span>