Bonjour %%RECIPIENT_SCREEN_NAME%%,

Nous avons bien reçu la version finale et le mot de passe arXiv de votre article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>). Votre article est désormais dans notre file de mise en page.

Message de l'équipe éditoriale :
%%COMMENT%%

Nous vous contacterons à nouveau lorsque l'épreuve sera prête pour approbation.

Sincères salutations,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
