Bonjour %%RECIPIENT_SCREEN_NAME%%,

Le %%COMMENT_DATE%%, vous aviez envoyé un message concernant un article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>) :

%%COMMENT%%

L'éditeur de cet article vient de vous répondre :

%%ANSWER%%


--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>