Bonjour %%RECIPIENT_SCREEN_NAME%%,

Vous avez été automatiquement assigné à cet article : "<i>#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</i>", qui est une version temporaire de <a href="%%PAPER_URL%%">celui-ci</a>.
Veuillez nous indiquer si vous acceptez ou non en vous rendant sur cette page : <a href="%%INVITATION_URL%%">%%INVITATION_URL%%</a>.

Sans réponse de votre part avant le %%INVITATION_DEADLINE%%, nous considérerons que vous n'êtes pas intéressé.
Si vous acceptez cette invitation, votre évaluation devra être effectuée avant le %%RATING_DEADLINE%%.


Sincères salutations,
--
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
