Bonjour %%RECIPIENT_SCREEN_NAME%%,

Vous avez la charge d'un article (<a href="%%ARTICLE_LINK%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>) dont le nombre de relecteurs est insuffisant (%%INVITED_REVIEWERS_COUNT%%).
Merci d'inviter au moins %%REQUIRED_REVIEWERS_COUNT%% relecteurs.

Sincères salutations,
--
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
