Bonjour %%RECIPIENT_SCREEN_NAME%%,

Le comité éditorial a fait une demande de sources concernant cet article : <a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>.
La date limite de modification a été définie au %%FORMATTING_DEADLINE%%. Il ne reste que %%REMINDER_DELAY%% jours.

Merci de vous assurer que l'auteur réponde à cette demande avant la date limite.

Sincères salutations,
--
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
