Bonjour %%RECIPIENT_SCREEN_NAME%%,

%%REVIEWER_FULLNAME%% (%%REVIEWER_EMAIL%%) a été invité(e) à relire un article (#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%) le %%INVITATION_DATE%% (il y a %%REMINDER_DELAY%% jours).
Nous n'avons pas encore reçu de réponse de sa part. 

Si vous souhaitez le relancer, voici le lien d'invitation à lui communiquer : <a href="%%INVITATION_LINK%%">%%INVITATION_LINK%%</a>.

Sincères salutations,
--
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
