Bonjour %%RECIPIENT_SCREEN_NAME%%,

Cet article <a href="%%ARTICLE_LINK%%">(#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%)</a> est resté dans son état initial (soumis) pendant %%REMINDER_DELAY%% jour(s).
Veuillez poursuivre le traitement de cet article.

Sincères salutations,
--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
