Bonjour %%RECIPIENT_SCREEN_NAME%%,

L'article <a href="%%ARTICLE_LINK%%">(#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%)</a> a été <strong>accepté</strong> le %%ACCEPTANCE_DATE%%.

Pouvez-vous s'il vous plaît voir pourquoi le statut de cet article n'a pas changé depuis son acceptation ?

merci,

Sincères salutations,
--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
