Bonjour %%RECIPIENT_SCREEN_NAME%%,

%%REVIEWER_FULLNAME%% (%%REVIEWER_EMAIL%%) a accepté de relire un article <a href="%%ARTICLE_LINK%%">(#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%)</a>.
Toutefois, la date de livraison de la relecture approche : il ne reste que %%REMINDER_DELAY%% jours. 

Sincères salutations,
--
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
