%%RECIPIENT_SCREEN_NAME%%,

Le comité éditorial a fait une demande de modifications concernant cet article : <a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>.
La date limite de modification avait été définie au %%REVISION_DEADLINE%%. Cetta date est maintenant dépassée de %%REMINDER_DELAY%% jours.

Merci de vous assurer que l'auteur réponde à cette demande le plus vite possible.

Sincères salutations,
--
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
