%%RECIPIENT_SCREEN_NAME%%,

Vous avez accepté de relire un article <a href="%%ARTICLE_RATING_LINK%%">(#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%)</a>, et nous vous en remercions.
Néanmoins, la date de livraison de votre relecture est dépassée depuis %%REMINDER_DELAY%% jours. 

Merci de finaliser votre évaluation au plus vite.

Sincères salutations,
--
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
