Bonjour %%RECIPIENT_SCREEN_NAME%%,

Vous avez la responsabilité d’un article (<a href="%%ARTICLE_LINK%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>) pour lequel le nombre de relecteurs ayant accepté l’invitation demeure insuffisant.
Nous vous remercions d’inviter au moins %%REQUIRED_REVIEWERS_COUNT%% nouveaux relecteurs afin de compléter le processus d’évaluation.

Sincères salutations,
--
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
Vous avez la responsabilité d’un article (<a href="%%ARTICLE_LINK%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>) pour lequel le nombre de relecteurs ayant accepté l’invitation demeure insuffisant.
Nous vous remercions d’inviter au moins %%REQUIRED_REVIEWERS_COUNT%% nouveaux relecteurs afin de compléter le processus d’évaluation.