Bonjour %%RECIPIENT_SCREEN_NAME%%,

Les évaluateurs ont terminé le travail de révision pour l'article <a href="%%ARTICLE_LINK%%">(#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%)</a> depuis %%REMINDER_DELAY%% jour(s).
Veuillez traiter cet article selon la suite du processus.

Sincères salutations,
--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
