Bonjour %%RECIPIENT_SCREEN_NAME%%,

L'article <a href="%%ARTICLE_LINK%%">(#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%)</a> a été <strong>soumis</strong> le %%SUBMISSION_DATE%%.

Est-il normal qu'il soit resté dans son état initial (soumis) pendant %%REMINDER_DELAY%% jours (s) ?

Sincères salutations,
--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_USERNAME_LOST_LOGIN%%">Login oublié ?</a></span>
