Bonjour %%RECIPIENT_SCREEN_NAME%%,

Le principal travail de révision a été effectué par les évaluateurs depuis %%REMINDER_DELAY%% jours (s) pour l'article <a href="%%ARTICLE_LINK%%">(#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%)</a>.

Sincères salutations,
--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org

<span class="username"><a href="%%RECIPIENT_USERNAME_LOST_LOGIN%%">Login oublié ?</a></span>
