%%RECIPIENT_SCREEN_NAME%%,

Vous avez été invité(e) à relire un article (#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%) le %%INVITATION_DATE%% (il y a %%REMINDER_DELAY%% jours).
Nous n'avons pas reçu de réponse de votre part. Peut-être avez-vous oublié ? 
Pour accepter ou décliner cette invitation, merci de suivre ce lien : <a href="%%INVITATION_LINK%%">%%INVITATION_LINK%%</a>.

Sincères salutations,
--
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
