Bonjour %%RECIPIENT_SCREEN_NAME%%,

Le comité éditorial a fait une demande de sources concernant la mise en forme de votre article : <a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>.
La date limite de votre réponse avait été définie au %%FORMATTING_DEADLINE%%. Cette date est maintenant dépassée de %%REMINDER_DELAY%% jours.

Merci de répondre à cette demande le plus vite possible.

Sincères salutations,
--
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
