Bonjour %%RECIPIENT_SCREEN_NAME%%,

Vous avez accepté de relire un article <a href="%%ARTICLE_RATING_LINK%%">(#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%)</a>, et nous vous en remercions.
Toutefois, la date de livraison de votre relecture approche : il vous reste %%REMINDER_DELAY%% jours. 

Merci de finaliser votre évaluation avant la date butoir.

Sincères salutations,
--
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Login oublié ?</a></span>
