Bonjour %%RECIPIENT_SCREEN_NAME%%,

Un compte lié à votre adresse email a été demandé sur le service central d'authentification du CCSD.

Si vous n'êtes pas à l'origine de cette demande vous pouvez ignorer ce message.

Sinon vous devez cliquez sur le lien suivant pour valider votre compte :

<a href="%%TOKEN_VALIDATION_LINK%%">%%TOKEN_VALIDATION_LINK%%</a>


--
Cet e-mail a été généré automatiquement par la plateforme Episciences.org
