<?php 
$this->jQuery()->addJavascriptFile(VENDOR_JQUERY_DATATABLES);
$this->jQuery()->addJavascriptFile(VENDOR_DATATABLES_BOOTSTRAP);
$this->jQuery()->addJavascriptFile('/js/library/es.dataTables.delete-buttons.js');
$this->jQuery()->addJavascriptFile('/js/section/datatable.js');
$this->jQuery()->addJavascriptFile('/js/editors/section-assignment.js');

$this->jQuery()->addStylesheet(VENDOR_DATATABLES_CSS);

?>

<style>
	.sortable-placeholder {
		width: 100%;
		height: 35px;
		background: #ddd !important;
	}
	
	.sortable-handle, .sortable-handle .glyphicon {
		cursor: move;
	}
</style>


<div class="form-actions">
    <a class="btn btn-default" href="/section/add">
    <span class="glyphicon glyphicon-book"></span>
    <span><?php echo $this->translate('Créer une rubrique'); ?></span>
    </a>
</div>
<hr />

<?php if ($this->sections) : ?>
<div>
	<table  class="table table-striped table-bordered dataTable" id="sections">
		<thead>
			<tr>
				<th class="hidden"><?php echo $this->translate('Position')?></th>
				<th width="14"></th>
				<th><?php echo $this->translate('Titre'); ?></th>
				<th width="150"><?php echo $this->translate('Rédacteurs'); ?></th>
				<th width="75" style="text-align:center"><?php echo $this->translate("Statut"); ?></th>
				<th width="30"><?php echo $this->translate('Actions'); ?></th>
			</tr>
		</thead>
		<tbody class="sortable">
			<?php foreach ($this->sections as $section) : ?>
			<tr id="section_<?php echo $section->getSid()	; ?>">
				<td class="hidden"><?php echo $section->getPosition(); ?></td>
				<td class="sortable-handle"><span class="glyphicon glyphicon-move"></span></td>
				<td><?php echo $this->translate('section_'.$section->getSid().'_title'); ?></td>
				<td>
					<div class="editors">
					<?php if ($section->getEditors()) : ?>
					<?php 	echo $this->partial('section/editors_list.phtml', array('editors'=>$section->getEditors()))?>
					<?php endif;?>
					</div>
					<button id="popover-link-<?php echo $section->getSid() ?>"
							style="float: right; 
							font-size: 10px" 
							class="btn btn-xs btn-default popover-link" 
							onclick="getEditors(this, <?php echo $section->getSid() ?>)">
							<span class="caret"></span>
					</button>
				</td>
				<td style="text-align:center">
					<?php 
						$status = '-';
						if ($section->getSetting('status') == 0) {
							$status = "Fermé";
							$class = "label-danger";
						} else {
							$status = "Ouvert";
							$class = "label-success";
						}
					?>
					<span class="label <?php echo $class?>"><?php echo $this->translate($status);?></span>			    		
				</td>
				<td style="text-align:right;">
						<a 	class=""
							title="<?php echo $this->translate('Modifier'); ?>" 
							href="/section/edit?id=<?php echo $section->getSid(); ?>">
							<span class="darkgrey glyphicon glyphicon-edit"></span></a>
						<a 	class="delete" 
							title="<?php echo $this->translate('Supprimer'); ?>" 
							href="/section/delete?id=<?php echo $section->getSid(); ?>">
							<span class="darkgrey glyphicon glyphicon-remove-sign"></span></a>
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>	
<?php else : ?>

<?php echo $this->translate('Aucune rubrique enregistrée')?>.

<?php endif; ?>
