<!-- Guideline -->
<div id="stats" class="panel panel-default collapsable">
    <div class="panel-heading">
        <h2 class="panel-title"><?php echo $this->translate('Bonnes pratiques'); ?></h2>
    </div>
    <div class="panel-body in">
        <p><?php echo $this->translate("Vous êtes sur le point de proposer un article. Veuillez vérifier :"); ?></p>
        <ul>
            <li><?php echo $this->translate("que votre article a été déposé dans une archive ouverte (%s)", $this->repositories); ?></li>
            <li><?php echo $this->translate("que vous connaissez son identifiant"); ?></li>
        </ul>
        <p><?php echo $this->translate("L'identifiant de l'article, sa version et l'archive ouverte dont il provient sont les seules informations dont vous avez besoin pour remplir le formulaire ci-dessous. Les métadonnées seront automatiquement récupérées, et vous verrez un résumé de votre article avant de confirmer sa soumission - veuillez vérifier qu'il s'agit bien de l'article que vous souhaitez soumettre au journal.") ?></p>
    </div>
</div>


<div id="showResult" style="display:none"></div>
<?php echo $this->form; ?>

<?php $this->jQuery()->addJavascriptFile('/js/submit/functions.js'); ?>
<?php $this->jQuery()->addJavascriptFile('/js/common/visualDeleteFile.js'); ?>
<?php if ($this->error) : ?>
    <script type="text/javascript">error();</script>
<?php endif; ?>

<script>

    $(document).ready(function() {

        var examples = <?php echo $this->examples; ?>;
        setPlaceholder();

        $('#search_doc-repoId').change(function() {
            setPlaceholder();

        });

        function setPlaceholder()
        {
            $('#search_doc-docId').attr('placeholder', translate('exemple : ')+examples[$('#search_doc-repoId').val()]);
        }

// Extracting the ID from URL

        $('#search_doc-docId').change(function(){

            if ($(this).val() !== ''){
                var tab = $(this).val().split('/');
                if(tab.length > 1){
                    if(tab[tab.length - 1] !== ''){
                        var str = tab[tab.length - 1];
                        // Delete VERSION from ID
                        var id = str.substr(0, str.length - 2);
                        $(this).val(id);
                    }
                }
            }

        });

    });
</script>
