<?php
$zSubmitUrl = EPISCIENCES_Z_SUBMIT_URL;
try {
    $zSubmitUrl .= '/' . Episciences_Tools::getLocale();
} catch (Zend_Exception $e) {
    trigger_error($e->getMessage());
}

$zSubmitUrl .= '/deposit?rvcode=' . RVCODE;

?>
<!-- Guideline -->
<div id="stats" class="panel panel-default collapsable">
    <div class="panel-heading">
        <h2 class="panel-title"><?php echo $this->translate('Bonnes pratiques'); ?></h2>
    </div>
    <div class="panel-body in">
        <p><?php echo $this->translate("Vous êtes sur le point de proposer un article. Veuillez vérifier :"); ?></p>
        <ul>
            <li><?php echo $this->translate("que votre article a été déposé dans une archive ouverte (%s)", $this->repositories); ?></li>
            <li><?php echo $this->translate("que vous connaissez son identifiant"); ?></li>
        </ul>
        <p><?php echo $this->translate("L'identifiant de l'article, sa version et l'archive ouverte dont il provient sont les seules informations dont vous avez besoin pour remplir le formulaire ci-dessous. Les métadonnées seront automatiquement récupérées, et vous verrez un résumé de votre article avant de confirmer sa soumission - veuillez vérifier qu'il s'agit bien de l'article que vous souhaitez soumettre au journal.") ?></p>
    </div>
</div>


<div id="showResult" style="display:none"></div>
<?php echo $this->form; ?>

<?php $this->jQuery()->addJavascriptFile('/js/submit/functions.js'); ?>
<?php $this->jQuery()->addJavascriptFile('/js/common/visualDeleteFile.js'); ?>
<?php $this->jQuery()->addJavascriptFile('/js/submit/index.js'); ?>

<?php if ($this->error) : ?>
    <script type="text/javascript">error();</script>
<?php endif; ?>

<script>
    let examples = <?= $this->examples ?>;
    let hasHook = false;
    let iSFromZSubmit = <?= $this->isFromZSubmit ?>;
    let zSubmitUrl = '<?= $this->zSubmitUrl ?>';
</script>
