Dear %%RECIPIENT_SCREEN_NAME%%,

I am pleased to inform you that your manuscript (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>), submitted on %%SUBMISSION_DATE%% as a temporary version, has been accepted for publication by the editorial board.

To proceed, please upload this final version to an open access repository. Once you have done so, kindly return to the Episciences platform to designate it as the final version for your article.

%%PAPER_RATINGS%%

Sincerely yours,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>
