Dear %%RECIPIENT_SCREEN_NAME%%,

We have successfully received the revised version of your manuscript (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>), which was submitted to %%REVIEW_CODE%%
We shall notify you of the outcome of the review process in due course.

Sincerely yours,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>
