%%RECIPIENT_SCREEN_NAME%%,

Your article
#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%
submitted on %%SUBMISSION_DATE%% as a final version, has just been accepted by the editorial board.

<strong>Please submit it now to the open archive <a href="%%PAPER_REPO_URL%%" target="_blank">%%PAPER_REPO_URL%%</a> that you used for your initial submission. The necessary delay to be put online may vary according the repository. Once this is accomplished, please come back to Episciences <a href="%%PAPER_URL%%">%%PAPER_URL%%</a> to register it as the final version of your article.</strong>


Sincerely yours,
%%SENDER_FULL_NAME%%
--
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>