%%RECIPIENT_SCREEN_NAME%%,

On %%REQUEST_DATE%%, you've asked the author of the article "<i>#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</i>" to bring the following modifications:

%%REQUEST_MESSAGE%%


The author didn't want to bring any modifications to his article for now, but replied this:

%%REQUEST_ANSWER%%


--
See you soon on Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>
