Dear %%RECIPIENT_SCREEN_NAME%%,

Your article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>), submitted on %%SUBMISSION_DATE%%, is waiting for author sources.

To upload your sources, please go to: <a href="%%PAPER_URL%%">%%PAPER_URL%%</a>.

Sincerely yours,
%%SENDER_FULL_NAME%%
--
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>