Dear %%RECIPIENT_SCREEN_NAME%%,

I am writing to inform you that, following a thorough review process, the editorial board has decided not to proceed with the publication of your manuscript, (#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%), submitted on %%SUBMISSION_DATE%%

While we appreciate the opportunity to consider your work, we regret to inform you that your submission has been declined on this occasion.

Please find the reviewers' specific feedback and assessments below

%%PAPER_RATINGS%%


Sincerely yours,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>
