Dear %%RECIPIENT_SCREEN_NAME%%,

Your article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>), submitted on %%SUBMISSION_DATE%% as a temporary version, has just been accepted by the editorial board.
Please submit it now on an open archive, and come back to Episciences to make it the final version of your article.

%%PAPER_RATINGS%%

Sincerely yours,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>
