Dear %%RECIPIENT_SCREEN_NAME%%,

The article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>) is ready for layout editing.

Message from the editorial team:
%%COMMENT%%

Please use the link above to access the article management page.

Sincerely yours,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>
