Dear %%RECIPIENT_SCREEN_NAME%%,

Please ensure that you upload the final version of your manuscript (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>) to an open access repository. Once this is complete, kindly return to the Episciences platform to finalise the submission as the version.

We would be grateful if you could complete this action by the following deadline: <span class="revision_deadline">%%REVISION_DEADLINE%%</span>.

Sincerely yours,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>
