Dear %%RECIPIENT_SCREEN_NAME%%,

%%CONTRIBUTOR_FULL_NAME%% has approved the proof for the article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>).

Message:
%%COMMENT%%

The article can now continue in the publication workflow.

Sincerely yours,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>
