Dear %%RECIPIENT_SCREEN_NAME%%,

I am pleased to inform you that your manuscript (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>), which was submitted on %%SUBMISSION_DATE%%, has been accepted for publication by the editorial board.

Congratulations on the acceptance of your work; we shall be in contact shortly regarding the next steps in the production process.


%%PAPER_RATINGS%%

Sincerely yours,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>
