Dear %%RECIPIENT_SCREEN_NAME%%,

The final version submitted for your article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>) requires a corrected LaTeX/source file.

Message from the editorial team:
%%COMMENT%%

Please use the link above to submit the corrected file(s).

Sincerely yours,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>
