Dear %%RECIPIENT_SCREEN_NAME%%,

The author has complied to this request, and sent a new version, which you can find here: <a href="%%PAPER_URL%%">%%PAPER_URL%%</a>.

On %%REQUEST_DATE%%, %%REQUESTER_EXPRESSION%% the author of the article "<i>#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</i>" to bring the following modifications:

%%REQUEST_MESSAGE%%

--
See you soon on Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>
