Dear %%RECIPIENT_SCREEN_NAME%%,

You are invited to review the following article: <a href="%%PAPER_REPO_URL%%">"<i>#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</i>".</a>
Please tell us if you accept or not, by going to this page:

<a href="%%INVITATION_URL%%">%%INVITATION_URL%%</a>

Without any answer from you within %%INVITATION_DEADLINE%%, we will consider that you were not interested.
In case you accept this invitation, your rating will be due before <span class="rating_deadline">%%RATING_DEADLINE%%</span>.


Sincerely yours,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>
