%%RECIPIENT_SCREEN_NAME%%,

The editorial board requests you to bring some major modifications to your article (#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%), submitted on %%SUBMISSION_DATE%%.

Please give an answer to this request before the deadline: <span class="revision_deadline">%%REVISION_DEADLINE%%</span>.

To answer this request, please go to: <a href="%%PAPER_URL%%">%%PAPER_URL%%</a>.


%%PAPER_RATINGS%%

Sincerely yours,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>
