%%RECIPIENT_SCREEN_NAME%%,

The editorial board requests you to format your article
#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%
submitted on %%SUBMISSION_DATE%%.

Here are the bibliographical references of your article:

    - Submission date: %%PAPER_SUBMISSION_DATE%%
    - Latest revision date: %%LAST_REVISION_DATE%%
    - Revision dates (if multiple versions): %%REVISION_DATES%%
    - Acceptation date: %%ACCEPTANCE_DATE%%
    - Permanent identifier: %%PERMANENT_ARTICLE_ID%%
    - Section name: %%SECTION_NAME%%
    - Volume name: %%VOLUME_NAME%%
    - Position in volume : %%PAPER_POSITION_IN_VOLUME%%
    - Volume editor(s): %%VOLUME_EDITORS%%
    - DOI : %%DOI%%
    - Current year : %%CURRENT_YEAR%%
    - Volume's bibliographical reference: %%TAG_VOL_BIBLIOG_REF%%

The style files and the rules for preparing a document adapted to this style can be found at the following address: <a href="%%REVIEW_CE_RESOURCES_URL%%">%%REVIEW_CE_RESOURCES_URL%%</a>

Please do not yet submit the processed file to your archive, but wait until we have given you the green light for this final version.

To upload your formatted document, please go to: <a href="%%PAPER_URL%%">%%PAPER_URL%%</a>.


Sincerely yours,
%%SENDER_FULL_NAME%%
--
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>