Dear %%RECIPIENT_SCREEN_NAME%%,

%%CONTRIBUTOR_FULL_NAME%% has requested changes to the proof for the article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>).

Message:
%%COMMENT%%

Please use the link above to review the author's request.

Sincerely yours,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>
