Dear %%RECIPIENT_SCREEN_NAME%%,

I am delighted to inform you that your article, '%%ARTICLE_TITLE%%' (#%%ARTICLE_ID%%), which was submitted on %%SUBMISSION_DATE%%, has now been published.

The final version is available for viewing and citation via the following link: <a href="%%PAPER_URL%%">%%PAPER_URL%%</a>.

Congratulations on this successful contribution to the field.

Sincerely yours,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>
