Dear %%RECIPIENT_SCREEN_NAME%%,

You've been automatically assigned to this article "<i>#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</i>", which is a new version of <a href="%%PAPER_URL%%">this one</a>.
You can review this article <a href="%%NEW_VERSION_URL%%">here</a>.


Sincerely yours,
--
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>
