Dear %%RECIPIENT_SCREEN_NAME%%,

The arXiv password provided for your article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>) could not be validated.

Message from the editorial team:
%%COMMENT%%

Please use the link above to submit a corrected password.

Sincerely yours,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>
