Dear %%RECIPIENT_SCREEN_NAME%%,

The editorial team requests the final version and the arXiv password for your article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>).

Message from the editorial team:
%%COMMENT%%

Please use the link above to submit the final version and password.

Sincerely yours,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>
