Dear %%RECIPIENT_SCREEN_NAME%%,

Please be advised that you have been automatically assigned to manage the manuscript entitled "<i>#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</i>",

This submission represents a revised version of a <a href="%%PAPER_URL%%">previous paper</a>.
You may conduct your review of the updated manuscript via the following link: <a href="%%NEW_VERSION_URL%%">here</a>.


Sincerely yours,
--
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>
