Dear %%RECIPIENT_SCREEN_NAME%%,

We have received the final version and arXiv password for your article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>). Your article has now entered our layout-editing queue.

Message from the editorial team:
%%COMMENT%%

We will contact you again when the proof is ready for your approval.

Sincerely yours,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>
