Dear %%RECIPIENT_SCREEN_NAME%%,

The proof of your article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>) is ready for your validation.

Message from the editorial team:
%%COMMENT%%

Please use the link above to review the proof and approve it or request changes.

Sincerely yours,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>
