Dear %%RECIPIENT_SCREEN_NAME%%,

%%CONTRIBUTOR_FULL_NAME%% has submitted the final version and arXiv password for the article (<a href="%%PAPER_URL%%">#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</a>).

Message:
%%COMMENT%%

The submitted file(s) are attached to this message.

Sincerely yours,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>
