%%RECIPIENT_SCREEN_NAME%%,

You've been invited to review this article: "<i>#%%ARTICLE_ID%% - %%ARTICLE_TITLE%%</i>". 
The rating deadline has been updated by %%EDITOR_FULLNAME%%.
The new rating deadline is: <span class="updated_deadline">%%UPDATED_DEADLINE%%</span>.


--
See you soon on Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>
