Dear %%RECIPIENT_SCREEN_NAME%%,

You were previously invited to review the manuscript entitled: #%%ARTICLE_ID%% - %%ARTICLE_TITLE%%.
Please be advised that this invitation has now been withdrawn; consequently, you are no longer required to provide a report or formal assessment for this submission.
We apologise for any inconvenience this change may have caused.

Sincerely yours,
--
%%SENDER_FULL_NAME%%
Episciences.org

<span class="username"><a href="%%RECIPIENT_FORGOTTEN_USERNAME_LINK%%">Forgotten username ?</a></span>
