<?php
$this->jQuery()->addJavascriptFile(VENDOR_JQUERY_DATATABLES);
$this->jQuery()->addJavascriptFile(VENDOR_DATATABLES_BOOTSTRAP);
$this->jQuery()->addJavascriptFile('/js/library/es.dataTables.delete-buttons.js');
$this->jQuery()->addJavascriptFile('/js/grid/list.js');
$this->jQuery()->addStylesheet(VENDOR_DATATABLES_CSS);
?>


<div class="panel panel-default collapsable">

    <div class="panel-heading">
        <h2 class="panel-title"><?php echo $this->translate('Grille par défaut') ?></h2>
    </div>


    <div class="panel-body in">
        <?php if (array_key_exists('grid_0', $this->grids)) : ?>
            <?php $defaultGrid = $this->grids['grid_0']; ?>
            <?php echo $this->partial('partials/grid_criteria.phtml', ['grid' => $this->grids['grid_0'], 'defaultGrid' => $defaultGrid, 'translator' => $this->translator]); ?>

        <?php else : ?>
            <?php $defaultGrid = null; ?>
            <p><?php echo $this->translate("Aucun critère de notation"); ?>.</p>
            <?php if (Episciences_Auth::isSecretary()) : ?>
                <a href="<?= $this->url(['controller' => 'grid', 'action' => 'addcriterion'])?>">
                    <button type="button" class="btn btn-default">
                        <?php echo $this->translate('Ajouter un critère'); ?>
                    </button>
                </a>
            <?php endif; ?>
        <?php endif; ?>

    </div>

</div>

<?php if ($this->grids) : ?>

    <?php foreach ($this->grids as $key => $grid) : ?>
        <?php if ($key != 'grid_0') : ?>

            <div class="panel panel-default collapsable">

                <div class="panel-heading">
                    <h2 class="panel-title">
                        <?php echo $this->translate('Grille pour le volume : '); ?>
                        <?= Episciences_VolumesManager::translateVolumeKey('volume_' . $grid->getId() . '_title'); ?>
                    </h2>
                </div>

                <div class="panel-body in">
                    <?php echo $this->partial('partials/grid_criteria.phtml', ['grid' => $grid, 'defaultGrid' => $defaultGrid, 'translator' => $this->translator]); ?>
                </div>

                <div class="panel-footer" style="text-align: center;">
                    <a href="<?= $this->url(['controller' => 'volume', 'action' => 'edit', 'id' => filter_var($key, FILTER_SANITIZE_NUMBER_INT)]) ?>" class="btn btn-default" role="button">
                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                        <?= $this->translate('Modifier ce volume'); ?>
                    </a>
                </div>

            </div>
        <?php endif; ?>
    <?php endforeach; ?>

<?php endif; ?>

<?php if (Episciences_Auth::isSecretary()) : ?>
    <?php if ($this->form) : ?>
        <?php echo $this->form; ?>
    <?php endif; ?>
<?php endif; ?>
