<?php if ($this->reviewsRequested || $this->reviewsReceived || $this->medianReviewsNumbe) : ?>
    <div id="evaluation">
        <h1 class="help-block" style="margin-top: 10px;"><?= $this->translate('Évaluation') ?></h1>
        <ul class="list-unstyled">
            <li>
                <?= $this->translate('Évaluations demandées') ?>
                <code><?= $this->reviewsRequested ?></code>
            </li>

            <li>
                <?= $this->translate('Évaluations reçues') ?>
                <code><?= $this->reviewsReceived ?></code>
            </li>

            <li>
                <?= $this->translate("Nombre médian d'évaluations d'articles de recherche") ?>
                <code><?= $this->medianReviewsNumber ?></code>
            </li>

        </ul>

    </div>
<?php endif; ?>
