<?php if (
        $this->submissionAcceptanceTime ||
        $this->submissionPublicationTime ||
        $this->submissionPublicationTimeMedian ||
        $this->submissionAcceptanceTimeMedian
) : ?>
    <div>

        <table class="delay table table-striped">

            <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col"><?= sprintf($this->translate('Moyenne [en %s]'), $this->translate(strtolower($this->submissionAcceptanceTimeUnit))) ?></th>
                <th scope="col"><?= sprintf($this->translate('Médiane [en %s]'), $this->translate(strtolower($this->submissionAcceptanceTimeMedianUnit))) ?></th>
            </tr>
            </thead>
            <tbody>

            <tr>
                <th><?= ucfirst($this->translate('délai soumission-publication')) ?></th>
                <td><?= $this->submissionPublicationTime ?></td>
                <td><?= $this->submissionPublicationTimeMedian ?></td>
            </tr>

            <tr>
                <th><?= ucfirst($this->translate('délai soumission-acceptation')) ?></th>
                <td><?= $this->submissionAcceptanceTime ?></td>
                <td><?= $this->submissionAcceptanceTimeMedian ?></td>
            </tr>
            </tbody>
        </table>

    </div>
<?php endif; ?>
