<?php
$isYear = isset($this->year);
$acceptedNoYetPublishedTooltipInfo = "Cela inclut les articles en cours de mise en forme et en attente de publication.";
$acceptedTooltipInfo = "Cela inclut les articles qui ont déjà été publiés";
$refusedTooltipInfo = "Cela inclut les articles qui ont été soumis antérieurement et refusés cette année.";
$otherStatusTooltipInfo = "Cela inclut les autres statuts.";
?>
<div class="panel panel-default collapsable">
    <div class="panel-heading"><h2
                class="panel-title"><?= $this->chart1Title ?><?= $this->year ? ' - <code>' . $this->year . '</code>' : '' ?></h2>
    </div>
    <div class="panel-body in">
        <div class="col-md-6">
            <div style="padding-top: 10px; ">

                <div>
                    <ul class="list-unstyled">

                        <?php if (!$this->startStatsAfterDate || !$isYear) : ?>
                            <?= $this->render('stats/total-submissions.phtml') ?>
                        <?php endif; ?>

                        <?php if ($this->startStatsAfterDate): ?>
                            <aside>
                                <p class="help-block"><?= $this->translate("À l'exception des statistiques sur les utilisateurs, les indicateurs ci-dessous ne comprennent que des données postérieures au ") ?><?= Episciences_View_Helper_Date::Date($this->startStatsAfterDate); ?></p>
                            </aside>


                            <?php if ($isYear): ?>

                                <?= $this->render('stats/total-submissions.phtml') ?>
                            <?php else: ?>

                                <li>
                                    <?= $this->translate('Soumissions') ?>
                                    <code><?= $this->allSubmissions ?></code>
                                    <?php if ($this->imported): ?>
                                        <?php $importedMsg = $this->imported > 1 ? 'dont %s importés' : 'dont %s importé'; ?>
                                        <p class="help-block" style="display: inline;">
                                            (<?= sprintf($this->translate($importedMsg), '<code>' . $this->imported . '</code>') ?>
                                            )
                                        </p>
                                    <?php endif; ?>

                                </li>
                            <?php endif; ?>


                        <?php endif ?>


                        <?php if ($this->allAcceptations) : ?>

                            <li>
                                <?= ucfirst($this->translate('articles acceptés')) ?>
                                <code><?= $this->allAcceptations ?></code>

                                <em class="fas fa-info-circle fa-sm" data-toggle="tooltip" title="<?= $this->translate($acceptedTooltipInfo) ?>"></em>

                            </li>

                        <?php endif; ?>

                        <?php if (!$isYear && $this->acceptanceRate): ?>
                            <?php
                            $acceptanceRateTooltipInfo = '(A/S)x100 <em>[ A' . $this->translate(' :') . ' ' . $this->translate("le nombre d'articles acceptés") . ', S' . $this->translate(' :') . ' ' . $this->translate('toutes les soumissions') . ' ]</em>';
                            $acceptanceRate = $this->acceptanceRate; ?>


                            <li>
                                <?= $this->translate("Taux d'acceptation") ?>
                                <code style="font-size: 105%;"><?= $this->acceptanceRate ?></code><em
                                        class="fas fa-percent fa-sm" style="margin-left: 5px;"></em>
                                <em class="fas fa-info-circle fa-sm" data-toggle="tooltip"
                                    title="<?= $this->translate($acceptanceRateTooltipInfo) ?>"></em>
                            </li>

                        <?php else: ?>

                            <?php if ($this->acceptedSubmittedSameYaer) : ?>
                                <li>
                                    <?= ucfirst($this->translate('articles acceptés')) ?>
                                    <span class="small">(<?= $this->translate('soumis la même année') ?>)</span>
                                    <code><?= $this->acceptedSubmittedSameYaer ?></code>

                                </li>
                            <?php endif; ?>
                            <?php if ($this->acceptationRateSubmittedSameYear) : ?>
                                <li>
                                    <?= $this->translate("Taux d'acceptation") ?>
                                    <code style="font-size: 105%;"><?= $this->acceptationRateSubmittedSameYear ?></code><em
                                            class="fas fa-percent fa-sm" style="margin-left: 5px;"></em>
                                    <em class="fas fa-info-circle fa-sm" data-toggle="tooltip"
                                        title="<?= $this->translate('(A/S)x100 <em>[ A' . $this->translate(' :') . ' ' . $this->translate("articles acceptés (soumis la même année)") . ', S' . $this->translate(' :') . ' ' . $this->translate("le nombre de soumissions sur l'ensemble de l'année")) ?>"></em>

                                </li>
                            <?php endif; ?>


                        <?php endif; ?>

                        <?php if ($this->allRefusals) : ?>

                            <li>
                                <?= ucfirst($this->translate('articles refusés')) ?>
                                <code><?= $this->allRefusals ?></code>
                                <?php if ($isYear): ?>
                                    <em class="fas fa-info-circle fa-sm" data-toggle="tooltip"
                                        title="<?= $this->translate($refusedTooltipInfo) ?>"></em>
                                <?php endif; ?>
                            </li>

                        <?php endif; ?>

                        <?php if ($this->allOtherStatus) : ?>

                            <li>
                                <?= ucfirst($this->translate('autres statuts')) ?>
                                <code><?= $this->allOtherStatus ?></code>
                                <?php if ($isYear): ?>
                                    <em class="fas fa-info-circle fa-sm" data-toggle="tooltip"
                                        title="<?= $this->translate($otherStatusTooltipInfo) ?>"></em>
                                <?php endif; ?>
                            </li>

                        <?php endif; ?>

                        <?= $this->render('stats/submission-delay.phtml') ?>

                        <?php if ($this->acceptedNotYetPublished) : ?>

                            <h1 class="help-block"
                                style="margin-top: 10px;"><?= $this->translate('En cours de publication') ?></h1>
                            <li>
                                <?= ucfirst($this->translate('articles acceptés')) ?>
                                <span class="small">(<?= $this->translate('non encore publiés') ?>)</span>
                                <code><?= $this->acceptedNotYetPublished ?></code>
                                <?php if ($isYear): ?>
                                    <em class="fas fa-info-circle fa-sm" data-toggle="tooltip"
                                        title="<?= $this->translate($acceptedNoYetPublishedTooltipInfo) ?>"></em>
                                <?php endif; ?>
                            </li>
                        <?php endif; ?>


                    </ul>

                </div>
            </div>
            <?= $this->render('stats/evaluations.phtml') ?>
        </div>
        <div class="col-md-6" style="margin-top: 40px; ">
            <canvas id="all-submissions-percentage" style="height: auto; width: auto;"></canvas>
        </div>
    </div>
</div>

<div class="panel panel-default collapsable">
    <div class="panel-heading"><h2 class="panel-title"><?= $this->chart2Title ?></h2></div>
    <div class="panel-body in">
        <canvas id="submissions-by-year-chart" style="height: auto; width: auto;"></canvas>
    </div>
</div>

<div class="panel panel-default collapsable">
    <div class="panel-heading"><h2 class="panel-title"><?= $this->chart3Title ?></h2></div>
    <div class="panel-body in">
        <canvas id="submissions-by-repo-chart" style="height: auto; width: auto;"></canvas>
    </div>
</div>

<div class="panel panel-default collapsable">
    <div class="panel-heading in"><h2 class="panel-title"><?= $this->chart4Title ?></h2></div>
    <div class="panel-body in">
        <canvas id="submissions-delay-chart" style="height: auto; width: auto;"></canvas>
    </div>
</div>






