<?php
$isYear = isset($this->year);
$acceptedNoYetPublishedTooltipInfo = "Cela inclut les versions acceptées (mise en forme ou non)";
$acceptedTooltipInfo = "Cela inclut les articles qui ont déjà été publiés";
$refusedTooltipInfo = "La revue peut rejeter plusieurs fois le même article. Dans ce cas, un seul rejet est comptabilisé par article.";
$otherStatusTooltipInfo = "Cela inclut les autres statuts.";
$baseMessage = "La somme du nombre total d’articles acceptés et du nombre total d’articles refusés";
$rateFormulaInfo = sprintf('(A/S)x100 [ A%s%s , S%s%s ]', $this->translate(' :'), $this->translate("le total des articles concernés par le taux X"), $this->translate(' :'), $this->translate($baseMessage));

?>
<div class="panel panel-default collapsable">
    <div class="panel-heading"><h2
                class="panel-title"><?= $this->chart1Title ?><?= $this->year ? ' - <span class="stat-code">' . $this->year . '</span>' : '' ?></h2>
    </div>
    <div class="panel-body in">
        <div class="col-sm-10">
            <div style="padding-top: 10px; ">

                <div>
                    <ul class="list-unstyled">

                        <?php if (!$this->startStatsAfterDate || !$isYear) : ?>
                            <?= $this->render('stats/total-submissions.phtml') ?>
                        <?php endif; ?>

                        <?php if ($this->startStatsAfterDate): ?>
                            <aside>
                                <p class="help-block"><?= $this->translate("À l'exception des statistiques sur les utilisateurs, les indicateurs ci-dessous ne comprennent que des données postérieures au ") ?><?= Episciences_View_Helper_Date::Date($this->startStatsAfterDate); ?></p>
                            </aside>

                            <?php if ($isYear): ?>
                                <?= $this->render('stats/total-submissions.phtml') ?>
                            <?php else: ?>

                                <?= $this->partial('stats/stat-item.phtml', [
                                        'itemLabel' => "Soumissions",
                                        'itemValue' => $this->allSubmissions,
                                        'help' => [
                                                'message' => $this->imported > 1 ? 'dont %s importés' : 'dont %s importé',
                                                'value' => $this->imported
                                        ]
                                ]) ?>

                            <?php endif; ?>

                        <?php endif ?>

                        <?php if ($this->imported > 1) : ?>
                            <aside>
                                <p class="help-block"><?= $this->translate("Les articles importés ne sont pas inclus") ?> </p>
                            </aside

                        <?php endif; ?>

                        <?php if ($this->allPublications && ($this->totalPublishedArticles !== $this->allPublications)) : ?>

                            <?= $this->partial('stats/stat-item.phtml', [
                                    'itemLabel' => 'articles publiés',
                                    'itemValue' => $this->allPublications,
                            ]) ?>

                        <?php endif; ?>


                        <?php if ($this->allAcceptations) : ?>

                            <?= $this->partial('stats/stat-item.phtml', [
                                    'itemLabel' => 'articles acceptés',
                                    'itemValue' => $this->allAcceptations,
                                    'help' => [
                                            'message' => $acceptedTooltipInfo,
                                            'isTooltip' => true
                                    ]
                            ]) ?>

                        <?php endif; ?>

                        <?php if ($this->allRefusals) : ?>

                            <?php if ($isYear):

                                $refusedTooltipInfo = $this->translate("Cela inclut les articles qui ont été soumis antérieurement et refusés cette année.")
                                        . ' ' .
                                        $this->translate($refusedTooltipInfo);
                                ?>
                            <?php endif; ?>



                            <?= $this->partial('stats/stat-item.phtml', [
                                    'itemLabel' => 'articles refusés',
                                    'itemValue' => $this->allRefusals,
                                    'help' => [
                                            'message' => $refusedTooltipInfo,
                                            'isTooltip' => true
                                    ]
                            ]) ?>


                        <?php endif; ?>

                        <?php if ($this->allOtherStatus) : ?>

                            <?= $this->partial('stats/stat-item.phtml', [
                                    'itemLabel' => 'autres statuts',
                                    'itemValue' => $this->allOtherStatus,
                                    'help' => [
                                            'message' => $otherStatusTooltipInfo,
                                            'isTooltip' => true
                                    ]
                            ]) ?>

                        <?php endif; ?>

                        <?php if ($isYear) : ?>

                            <h1 class="help-block" style="margin-top: 10px;"></h1>
                            <div class="submisions-same-year">
                                <?= $this->partial('stats/stat-item.phtml', [
                                        'itemLabel' => [
                                                'articles acceptés',
                                                'clarification' => 'soumis la même année'
                                        ],
                                        'itemValue' => $this->acceptedSubmittedSameYear
                                ]) ?>

                                <?= $this->partial('stats/stat-item.phtml', [
                                        'itemLabel' => [
                                                'articles publiés',
                                                'clarification' => 'soumis la même année'
                                        ],
                                        'itemValue' => $this->publishedSubmittedSameYear
                                ]) ?>

                                <?= $this->partial('stats/stat-item.phtml', [
                                        'itemLabel' => [
                                                'articles refusés',
                                                'clarification' => 'soumis la même année'
                                        ],
                                        'itemValue' => $this->refusedSubmittedSameYear
                                ]) ?>

                            </div>


                        <?php endif; ?>

                        <div class="rate">

                            <h1 class="help-block" style="margin-top: 10px;"><?= $this->translate('Taux') ?></h1>
                            <div class="rate-formula"><?= $this->translate($rateFormulaInfo) ?></div>

                            <div class="row">

                                <div class="col-sm-6">

                                    <?= $this->partial('stats/stat-item.phtml', [
                                            'itemLabel' => "taux d'acceptation",
                                            'itemValue' => $this->acceptanceRate,
                                            'isRate' => true
                                    ]) ?>

                                    <?= $this->partial('stats/stat-item.phtml', [
                                            'itemLabel' => 'taux de publication',
                                            'itemValue' => $this->publicationRate,
                                            'isRate' => true
                                    ]) ?>

                                    <?= $this->partial('stats/stat-item.phtml', [
                                            'itemLabel' => 'taux de refus',
                                            'itemValue' => $this->declineRate,
                                            'isRate' => true
                                    ]) ?>

                                </div>
                                <div class="col-sm-6">
                                    <canvas id="all-submissions-percentage" style="height: auto; width: auto;"></canvas>
                                </div>
                            </div>
                        </div>

                        <?= $this->render('stats/submission-delay.phtml') ?>

                        <?php if ($this->acceptedNotYetPublished) : ?>

                            <h1 class="help-block"
                                style="margin-top: 10px;"><?= $this->translate('En cours de publication') ?></h1>

                            <?= $this->partial('stats/stat-item.phtml', [
                                    'itemLabel' => [
                                            'articles acceptés',
                                            'clarification' => 'non encore publiés'
                                    ],
                                    'itemValue' => $this->acceptedNotYetPublished,
                                    'help' => [
                                            'message' => $acceptedNoYetPublishedTooltipInfo,
                                            'isTooltip' => true
                                    ]
                            ]) ?>

                        <?php endif; ?>

                    </ul>
                </div>
            </div>
            <?= $this->render('stats/evaluations.phtml') ?>
        </div>
    </div>
</div>

<div class="panel panel-default collapsable">
    <div class="panel-heading"><h2 class="panel-title"><?= $this->chart2Title ?></h2></div>
    <div class="panel-body in">
        <canvas id="submissions-by-year-chart" style="height: auto; width: auto;"></canvas>
    </div>
</div>

<div class="panel panel-default collapsable">
    <div class="panel-heading"><h2 class="panel-title"><?= $this->chart3Title ?></h2></div>
    <div class="panel-body in">
        <canvas id="submissions-by-repo-chart" style="height: auto; width: auto;"></canvas>
    </div>
</div>

<?php if (
        !empty($this->seriesFromView['submissionDelay']['datasets'][0]['data']) ||
        !empty($this->seriesFromView['submissionDelay']['datasets'][1]['data'][1])
): ?>

    <div class="panel panel-default collapsable">
        <div class="panel-heading in"><h2 class="panel-title"><?= $this->chart4Title ?></h2></div>
        <div class="panel-body in">
            <canvas id="submissions-delay-chart" style="height: auto; width: auto;"></canvas>
        </div>
    </div>
<?php endif; ?>






