<div class="panel panel-default collapsable">
    <div class="panel-heading"><h2 class="panel-title"><?= $this->chart5Title ?></h2></div>
    <div class="panel-body">
        <div style="padding-top: 10px; text-align: center; ">
            <p><?= $this->translate("Nombre total d'utilisateurs : ") ?>
                <code><?= $this->allUsers ?></code>
            </p>
        </div>
        <canvas id="users-by-roles-chart" style="height: auto; width: auto;"></canvas>
    </div>
</div>
<?php
