<?php
/**
 * @var Episciences_Review $journal
 */
$journal = $this->journal;
?>

<h2><?= $this->translate('acceptedPaperOn') . " " . $this->escape($journal->getName()) ?></h2>
<div>
    <ul>
        <?php foreach ($this->acceptedPapers as $acceptedPaper) :
            /** @var Episciences_Paper $acceptedPaper */
            $epiUrl = $this->url(
                [
                    'controller' => 'administratepaper',
                    'action' => 'view',
                    'id' => $acceptedPaper->getDocid()
                ]);
            ?>
            <li>
                <a href="<?= $this->escape($acceptedPaper->getDocUrl()) ?>" target="_blank" rel="noopener">
                    <em><?= $this->escape($acceptedPaper->getTitle()) ?></em></a>
                <?php $authors = $acceptedPaper->getMetadata('authors'); ?>
                <?php if (is_array($authors)): ?>
                    <?= $this->translate('de') ?>
                    <?php $lastkey = count($authors); ?>
                    <?php foreach ($authors as $key => $creatorName): ?>
                        <?= $this->escape(Episciences_Tools::reformatOaiDcAuthor($creatorName)) ?>
                        <?php if ($lastkey !== $key + 1) : ?>;<?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
                (<?= $this->translate('Accepté le : ') . " " . date('Y-m-d', strtotime($acceptedPaper->getAcceptanceDate())) ?>)
                <?php if ($this->isSecretary) : ?>
                <a href="<?= $epiUrl ?>">#<?= $acceptedPaper->getDocid() ?></a>
                <?php endif; ?>
                <?php ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
