<div id="latest-articles">
    <?php if (empty($this->articles['response']['docs'])) : ?>
        <div class="no-results"><?php echo $this->translate('Aucun article pour le moment'); ?></div>
    <?php else: ?>


        <?php $locale = Episciences_Tools::getLocale(); ?>

        <?php foreach ($this->articles['response']['docs'] as $doc) :
            $docLanguage = $doc['language_s'] ?? null;
            $title = $docLanguage && isset($doc[sprintf("%s_paper_title_t", $docLanguage)]) ? $doc[sprintf("%s_paper_title_t", $docLanguage)] : ($doc['paper_title_t'][0] ?? '');
            $abstract = $docLanguage && isset($doc[sprintf("%s_abstract_t", $docLanguage)]) ? $doc[sprintf("%s_abstract_t", $docLanguage)] : ($doc['abstract_t'][0] ?? '');
            $docUrl = '/' . $this->escape($doc['docid']);
            $localVolumeTitleIndex = $locale . '_volume_title_t';
            ?>

            <?php

            if (array_key_exists($localVolumeTitleIndex, $doc)) {
                $volume = $doc[$localVolumeTitleIndex];
            } elseif (array_key_exists('volume_title_t', $doc) && $doc['volume_title_t'][0]) {
                $volume = $doc['volume_title_t'][0];
            } else {
                $volume = '';
            }


            if (array_key_exists($locale . '_section_title_t', $doc)) {
                $section = $doc[$locale . '_section_title_t'] ?: '';
            } else {
                $section = '';
            }
            ?>
            <div class="article-block">
                <div class="article-title"><a
                            href="<?= $docUrl ?>"><?= $this->escape($title) ?></a>
                </div>
                <div class="authors"><span class="authors-label"><?php echo $this->translate('Auteurs : ') ?></span>
                    <?php
                    if (array_key_exists('author_fullname_s', $doc)) {
                        $arrayOfAuthors = [];
                        $authorSeparator = '&nbsp;;&nbsp;';
                        $maxNumberOfAuthors = 10;
                        $outputFormat = '<a data-toggle="tooltip" data-placement="bottom" title="' . $this->translate("Articles de l'auteur") . '" href="%s">%s</a>';
                        $arrayOfAuthorsWithURL = [];

                        foreach ($doc['author_fullname_s'] as $author) {
                            $tab = Ccsd_Search_Solr::facetStringResultAsArray($author);
                            $arrayOfAuthors[] = $tab[0];
                        }

                        if (count($arrayOfAuthors) > $maxNumberOfAuthors) {
                            $multiArraysOfAuthors = array_chunk($arrayOfAuthors, $maxNumberOfAuthors, true);

                            foreach ($multiArraysOfAuthors[0] as $authorName) {
                                $url = $this->url(array(
                                    'controller' => 'search',
                                    'action' => 'index',
                                    'q' => '*',
                                    'author_fullname_t' => $this->escape($authorName)), null, TRUE);
                                $arrayOfAuthorsWithURL[] = sprintf($outputFormat, $url, $authorName);
                            }
                            $authorList = implode($authorSeparator, $arrayOfAuthorsWithURL) . ' <abbr lang="la" title="et alii">et al.</abbr>';
                        } else {

                            foreach ($arrayOfAuthors as $authorName) {
                                $url = $this->url(array(
                                    'controller' => 'search',
                                    'action' => 'index',
                                    'q' => '*',
                                    'author_fullname_t' => $this->escape($authorName)), null, true);
                                $arrayOfAuthorsWithURL[] = sprintf($outputFormat, $url, $authorName);
                            }
                            $authorList = implode($authorSeparator, $arrayOfAuthorsWithURL);
                            if (mb_substr($authorList, -1) !== '.') {
                                $authorList .= '.';
                            }
                        }

                        echo $authorList;
                    }
                    ?>
                </div>
                <p style="text-align: justify" class="small">
                    <?php
                    if ($abstract !== '') {
                        echo '<br/><blockquote><small>';
                        echo Ccsd_Tools_String::truncate($this->escape($abstract), ABSTRACT_MAX_LENGTH, '&nbsp;[&hellip;]');
                        echo '</small></blockquote>';
                    }
                    ?>
                </p>
                <hr>
                <?php if ($volume) : ?>
                    <div class="volume">
                        <?php if (isset($doc['volume_id_i'])) : ?>
                            <a href="/volume/view/id/<?php echo $this->escape($doc['volume_id_i']) ?>"><?php echo $volume; ?></a>
                        <?php else : ?>
                            <?php echo $volume; ?>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>

                <?php if ($section) : ?>
                    <div class="section">
                        <a href="/section/view/id/<?php echo $this->escape($doc['section_id_i']) ?>"><?php echo $section; ?></a>
                    </div>
                <?php endif; ?>
                <?php if (array_key_exists('publication_date_tdate', $doc)) : ?>
                    <div class="small">
                        <?php echo $this->translate('Publié le '); ?>
                        <?php echo $this->Date($doc['publication_date_tdate']); ?>
                    </div>
                <?php endif; ?>
            </div>
        <?php endforeach;  // end results ?>
    <?php endif; ?>

</div>



