<div id="latest-articles">

	<?php if (empty($this->articles['response']['docs'])) : ?>
	<div class="no-results"><?php echo $this->translate('Aucun article pour le moment'); ?></div>
	<?php endif; ?>

	<?php $locale = Episciences_Tools::getLocale(); ?>
	<?php foreach ($this->articles['response']['docs'] as $doc) : ?>
	<div class="article-block">
		<div class="article-title"><a href="/<?php echo $this->escape($doc['docid']); ?>"><?php echo Episciences_Tools::getTitleFromIndexedPaper($doc, $locale); ?></a></div>
		<div class="authors"><span class="authors-label"><?php echo $this->translate('Auteurs : ') ?></span> 
		<?php
		if (array_key_exists('author_fullname_s', $doc)) {
			$arrayOfAuthors = [];
	        $authorSeparator = '&nbsp;;&nbsp;';
	        $maxNumberOfAuthors = 10;
	        $outputFormat = '<a data-toggle="tooltip" data-placement="bottom" title="' . $this->translate("Articles de l'auteur") . '" href="%s">%s</a>';
	        $arrayOfAuthorsWithURL = [];
	
	        foreach ($doc['author_fullname_s'] as $author) {
	        	$tab = '';
	            $tab = Ccsd_Search_Solr::facetStringResultAsArray($author);
	            $arrayOfAuthors[] = $tab[0];
			}
	
			if (count($arrayOfAuthors) > $maxNumberOfAuthors) {
	        	$multiArraysOfAuthors = array_chunk($arrayOfAuthors, $maxNumberOfAuthors, true);
	
	        	foreach ($multiArraysOfAuthors[0] as $authorName) {
	            	$url = $this->url(array(
	                	'controller' => 'search',
	                    'action' => 'index',
	                    'q' => '*',
						'author_fullname_t' => $this->escape($authorName)), null, TRUE);
					$arrayOfAuthorsWithURL[] = sprintf($outputFormat, $url, $authorName);
				}
	            $authorList = implode($authorSeparator, $arrayOfAuthorsWithURL) . ' <abbr lang="la" title="et alii">et al.</abbr>';
			} else {
	
				foreach ($arrayOfAuthors as $authorName) {
					$url = $this->url(array(
							'controller' => 'search',
							'action' => 'index',
							'q' => '*',
							'author_fullname_t' => $this->escape($authorName)), null, TRUE);
					$arrayOfAuthorsWithURL[] = sprintf($outputFormat, $url, $authorName);
				}
				$authorList = implode($authorSeparator, $arrayOfAuthorsWithURL);
				if (substr($authorList, - 1) != '.') {
					$authorList .= '.';
				}
			}
	
	        echo $authorList;
		}
		?>
		</i></div>
		<p style="text-align: justify" class="small"><?php
		$abstract = Episciences_Tools::getAbstractFromIndexedPaper($doc, $locale);
		if ($abstract) {
			echo '<br/><blockquote><small>';
	        echo Ccsd_Tools_String::truncate($abstract, ABSTRACT_MAX_LENGTH, '&nbsp;[&hellip;]');
	        echo '</small></blockquote>';
		}
		?></p>
		<hr>
		<?php if (array_key_exists('volume_id_i', $doc)) : ?>
	        <div class="small">
	        	<?php echo $this->translate('Volume : '); ?>
		        <?php echo $this->translate('volume_'.$doc['volume_id_i'].'_title'); ?>
	        </div>
		<?php endif;?>
		<?php if (array_key_exists('section_id_i', $doc)) : ?>
	        <div class="small">
	        	<?php echo $this->translate('Rubrique : '); ?>
		        <?php echo $this->translate('section_'.$doc['section_id_i'].'_title'); ?>
	        </div>
		<?php endif;?>
		<?php if (array_key_exists('publication_date_tdate', $doc)) : ?>
	        <div class="small">
		        <?php echo $this->translate('Publié le '); ?>
		        <?php echo $this->Date($doc['publication_date_tdate']); ?>
	        </div>
		<?php endif;?>
	</div>
	<?php endforeach;  // end results ?>

</div>