<?php
/* @var $section Episciences_Section */
/* @var $editor Episciences_Editor */
?>


<div id="sections-list">
    <?php if (count($this->sections)) : ?>

        <?php foreach ($this->sections as $section) : ?>

            <h2 class="section-title">
                <a href="/section/view/id/<?php echo $section->getSid() ?>">
                    <span><strong><?= $this->escape($section->getNameKey()) ?></strong></span>
                </a>
                <span>(<?= $section->getCountOfPapers() . ' ' . $this->translate(['article', 'articles', $section->getCountOfPapers()]) ?>)</span>
            </h2>

            <?php if (Zend_Registry::get('Zend_Translate')->isTranslated($section->getDescriptionKey())) : ?>
                <p><?php echo $this->translate($section->getDescriptionKey()); ?></p>
            <?php endif; ?>

            <?php // list editors ?>
            <?php echo $this->partial('partials/section_list_editors.phtml', ['section' => $section]); ?>

            <hr/>

        <?php endforeach; ?>

        <?php if ($this->total > count($this->sections)) : ?>
            <?php $nbpages = ceil($this->total / $this->limit); ?>
            <nav>
                <ul class="pagination">

                    <?php if ($this->page - 1 > 0) : ?>
                        <li><a href="/browse/section/page/<?php echo $this->page - 1; ?>" aria-label="Previous"><span
                                        aria-hidden="true">&laquo;</span></a></li>
                    <?php else: ?>
                        <li class="disabled"><span aria-hidden="true">&laquo;</span></li>
                    <?php endif; ?>

                    <?php for ($i = 1; $i <= $nbpages; $i++) : ?>
                        <li<?php if ($this->page == $i) echo ' class="active"' ?>><a
                                    href="/browse/section/page/<?php echo $i; ?>"><?php echo $i; ?></a></li>
                    <?php endfor; ?>

                    <?php if ($this->page < $this->total) : ?>
                        <li><a href="/browse/section/page/<?php echo $this->page + 1; ?>" aria-label="Next"><span
                                        aria-hidden="true">&raquo;</span></a></li>
                    <?php else: ?>
                        <li class="disabled"><span aria-hidden="true">&raquo;</span></li>
                    <?php endif; ?>

                </ul>
            </nav>
        <?php endif; ?>

    <?php else : ?>

        <?php echo $this->translate('Aucune rubrique pour le moment'); ?>

    <?php endif; ?>
</div>