<?php
$this->jQuery()
    ->addJavascriptFile(VENDOR_JQUERY_NESTED_SORTABLE)
    ->addJavascriptFile("/js/website/menu.js") ?>

<?php $this->layout()->pageDescription = $this->translate("Ajout/suppression de nouvelles pages dans le site") ?>

<style>
    .sortable {
        margin: 0;
    }

    .sortable, .sortable > li ul {
        list-style-type: none;
    }

    .sortable > li ul {
        border-left: 1px solid #dddddd;
        padding-left: 10px;
    }

    .sortable > li {
        padding: 10px;
        border-top: 1px solid #dddddd;
    }

    .sortable ul li {
        border-top: 1px dotted #dddddd;
    }

    .sortable > li:hover {
        background: #f5f5f5;
    }

    .sortable > li td {
        vertical-align: top;
    }

    #tableHeader {
        margin-bottom: 0px;
    }

    .placeholder {
        margin: 5px 0px;
        height: 20px;
        background-color: #dff0d8;
        border: 1px solid #d6e9c6;
        -webkit-border-radius: 4px;
        -moz-border-radius: 4px;
        border-radius: 4px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
        -moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
        box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
    }

    .ui-nestedSortable-error {
        margin: 0px;
        height: 0px;
        background-color: #ffffff;
        border: 0px;
        box-shadow: inherit;
    }

    .search-affi {
        margin-bottom: 5px;
    }

    .label {
        font-size: 100%;
    }

    #type option[data-predefined="true"] {
        font-weight: 500;
    }
</style>

<?php //Ajout de nouvelles pages ?>
<div class="form-actions">
    <div class="row">
        <div class="col-md-5 offset-md-1">
            <select name="type" id="type" class="form-control">
                <option value=""><?= $this->translate('Choisissez une page') ?></option>
                <?php foreach ($this->groupedPageTypes as $group => $types) : ?>
                    <optgroup label="<?= $this->translate($group) ?>">
                        <?php foreach ($types as $type) :

                            $label = sprintf('Episciences_Website_Navigation_Page_%s', ucfirst($type));
                            $disabled = '';

                            foreach ($this->pages as $page) {
                                if ($label === get_class($page) && !$page->isMultiple()) {
                                    //La page est déjà ajoutée et non multiple
                                    $disabled = ' disabled = "disabled"';
                                    break;
                                }
                            }

                            ?>

                            <option value="<?= $type ?>" <?= $disabled ?> type="<?= $label ?>"><?= $this->translate($label) ?><?php if (!empty($this->predefinedPageTypes[$type])): ?> 🛈 <?php endif; ?>
                            </option>

                        <?php endforeach; ?>
                    </optgroup>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="col-md-6">
            <button type="button" class="btn btn-default" onclick="addformPage()"><i
                        class="glyphicon glyphicon-file"></i>&nbsp;<?= $this->translate("Ajouter la page") ?>
            </button>
            &nbsp;<?= $this->translate("ou") ?>&nbsp;
            <button type="button" class="btn btn-default" onclick="addformFolder()"><i
                        class="glyphicon glyphicon-folder-open"></i>&nbsp;<?= $this->translate("Ajouter un dossier") ?>
            </button>
        </div>
    </div>
</div>

<?php //Liste des pages ?>
<form action="<?= $this->url(['controller' => 'website', 'action' => 'menu']) ?>" enctype="multipart/form-data" method="post" class="form-horizontal">
    <table class="table table-hover" id="tableHeader">
        <thead>
        <tr>
            <th width="30px"></th>
            <th width="70px"><?= $this->translate("Actions") ?></th>
            <th><?= $this->translate("Pages") ?></th>
        </tr>
        </thead>
    </table>
    <ul class="sortable">
        <?php foreach ($this->order as $key => $value) {
            $this->i = $key;
            if (!isset($this->pages[$key])) {
                continue;
            }
            $this->page = $this->pages[$key];
            ?>
            <li id="page_<?= $this->i ?>" class="<?= $this->page->isFolder() ? '' : 'no-nest' ?>">
                <?php include __DIR__ . "/menu-page.phtml";
                if (is_array($value) && count($value) > 0) {
                    ?>
                    <ul>
                        <?php foreach ($value as $k => $svalue) {
                            $this->i = $k;
                            if (!isset($this->pages[$k])) {
                                continue;
                            }
                            $this->page = $this->pages[$k];
                            ?>
                            <li id="page_<?= $this->i ?>"
                                class="<?= $this->page->isFolder() ? '' : 'no-nest' ?>">
                                <?php include __DIR__ . "/menu-page.phtml";
                                if (is_array($svalue) && count($svalue) > 0) {
                                    ?>
                                    <ul>
                                        <?php foreach ($svalue as $sk => $ssvalue) {
                                            $this->i = $sk;
                                            if (!isset($this->pages[$sk])) {
                                                continue;
                                            }
                                            $this->page = $this->pages[$sk];
                                            ?>
                                            <li id="page_<?= $this->i; ?>" class="no-nest">
                                                <?php include __DIR__ . "/menu-page.phtml"; ?>
                                            </li>
                                        <?php } ?>
                                    </ul>
                                <?php } ?>
                            </li>
                        <?php } ?>
                    </ul>
                <?php } ?>
            </li>
        <?php } ?>
    </ul>

    <div id="clone" style="display:none;">
        <li class="">
            <div>
                <table width="100%">
                    <tr>
                        <td width="20px"><i class="glyphicon glyphicon-move"></i></td>
                        <td class="page-content"></td>
                        <td width="70px">
                            <div class="pull-right">
                                <a class="btn btn-danger btn-xs" href="javascript:void(0)" onclick="$(this).closest('li').remove();"
                                   title="<?= $this->translate("Supprimer") ?>"><i
                                            class="glyphicon glyphicon-trash"></i></a>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </li>
    </div>

    <div class="form-actions text-center">
        <a href="<?= $this->url(['controller' => 'website', 'action' => 'reset'])?>">
            <button type="button" class="btn btn-default btn-sm"><?= $this->translate('Annuler') ?></button>
        </a>
        <button type="submit" class="btn btn-primary"><?= $this->translate('Enregistrer') ?></button>
    </div>

</form>

<?= $this->confirm("Suppression de la page", "Souhaitez-vous supprimer la page ?")
    ->setTrigger('.remove-page')
    ->setJsInit('$("#confirm-id").val($(this).closest("li").find("input[type=hidden]").val());')
    ->setJsCallback('deletePage();') ?>


<script>

    $(document).ready(function () {
        //Tri des pages
        $('ul.sortable').nestedSortable({
            disableNesting: 'no-nest',
            listType: 'ul',
            handle: '.glyphicon-move',
            items: 'li',
            maxLevels: 3,
            opacity: .6,
            placeholder: 'placeholder',
            stop: function (event, ui) {
                $.ajax({
                    url: JS_PREFIX_URL + 'website/ajaxorder',
                    type: 'post',
                    data: $('ul.sortable').nestedSortable('serialize')
                });
            }
        });

        //Edition des informations sur une page
        $('.editPage').click(function () {
            $(this).parents('tr').find('.div-plus').toggle('slow');
        });

        //Création du permalien
        $('.permalien-src').focus(function () {
            createPermalien($(this));
        });
        $('.permalien').blur(function () {
            $(this).val(permalink($(this).val()));
        });
    });

    function addformPage() {
        formNewPage($('#type').val());
    }

    function addformFolder() {
        formNewPage('folder');
    }

    function formNewPage(type) {
        $.ajax({
            url: JS_PREFIX_URL + "website/ajaxformpage",
            type: 'post',
            data: {'type': type},
            success: function (result) {
                if (result != '') {
                    var clone = $('#clone>li').clone();
                    $('.page-content', clone).html(result);
                    $(clone).attr('id', 'page_' + $('input[type="hidden"]', clone).val());
                    if (type != 'folder') {
                        $(clone).attr('class', 'no-nest');
                    }
                    $('.permalien-src', clone).blur(function () {
                        createPermalien($(this));
                    });
                    $('.permalien', clone).blur(function () {
                        $(this).val(permalink($(this).val()));
                    });


                    $('ul.sortable').append(clone);
                    jQuery('html,body').animate({scrollTop: jQuery("#page_" + $('input[type="hidden"]', clone).val()).offset().top}, 1000, 'swing');
                }
            }
        });
    }

    function deletePage() {
        $.ajax({
            url: JS_PREFIX_URL + "website/ajaxrmpage",
            type: 'post',
            data: {'idx': $('#confirm-id').val()},
            success: function (result) {
                $('#type option[type="' + $('#pages_' + $('#pageDelete').val() + '-type').attr('class') + '"]').removeAttr('disabled');
                $('#page_' + $('#confirm-id').val()).remove();
                $('#modalDelete').modal('hide');
            }
        });
    }

    function createPermalien(elem) {
        var permalien = $(elem).closest('li').find('.permalien');
        if ($(permalien).val() == '') {
            $(permalien).val(permalink($(elem).val()));
        }
    }

</script>
