<?php $this->layout()->description = $this->translate("Ajout / modifications d'actualités pour le site") ?>

<div class="form-actions">
    <button type="button" class="btn btn-default add-news"><span
                class="glyphicon glyphicon-plus"></span>&nbsp;<?php echo $this->translate("Ajouter une actualité") ?>
    </button>
</div>

<div class="table-responsive">
    <table class="table table-hover table-striped table-condensed" id="news-list">
        <thead>
        <tr>
            <th><?php echo $this->translate('Statut') ?></th>
            <th><?php echo $this->translate('Titre') ?></th>
            <th><?php echo $this->translate('Contenu') ?></th>
            <th><?php echo $this->translate('Actions') ?></th>
        </tr>
        </thead>


        <tbody>
        <?php if (is_array($this->errors)) {
            $this->form->populate($this->errors);
            $display = '';
        } else {
            $display = 'display:none;';
        } ?>
        <tr style="<?php echo $display ?>" class="form-add-news">
            <td colspan="4">
                <?php echo $this->form; ?>
            </td>
        </tr>
        <?php foreach ($this->news as $news) { ?>
            <tr class="news-<?php echo $news['NEWSID'] ?>">
                <td>
                    <?php
                    if ($news['ONLINE'] != 0) {
                        $class = 'label-success';
                        $text = $this->translate('En ligne');
                    } else {
                        $class = '';
                        $text = $this->translate('Invisible');
                    }
                    ?>
                    <span class="label <?php echo $class ?>"><?php echo $text; ?></span>
                </td>
                <td><b><?php echo $this->translate($news['TITLE']); ?></b><br/>
                    <small><?php echo $this->translate($news['DATE_POST']); ?></small>
                </td>
                <td>

                    <?php try {
                        if (Zend_Registry::get('Zend_Translate')->istranslated($news['CONTENT'])): ?>
                            <div class="content">
                                <div class="truncate"><?php echo $this->truncate($this->translate($news['CONTENT']))->withPostfix('&#0133; <a href="javascript:void(0);" class="more"><span class="glyphicon glyphicon-plus-sign"></span></a>'); ?></div>
                                <div class="complete"
                                     style="display:none;"><?php echo $this->translate($news['CONTENT']); ?></div>
                            </div>
                        <?php endif;
                    } catch (Zend_Exception $e) {
                        trigger_error($e->getMessage());
                    } ?>
                </td>
                <td style="text-align:right;">

                    <a href="javascript:void(0)" class="btn btn-default btn-xs edit-news"
                       title="<?php echo $this->translate("Modifier"); ?>"
                       data-newsid="<?php echo $this->escape($news['NEWSID']) ?>"><span
                                class="glyphicon glyphicon-pencil"></span>&nbsp;<?php echo $this->translate("Modifier"); ?>
                    </a>

                    &nbsp;

                    <a href="javascript:void(0)" class="btn btn-danger btn-xs remove-news"
                       title="<?php echo $this->translate("Supprimer"); ?>"
                       data-newsid="<?php echo $this->escape($news['NEWSID']) ?>"><span
                                class="glyphicon glyphicon-trash"></span>&nbsp;<?php echo $this->translate("Supprimer"); ?>
                    </a>
                </td>
            </tr>
        <?php } ?>
        </tbody>
        <tfoot style="display:none;">
        <tr>
            <td colspan="4">
            </td>
        </tr>
        </tfoot>
    </table>
</div>

<?php echo $this->confirm("Suppression de l'actualité", "Souhaitez-vous supprimer l'actualité ?")
    ->setTrigger('.remove-news')
    ->setJsInit('$("#confirm-id").val($(this).attr("data-newsid"));')
    ->setJsCallback('deleteNews();'); ?>

<script>
    $(document).ready(function () {
        $('a.more').click(function () {
            $(this).closest('div.content').find('.truncate').hide();
            $(this).closest('div.content').find('.complete').toggle();
        });
        //Ajout d'une nouvelle actu
        $('.add-news').click(function () {
            $('.form-add-news').show();
        });
        //Récupération du formulaire rempli
        $('.edit-news').click(function () {
            newsid = $(this).attr('data-newsid');
            $.ajax({
                url: JS_PREFIX_URL + "website/ajaxnewsform",
                type: 'post',
                data: {'newsid': newsid},
                success: function (result) {
                    if (result != '') {
                        $('#news-list tfoot td').html(result);
                        $('.news-' + newsid).replaceWith($('#news-list tfoot').html());
                    }
                }
            });
        });
    });

    function deleteNews() {
        $.ajax({
            url: JS_PREFIX_URL + "website/ajaxnewsdelete",
            type: 'post',
            data: {'newsid': $('#confirm-id').val()},
            success: function (result) {
                $('.news-' + $('#confirm-id').val()).remove();
                $('#confirmModal').modal('hide');
            }
        });
    }
</script>