<div class="es-block-focus es-block-focus-red fixed">
    <h4 class="text-danger" style="margin-bottom: 20px"><?php echo $this->translate($this->message) ?></h4>
    <?php if (isset($this->description)) : ?>
        <p><?php echo $this->translate($this->description); ?></p>
    <?php endif; ?>
    <?php if (isset($this->exception)) : ?>
        <p><?php echo $this->translate($this->exception->getMessage()); ?></p>
    <?php endif; ?>
</div>


<?php if (isset($this->sql)) { ?>
    <h2><?php echo $this->translate('Erreur SQL') ?> : </h2>
    <pre><?php echo $this->sql ?></pre>
<?php } ?>

<?php if (isset($this->exception)) { ?>
    <h2>Stack trace:</h2>
    <pre><?php echo $this->exception->getTraceAsString() ?></pre>

    <h2>Request Parameters:</h2>
    <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?></pre>
<?php } ?>
