<p>
    <strong><?= $this->translate('Demande de modification :') ?></strong>
    (<?= $this->Date($this->comment['when'], null, Zend_Date::DATE_LONG . ' - ' . Zend_Date::TIME_SHORT) ?>)
</p>

<?= $this->form ?>

<script>
    $.getScript('/js/paper/answerrequest.js?_=v<?= APPLICATION_VERSION ?>').fail(function (xhr, status, error) {
        console.log('loading failed:' + error);
    });


    $.getScript('/js/common/visualDeleteFile.js?_=v<?= APPLICATION_VERSION ?>').fail(function (xhr, status, error) {
        console.log('loading failed:' + error);
    });
</script>
