<?php
/** @var Episciences_Paper $paper */
$paper = $this->paper;

if ($paper->ignoreLicenseCheck()) {
    return;
}

$icon = 'fa-bell';

if (!$paper->getLicence()) {
    $title = 'Licence manquante';
    $message = 'Merci de préciser la licence pour cette publication avant sa mise en ligne.';
} else {
    $title = 'Licence non reconnue';
    $message = 'La licence choisie ne correspond pas à la licence choisie par la revue.';
}


?>
<div class="info-license-box" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="info-icon" aria-hidden="true">
        <span class="fa-regular <?= $this->escape($icon) ?> fa-shake fa-sm"></span>
    </div>

    <div class="info-content">
        <h4><?= $this->escape($this->translate($title)) ?></h4>
        <p>
            <?= $this->escape($this->translate($message)) ?>
        </p>
    </div>
</div>