<?php
/** @var Episciences_Paper $paper */
$paper = $this->paper;

if ($paper->ignoreLicenseCheck()) {
    return;
}

if (!$paper->getLicence()) {
    $message = 'Merci de préciser la licence pour cette publication avant sa mise en ligne.';

} else {
    $message = 'La licence choisie ne correspond pas à la licence choisie par la revue.';
}


?>
<div class="info-license-box">
    <div class="info-icon">
        <span class="fa-regular fa-bell fa-shake fa-sm"></span>
    </div>

    <div class="info-content">
        <h4><?= $this->translate('Information importante') ?></h4>
        <p>
            <?= $this->translate($message) ?>
        </p>
    </div>
</div>