<?php
/** @var Episciences_Paper $paper */
$paper = $this->paper;
$licence = $paper->getLicence();
?>
<div class="small">
    <?= $this->escape($this->translate('Licence : ')) ?>
    <a rel="noopener" target="_blank" id="paper-license-link" href="<?= $this->escape($licence) ?>">
        <?= $this->escape(Ccsd_Tools::translateLicense($licence)) ?>
    </a>

    <button class="btn btn-default btn-xs popover-link edit-license" style="margin-left: 5px"
            onclick="getLicensesForm(this, <?= (int)$paper->getDocid() ?>)">
        <span class="fa-solid fa-pen-to-square" style="margin-right: 5px"></span>
        <?= $this->escape($this->translate('Modifier')) ?>
    </button>
</div>
