<?php $graphAbs = $this->escape($this->paper->getGraphical_abstract($this->paper->getDocId())) ?>
<div class="panel panel-default collapsable">
    <div class="panel-heading">
        <h2 class="panel-title"><?= $this->translate('Graphical Abstract') ?></h2>
    </div>
    <div class="panel-body <?= ($graphAbs !== "") ? 'in' : '' ?>">
        <form id="f-graph-abs">
            <div style="max-height:480px;overflow: auto;">
                <?php if ($graphAbs !== "") : ?>
                    <img alt="graphical abstract"
                         style="max-width: 100%;max-height: 100%; object-fit: contain; overflow: scroll"
                         src="/public/documents/<?= $this->paper->getDocId() ?>/<?= $graphAbs ?>">
                <?php endif; ?>
            </div>
            <?php if (Episciences_Auth::isAllowedToManagePaper() || Episciences_Auth::isAuthor()) : ?>
                <div style="display: inline-block; margin-top: 10px;">
                    <div>
                        <input name="paper_docId" class="hidden" id="paper_docId"
                               value="<?= $this->paper->getDocid() ?>">
                        <input name="paper_id" class="hidden" id="paper_id" value="<?= $this->paper->getPaperid() ?>">
                        <input type="file" name="upload-gabs" id="upload-gabs" class="hidden" accept="image/*"/>
                        <label class="btn btn-default btn-sm" for="upload-gabs">
                            <i class="fa-solid fa-chart-area"
                               style="margin-right: 5px"></i><?php echo ($graphAbs !== "") ? $this->translate("Modifier l'abstract graphique") : $this->translate("Ajouter un abstract graphique") ?>
                        </label>
                        <span id="file-chosen"></span>
                        <button id="btn-cancel-graph" type="button"
                                class="btn btn-default"><?= $this->translate('Annuler') ?></button>
                        <input type="submit" class="btn btn-primary" id="i-graph-abs" value="<?= $this->translate('Envoyer')?>">
                        <?php if ($graphAbs !== "") : ?>
                            <button class="btn btn-danger btn-xs" type="button" id="b-graph-abs-delete"
                                    data-img="<?= $graphAbs ?>">
                                <i class="fa-solid fa-trash-can"></i>
                            </button>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="help-block" style="margin:4px;">
                        <span>
                                <?= $this->translate('Poids maximum du fichier : 100 ko, Hauteur maximale : 880px') ?>
                        </span>
                </div>
            <?php endif; ?>
        </form>
    </div>
</div>
<?php $this->jQuery()->addJavascriptFile('/js/paper/graphicalAbstract.js'); ?>