<?php
/** @var Episciences_Paper $paper */
$paper = $this->paper;
$action = 'oafiles';
$files = $paper->getFiles();
?>
<?php if ($paper->hasHook && $files): ?>
    <div class="panel panel-default collapsable" id="paper-files">
        <div class="panel-heading">
            <h2 class="panel-title"><?= $this->translate('Fichiers') ?>
                <!-- small class=""> ()</small-->
            </h2>
        </div>
        <div class="panel-body in">
            <table class="table table-striped">
                <thead>
                <tr class="">
                    <th> <?= $this->translate('Nom') ?></th>
                    <?php if (array_filter($files, fn($f) => $f->getFileSize() > 0)): ?>
                    <th> <?= $this->translate('Taille') ?></th>
                    <?php endif; ?>
                </tr>
                </thead>
                <tbody>
                <?php /** @var  Episciences_Paper_File $oFile */ ?>
                <?php foreach ($files as $oFile) : ?>
                    <tr>
                        <td>
                            <a href="<?= $oFile->getSelfLink() ?>" target="_blank"><?= $oFile->getName() ?></a>
                            <?php if ($oFile->getChecksum() !== ''): ?>
                            <br/>
                            <small class="label label-default"> <?= $oFile->getChecksumType() ?><?= $this->translate(' :') . ' ' ?><?= $oFile->getChecksum() ?>
                            </small>
                            <?php endif; ?>
                        </td>
                        <?php if (array_filter($files, fn($f) => $f->getFileSize() > 0)): ?>
                        <td> <?= Episciences_Tools::toHumanReadable($oFile->getFileSize()) ?></td>
                        <?php endif; ?>
                        <td>
                    <span class="pull-right">
                        <a class="btn btn-xs btn-default" href="<?= $oFile->getDownloadLike() ?>" data-toggle="tooltip" title="<?= $this->translate('Télécharger le fichier') ?>">
                           <i class="fas fa-file-download"></i>
                        </a>
                    </span>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
<?php endif; ?>