<?php if ($this->hasHook): ?>
    <div class="panel panel-default collapsable" id="paper-files">
        <div class="panel-heading">
            <h2 class="panel-title"><?= $this->translate('Fichiers') ?>
                <!-- small class=""> ()</small-->
            </h2>
        </div>
        <div class="panel-body in">
            <table class="table table-striped">
                <thead>
                <tr class="">
                    <th> <?= $this->translate('Nom') ?></th>
                    <th> <?= $this->translate('Taille') ?></th>
                </tr>
                </thead>
                <tbody>
                <?php /** @var  Episciences_Paper_File $oFile */ ?>
                <?php foreach ($this->oPaperFiles as $oFile) : ?>
                    <tr>
                        <td>
                            <a class="" href="<?= $oFile->getSelfLink() ?>"><?= $oFile->getFileName() ?></a>
                            <br/>
                            <small class=""> <?= $oFile->getChecksumType() ?>:<?= $oFile->getChecksum() ?>
                                <i class="fa fa-question-circle text-muted" data-toggle="tooltip" data-placement="top"
                                   title=<?= $this->translate("Il s'agit de l'empreinte du fichier (somme de contrôle MD5), qui peut être utilisée pour vérifier l'intégrité du fichier.") ?>></i>
                            </small>
                        </td>
                        <td> <?= Episciences_Tools::toHumanReadable($oFile->getFileSize()) ?></td>
                        <td>
                    <span class="pull-right">
                        <a class="btn btn-xs btn-default" href="<?= $oFile->getSelfLink() ?>">
                            <i class="fa fa-download"></i> <?= $this->translate('Télécharger') ?>
                        </a>
                    </span>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
<?php endif; ?>