<?php $metadatas = $this->metadatas;
$keepUniqueIdentifier = [];
$originalInfo = $this->originalInfo;
?>
<div>
    <?php if ( (array_key_exists('creators', $metadatas)) && (is_array($metadatas['creators']))) : ?>
    <i><?= $metadatas['title'] ?></i>
    <?php foreach ($metadatas['creators'] as $key => $metadata) : ?>
        <?php if (!empty($metadata['identifiers'])): ?>
            <p>
                <?php foreach ($metadatas['creators'] as $cIndex => $creatorInfo) : ?>
                    <?= $creatorInfo['name'] ?>
                    <?php if (!empty($creatorInfo['identifiers'])): ?>
                        <?php foreach ($creatorInfo['identifiers'] as $cId => $creatorIdentifier) : ?>
                            <?php if ($creatorIdentifier['schema'] === 'ORCID'): ?>
                                <a rel="noopener" href="<?= "https://orcid.org/" . $creatorIdentifier['identifier'] ?>"
                                   data-toggle="tooltip" data-placement="bottom"
                                   data-original-title="<?= $creatorIdentifier['identifier'] ?>" target="_blank">
                                    <img srcset="/img/orcid_id.svg" src="/img/ORCID-iD.png" height="16px" alt="ORCID"/>
                                </a>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <?php if ($cIndex !== array_key_last($metadatas['creators'])) {
                        echo ';';
                    } ?>
                <?php endforeach; ?>
            </p>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
<?php endif; ?>

<?php if (array_key_exists('identifiers', $metadatas)) : ?>
    <div>
        <ul class="list-unstyled">
            <?php if (isset($originalInfo['value'])): ?>
                    <a href="<?= $originalInfo['link'] ?>"><?= $originalInfo['value'] ?></a>&nbsp;<sup><?= $originalInfo['sourceToSup'] ?></sup>
                    <?php $keepUniqueIdentifier[] = $originalInfo['value']; ?>
            <?php endif; ?>
            <?php foreach ($metadatas['identifiers'] as $key => $metadata) : ?>
                <li><?php if (!in_array($metadata['identifier'], $keepUniqueIdentifier, true)): ?>
                        <?php if ($metadata['schema'] === 'doi'): ?>
                            <a href="<?= Episciences_Paper_DatasetsManager::URL_DOI . $metadata['identifier'] ?>"><?= $metadata['identifier'] ?></a>
                        <?php else: ?>
                            <?= $metadata['identifier'] ?>
                        <?php endif; ?>
                        <?php $keepUniqueIdentifier[] = $metadata['identifier'] ?>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
