<?php

/** @var Episciences_Paper $paper */
$paper = $this->paper;
$metadata = $this->metadata;
$status = $paper->getStatus();
$isSecretary = Episciences_Auth::isSecretary();
$loggedUid = Episciences_Auth::getUid();
$isAllowedToSeeNoPublicDetails = $this->isAllowedToSeeNoPublicDetails;
$isAllowedToAnswerNewVersion = $this->isAllowedToAnswerNewVersion;


$language = $paper->getMetadata('language') ?? 'en';

if ($paper->isPublished()) {
    $this->headLink(['rel' => 'schema.DC', 'href' => 'http://purl.org/dc/elements/1.1/']);
    $headMeta = Episciences_PapersManager::headMetaData($paper);
    foreach ($headMeta['citation'] as $citationKey => $citationMeta) {
        switch ($citationKey) {
            case "volume":
            case "doi":
            case "abstract":
                if ($citationMeta) {
                    $this->headMeta()->appendName('citation_'.$citationKey, $citationMeta);
                }
                break;
            case "author":
                foreach ($citationMeta as $authors) {
                    $this->headMeta()->appendName('citation_author', $authors['citation_author']);
                    if (array_key_exists('citation_author_institution', $authors)) {
                        foreach ($authors['citation_author_institution'] as $affiliation) {
                            $this->headMeta()->appendName('citation_author_institution', $affiliation);
                        }
                    }
                    if (array_key_exists('citation_author_orcid', $authors)) {
                        $this->headMeta()->appendName('citation_author_orcid', $authors['citation_author_orcid']);
                    }
                }
                break;
            case "keywords":
                foreach ($citationMeta as $meta) {
                    $this->headMeta()->appendName("citation_". $citationKey, $meta);
                }
                break;
            case "publication_date":
                if ($citationMeta) {
                    $date = $this->Date($paper->getPublication_date(), $language, Zend_Date::YEAR . '-' . Zend_Date::MONTH . '-' . Zend_Date::DAY);
                    $this->headMeta()->appendName('citation_' . $citationKey, $date);
                }
                break;
            case "issue":
                if ($citationMeta !== "") {
                    $this->headMeta()->appendName('citation_'.$citationKey, $citationMeta);
                }
                break;
            case "issn":
                foreach ($citationMeta as $meta) {
                    if ($meta !== "") {
                        $this->headMeta()->appendName("citation_" . $citationKey, $this->FormatIssn($meta));
                    }
                }
                break;
            case "fundings":
                if (!empty($citationMeta)) {
                    foreach ($citationMeta as $project) {
                        if ($project['funderName'] !== 'unidentified') {
                            $strFunding = "citation_funder=".$project['funderName'].";";
                            if ($project['code'] !== 'unidentified'){
                                $strFunding .= " citation_grant_number=".$project['code'].";";
                            }
                            $this->headMeta()->appendName('citation_funder_source', $strFunding);
                        }
                    }
                }
                break;
            default :
                $this->headMeta()->appendName('citation_' . $citationKey, $citationMeta);
                break;
        }
    }
    foreach ($headMeta['dc'] as $dcKey => $dcMeta) {
        switch ($dcKey) {
            case "creator":
                foreach ($dcMeta as $author) {
                    $this->headMeta()->appendName('DC.'.$dcKey, $author['citation_author']);
                }
            break;
            case "date":
                if ($dcMeta) {
                    $date = $this->Date($paper->getPublication_date(), $language, Zend_Date::YEAR . '-' . Zend_Date::MONTH . '-' . Zend_Date::DAY);
                    $this->headMeta()->appendName('DC.' . $dcKey, $date);
                }
                break;
            case "abstract":
                if ($dcMeta) {
                    $this->headMeta()->appendName('DC.description', $dcMeta);
                }
                break;
            case "keywords":
                foreach ($dcMeta as $meta) {
                    $this->headMeta()->appendName('DC.subject', $meta);
                }
                break;
            case "volume":
                if ($dcMeta !== '') {
                    $this->headMeta()->appendName('DC.citation.volume', $dcMeta);
                }
                break;
            case "identifier":
                foreach ($dcMeta as $key => $meta) {
                    if (($key === 'doi') && !empty($meta)) {
                        $this->headMeta()->appendName('DC.identifier', $meta);
                        continue;
                    }
                    $this->headMeta()->appendName('DC.identifier', $meta);
                }
                break;
            case "relation":
                $this->headMeta()->appendName("DC.relation.ispartof", $dcMeta);
                break;
            default :
                $this->headMeta()->appendName('DC.' . $dcKey, $dcMeta);
                break;
        }
    }
    foreach ($headMeta['og'] as $ogKey => $ogMeta) {
        switch ($ogKey) {
            case 'url':
                foreach ($ogMeta as $key => $meta) {
                    $this->headMeta()->appendProperty('og:' . $ogKey, $meta);
                }
                break;
            case 'description':
                if ($ogMeta) {
                    $this->headMeta()->appendProperty('og:' . $ogKey, $ogMeta);
                }
                break;
            default:
                $this->headMeta()->appendProperty('og:' . $ogKey, $ogMeta);
        }
    }
    foreach ($headMeta['header'] as $hKey => $headerMeta) {
        switch ($hKey) {
            case 'description':
                if ($hKey) {
                    $this->headMeta()->appendName($hKey, $headerMeta);
                }
                break;
            case "keywords":
                foreach ($headerMeta as $meta) {
                    $this->headMeta()->appendName($hKey, $meta);
                }
                break;
            default:
                $this->headMeta()->appendName($hKey, $headerMeta);
        }
    }

}
?>


<?php
$this->headTitle("#" . $paper->getDocid() . ' - ' . $paper->getTitle($language, true));
$this->jQuery()->addJavascriptFile('/js/paper/view.js');

?>

<?php if ($this->isAllowedToBackToAdminPage): ?>
    <?= $this->partial('partials/paper_controller_link_switch.phtml', ['paper' => $paper]) ?>
<?php endif; ?>

<?php // obsolete paper notice ****************************************************** ?>
<?php if ($paper->isObsolete()) : ?>
    <?php if ($paper->isObsolete()) : ?>
        <?= $this->partial('partials/old_version.phtml', ['url' => $this->linkToLatestDocId]) ?>
    <?php endif; ?>
<?php endif; ?>

<?php // paper ************************************************************************* ?>
<div>
    <?= $paper->getXslt() ?>
    <?= $this->partial('paper/paper_files.phtml', ['paper' => $paper]) ?>
    <?= $this->partial('paper/paper_datasets.phtml', ['paper' => $paper, 'metadata' => $metadata]) ?>
    <?= $this->partial('partials/paper_password_form.phtml', ['paper' => $paper, 'displayPaperPasswordBloc' => $this->displayPaperPasswordBloc, 'paperPassword' => $this->paperPassword]) ?>

</div>

<?php if ($isAllowedToSeeNoPublicDetails): ?>

    <?php // paper status ?>
    <div class="panel panel-default collapsable">
        <div class="panel-heading">
            <h2 class="panel-title"><?= $this->translate("Statut de l'article") ?></h2>
        </div>
        <div class="panel-body in">
            <?php $statusMsg = $this->translate('Statut actuel') . $this->translate(' :') . ' '; ?>
            <p>
                <strong><?= $statusMsg ?></strong>
                <span class="label label-status-<?= $status ?>"><?= ucfirst($this->translate(Episciences_PapersManager::getStatusLabel($status))) ?></span>
                <?= $this->partial('partials/paper-revision-deadline.phtml', ['revisionDeadline' => $this->revisionDeadline]) ?>
            </p>
        </div>
    </div>

    <?php // préparation de copie?>

    <?php if ($this->copyEditingDemands && !$paper->isPublished()) : ?>
        <div id="copy-editing" class="panel panel-default collapsable">
            <div class="panel-heading">
                <h2 class="panel-title"><?= $this->translate('Préparation de copie') ?></h2>
            </div>
            <div class="panel-body in" style="overflow: visible">
                <?= $this->partial('partials/paper_copy_editing.phtml', [
                        'copyEditingDemands' => $this->copyEditingDemands,
                        'copyEditingReplyForms' => $this->copyEditingReplyForms,
                        'paperStatus' => $status,
                        'latestDocId' => $this->latestDocId,
                        'linkToLatestDocId' => $this->linkToLatestDocId,
                        'isFromZSubmit' => $this->isFromZSubmit,
                        'zSubmitUrl' => $this->zSubmitUrl
                    ]
                ) ?>
            </div>
        </div>
    <?php endif; ?>

    <?php // versions *****************************************************
    if (
        Episciences_Auth::isLogged() &&
        (
            array_key_exists($loggedUid, $paper->getReviewers()) || // nor reviewer
            $paper->getUid() === $loggedUid
        )
    ) {
        echo $this->partial('partials/paper_versions.phtml', ['paper' => $paper, 'versions' => $this->versions]);
    }
    ?>

    <?php // rating reports ************************************************************************* ?>
    <?php if ($this->reports) : ?>
        <div id="ratings" class="panel panel-default collapsable">
            <div class="panel-heading">
                <h2 class="panel-title"><?= $this->translate('Evaluations') ?></h2>
            </div>
            <div class="panel-body in" style="max-height: 350px; overflow: auto;">
                <?= $this->partial('partials/paper_reports.phtml', ['paper' => $paper, 'reports' => $this->reports, 'isAllowedToSeeReportDetails' => $this->isAllowedToSeeReportDetails]) ?>
            </div>
        </div>
    <?php endif; ?>

    <?php // author's comments and cover letter ************************************************************************* ?>
    <?php if ($this->author_comments && !$paper->isPublished()) : ?>
        <?php // Author comments  *****************************************?>
        <?= $this->render('partials/paper_author_comments_bloc.phtml') ?>
    <?php endif; ?>

    <?php // reviewer comments ************************************** ?>
    <?php if ($this->comments && !$paper->isPublished()) : ?>
        <div id="comments" class="panel panel-default collapsable">
            <div class="panel-heading">
                <h2 class="panel-title"><?= $this->translate('Commentaires des relecteurs') ?></h2>
            </div>
            <div class="panel-body in" style="max-height: 350px; overflow: auto;">
                <?= $this->partial('partials/paper_reviewer_comments.phtml', ['comments' => $this->comments, 'replyForms' => $this->replyForms, 'paperContributorUid' => $this->paper->getUid()]) ?>
            </div>
        </div>
    <?php endif; ?>

    <?php // revision requests ***************************************************** ?>
    <?php if ($isAllowedToAnswerNewVersion && ($this->revision_requests || $this->currentDemand || $this->previousVersionsDemands) && !$paper->isPublished()) : ?>
        <div id="answer" class="panel panel-default collapsable">
            <div class="panel-heading">
                <h2 class="panel-title"><?= $this->translate('Demandes de modifications') ?></h2>
            </div>
            <div class="panel-body in" style="overflow: visible">
                <?= $this->partial('partials/answer_revision_request_form.phtml', [
                    'paper' => $paper,
                    'review' => $this->review,
                    'current_demand' => $this->currentDemand,
                    'zIdentifier' => $this->zIdentifier
                ])
                ?>

                <?= !empty($this->currentDemand) ? '<hr>' : '' ?>

                <?= $this->partial('partials/paper_demands.phtml', [
                    'paper' => $paper,
                    'review' => $this->review,
                    'current_demand' => $this->currentDemand,
                    'previous_demands' => $this->revision_requests,
                    'previousVersions' => $this->previousVersions,
                    'previousVersionsDemands' => $this->previousVersionsDemands
                ])
                ?>
            </div>

        </div>
    <?php endif; ?>

<?php endif; // end if $isAllowedToSeeNoPublicDetails ?>

<?php // Citations *****************************************************
if ($this->citations !== '') {
    echo $this->partial('partials/paper_citations.phtml', ['citations' => $this->citations, 'counterCitations' => $this->counterCitations]);
}
?>

<?php // export options ***************************************************** ?>
<?php if ($paper->isPublished()) : ?>
    <div class="panel panel-default collapsable">
        <div class="panel-heading">
            <h2 class="panel-title"><?= $this->translate('Exporter') ?></h2>
        </div>
        <div class="panel-body in" style="overflow: visible">
            <a class="btn btn-default btn-sm" target="_blank"
               href="<?= $this->url(['id' => $paper->getDocid()], 'bibtex') ?>">
                BibTeX
            </a>
            <a class="btn btn-default btn-sm" target="_blank"
               href="<?= $this->url(['id' => $paper->getDocid()], 'tei') ?>">
                <abbr title="Text Encoding Initiative">TEI</abbr>
            </a>
            <a class="btn btn-default btn-sm" target="_blank"
               href="<?= $this->url(['id' => $paper->getDocid()], 'dc') ?>">
                <abbr title="Dublin Core">DC</abbr>
            </a>
            <a class="btn btn-default btn-sm" target="_blank"
               href="<?= $this->url(['id' => $paper->getDocid()], 'datacite') ?>">OpenAIRE</a>
            <a class="btn btn-default btn-sm" target="_blank"
               href="<?= $this->url(['id' => $paper->getDocid()], 'crossref') ?>">Crossref</a>
            <a class="btn btn-default btn-sm" target="_blank"
               href="<?= $this->url(['id' => $paper->getDocid()], 'doaj') ?>">DOAJ</a>
            <a class="btn btn-default btn-sm" target="_blank"
               href="<?= $this->url(['id' => $paper->getDocid()], 'zbjats') ?>">zbJATS</a>
            <a class="btn btn-default btn-sm" target="_blank"
               href="<?= $this->url(['id' => $paper->getDocid()], 'json') ?>">JSON</a>
        </div>
    </div>
<?php endif; ?>

<?php // share options ***************************************************** ?>
<?php if ($paper->isPublished()) : ?>
    <div class="panel panel-default collapsable">
        <div class="panel-heading">
            <h2 class="panel-title"><?= $this->translate('Partager') ?></h2>
        </div>
        <div class="panel-body in" style="overflow: visible">
            <!-- AddToAny BEGIN -->
            <div class="a2a_kit a2a_kit_size_32 a2a_default_style">
                <a class="a2a_dd" href="https://www.addtoany.com/share"></a>
                <a class="a2a_button_twitter"></a>
                <a class="a2a_button_facebook"></a>
                <a class="a2a_button_email"></a>
                <a class="a2a_button_reddit"></a>
                <a class="a2a_button_mendeley"></a>
                <a class="a2a_button_citeulike"></a>
                <a class="a2a_button_evernote"></a>
                <a class="a2a_button_linkedin"></a>
            </div>
            <script>
                var a2a_config = a2a_config || {};
                a2a_config.num_services = 6;
            </script>
            <script async src="https://static.addtoany.com/menu/page.js"></script>
            <!-- AddToAny END -->
        </div>
    </div>
<?php endif; ?>


<?php if ($this->page_count || $this->file_count) : ?>
    <!-- stats -->
    <div id="stats" class="panel panel-default collapsable">
        <div class="panel-heading">
            <h2 class="panel-title"><?= $this->translate('Statistiques de consultation') ?></h2>
        </div>
        <div class="panel-body in">
            <?php if ($this->page_count) : ?>
                <div><?= $this->translate("Cette page a été consultée %s fois.", $this->page_count) ?></div>
            <?php endif; ?>
            <?php if ($this->file_count) : ?>
                <div><?= $this->translate("Le PDF de cet article a été téléchargé %s fois.", $this->file_count) ?></div>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>

<?php if ($this->isAllowedToBackToAdminPage): ?>
    <?= $this->partial('partials/paper_controller_link_switch.phtml', ['paper' => $paper]) ?>
<?php endif; ?>


<?php
// modal (for revision request answer forms)
$style = ['width' => '50%'];
echo $this->partial('partials/modal.phtml', ['style' => $style]);
?>

<?php
$this->jQuery()->addJavascriptFile(VENDOR_TINYMCE_JQUERY);
$this->jQuery()->addJavascriptFile(VENDOR_TINYMCE);
$this->jQuery()->addJavascriptFile(TINYMCE_DIR . "tinymce_patch.js");
$this->jQuery()->addJavascriptFile('/js/common/visualDeleteFile.js');
$this->jQuery()->addJavascriptFile('/js/paper/copy_editing_form.js');
$this->jQuery()->addJavascriptFile('/js/common/updateMetaData.js');
$this->jQuery()->addJavascriptFile('/js/user/affiliations.js');
$this->jQuery()->addJavascriptFile(VENDOR_JQUERY_FILE_UPLOAD);
?>
<script>
    let hasHook = <?= json_encode($this->hasHook) ?>;
    let isFromZSubmit = <?= $this->isFromZSubmit ?>;
    let zSubmitStatus = <?= json_encode($this->zSubmitStatus) ?>;
</script>
