<form data-library="ccsd" style="display: none" role="form"<?php
if ($this->element->getAttrib('name')) echo ' name="' . $this->element->getAttrib('name') . '"';
if ($this->element->getAttrib('id')) echo ' id="' . $this->element->getAttrib('id') . '"';
if ($this->element->getAttrib('class')) echo 'class="' . $this->element->getAttrib('class') . '"';
if ($this->element->getAction()) echo 'action="' . $this->element->getAction() . '"';
if ($this->element->getMethod()) echo 'method="' . $this->element->getMethod() . '"';
?>>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title"><?php echo $this->translate($this->name) ?></h2>
        </div>
        <div class="panel-body in">
            <?php
            foreach ($this->element->getElements() as $element) {
                echo $element;
            }
            ?>
        </div>
    </div>
</form>
