<?php $this->layout()->pageTitle = $this->translate("Invitation à la relecture d'un article");
$canLinkInvitation = isset($this->displayLinkedInvitationForm) && $this->displayLinkedInvitationForm;
$displayInvitationDetails = $this->displayInvitationDetails ?? false;
?>

<?php if ($this->errors) : ?>

    <?= $this->partial('partials/info-box.phtml', ['messages' => $this->errors]) ?>
    <?php if ($displayInvitationDetails): ?>
        <?= $this->render('reviewer/invitation_details.phtml') ?>
    <?php endif; ?>

    <div>

        <?php if ($canLinkInvitation) : ?>
            <?= $this->render('reviewer/linkInvitationForm.phtml') ?>
        <?php endif; ?>


        <?php if (!$canLinkInvitation) : ?>

            <?= $this->render('reviewer/reviewArticlesBtnLink.phtml') ?>

        <?php endif; ?>

    </div>

<?php else : ?>


    <p class="info-box"><?= $this->translate('Vous avez été invité à relire cet article : ') ?></p>

    <div>
        <?= $this->paper->getXslt() ?>
        <?= $this->partial('paper/paper_files.phtml', ['paper' => $this->paper]) ?>
        <?= $this->partial('paper/paper_datasets.phtml', ['paper' => $this->paper, 'metadata' => $this->metadata]) ?>
    </div>


    <?php // Author comments?>
    <?= $this->render('partials/paper_author_comments_bloc.phtml') ?>

    <?php // Invitation details ?>
    <?= $this->render('reviewer/invitation_details.phtml') ?>
    <?= $this->render('reviewer/invitation_response_form.phtml') ?>
<?php endif; // endif (errors) ?>
