<?php $this->layout()->pageTitle = $this->translate("Invitation à la relecture d'un article");
$canLinkInvitation = isset($this->displayLinkedInvitationForm) && $this->displayLinkedInvitationForm;
?>

<?php if ($this->errors) : ?>
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title"><span class="fa-solid fa-triangle-exclamation fa-beat"
                                          style="margin-right: 5px;"></span><?= $this->translate('Information') ?></h3>
        </div>
        <div class="panel-body">
            <?php foreach ($this->errors as $error) : ?>

                <h2><?= $this->translate($error) ?></h2>

                <?php if ($canLinkInvitation) : ?>
                    <?= $this->render('reviewer/linkInvitationForm.phtml') ?>
                <?php endif; ?>
            <?php endforeach; ?>

            <?php if (!$canLinkInvitation) : ?>

                <?= $this->render('reviewer/reviewArticlesBtnLink.phtml') ?>

            <?php endif; ?>

        </div>
    </div>
<?php else : ?>

    <?php if (!$this->invitation->hasExpired() && !$this->invitation->isAnswered()) : ?>
        <?php $this->jQuery()->addJavascriptFile("/js/reviewer/invitation.js"); ?>
    <?php endif; ?>

    <p><?= $this->translate('Vous avez été invité à relire cet article : '); ?></p>

    <div>
        <?= $this->paper->getXslt() ?>
        <?= $this->partial('paper/paper_files.phtml', ['paper' => $this->paper]) ?>
        <?= $this->partial('paper/paper_datasets.phtml', ['paper' => $this->paper, 'metadata' => $this->metadata]) ?>
    </div>


    <?php // Author comments?>
    <?= $this->render('partials/paper_author_comments_bloc.phtml'); ?>

    <div class="panel panel-default collapsable">
        <div class="panel-heading">
            <h2 class="panel-title"><?= $this->translate('Détails') ?></h2>
        </div>
        <div class="panel-body in">
            <?php if ($this->invitation->getSender() instanceof Episciences_User) : ?>
                <div>
                    <?= $this->translate("Invitation envoyée par :"); ?>
                    <?= $this->invitation->getSender()->getFullname(); ?>
                </div>
            <?php endif; ?>

            <div>
                <?= $this->translate("Date d'envoi de l'invitation :"); ?>
                <?= $this->Date($this->invitation->getSending_date()); ?>
            </div>
            <div>
                <?= $this->translate("Date d'expiration de l'invitation :"); ?>
                <?= $this->Date($this->invitation->getExpiration_date()); ?>
            </div>

            <br/>
            <div>
                <?= $this->translate("Relecture attendue avant le :"); ?>
                <?= $this->Date($this->rating_deadline); ?>
                <?php
                ?>
            </div>

            <?php if ($this->invitation->isAnswered()) : ?>
                <br/>
                <div class="red">
                    <?= $this->translate("Vous avez déjà répondu à cette invitation."); ?>
                </div>
                <br/>
                <div><?= $this->translate('Réponse envoyée le :') ?><?= $this->Date($this->invitation->getAnswer()->getAnswer_date()); ?></div>
                <div><?= $this->translate('Vous avez répondu :') ?><?= ucfirst($this->invitation->getAnswer()->getAnswer()); ?></div>
                <?php if ($this->invitation->getAnswer()->getDetail('comment')) : ?>
                    <div><?= $this->translate('Commentaire :') ?><?= $this->invitation->getAnswer()->getDetail('comment') ?></div>
                <?php endif; ?>
                <?php if ($this->invitation->getAnswer()->getDetail('reviewer_suggest')) : ?>
                    <div><?= $this->translate('Vous avez suggéré de proposer la relecture à :') ?><?= $this->invitation->getAnswer()->getDetail('reviewer_suggest') ?></div>
                <?php endif; ?>

            <?php elseif ($this->invitation->hasExpired() || $this->invitation->isCancelled()): ?>
                <br/>
                <div class="red">
                    <?php if ($this->invitation->hasExpired()) : ?>
                        <?= $this->translate("Cette invitation a expiré.") ?>
                    <?php elseif ($this->invitation->isCancelled()) : ?>
                        <?= $this->translate("Cette invitation a été annulée, vous n'avez plus besoin d'évaluer cet article.") ?>
                    <?php endif; ?>
                </div>
            <?php endif; ?>

            <?= $this->render('reviewer/reviewArticlesBtnLink.phtml') ?>

        </div>
    </div>

    <?php if (
            !$this->invitation->hasExpired() &&
            !$this->invitation->isAnswered() &&
            !$this->invitation->isCancelled()
    ) : ?>
        <div class="form-actions text-center">
            <?php if ($this->user_form) : ?>
                <button id="accept-button" type="button" class="btn btn-success" onclick="show_user_form()">
                    <?= $this->translate("J'accepte de relire cet article") ?>
                </button>
            <?php else : ?>
                <form method="post" style="display:inline">
                    <button name="submitaccept" id="submitaccept" type="submit"
                            class="btn btn-success"><?= $this->translate("J'accepte de relire cet article") ?></button>
                </form>
            <?php endif ?>
            <button id="refuse-button" type="button" class="btn btn-danger"
                    onclick="refuseInvitation()"><?= $this->translate("Je refuse de relire cet article") ?></button>
        </div>

        <?php
        if ($this->user_form) {
            echo $this->user_form;
        }
        ?>

        <div id="refuse_form" style="display: none">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title"><?= $this->translate('Détails de la réponse') ?></h2>
                </div>
                <div class="panel-body in">
                    <p class="text-danger">
                        <strong><?= $this->translate("Vous ne souhaitez pas relire cet article") ?></strong></p>
                    <?= $this->refuse_form; ?>
                </div>
            </div>
        </div>

        <?php if ($this->invalid_form) : ?>
            <script>
                display_errors();
            </script>
        <?php endif; ?>

    <?php endif; // endif (!hasExpired && !isAnswered) ?>

<?php endif; // endif (errors) ?>
