<div id="<?php echo $this->element->getName() ?>" style="display: none" class="form-inline">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title"><?php echo $this->translate($this->name) ?></h2>
        </div>
        <div class="panel-body in">
            <p class="text-success">
                <strong><?php echo $this->translate("Vous avez choisi d'accepter de relire cet article") ?></strong></p>
            <p><?php echo $this->translate('Sous quels délais pensez-vous effectuer votre relecture ?') ?></p>

            <?php
            foreach ($this->element->getElements() as $element) {
                echo $element;
            }
            ?>
        </div>
    </div>
</div>
