<form class="form-container" id="linkedInvitationForm" method="POST">
    <?php
    $loggedScreenName = Episciences_Auth::getScreenName();
    $loggedEmail = Episciences_Auth::getEmail();
    ?>
    <p>
        <?= sprintf($this->translate('Elle a été envoyée au compte %s%s < %s >%s'), '<a>', $this->fromScreeName, $this->fromEmail, '</a>') ?>
    </p>
    <p>
        <?= sprintf($this->translate("Voulez-vous l’associer à votre compte %s %s < %s > %s pour continuer ?"), '<a>', $loggedScreenName, $loggedEmail, '</a>') ?>
    </p>

    <input type="hidden" name="hidden" value="">

    <div class="form-actions text-center">
        <button type="submit" class="btn btn-success" name="linkInvitation" value="acceptToLink" style="display:inline">
            <span class="fa-solid fa-check"></span>
            <?= $this->translate('Accepter') ?>
        </button>
        <button type="submit" class="btn btn-danger" name="linkInvitation" value="declineToLink">
            <span class="fa-solid fa-xmark"></span>
            <?= $this->translate('Refuser') ?>
        </button>
    </div>

    <p class="status" id="statusMsg"></p>
</form>