
<div style="margin:2em;">
<ul>
    <li>
        <span><i class="fas fa-rss"></i></span>
        <a target="_blank"
           href="<?= $this->url(['controller' => 'feed', 'action' => 'rss']) ?>">RSS - <?php echo $this->translate('Derniers articles publiés, par revue'); ?></a>
    </li>


    <li>
        <span><i class="fas fa-rss"></i></span>
        <a target="_blank"
           href="<?= $this->url(['controller' => 'feed', 'action' => 'atom']) ?>">ATOM - <?php echo $this->translate('Derniers articles publiés, par revue'); ?></a>
    </li>

</ul>

</div>