<style>
    .table-responsive {
        max-height: 600px;
        overflow: auto; /* Active le défilement vertical */
    }

    table {
        width: 100%;
        border-collapse: collapse; /* fusionne les bordure de la table*/
        th, td {
            padding: 10px;
            text-align: left;
        }
        thead th {
            background: white;
            position: sticky;
            top: 0;
            z-index: 1;
        }
    }
</style>

<?php $this->layout()->pageTitle = $this->translate('Permissions | Episciences');
$description = $this->translate("Le tableau suivant décrit les différents niveaux de permission des utilisateurs.");
$allowedClass = 'fas fa-toggle-on text-success';
$noTAllowedClass = 'fas fa-toggle-off text-danger';

?>
<div class="table-responsive">
    <table class="table table-striped">
        <caption style="font-weight: bold;font-size: 120%;margin:1em;"><?= $this->translate($description) ?></caption>
        <thead>
        <tr>
            <th  scope="col"><?= $this->translate('Action') ?></th>
            <?php foreach ($this->roles as $role): ?>
                <th scope="col" class="role-<?= $role ?> text-center"><?= $this->translate($role) ?></th>
            <?php endforeach; ?>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->resources as $resource): ?>
            <tr>
                <td><strong><?= $this->translate($resource) ?></strong></td>
                <?php foreach ($this->roles as $index => $role): ?>
                    <td class="text-center">
                        <?php $isAllowed = $this->permissions[$resource][$role]; ?>
                        <?php if (is_bool($isAllowed)): ?>
                            <em class="<?= $isAllowed ? $allowedClass : $noTAllowedClass ?>"></em>
                        <?php elseif (is_string($isAllowed)): ?>
                            <em class="text-warning" data-toggle="tooltip" title="<?= $this->translate('Paramétrable par la revue') ?>"> <?= $this->translate($isAllowed) ?></em>
                        <?php endif; ?>
                    </td>
                <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

