<?php if($this->socialMedias || $this->webSites ): ?> <br> <?php endif ?>
<?php if (!empty($this->socialMedias)) : ?>
    <?php foreach ($this->socialMedias as $socialMedia): ?>
        <?php if (!empty($socialMedia)) : ?>
        <?php $socialMedia = $this->escape($socialMedia) ?>
            &nbsp;<small>
                <a href="https://twitter.com/<?= $socialMedia ?>" target="_blank">
                    <span class="fa-brands fa-twitter" style="margin-right: 5px;"></span>
                    <?= $socialMedia ?>
                </a>
            </small>
            <br>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>

<?php if (!empty($this->webSites)) : ?>

    <?php foreach ($this->webSites as $webSite): ?>
        &nbsp;<small>
            <a href="<?= $this->escape($webSite) ?>" target="_blank"> <span class="fas fa-link" style="margin-right: 5px;"></span></a><?= $this->escape($webSite) ?>
        </small>
        <br>
    <?php endforeach; ?>
<?php endif; ?>


