<?php $this->layout()->pageTitle = $this->translate('Mes commentaires'); ?>
<div class="panel panel-default collapsable">
    <div class="panel-heading">
        <h2 class="panel-title"><?php echo  $this->translate("Edition"); ?></h2>
    </div>
    <div class="panel-body in">
        <?php echo $this->edit_comment_form; ?>
    </div>
</div>
<?php
$this->jQuery()->addJavascriptFile('/js/common/visualDeleteFile.js');