<?php
/**
 * Database debug information
 */
$profileur = Zend_Db_Table_Abstract::getDefaultAdapter()->getProfiler();
$viewDbProfiler = $profileur->getEnabled();
?>
<?php if ($viewDbProfiler) { ?>
    <div class="debug" style="border-top:1px solid #dddddd;padding:0.5em;margin:0.5em">
        <p>Query Profiler</p>
        <div class="tab-content">
            <?php $dbconfig = Zend_Db_Table_Abstract::getDefaultAdapter()->getConfig(); ?>
            <blockquote>Host: <b><?php echo $dbconfig['host']; ?></b> <br/>Database:
                <b><?php echo $dbconfig['dbname']; ?></b> <br/>Number of requests:
                <b><?php echo $profileur->getTotalNumQueries() ?></b> <br/>Total time:
                <b><?php echo $profileur->getTotalElapsedSecs() ?> (sec)</b>
            </blockquote>
            <table class="table table-hover table-striped table-bordered">
                <thead>
                <tr>
                    <th style="width:auto"><i class="glyphicon glyphglyphicon glyphicon-tasks active"></i>&nbsp;Requests
                    </th>
                    <th style="width:20px"><i class="glyphicon glyphglyphicon glyphicon-time active"></i>&nbsp;Time
                        (sec.)
                    </th
                </tr>
                </thead>
                <tbody>
                <?php foreach ($profileur->getQueryProfiles() as $query) { ?>
                    <tr>
                        <td><small><?php echo $query->getQuery(); ?></small></td>
                        <td><?php echo $query->getElapsedSecs(); ?></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
<?php } ?>