<?php
$journalSettings = Zend_Registry::get('reviewSettings');
?>

<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <ul class="contact">
                    <span><?php echo $this->translate('À propos'); ?></span>
                    <li><i class="fas fa-rss"></i>&nbsp;<a href="<?php echo APPLICATION_URL; ?>/rss/papers">RSS</a></li>
                    <?php
                    if (isset($journalSettings[Episciences_Review::SETTING_CONTACT_JOURNAL_EMAIL]) && $journalSettings[Episciences_Review::SETTING_CONTACT_JOURNAL_EMAIL] !== '') {
                        echo sprintf('<li><i class="fas fa-envelope"></i>&nbsp;<a href="mailto:%s" >%s </a ></li>', $journalSettings[Episciences_Review::SETTING_CONTACT_JOURNAL_EMAIL], $this->translate('Courriel'));
                    }
                    if (isset($journalSettings[Episciences_Review::SETTING_CONTACT_JOURNAL]) && $journalSettings[Episciences_Review::SETTING_CONTACT_JOURNAL] !== '') {
                        echo sprintf('<li><i class="fas fa-address-book" ></i >&nbsp;<a href="%s" >%s </a ></li>', $journalSettings[Episciences_Review::SETTING_CONTACT_JOURNAL], $this->translate('Contact'));
                    }
                    if (isset($journalSettings[Episciences_Review::SETTING_ISSN]) && $journalSettings[Episciences_Review::SETTING_ISSN] !== '') {
                        echo ' <li><abbr title = "International Standard Serial Number" > ISSN</abbr > ' . $this->FormatIssn($journalSettings[Episciences_Review::SETTING_ISSN]) . '</a ></li>';
                    }
                    if (isset($journalSettings[Episciences_Review::SETTING_ISSN_PRINT]) && $journalSettings[Episciences_Review::SETTING_ISSN_PRINT] !== '') {
                        echo ' <li><abbr title = "International Standard Serial Number" > ISSN(print)</abbr > ' . $this->FormatIssn($journalSettings[Episciences_Review::SETTING_ISSN_PRINT]) . '</a ></li>';
                    }
                    ?>
                </ul>
            </div>

            <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                <ul class="social">
                    <span><?php echo $this->translate('Support'); ?></span>
                    <li>
                        <i class="fas fa-book"></i>&nbsp;<a
                                href="https://doc.episciences.org/"><?php echo $this->translate('Documentation'); ?></a>
                    </li>
                    <?php
                    if (isset($journalSettings[Episciences_Review::SETTING_CONTACT_TECH_SUPPORT_EMAIL]) && $journalSettings[Episciences_Review::SETTING_CONTACT_TECH_SUPPORT_EMAIL] !== '') {
                        echo sprintf('<li><i class="fas fa-life-ring"></i>&nbsp;<a href="mailto:%s">%s</a></li>', $journalSettings[Episciences_Review::SETTING_CONTACT_TECH_SUPPORT_EMAIL], $this->translate('Courriel support technique'));
                    }
                    if (isset($journalSettings[Episciences_Review::SETTING_CONTACT_TECH_SUPPORT]) && $journalSettings[Episciences_Review::SETTING_CONTACT_TECH_SUPPORT] !== '') {
                        echo sprintf('<li><i class="fas fa-life-ring" ></i >&nbsp;<a href="%s">%s</a></li>', $journalSettings[Episciences_Review::SETTING_CONTACT_TECH_SUPPORT], $this->translate('Support technique'));
                    }
                    ?>
                    <li>
                        <i class="fas fa-balance-scale"></i>&nbsp;<a href="//www.<?php echo DOMAIN; ?>/page/legal"><?php echo $this->translate('Mentions légales'); ?></a>
                    </li>
                    <li>
                        <i class="fas fa-cookie-bite"></i>&nbsp;<a href="//www.<?php echo DOMAIN; ?>/page/privacy"><?php echo $this->translate('Vie privée'); ?></a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-5 col-md-5 col-sm-4 col-xs-12">
                <ul class="about">
                    <span><?php echo $this->translate("À propos d'Episciences"); ?></span>

                    <li>
                        <a href="https://www.episciences.org/"> Episciences</a>
                    </li>

                    <li>
                        <a href="https://www.episciences.org/page/journals"><?php echo $this->translate('Revues hébergées'); ?> </a>
                    </li>
                    <li>
                        <a href="https://www.episciences.org/page/acknowledgements"><?php echo $this->translate('Remerciements'); ?> </a>
                    </li>

                </ul>
            </div>


        </div>
    </div>
</footer>
