<?php
$journalSettings = Zend_Registry::get('reviewSettings');
?>
<footer>
    <div class="container">
        <div class="row">


            <div class="col-lg-5 col-md-5 col-sm-4 col-xs-12">
                <ul class="about">
                    <span><?php echo $this->translate("À propos d'Episciences"); ?></span>
                    <li>
                        <a href="https://www.ccsd.cnrs.fr/category/episciences/">Blog</a>
                    </li>
                    <li>
                        <a href="mailto:<?= EPISCIENCES_CONTACT ?>">Contact</a>
                    </li>

                </ul>
            </div>

            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <ul class="contact">
                    <span>Support</span>
                    <li>
                        <i class="fas fa-book"></i>&nbsp;<a
                                href="https://doc.episciences.org/"><?php echo $this->translate('Documentation'); ?></a>
                    </li>
                    <?php
                    if (isset($journalSettings[Episciences_Review::SETTING_CONTACT_TECH_SUPPORT_EMAIL]) && $journalSettings[Episciences_Review::SETTING_CONTACT_TECH_SUPPORT_EMAIL] !== '') {
                        echo sprintf('<li><i class="fas fa-life-ring"></i>&nbsp;<a href="mailto:%s">%s</a></li>', $journalSettings[Episciences_Review::SETTING_CONTACT_TECH_SUPPORT_EMAIL], $this->translate('Courriel support technique'));
                    }
                    if (isset($journalSettings[Episciences_Review::SETTING_CONTACT_TECH_SUPPORT]) && $journalSettings[Episciences_Review::SETTING_CONTACT_TECH_SUPPORT] !== '') {
                        echo sprintf('<li><i class="fas fa-life-ring" ></i >&nbsp;<a href="%s">%s</a></li>', $journalSettings[Episciences_Review::SETTING_CONTACT_TECH_SUPPORT], $this->translate('Support technique'));
                    }
                    ?>
                    <li>
                        <i class="fas fa-balance-scale"></i>&nbsp;<a
                                href="//www.<?php echo DOMAIN; ?>/page/legal"><?php echo $this->translate('Mentions légales'); ?></a>
                    </li>
                    <li>
                        <i class="fas fa-cookie-bite"></i>&nbsp;<a
                                href="//www.<?php echo DOMAIN; ?>/page/privacy"><?php echo $this->translate('Vie privée'); ?></a>
                    </li>
                    <li>
                        <i class="fas fa-comment-alt"></i>&nbsp;<a
                                href="https://survey.ccsd.cnrs.fr/index.php/852898?newtest=Y&lang=en"><?php echo $this->translate('Retours utilisateurs'); ?></a>
                    </li>
                    <li><i class="fa-solid fa-handshake"></i>&nbsp;<a href="https://www.episciences.org/page/tou"><abbr
                                    title="<?= $this->translate("Conditions Générales d'Utilisation") ?>"><?= $this->translate('CGU') ?></abbr></a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                <ul class="social">
                    <span>Code/dev</span>
                    <li>
                        <i class="fas fa-code-branch"></i>&nbsp;<a
                                href="https://github.com/CCSDForge/episciences">Code</a>
                    </li>

                    <li>
                        <a href="https://doc.episciences.org/oai-pmh">OAI-PMH</a>
                    </li>

                    <li>
                        <a href="https://github.com/CCSDForge/episciences/projects/2"><?php echo $this->translate('Feuille de route'); ?></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">

            <div style="margin: 0 4% 0 4%" class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <p><img srcset="/img/flags/eu.svg" height="14px"
                        style="border: 0;"
                        alt="European Union"/>
                    Episciences has received support from <a href="https://www.openaire.eu/">OpenAIRE</a> and its
                    services, notably for the integration of
                    its service in the OpenAIRE Nexus project: funding from the <a
                            href="https://cordis.europa.eu/project/id/101017452">European Commission grant 101017452</a>
                    “OpenAIRE Nexus - OpenAIRE-Nexus Scholarly Communication Services for EOSC users”.</p>
            </div>
        </div>
    </div>
</footer>

