<div class="container text-center">
    <hr/>
    <div class="row">
        <div class="col-lg-12">
            <div class="col-md-6">
                <ul class="nav nav-pills nav-stacked">
                    <li><a href="//<?php echo DOMAIN; ?>"><img src="/img/episciences_tampon_50x50.png"
                                                               alt="episciences.org stamp"></a></li>
                </ul>
            </div>
            <div class="col-md-6">
                <ul class="nav nav-pills nav-stacked">
                    <li><a href="/"><?php echo RVNAME; ?></a></li>
                </ul>
            </div>
        </div>
    </div>


</div>






