<?php if (RVCODE !== 'portal'): ?>
    <form id="search-simple-form-navbar" action="/search" name="search-simple-navbar" method="get"
          class="navbar-form navbar-left" role="search">
        <div class="input-group">
            <input data-src="default" id="q" name="q" class="form-control" type="text"
                   pattern=".{0,300}" title="300 max."
                   style="min-width: 300px;" value="">
            <div class="input-group-btn">
                <button name="submit" type="submit" class="btn btn-default">
                    <span class="glyphicon glyphicon-search"></span></button>
            </div>
        </div>
    </form>
<?php endif; ?>