<?php $verticalNav = $this->navigation == Ccsd_Website_Style::ORIENTATION_V; ?>
<div id="navigation" class="<?php echo $verticalNav ? 'well sidebar-nav' : '';?>">
    <ul class="nav <?php echo $verticalNav ? 'nav-list' : 'nav-tabs';?>">
        <?php foreach ($this->nav()->getPages() as $page) {

            $params = $page->getParams();
            $label = $this->translate($page->getLabel());

            if (!$this->nav()->accept($page)) {
                continue;
            }

            $active = $page->isActive(true);
            $subPages = $page->getPages();
            $href = $this->url(['controller' =>$page->getController(), 'action' => $page->getAction()]);
            $params = $page->getParams();
            if ($params) {
                $href .= '?'.http_build_query($params);
            }

            if ($subPages) {
                ?>
                <li class="<?php echo $verticalNav ? 'dropdown-submenu' : 'dropdown';?> <?php echo $active ? 'active' : ''?>">
                    <?php if ($verticalNav) { ?>
                        <a tabindex="-1" href="<?php echo $href;?>"><?php echo $label?></a>
                    <?php } else { ?>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $label?><b class="caret"></b></a>
                    <?php } ?>
                    <ul class="dropdown-menu">
                        <?php
                        foreach ($subPages as $subPage) {
                            if (!$this->nav()->accept($subPage)) {
                                continue;
                            }
                            $label = $this->translate($subPage->getLabel());

                            $href = PREFIX_URL . $subPage->getController() . '/' . $subPage->getAction();
                            $params = $subPage->getParams();
                            if ($params) {
                                $href .= '?'.http_build_query($params);
                            }
                            ?>
                            <li><a href="<?php echo $href?>"><?php echo $label?></a></li>
                            <?php
                        }
                        ?>
                    </ul>
                </li>
                <?php
            } else {
                ?>
                <li class="<?php echo $active ? 'active' : ''?>"><a href="<?php echo $href?>"><?php echo $label?></a></li>
                <?php
            }
        } ?>
    </ul>
</div>
