<?php
$this->jQuery()->addStylesheet(VENDOR_JQUERY_UI_THEME_CSS);
$this->jQuery()
    ->addJavascriptFile('/js/search/autocomplete.js')
    ->addJavascriptFile('/js/search/search.js')
    ->addJavascriptFile('/js/vendor/jquery.fastLiveFilter.js');
?>




<?php

echo $this->partial('partials/search_navbar.phtml');

if ((isset($this->parsedSearchParams['rpp'])) and ($this->parsedSearchParams['rpp'] == $this->paginatordefaultNumberOfResults)) {
    unset($this->parsedSearchParams['rpp']);
}
?>


<div
	id="search-form"
	class="row"
>

<?php echo $this->partial('partials/search_author_form.phtml', array('parsedSearchParams' => $this->parsedSearchParams, 'paginatorNumberOfResultsArray' =>$this->paginatorNumberOfResultsArray)); ?>

</div>


<div class="row">

<?php if ($this->paginator): ?>
    <div class="span12">

       <?php
    echo $this->paginationControl($this->paginator, 'Sliding', 'partials/search_pagination.phtml', array(
            'parsedSearchParams' => $this->parsedSearchParams
    ));
    ?>
  </div>
<?php endif; ?>



<?php if ($this->results) : ?>
    	<div class="span12">





		<table class="table table-striped table-hover table-condensed">
			<caption><?php echo $this->numFound . '&nbsp;' .$this->translate('auteurs'); ?></caption>
			<thead>
				<tr>
					<th><?php echo $this->translate('Auteur'); ?></th>
					<th><?php echo $this->translate('Organisme'); ?></th>
					<th><?php echo $this->translate('URL'); ?></th>
				</tr>
			</thead>

			<tbody>


    <?php
    foreach ($this->results as $doc) {

        // var_dump($doc);

        $this->parsedSearchParams['autid'] = $doc->docid;

        ?>
<tr
					<?php if ($doc->current_bool == (bool)true): ?>
					class="success"
					<?php endif; ?>
				>

					<td><a
						data-toggle="tooltip"
						title="<?php echo $this->translate('Recherche de formes similaires'); ?>"
						href="<?php echo $this->url(array('controller'=> 'search', 'action'=> 'author', 'q'=> $this->escape($doc->fullname_s)), null, true); ?>"
					><span class="glyphicon glyphicon-search"></span></a> &nbsp; <a
						data-toggle="tooltip"
						title="<?php echo $this->translate('Documents de cet auteur'); ?>"
						href="<?php echo $this->url(array('controller'=> 'search', 'action'=> 'index', 'q'=> 'author_id_i:' . $this->escape($doc->docid)), null, true); ?>"
					><span class="glyphicon glyphicon-file"></span></a> &nbsp; <a
						data-toggle="tooltip"
						title="<?php echo $this->translate('Fiche auteur'); ?>"
						href="<?php echo $this->url(array('controller'=> 'search', 'action'=> 'author', 'q'=> $this->escape($doc->fullname_s),'autid'=>$doc->docid), null, true); ?>"
					><span class="glyphicon glyphicon-user"></span>&nbsp;<?php echo $this->escape($doc->fullname_s); ?></a>

					</td>


					<td>
		       <?php
        if ($doc->organism_s != '') {
            echo $doc->organism_s;
        }
        ?>


					</td>

					<td>
        <?php if ($doc->url_s != ''): ?>
            <a href="<?php echo $doc->url_s; ?>"><?php echo $doc->url_s; ?></a>

       <?php endif; ?>
</td>

				</tr>
        <?php
    }
    ?>
  </tbody>
		</table>
	</div>
<?php endif; ?>



	<?php if ($this->paginator): ?>
    <div class="span12">

       <?php
    echo $this->paginationControl($this->paginator, 'Sliding', 'partials/search_pagination.phtml', array(
            'parsedSearchParams' => $this->parsedSearchParams
    ));
    ?>
  </div>
<?php endif; ?>

	</div>
<!-- div class row -->