ALTER TABLE `REVIEWER_REPORT` ADD `ONBEHALF_UID` INT(11) UNSIGNED NULL AFTER `UID`, ADD INDEX `ONBEHALF_UID` (`ONBEHALF_UID`) USING BTREE;

ALTER TABLE `REVIEWER_REPORT` CHANGE `ONBEHALF_UID` `ONBEHALF_UID` INT(11) UNSIGNED NULL DEFAULT NULL COMMENT 'Mis à jour [!= de NULL] uniquement si l’évaluation est faite à la place de relecteur UID'; 
