CREATE TABLE IF NOT EXISTS `episciences_dev`.`USER_MERGE` (
`MID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT ,
`TOKEN` VARCHAR(40) NULL DEFAULT NULL ,
`MERGER_UID` INT(11) UNSIGNED NOT NULL COMMENT 'CASID du compte à fusionner'  ,
`KEEPER_UID` INT(11) UNSIGNED NOT NULL COMMENT 'CASID du compte à conserver' ,
`DETAIL` TEXT NULL DEFAULT NULL ,
`DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
PRIMARY KEY (`MID`)
) ENGINE = InnoDB CHARSET=utf8 COLLATE utf8_general_ci;