-- Unsign integers in most tables

ALTER TABLE `MAIL_LOG` CHANGE `ID` `ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT, CHANGE `RVID` `RVID` INT(11) UNSIGNED NOT NULL, CHANGE `DOCID` `DOCID` INT(11) UNSIGNED NULL DEFAULT NULL;

ALTER TABLE `MAIL_TEMPLATE` CHANGE `ID` `ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT, CHANGE `PARENTID` `PARENTID` INT(11) UNSIGNED NULL DEFAULT NULL, CHANGE `RVID` `RVID` INT(11) UNSIGNED NULL DEFAULT NULL, CHANGE `POSITION` `POSITION` INT(11) UNSIGNED NULL DEFAULT NULL;

ALTER TABLE `NEWS` CHANGE `ONLINE` `ONLINE` TINYINT(4) UNSIGNED NOT NULL;

ALTER TABLE `PAPERS` CHANGE `PAPERID` `PAPERID` INT(11) UNSIGNED NULL DEFAULT NULL, CHANGE `SID` `SID` INT(11) UNSIGNED NOT NULL DEFAULT '0';

ALTER TABLE `PAPER_COMMENTS` CHANGE `PCID` `PCID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT, CHANGE `PARENTID` `PARENTID` INT(11) UNSIGNED NULL DEFAULT NULL, CHANGE `TYPE` `TYPE` INT(11) UNSIGNED NOT NULL;

ALTER TABLE `PAPER_LOG` CHANGE `PAPERID` `PAPERID` INT(11) UNSIGNED NOT NULL;

ALTER TABLE `PAPER_SETTINGS` CHANGE `DOCID` `DOCID` INT(11) UNSIGNED NOT NULL;

ALTER TABLE `REVIEWER_ALIAS` CHANGE `UID` `UID` INT(11) UNSIGNED NOT NULL, CHANGE `DOCID` `DOCID` INT(11) UNSIGNED NOT NULL, CHANGE `ALIAS` `ALIAS` INT(11) UNSIGNED NOT NULL;

ALTER TABLE `REVIEWER_POOL` CHANGE `RVID` `RVID` INT(11) UNSIGNED NOT NULL, CHANGE `VID` `VID` INT(11) UNSIGNED NOT NULL DEFAULT '0', CHANGE `UID` `UID` INT(11) UNSIGNED NOT NULL;

ALTER TABLE `REVIEWER_REPORT` CHANGE `ID` `ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT, CHANGE `UID` `UID` INT(11) UNSIGNED NOT NULL, CHANGE `DOCID` `DOCID` INT(11) UNSIGNED NOT NULL, CHANGE `STATUS` `STATUS` INT(11) UNSIGNED NOT NULL;

ALTER TABLE `SECTION` CHANGE `SID` `SID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT, CHANGE `RVID` `RVID` INT(11) UNSIGNED NOT NULL, CHANGE `POSITION` `POSITION` INT(11) UNSIGNED NOT NULL;

ALTER TABLE `SECTION_SETTING` CHANGE `SID` `SID` INT(11) UNSIGNED NOT NULL;

ALTER TABLE `USER_ASSIGNMENT` CHANGE `ID` `ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT, CHANGE `INVITATION_ID` `INVITATION_ID` INT(11) UNSIGNED NULL DEFAULT NULL, CHANGE `RVID` `RVID` INT(11) UNSIGNED NOT NULL, CHANGE `TMP_USER` `TMP_USER` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0';

ALTER TABLE `USER_INVITATION` CHANGE `ID` `ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT, CHANGE `AID` `AID` INT(10) UNSIGNED NOT NULL COMMENT 'Assignment ID', CHANGE `SENDER_UID` `SENDER_UID` INT(11) UNSIGNED NULL DEFAULT NULL;

ALTER TABLE `USER_INVITATION_ANSWER` CHANGE `ID` `ID` INT(11) UNSIGNED NOT NULL COMMENT 'Invitation ID';

ALTER TABLE `USER_INVITATION_ANSWER_DETAIL` CHANGE `ID` `ID` INT(11) UNSIGNED NOT NULL COMMENT 'Invitation ID';

ALTER TABLE `USER_ROLES` CHANGE `UID` `UID` INT(11) UNSIGNED NOT NULL, CHANGE `RVID` `RVID` INT(11) UNSIGNED NOT NULL DEFAULT '0';

ALTER TABLE `USER_TMP` CHANGE `ID` `ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE `VOLUME_METADATA` CHANGE `ID` `ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT, CHANGE `VID` `VID` INT(11) UNSIGNED NOT NULL, CHANGE `CONTENT` `CONTENT` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0';

ALTER TABLE `VOLUME_PAPER` CHANGE `ID` `ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT, CHANGE `VID` `VID` INT(11) UNSIGNED NOT NULL, CHANGE `DOCID` `DOCID` INT(11) UNSIGNED NOT NULL;

ALTER TABLE `VOLUME_PAPER_POSITION` CHANGE `VID` `VID` INT(11) UNSIGNED NOT NULL, CHANGE `DOCID` `DOCID` INT(11) UNSIGNED NOT NULL, CHANGE `POSITION` `POSITION` INT(11) UNSIGNED NOT NULL;

ALTER TABLE `WEBSITE_NAVIGATION` CHANGE `PARENT_PAGEID` `PARENT_PAGEID` INT(11) UNSIGNED NOT NULL;

-- Add indexes

ALTER TABLE `MAIL_LOG` ADD INDEX(`RVID`);
ALTER TABLE `MAIL_LOG` ADD INDEX(`DOCID`);
ALTER TABLE `MAIL_LOG` ADD INDEX(`WHEN`);
ALTER TABLE `PAPER_SETTINGS` ADD INDEX(`SETTING`);
ALTER TABLE `PAPER_SETTINGS` ADD INDEX(`DOCID`);
ALTER TABLE `USER_ASSIGNMENT` ADD INDEX(`ITEM`);
ALTER TABLE `USER_ASSIGNMENT` ADD INDEX(`ROLEID`);
ALTER TABLE `USER_ASSIGNMENT` ADD INDEX(`RVID`);
ALTER TABLE `USER_ASSIGNMENT` ADD INDEX(`STATUS`);
ALTER TABLE `USER_ASSIGNMENT` ADD INDEX(`WHEN`);
ALTER TABLE `USER_ASSIGNMENT` ADD INDEX(`TMP_USER`);
ALTER TABLE `PAPERS` ADD INDEX(`STATUS`);

-- fix for SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xC5\x84ski ...' for column 'TO' at row 1, query was: INSERT INTO `MAIL_LOG` (`RVID`, `DOCID`, `FROM`, `REPLYTO`, `TO`, `CC`, `BCC`, `SUBJECT`, `CONTENT`, `FILES`, `WHEN`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW())

ALTER TABLE MAIL_LOG CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci