UPDATE PAPERS p
SET p.FLAG = 'imported'
WHERE p.FLAG != 'imported'
AND (
YEAR(p.PUBLICATION_DATE) < 2013
OR YEAR(p.SUBMISSION_DATE) < 2013
OR DATE(p.PUBLICATION_DATE) <= DATE(p.SUBMISSION_DATE)
OR (p.STATUS = 16 AND (DATE(p.SUBMISSION_DATE) > DATE(`WHEN`) OR DATE(p.PUBLICATION_DATE) < DATE(`WHEN`)))
);