ALTER TABLE `PAPERS` ADD `PASSWORD` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL AFTER `FLAG`;
-- ALTER TABLE `PAPERS` ADD `TYPE` ENUM('article','dataset','dataPaper','proceedingAct','other') NOT NULL DEFAULT 'article' AFTER `DOI`, ADD INDEX `type` (`TYPE`);

-- Unreleased
ALTER TABLE `PAPERS` ADD `TYPE` JSON NULL DEFAULT NULL AFTER `DOI`;
UPDATE PAPERS SET `TYPE` = '{"title": "article"}' WHERE STATUS = 16;

ALTER TABLE `PAPERS` ADD `DOCUMENT` JSON NULL DEFAULT NULL AFTER `RECORD`;
ALTER TABLE `PAPERS` CHANGE `TYPE` `TYPE` JSON NULL DEFAULT NULL AFTER `REPOID`; -- repoId must be initialized before type @see Episciences_Paper::setType()
