<?php 
	$this->jQuery()->addJavascriptFile(VENDOR_TINYMCE_JQUERY);
	$this->jQuery()->addJavascriptFile(VENDOR_TINYMCE);
	$this->jQuery()->addJavascriptFile(TINYMCE_DIR . "tinymce_patch.js");
    $this->jQuery()->addJavascriptFile("/js/volume/confproceeding.js");
    $this->jQuery()->addJavascriptFile("/js/datepicker/datepicker-" . Zend_Registry::get('lang') . ".js");
    $this->jQuery()->addJavascriptFile("/js/datepicker/datepicker.js");
    $this->jQuery()->addStylesheet(VENDOR_JQUERY_UI_THEME_CSS);
	
	echo $this->form;
	echo $this->partial('partials/modal.phtml', array('content'=>$this->metadataForm));
