<?php 
	$this->jQuery()->addJavascriptFile(VENDOR_TINYMCE);
	$this->jQuery()->addJavascriptFile(TINYMCE_DIR . "tinymce_patch.js");
    $this->jQuery()->addJavascriptFile("/js/volume/confproceeding.js");
    $this->jQuery()->addJavascriptFile("/js/datepicker/datepicker-" . Zend_Registry::get('lang') . ".js");
    $this->jQuery()->addJavascriptFile("/js/datepicker/datepicker.js");
    $this->getHelper('webpackAssets')->queueStylesheet('jquery-ui-theme');

echo $this->form;
echo $this->partial('partials/modal.phtml', array('content'=>$this->metadataForm));
