<style>
    .form-control-nowidth {
        height: 34px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.42857143;
        color: #555;
        background-color: #fff;
        background-image: none;
        border: 1px solid #ccc;
        border-radius: 4px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        -o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
    }

</style>
<div id="conference_doi_group" class="row" style="margin-bottom: 8px;">
    <label class="col-md-3 control-label" style="margin-right: 24px;"><?= $this->translate("DOI de l'acte de conférence") ?></label>
    <?php if (Zend_Registry::get('reviewSettingsDoi')->getDoiPrefix()) : ?>
        <input id="doi_proceedings_prefix_input" name="doi_proceedings_prefix_input" class="col-offset-1 col-sm-2 d-inline-block form-control-nowidth" style="margin-right: 4px;" value="<?= Zend_Registry::get('reviewSettingsDoi')->getDoiPrefix().'/'.RVCODE.".proceedings." ?>" disabled>
        <input id="conference_proceedings_doi" name="conference_proceedings_doi" class="col-sm-2 d-inline-block form-control-nowidth" style="margin-right: 4px;" maxlength="20" value="<?= $this->value ?>" autocomplete="off">
        <input type="button" class="col-sm-1 d-inline-block btn btn-primary" id="btn-request-proceedings" value="<?= $this->translate("Demande de DOI") ?>">
        <input type="button" class="col-sm-1 d-inline-block btn btn-warning" id="btn-cancel-request-proceedings" value="<?= $this->translate("Annulation DOI") ?>" style="display:none;">
    <?php endif;?>
</div>