<?php if ($this->editors) : ?>
    <?php
    $nbEditors = count($this->editors);
    if ($nbEditors > 1) :
        $editors_list = array();
        /** @var Episciences_Editor $editor */
        foreach ($this->editors as $editor) {
            $editors_list[] = '<span>' . $this->escape($editor->getFullname()) . '</span>';
        }
        $editors_string = implode('<br/>', $editors_list);
        ?>
        <span data-toggle="tooltip"
              title="<?php echo $this->escape($editors_string); ?>"><?php echo $nbEditors . ' ' . mb_strtolower($this->translate(Episciences_Acl::ROLE_EDITOR_PLURAL), 'UTF-8'); ?></span>
    <?php else :
        $editor = reset($this->editors);
        if ($editor instanceof Episciences_Editor) : ?>
            <span><?php echo $this->escape($editor->getFullname()); ?></span>
            <br/>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
