<?php
	$this->jQuery()->addJavascriptFile(VENDOR_TINYMCE_JQUERY);
	$this->jQuery()->addJavascriptFile(VENDOR_TINYMCE);
	$this->jQuery()->addJavascriptFile(TINYMCE_DIR . "tinymce_patch.js");
	$this->jQuery()->addJavascriptFile("/js/volume/special.js");
    $this->jQuery()->addJavascriptFile("/js/volume/confproceeding.js");
    $this->jQuery()->addJavascriptFile("/js/datepicker/datepicker-" . Zend_Registry::get('lang') . ".js");
    $this->jQuery()->addJavascriptFile("/js/datepicker/datepicker.js");
    $this->jQuery()->addStylesheet(VENDOR_JQUERY_UI_THEME_CSS);


?>

    <div class="panel panel-default">
        <div class="panel-body">
            <?php
            echo $this->form;
            echo $this->partial('partials/modal.phtml', array('content' => $this->metadataForm));
            ?>
        </div>
        <div class="panel-footer" style="text-align: center;">
            <a href="<?= $this->url(['controller' => 'grid', 'action' => 'list']) ?>" class="btn btn-default" role="button">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                <?= $this->translate('Grilles de relecture'); ?>
            </a>
        </div>
    </div>

<?php if ($this->volume->getSetting('access_code')) : ?>
<script>var access_code = '<?php echo $this->volume->getSetting('access_code'); ?>';</script>
<?php endif; ?>