<?php if ($this->editors) : ?>

<?php if (count($this->editors) > 1 ) : ?>
<?php 
	$editors_string = '';
	foreach ($this->editors as $editor) {
		$editors_string .= '<span>' . $editor->getFullname() . '</span><br/>';
	} 
?>
<span data-toggle="tooltip" title="<?php echo htmlentities($editors_string);?>"><?php echo count($this->editors) . ' ' . mb_strtolower($this->translate(Episciences_Acl::ROLE_EDITOR_PLURAL), 'UTF-8'); ?></span>
<script>$("[data-toggle~='tooltip']").tooltip({'container': 'body', 'placement': 'bottom', 'html': true, 'delay': {'show': 200, 'hide': 100}});</script>
<?php else : ?>
<span>
	<?php echo array_shift($this->editors)->getFullname()?>
</span>
<br/>
<?php endif; ?>

<?php endif; ?>