<?php $this->jQuery()->addJavascriptFile("/js/volume/form.js"); ?>

<script>var lang = '<?= Zend_Registry::get('Zend_Translate')->getLocale() ?>';</script>

<div class="row">
    <span class="col-md-3 col-md-offset-9 ccsd_form_required"><?= $this->translate('Champ requis') ?></span>
</div>
<div class="row">


    <form class="<?= $this->element->getAttrib('class') ?>" action="<?= $this->element->getAction() ?>"
          method="<?= $this->element->getMethod() ?>" data-library="ccsd" role="form"
          data-volume-has-articles="<?= isset($this->hasPublishedPapers) && $this->hasPublishedPapers ? 'true' : 'false' ?>">

        <?php if (isset($this->hasPublishedPapers) && $this->hasPublishedPapers): ?>
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-info" role="alert">
                    <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                    <strong><?= $this->translate('Information') ?> :</strong>
                    <?= $this->translate('Le nom du volume ne peut pas être modifié car des articles sont déjà associés à ce volume') ?>.
                </div>
            </div>
        </div>
        <?php endif; ?>

        <?php foreach ($this->element->getElements() as $element) : ?>
            <div id="<?= $element->getName() ?>-element" class="form-group" <?php if ($element->getAttrib('data-none')):?>style="display: none;" <?php endif;?>>
                <?= $element ?>
            </div>
        <?php endforeach; ?>

        <?= $this->partial('volume/doi_proceedings_row.phtml', [
                'value' => $this->element->getDecorator('ViewScript')->getOption('value')
        ]) ?>


        <div id="metadata-element" class="form-group row">
            <label class="col-md-3 control-label optional"><?= $this->translate('Métadonnées') ?></label>
            <div class="col-md-9" style="padding-top: 7px">

                <div id="metadatas">
                    <?php if ($this->element->getView()->volume) : ?>
                        <?php $metadatas = $this->element->getView()->volume->getMetadatas(); ?>


                        <?php foreach ($metadatas as $metadata) : ?>
                            <div class="metadata input-group" style="margin-bottom: 2px">
					<span style="font-size: inherit; display: block; text-align: justify; white-space: normal; padding: 1px  0px 1px 10px;"
                          class="label label-primary">
						<?= $metadata->getTitle(); ?>
						<a class="modal-opener"
                           data-width="50%"
                           data-init="init"
                           data-callback="submit"
                           data-onclose="onclose"
                           title="<?= $this->translate('Modifier une métadonnée') ?>"><button
                                    class="btn btn-xs btn-primary edit-metadata"
                                    type="button"><span
                                        class="glyphicon glyphicon-pencil"></span></button></a><button
                                onclick="removeMetadata($(this))" data-placement="right"
                                style="border-radius:0; height: 20px; padding-top:0; padding-bottom: 0;"
                                class="btn btn-xs btn-primary" type="button"><span
                                    class="glyphicon glyphicon-trash"></span></button>
					</span>
                                <input type="hidden"
                                       value="<?= htmlspecialchars(Zend_Json::encode(['id' => $metadata->getId(), 'title' => $metadata->getTitles(), 'content' => $metadata->getContents(), 'file' => $metadata->getFile()])) ?>">
                            </div>
                        <?php endforeach; ?>

                    <?php endif; ?>
                </div>

                <div>
                    <a class="modal-opener"
                       title="<?= $this->translate('Ajouter un fichier (Édito, Erratum, Addendum, ...)') ?>"
                       data-init="init"
                       data-callback="submit"
                       data-width="50%">
                        <button class="btn btn-default btn-sm" type="button" id="addmetadata" name="addmetadata">
                            <?= $this->translate('Ajouter un fichier (Édito, Erratum, Addendum, ...)') ?>
                        </button>
                    </a>
                </div>
            </div>
        </div>


        <?php if ($this->element->getView()->volume && $this->element->getView()->paperList) : ?>
            <?php
            if (!empty($this->element->getView()->gapsInOrderingPapers)) {
                echo '<div class="alert alert-warning" role="alert">';
                echo $this->translate('Des vides ont été détectés dans la numérotation des papiers : ');
                echo '<ul>';
                foreach ($this->element->getView()->gapsInOrderingPapers as $gapNumber) {
                    printf('<li><span class="label label-default">%d</span></li>', $gapNumber + 1);
                }
                echo '</ul>';
                echo '</div>';
            }
            ?>
            <div id="papers-element" class="form-group row">
                <label class="col-md-3 control-label optional"><?= $this->translate('Articles') ?></label>
                <div class="col-md-9" style="padding-top: 7px">
                    <div id="papers">
                        <?php foreach ($this->element->getView()->paperList as $paperOrder => $paper) : ?>
                            <?php
                            $title = $paper['title'];
                            $paperDocid = $paper['docid'];
                            $titleStr = $this->escape(Ccsd_Tools::truncate($title, 50));
                            ?>
                            <div id="paper-<?= $paper['paperid'] ?>" class="paper input-group">
                            <span class="label label-status-<?= $paper['status'] ?>" data-toggle="tooltip"
                                  title="<?= ucfirst($this->translate(Episciences_PapersManager::getStatusLabel($paper['status']))) ?>">
                           <?= (int)$paperOrder + 1 ?></span>
                                [<a href="<?= $this->url(['controller' => 'administratepaper', 'action' => 'view', 'id' => $paperDocid]) ?>"># <?= $paperDocid ?></a>]&nbsp;
                                <?= $titleStr ?>
                            </div>
                        <?php endforeach; ?>
                    </div>
                    <input id="paper_positions" name="paper_positions" type="hidden" value=""/>
                </div>
            </div>
        <?php endif; ?>


        <div class="form-actions text-center">
            <?php $location = $this->element->getDecorator('ViewScript')->getOption('referer'); ?>
            <button onclick="window.location='<?= $location ?>'" class="btn btn-default" type="button" id="back"
                    name="back"><?= $this->translate('Annuler') ?></button>
            <button class="btn btn-primary" value="Valider" type="submit" id="submit"
                    name="submit"><?= $this->translate('Valider') ?></button>
        </div>

    </form>

</div>

