<?php
/**
 * @var Episciences_Volume $volume
 */
$volume = $this->volume;
$this->layout()->pageTitle = $volume->getNameKey();
$metadatas = $volume->getMetadatas();
$indexedPapers = $volume->getIndexedPapers();

?>
<div id="volume">

    <div class="row">
        <div class="col-md-12" id="proceeding-info">
            <?php if ($volume->getSetting(Episciences_Volume::VOLUME_IS_PROCEEDING) === "1"): ?>
                <div class="col-sm-12">
                    <p>
                        <b style="font-size: 14px"><?= $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_NAME) ?></b>
                    </p>
                    <p>
                        <?= $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_ACRONYM) !== '' ? $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_ACRONYM) . ";" : '' ?>
                        <?= $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_NUMBER) !== '' ? "N°" . $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_NUMBER) . ";" : '' ?>
                    </p>
                    <p>
                        <?= $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_LOCATION) !== '' ? $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_LOCATION) . ";" : '' ?>
                        <?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_START_DATE) !== '' && $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_END_DATE) !== '') : ?>
                            <?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_START_DATE) === $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_END_DATE)) : ?>

                                <?= $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_START_DATE) ?>
                            <?php else: ?>
                                <?= Zend_Registry::get('Zend_Translate')->translate('Du') . ' ' . $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_START_DATE) . ' ' . Zend_Registry::get('Zend_Translate')->translate('Au') . ' ' . $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_END_DATE) ?>
                            <?php endif; ?>
                        <?php endif; ?>
                    </p>
                    <p><?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_THEME) !== '') {
                            echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_THEME) . ";";
                        } ?></p>
                </div>
                <div class="col-sm-12">
                    <p>
                        <?php if (substr(strrchr($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_DOI), "."), 1) !== '') {
                            echo "DOI: <a href='https://doi.org/" . $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_DOI) . "'target='_blank' rel='noopener'>" . $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_DOI) . "</a>";
                        } ?>
                    </p>
                </div>
            <?php endif; ?>

        </div>
        <div class="col-sm-12">

            <div id="description" class="col-sm-12">
                <p class="text-justify text-primary"><?= $volume->getDescriptionKey() ?></p>
            </div>

            <?php if ($metadatas) : ?>
                <div id="metadatas" class="volume-metadata">
                    <?= $this->partial('volume/volume-metadatas.phtml', ['metadatas' => $metadatas, 'volume' => $volume]) ?>

                </div>
            <?php endif; ?>

        </div>

    </div>

    <?php if ($indexedPapers) : ?>

        <?= $this->partial('volume/volume-indexed-papers.phtml', ['indexedPapers' => $indexedPapers, 'volume' => $volume]) ?>
    <?php else: ?>
        <div class="row">
            <blockquote style="padding:1em;">
                <?= $this->translate('Ce volume ne contient pas encore de documents.') ?>
            </blockquote>
        </div>

    <?php endif; ?>
</div>