<?php
$this->layout()->pageTitle = $this->translate($this->volume->getNameKey());
$metadatas = $this->volume->getMetadatas();
$indexedPapers = $this->volume->getIndexedPapers();
?>
<div id="volume">


    <div class="row">
        <div class="col-sm-12">
            <?php if (Zend_Registry::get('Zend_Translate')->isTranslated($this->volume->getDescriptionKey())) : ?>

                <div id="description" class="col-sm-12">
                    <p class="text-justify text-primary"><?= $this->translate($this->volume->getDescriptionKey()) ?></p>
                </div>

            <?php endif; ?>

            <?php if ($metadatas) : ?>
                <div id="metadatas" class="volume-metadata">
                    <?= $this->partial('volume/volume-metadatas.phtml', ['metadatas' => $metadatas]) ?>
                </div>
            <?php endif; ?>
        </div>

    </div>

    <?php if ($indexedPapers) : ?>

        <?= $this->partial('volume/volume-indexed-papers.phtml', ['indexedPapers' => $indexedPapers, 'volume' => $this->volume]) ?>

    <?php else: ?>
        <div class="row">
            <blockquote style="padding:1em;">
                <?= $this->translate('Ce volume ne contient pas encore de documents.') ?>
            </blockquote>
        </div>

    <?php endif; ?>
</div>