<?php
$this->layout()->pageTitle = $this->translate($this->volume->getNameKey());
$metadatas = $this->volume->getMetadatas();
$indexedPapers = $this->volume->getIndexedPapers();
/**
 * @var Episciences_Volume $volume
 */
$volume = $this->volume;
?>
<div id="volume">


    <div class="row">
        <div class="col-sm-12">
            <?php if (Zend_Registry::get('Zend_Translate')->isTranslated($this->volume->getDescriptionKey())) : ?>

                <div id="description" class="col-sm-12">
                    <p class="text-justify text-primary"><?= $this->translate($this->volume->getDescriptionKey()) ?></p>
                </div>

            <?php endif; ?>
            <?php if ($metadatas) : ?>
                <div id="metadatas">
                    <?= $this->partial('volume/volume-metadatas.phtml', ['metadatas' => $metadatas, 'volume' => $this->volume]) ?>

                </div>
            <?php else: ?>
                <?php if ($volume->getSetting(Episciences_Volume::VOLUME_IS_PROCEEDING) === "1"): ?>
                    <div class="col-sm-12">
                            <p><b style="font-size: 14px"><?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_NAME) !== ''){ echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_NAME);} ?></b></p>
                            <p>
                                <?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_ACRONYM) !== ''){ echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_ACRONYM).";"; } ?>
                                <?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_NUMBER) !== ''){ echo "N°".$volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_NUMBER).";"; } ?>
                            </p>
                            <p>
                                <?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_LOCATION) !== ''){echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_LOCATION).";";} ?>
                                <?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_START_DATE) !== '' && $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_END_DATE) !== '') {
                                    if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_START_DATE) === $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_END_DATE) ){
                                        echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_START_DATE);
                                    } else {
                                        echo Zend_Registry::get('Zend_Translate')->translate('Du').' '.$volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_START_DATE).' '.Zend_Registry::get('Zend_Translate')->translate('Au').' '.$volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_END_DATE);
                                    }
                                }
                                ?>
                            </p>
                            <p><?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_THEME) !== ''){ echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_THEME).";"; } ?></p>
                    </div>
                    <div class="col-sm-12">
                        <p>
                            <?php if (substr(strrchr($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_DOI), "."), 1) !== '') {
                                echo "DOI: <a href='https://doi.org/" . $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_DOI) . "'target='_blank' rel='noopener'>" . $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_DOI) . "</a>";
                            } ?>
                        </p>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
        </div>

    </div>

    <?php if ($indexedPapers) : ?>

        <?= $this->partial('volume/volume-indexed-papers.phtml', ['indexedPapers' => $indexedPapers, 'volume' => $this->volume]) ?>
    <?php else: ?>
        <div class="row">
            <blockquote style="padding:1em;">
                <?= $this->translate('Ce volume ne contient pas encore de documents.') ?>
            </blockquote>
        </div>

    <?php endif; ?>
</div>