<?php $metadatas = $this->metadatas; ?>

<?php
/**
 * @var Episciences_Volume $volume
 */
$volume = $this->volume;
?>
<?php
/** @var Episciences_Volume_Metadata $metadata */
foreach ($metadatas

as $metadata) : ?>
<?php
$content = $metadata->getContent();
$metaId = $metadata->getId();
$hasFile = $metadata->hasFile();
$hasContent = !empty($metadata->getContent());
?>
<?php if ($volume->getSetting(Episciences_Volume::VOLUME_IS_PROCEEDING) === "1"): ?>
    <div class="col-sm-12">
        <p>
            <b style="font-size: 12px"><?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_NAME) !== '') {
                    echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_NAME);
                } ?></b></p>
        <p>
            <?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_ACRONYM) !== '') {
                echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_ACRONYM) . ";";
            } ?>
            <?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_NUMBER) !== '') {
                echo "N°" . $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_NUMBER) . ";";
            } ?>
        </p>
        <p>
            <?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_LOCATION) !== '') {
                echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_LOCATION) . ";";
            } ?>
            <?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_START_DATE) !== '' && $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_END_DATE) !== '') {
                if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_START_DATE) === $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_END_DATE)) {
                    echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_START_DATE);
                } else {
                    echo Zend_Registry::get('Zend_Translate')->translate('Du') . ' ' . $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_START_DATE) . ' ' . Zend_Registry::get('Zend_Translate')->translate('Au') . ' ' . $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_END_DATE);
                }
            }
            ?>
        </p>
        <p><?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_THEME) !== '') {
                echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_THEME) . ";";
            } ?></p>
    </div>
    <div class="col-sm-12">
        <p>
            <?php if (substr(strrchr($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_DOI), "."), 1) !== '') {
                echo sprintf('DOI: <a href="https://doi.org/%s" target="_blank" rel="noopener">%s</a>', $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_DOI), $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_DOI));
            } ?>
        </p>
    </div>
<?php endif; ?>
<div id="meta-<?= $metaId ?>">

    <?php if ($hasFile): ?>

    <div class="row">
        <div class="col-sm-2">


            <?php if ($metadata->isPicture()) : ?>

                <?php
                $mTitles = $metadata->getTitles();
                $locale = Episciences_Tools::getLocale();
                $alt = array_key_exists($locale, $mTitles) ? $mTitles[$locale] : $mTitles[array_key_first($mTitles)];

                ?>


                <img class="attachment-metadata-volume" src="<?= $metadata->getFileUrl() ?>" alt="<?= $alt ?>"
                     data-toggle="tooltip" title="<?= $alt ?>"/>


            <?php else: ?>

                <?php $download = !$metadata->isPDF() ? 'download="' . $metadata->getFile() . '"' : ''; ?>

                <a class="metadata-file" href="<?= $metadata->getFileUrl() ?>" <?= $download ?> target="_blank">
                        <span class="glyphicon glyphicon-file"></span>
                    <?= $metadata->getTitle() ?>
                </a>

            <?php endif; ?>

            <?php endif; ?>

        </div>

        <div class="col-sm-10">

            <?php if ($hasContent) : ?>
                <p class="attachment-metadata-volume small"><?= nl2br($content) ?></p>
            <?php endif; ?>
        </div>

    </div>

    <?php endforeach; ?>
