<?php $metadatas = $this->metadatas; ?>

<?php
/**
 * @var Episciences_Volume $volume
 */
$volume = $this->volume;
?>
<?php
/** @var Episciences_Volume_Metadata $metadata */
foreach ($metadatas as $metadata) : ?>
<?php
$content = $metadata->getContent();
$metaId = $metadata->getId();
$hasFile = $metadata->hasFile();
$hasContent = !empty($metadata->getContent());
?>
<?php if ($volume->getSetting(Episciences_Volume::VOLUME_IS_PROCEEDING) === "1"): ?>
    <div class="col-sm-12">
        <p>
            <?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_NAME) !== ''){ echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_NAME).";"; } ?>
            <?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_THEME) !== ''){ echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_THEME).";"; } ?>
            <?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_ACRONYM) !== ''){ echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_ACRONYM).";"; } ?>
            <?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_NUMBER) !== ''){ echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_NUMBER).";"; } ?>
            <?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_START_DATE) !== ''){ echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_START_DATE).";"; } ?>
            <?php if ($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_END_DATE) !== ''){ echo $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_END_DATE); } ?>
        </p>
    </div>
    <div class="col-sm-12">
        <p>
            <?php if (substr(strrchr($volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_DOI), "."), 1) !== '') {
                echo "DOI: <a href='https://doi.org/" . $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_DOI) . "'target='_blank' rel='noopener'>" . $volume->getSetting(Episciences_Volume::VOLUME_CONFERENCE_DOI) . "</a>";
                } ?>
        </p>
    </div>
<?php endif; ?>
<div id="meta-<?= $metaId ?>">

    <?php if ($hasFile): ?>

    <div class="row">
        <div class="col-sm-2">


            <?php if ($metadata->isPicture()) : ?>

                <?php
                $mTitles = $metadata->getTitles();
                $locale = Episciences_Tools::getLocale();
                $alt = array_key_exists($locale, $mTitles) ? $mTitles[$locale] : $mTitles[array_key_first($mTitles)];

                ?>


                <img class="attachment-metadata-volume" src="<?= $metadata->getFileUrl() ?>" alt="<?= $alt ?>"
                     data-toggle="tooltip" title="<?= $alt ?>"/>


            <?php else: ?>

            <?php $download = !$metadata->isPDF() ? 'download="' . $metadata->getFile() . '"' : ''; ?>

                <a href="<?= $metadata->getFileUrl() ?>" <?= $download ?> target="_blank">
                    <button class="btn btn-default btn-sm attachment-metadata-volume">
                        <span class="glyphicon glyphicon-file"></span>
                        <?= $metadata->getTitle() ?>
                    </button>
                </a>

            <?php endif; ?>

            <?php endif; ?>

        </div>

        <div class="col-sm-10">

            <?php if ($hasContent) : ?>
                <p class="attachment-metadata-volume small"><?= $content ?></p>
            <?php endif; ?>
        </div>

    </div>

    <?php endforeach; ?>
