<h1><?php echo $this->translate('Création de compte'); ?></h1>

<?php 
	if (Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger')->setNamespace('success')->hasMessages() || 
        Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger')->setNamespace('success')->hasCurrentMessages()) : 
?>
	<p><a href="<?= $this->url(['controller' => 'index'])?>" class="btn">Retourner à l'accueil</a></p>
<?php else: ?>
	<?php echo $this->form; ?>
<?php endif; ?>