<style>
#myDisplayGroup-label {
	display: none;
}
#or-label {
	display: inline;
	
}
</style>

<?php if (Episciences_Auth::isSecretary()) :?>
<div class="form-actions">
	<?php echo $this->autocomplete; ?>
</div>
<?php endif;?>

<?php if ($this->localUsers) : ?>
	
<table class="table table-striped table-bordered dataTable" id="localUsers">
	<thead>
		<tr>
			<th><?php echo $this->translate('Id'); ?></th>
			<th><?php echo $this->translate("Nom d'utilisateur"); ?></th>
			<th><?php echo $this->translate("Identifiant"); ?></th>
			<th><?php echo $this->translate('E-mail'); ?></th>
			<th><?php echo $this->translate('Rôles'); ?></th>
			<th><?php echo $this->translate('Actions'); ?></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->localUsers as $user) : ?>	
		<?php 
		// On filtre l'affichage des utilisateurs root, si on est pas root
		if (!Episciences_Auth::isRoot() && in_array(Episciences_Acl::ROLE_ROOT, $user['ROLES'])) {
			continue;
		}		
		?>
		<tr id="localUsers_<?php echo $user['UID']; ?>">
			<td><?php echo $user['UID']?></td>
			<td><?php echo $user['SCREEN_NAME']?></td>
			
			<td><?php echo $user['CAS']['USERNAME']?></td>
			<td><?php echo $user['CAS']['EMAIL']?></td>
			<td>
				<div class="tags" style="float:left; max-width: 250px; display: inline">
				<?php if ($user['ROLES']) : ?>
				<?php 	echo $this->partial('partials/user_roles.phtml', array('roles'=>$user['ROLES']))?>
				<?php endif;?>
				</div>
				
				<?php if (Episciences_Auth::isSecretary()) :?>
				<button onclick="getRoles(this, <?php echo $user['UID'] ?>)" class="btn btn-mini popover-link" style="float: right; font-size: 10px"><i class="icon-caret-down"></i></button>
				<?php endif;?>
				
			</td>
			<td style="text-align:right;"> 
				<a href="<?= $this->url(['controller' => 'user', 'action' => 'view', 'userid' => $user['UID']]) ?>"><i class="darkgrey icon-info-sign"></i></a>&nbsp;
				<?php if (Episciences_Auth::isSecretary()) :?>
				<a href="<?= $this->url(['controller' => 'user', 'action' => 'edit', 'userid' => $user['UID']]) ?>"><i class="darkgrey icon-edit"></i></a>&nbsp;
				<a id="delete_localUsers_<?php echo $user['UID']; ?>" href="#"><i class="darkgrey icon-trash"></i></a>
				<?php endif; ?>
			</td>
			
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<?php else : ?>

<?php echo $this->translate('Aucun utilisateur enregistré'); ?>.

<?php endif; ?>