<h1><?php echo $this->translate('Déconnexion du serveur d\'authentification du')?> <abbr title="Centre pour la Communication Scientifique Directe">CCSD</abbr></h1>

<?php if ($this->message == Ccsd_User_Models_User::LOGOUT_SUCCESS) : ?>
    <div class="alert alert-success"><?php echo $this->translate('Déconnexion réussie')?></div>
    <p><a href="/" class="btn"><?php echo $this->translate('Retourner à l\'accueil')?></a></p>
<?php else : ?>
    <div class="alert alert-error"><?php echo $this->translate('Échec de la déconnexion')?></div>
    <p><a href="/" class="btn btn-danger"><?php echo $this->translate('Retourner à l\'accueil')?></a></p>
<?php endif; ?>