<h1><?php echo $this->translate('Fichier introuvable'); ?></h1>
<p><?php echo $this->translate("Le fichier demandé n'existe pas, ou bien vous n'avez pas les autorisations nécessaires pour y accéder.") ?></p>
<div style="margin-top: 20px">
	<a href="<?= $this->url(['controller' => 'index']) ?>"><button class="btn btn-default"><?php echo $this->translate("Retourner à l'accueil"); ?></button></a>
</div>
