<?php 
	$this->jQuery()->addJavascriptFile(VENDOR_TINYMCE_JQUERY);
	$this->jQuery()->addJavascriptFile(VENDOR_TINYMCE);
	$this->jQuery()->addJavascriptFile(TINYMCE_DIR . "tinymce_patch.js");
	
	echo $this->form; 
?>

<script>
	__initMCE ('textarea', undefined, {
		theme: "modern",
		plugins: "link image code",
		toolbar1: "bold italic underline | link image | code",
		menubar: false
	});
</script>